/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustrationMetadata = {
  numIllustrations: 1402,
  spotSquareCount: 91,
  spotRectangleCount: 66,
  heroSquareCount: 268,
  pictogramCount: 273,
  newIllustrations: [],
  modifiedIllustrations: [
    'pictogram/accountsNavigation-dark',
    'pictogram/accountsNavigation-light',
    'pictogram/advancedTradingNavigation-dark',
    'pictogram/advancedTradingNavigation-light',
    'pictogram/analyticsNavigation-dark',
    'pictogram/analyticsNavigation-light',
    'pictogram/assetHubNavigation-dark',
    'pictogram/assetHubNavigation-light',
    'pictogram/borrowNavigation-dark',
    'pictogram/borrowNavigation-light',
    'pictogram/cardNavigation-dark',
    'pictogram/cardNavigation-light',
    'pictogram/cloudNavigation-dark',
    'pictogram/cloudNavigation-light',
    'pictogram/commerceNavigation-dark',
    'pictogram/commerceNavigation-light',
    'pictogram/connectNavigation-dark',
    'pictogram/connectNavigation-light',
    'pictogram/custodyNavigation-dark',
    'pictogram/custodyNavigation-light',
    'pictogram/dataMarketplaceNavigation-dark',
    'pictogram/dataMarketplaceNavigation-light',
    'pictogram/delegateNavigation-dark',
    'pictogram/delegateNavigation-light',
    'pictogram/derivativesNavigation-dark',
    'pictogram/derivativesNavigation-light',
    'pictogram/directDepositNavigation-dark',
    'pictogram/directDepositNavigation-light',
    'pictogram/earnNavigation-dark',
    'pictogram/earnNavigation-light',
    'pictogram/exchangeNavigation-dark',
    'pictogram/exchangeNavigation-light',
    'pictogram/helpCenterNavigation-dark',
    'pictogram/helpCenterNavigation-light',
    'pictogram/institutionalNavigation-dark',
    'pictogram/institutionalNavigation-light',
    'pictogram/learningRewardsNavigation-dark',
    'pictogram/learningRewardsNavigation-light',
    'pictogram/nftNavigation-dark',
    'pictogram/nftNavigation-light',
    'pictogram/participateNavigation-dark',
    'pictogram/participateNavigation-light',
    'pictogram/payNavigation-dark',
    'pictogram/payNavigation-light',
    'pictogram/primeNavigation-dark',
    'pictogram/primeNavigation-light',
    'pictogram/privateClientNavigation-dark',
    'pictogram/privateClientNavigation-light',
    'pictogram/proNavigation-dark',
    'pictogram/proNavigation-light',
    'pictogram/queryTransactNavigation-dark',
    'pictogram/queryTransactNavigation-light',
    'pictogram/rewardsNavigation-dark',
    'pictogram/rewardsNavigation-light',
    'pictogram/rosettaNavigation-dark',
    'pictogram/rosettaNavigation-light',
    'pictogram/signInNavigation-dark',
    'pictogram/signInNavigation-light',
    'pictogram/taxCenterNavigation-dark',
    'pictogram/taxCenterNavigation-light',
    'pictogram/venturesNavigation-dark',
    'pictogram/venturesNavigation-light',
    'pictogram/walletLinkNavigation-dark',
    'pictogram/walletLinkNavigation-light',
    'pictogram/walletNavigation-dark',
    'pictogram/walletNavigation-light',
  ],
  deletedIllustrations: [],
};
