/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustrationMetadata = {
  numIllustrations: 1360,
  spotSquareCount: 84,
  spotRectangleCount: 64,
  heroSquareCount: 264,
  pictogramCount: 265,
  newIllustrations: [
    'heroSquare/alienDonutSystemError-dark',
    'heroSquare/alienDonutSystemError-light',
    'heroSquare/artFrameEmptyState-dark',
    'heroSquare/artFrameEmptyState-light',
    'heroSquare/browseDecentralizedApps-dark',
    'heroSquare/browseDecentralizedApps-light',
    'heroSquare/cardError-dark',
    'heroSquare/cardError-light',
    'heroSquare/catHoldingWalletEmptyState-light',
    'heroSquare/catHoldingWalletEmptyState-light',
    'heroSquare/catLostSystemError-dark',
    'heroSquare/catLostSystemError-light',
    'heroSquare/chickenFishSystemError-dark',
    'heroSquare/chickenFishSystemError-light',
    'heroSquare/exchangeEmptyState-dark',
    'heroSquare/exchangeEmptyState-light',
    'heroSquare/iceCreamMeltingSystemError-dark',
    'heroSquare/iceCreamMeltingSystemError-light',
    'heroSquare/octopusFloatSystemError-dark',
    'heroSquare/octopusFloatSystemError-light',
    'heroSquare/serverCatSystemError-dark',
    'heroSquare/serverCatSystemError-light',
    'heroSquare/spacedOutSystemError-dark',
    'heroSquare/spacedOutSystemError-light',
    'heroSquare/squidEmptyState-dark',
    'heroSquare/squidEmptyState-light',
    'heroSquare/walletFlyEmptyState-dark',
    'heroSquare/walletFlyEmptyState-light',
    'pictogram/cardSuccess-dark',
    'pictogram/cardSuccess-light',
    'pictogram/mobileError-dark',
    'pictogram/mobileError-light',
    'pictogram/mobileSuccess-dark',
    'pictogram/mobileSuccess-light',
    'pictogram/mobileWarning-dark',
    'pictogram/mobileWarning-light',
    'pictogram/myNumberCard-dark',
    'pictogram/myNumberCard-light',
    'pictogram/walletError-dark',
    'pictogram/walletError-light',
    'pictogram/walletSuccess-dark',
    'pictogram/walletSuccess-light',
    'pictogram/walletWarning-dark',
    'pictogram/walletWarning-light',
    'spotSquare/futuresSpotSquare-dark',
    'spotSquare/futuresSpotSquare-light',
  ],
  modifiedIllustrations: [
    'heroSquare/contactsListWarning-dark',
    'heroSquare/contactsListWarning-light',
    'heroSquare/restrictedCountry-dark',
    'heroSquare/restrictedCountry-light',
    'pictogram/cardBlocked-dark',
    'pictogram/cardBlocked-light',
    'pictogram/cardDeclined-dark',
    'pictogram/cardDeclined-light',
    'pictogram/walletWarning-dark',
    'pictogram/walletWarning-dark',
    'pictogram/walletWarning-light',
    'pictogram/walletWarning-light',
    'pictogram/warning-dark',
    'pictogram/warning-light',
    'spotRectangle/ledgerFailed-dark',
    'spotRectangle/ledgerFailed-light',
    'spotRectangle/marginWarningRectangle-dark',
    'spotRectangle/marginWarningRectangle-light',
    'spotRectangle/ratMigrationerror-dark',
    'spotRectangle/ratMigrationerror-light',
    'spotSquare/frameEmpty-dark',
    'spotSquare/frameEmpty-light',
    'spotSquare/offersEmpty-dark',
    'spotSquare/offersEmpty-light',
  ],
  deletedIllustrations: [],
};
