apiVersion: v2
name: cds
description: "" # TODO: Add a description of your project here.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: infra-common
    version: 0.1.19
    repository: "oci://652969937640.dkr.ecr.us-east-1.amazonaws.com/charts/infra-common"
