import type { IconName, NavigationBaseIconProps, NavigationIconName } from '@cbhq/cds-common';

/* -------------------------------------------------------------------------- */
/*                    DELETE THIS FILE AFTER ICON MIGRATION                   */
/* -------------------------------------------------------------------------- */

export type TemporarySheetName =
  | IconName
  | [NavigationIconName, Omit<NavigationBaseIconProps, 'name'>];

export const oldIconSheetNames: TemporarySheetName[] = [
  'cashUSD',
  'cashGBP',
  'cashEUR',
  'cashJPY',
  'phone',
  'checkmark',
  'lock',
  'deposit',
  'arrowLeft',
  'arrowRight',
  'step1',
  'step2',
  'step3',
  'step4',
  'step5',
  'step6',
  'step7',
  'step8',
  'step9',
  'step0',
  'withdraw',
  'exclamationMark',
  'statusDot',
  'more',
  'sortUp',
  'smartContract',
  'email',
  'sortUpCenter',
  'sortDown',
  'doubleChevronRight',
  'identityCard',
  'wallet',
  'visibleInactive',
  'paypal',
  'sofort',
  'ideal',
  'bank',
  'card',
  'bell',
  'qrCode',
  'search',
  'paperAirplane',
  'starActive',
  'starInactive',
  'home',
  'chartBar',
  'profile',
  'ethereum',
  'defi',
  'currencies',
  'nft',
  'cash',
  'flame',
  'gear',
  'list',
  'chartVolume',
  'arrowsHorizontal',
  'initiator',
  'globe',
  'circulatingSupply',
  'allTimeHigh',
  'pulse',
  'sparkle',
  'chartPie',
  'recurring',
  'convert',
  'add',
  'minus',
  'arrowDown',
  'arrowUp',
  'info',
  'dot',
  'arrowsVertical',
  'wireTransfer',
  'calendar',
  'document',
  'shield',
  'heartActive',
  'heartInactive',
  'play',
  'pause',
  'api',
  'soundOn',
  'stake',
  'soundOff',
  'safe',
  'speaker',
  'visibleActive',
  'pencil',
  'blockchain',
  'gavel',
  'chartPieCircle',
  'questionMark',
  'giftBox',
  'newsFeed',
  'marketCap',
  'checkboxChecked',
  'checkboxEmpty',
  'copy',
  'percentage',
  'checkboxChecked',
  'circleCross',
  'undo',
  'chartLine',
  'chartCandles',
  'externalLink',
  'clock',
  'verticalLine',
  'annotation',
  'fib',
  'horizontalLine',
  'continuous',
  'crossTrade',
  'diagonalRightArrow',
  'average',
  'rectangle',
  'reCenter',
  'expandAll',
  'expandAddress',
  'circleCheckmark',
  'trashCan',
  'error',
  'outline',
  'hamburger',
  'closeCaption',
  'gauge',
  'expand',
  'collapse',
  'pay',
  'share',
  'drag',
  'trophy',
  'filter',
  'giftCard',
  'avatar',
  'regulated',
  'protection',
  'camera',
  'orderHistory',
  'backArrow',
  'forwardArrow',
  'upArrow',
  'downArrow',
  'warning',
  'chatBubble',
  'caretRight',
  'caretLeft',
  'caretUp',
  'caretDown',
  'close',
  'lightningBolt',
  ['chartCandles', { active: false }],
  ['trading', { active: false }],
  ['bell', { active: false }],
  ['trading', { active: true }],
  ['bell', { active: true }],
  ['pay', { active: false }],
  ['chartPie', { active: false }],
  ['chartPie', { active: true }],
  ['chartCandles', { active: true }],
  ['pay', { active: true }],
  ['newsfeed', { active: false }],
  ['newsfeed', { active: true }],
  ['dashboard', { active: false }],
  ['dashboard', { active: true }],
  ['tag', { active: false }],
  ['tag', { active: true }],
  ['invoice', { active: false }],
  ['invoice', { active: true }],
  ['giftBox', { active: true }],
  ['caret', { active: false }],
  ['caret', { active: true }],
  ['giftBox', { active: false }],
  ['cash', { active: false }],
  ['addPeople', { active: false }],
  ['defi', { active: false }],
  ['defi', { active: true }],
  ['gab', { active: false }],
  ['home', { active: false }],
  ['gab', { active: true }],
  ['home', { active: true }],
  ['addPeople', { active: true }],
  ['cash', { active: true }],
  'sortDownCenter',
  'followInactive',
  'followActive',
  ['wallet', { active: false }],
  ['settings', { active: false }],
  ['settings', { active: true }],
  ['wallet', { active: true }],
  ['scanQrCode', { active: true }],
  ['scanQrCode', { active: false }],
  'pin',
  'keyboard',
  'clipboard',
  'dex',
  ['chartBar', { active: false }],
  ['chartBar', { active: true }],
  'pyramid',
  'bookmarkInactive',
  'bookmarkActive',
  'reportActive',
  ['earn', { active: false }],
  ['earn', { active: true }],
  'airdrop',
  'fork',
  'unknown',
  'thumbsDown',
  'thumbsUp',
  ['directDeposit', { active: false }],
  ['directDeposit', { active: true }],
  ['support', { active: false }],
  ['support', { active: true }],
  ['planet', { active: false }],
  ['planet', { active: true }],
  'paperclip',
  'upload',
  'noWifi',
  'wifi',
  'telephone',
  'laptop',
  'clockOutline',
  'cashRupee',
  'chainLink',
  ['application', { active: false }],
  ['application', { active: true }],
  ['appSwitcher', { active: false }],
  ['appSwitcher', { active: true }],
  'reportInactive',
  'download',
  'setPinCode',
  'diagonalUpArrow',
  'diagonalDownArrow',
  ['shoppingCart', { active: false }],
  ['shoppingCart', { active: true }],
  ['account', { active: false }],
  ['account', { active: true }],
  ['securityShield', { active: true }],
  ['eye', { active: true }],
  ['securityShield', { active: false }],
  ['eye', { active: false }],
  ['taxes', { active: false }],
  ['taxes', { active: true }],
  ['documentation', { active: false }],
  ['documentation', { active: true }],
  ['paymentCard', { active: false }],
  ['paymentCard', { active: true }],
  ['trophyCup', { active: false }],
  ['trophyCup', { active: true }],
  ['moreVertical', { active: false }],
  ['moreVertical', { active: true }],
  'seenActive',
  ['browser', { active: false }],
  ['browser', { active: true }],
  ['interest', { active: false }],
  ['interest', { active: true }],
  'comment',
  'unlock',
  'taxesReceipt',
  ['crystalBall', { active: false }],
  ['crystalBall', { active: true }],
  'visibleFilled',
  'thumbsUpOutline',
  ['faces', { active: false }],
  ['faces', { active: true }],
  ['moon', { active: false }],
  ['moon', { active: true }],
  ['sun', { active: false }],
  ['light', { active: false }],
  ['sun', { active: true }],
  ['light', { active: true }],
  ['astronautHelmet', { active: false }],
  ['astronautHelmet', { active: true }],
  ['peopleGroup', { active: false }],
  ['peopleGroup', { active: true }],
  'group',
  'thumbsDownOutline',
  'chatBotAgent',
  ['heart', { active: false }],
  ['heart', { active: true }],
  ['hammer', { active: false }],
  ['hammer', { active: true }],
  ['collection', { active: false }],
  ['collection', { active: true }],
  ['drops', { active: false }],
  ['drops', { active: true }],
  ['diamond', { active: false }],
  ['diamond', { active: true }],
  ['comment', { active: false }],
  ['comment', { active: true }],
  ['hiddenEye', { active: false }],
  ['hiddenEye', { active: true }],
  'bridging',
  'cashBrazillianReal',
  'cashBrazilianReal',
  ['pencil', { active: true }],
  ['pencil', { active: false }],
  ['comment', { active: true }],
  'cashThaiBaht',
  'cashPhilippinePeso',
  'cashIndonesianRupiah',
  'cashVietnameseDong',
  'cashTurkishLira',
  'cashSwissFranc',
  'cashPolishZłoty',
  'cashUaeDirham',
  'cashAustralianDollar',
  ['cloud', { active: false }],
  ['cloud', { active: true }],
  ['participate', { active: false }],
  ['participate', { active: true }],
  ['queryTransact', { active: false }],
  ['queryTransact', { active: true }],
  ['hammer', { active: false }],
  ['hammer', { active: true }],
  'nftSaleInactive',
  'nftSaleActive',
  'nftBuyInactive',
  'nftBuyActive',
  ['ghost', { active: false }],
  ['ghost', { active: true }],
  ['royalty', { active: false }],
  ['royalty', { active: true }],
  'nftOfferInactive',
  'nftOfferActive',
  ['ghost', { active: false }],
  ['ghost', { active: true }],
  ['royalty', { active: false }],
  ['royalty', { active: true }],
  'taxesReceiptInactive',
  ['directDeposit', { active: true }],
  ['directDeposit', { active: false }],
  ['activity', { active: false }],
  ['activity', { active: true }],
  'generalCharacter',
  ['magnifyingGlass', { active: false }],
  ['magnifyingGlass', { active: true }],
  'collectibles',
  'pFPS',
  'artwork',
  'ultility',
  'games',
  'metaverse',
  'music',
  'save',
  'briefcase',
  'pencil',
  'rocket',
  'qrCodeAlt',
  ['copy', { active: false }],
  ['copy', { active: true }],
  'affiliates',
  'lightbulb',
  'megaphone',
  'book',
  'newsletter',
  'blog',
  'institute',
  'cryptobasics',
  ['menu', { active: false }],
  ['menu', { active: true }],
  'fingerprint',
  'faceScan',
  'twitterLogo',
  'instagramLogo',
  'discordLogo',
  'refresh',
  'payouts',
  'wrapToken',
  'transactions',
  ['rocketShip', { active: true }],
  ['rocketShip', { active: false }],
  'faucetInactive',
  'faucetActive',
];
