secure:
  required_reviews: 1
  branches:
    - master
build:
  engines:
    # Apps
    - BaldurECR:
        name: cds-website-docs
        path: ./apps/website/production.Dockerfile
    - BaldurECR:
        name: cds-website-docs-development
        path: ./apps/website/development.Dockerfile
    # Packages
    - BaldurNode:
        name: package-cds-utils
        path: ./packages/utils/publish.Dockerfile
