secure:
  required_reviews: 1
  codeowners_enabled: true
  branches:
    - master
    - cds5-master
    - v5
    - 6.2.0-beta.0
    - 6.3.0-rc.1-2
    - 6.19.0-alpha.1
    - 7.0.0-alpha
  auto_assign_reviewers: true
build:
  engines:
    # Apps
    - BaldurECR:
        name: cds-adoption
        path: ./apps/cds-adoption/Dockerfile
        autobuild: false
    - BaldurECR:
        name: cds-adoption-trigger
        path: ./apps/cds-adoption/trigger.Dockerfile
        autobuild: false
    - BaldurECR:
        name: cds-css-upload
        path: ./packages/web/cssupload-production.Dockerfile
        autobuild_files:
          - packages/web/package.json
    - BaldurECR:
        name: cds-css-upload-development
        path: ./packages/web/cssupload-development.Dockerfile
        autobuild_files:
          - packages/web/package.json
    - BaldurECR:
        name: cds-figma-sync
        path: ./apps/cds-figma-sync/Dockerfile
        autobuild: false
    - BaldurECR:
        name: cds-figma-sync-trigger
        path: ./apps/cds-figma-sync/trigger.Dockerfile
        autobuild: false
    - BaldurECR:
        name: cds-storybook
        path: ./apps/storybook/production.Dockerfile
        autobuild: true
    - BaldurECR:
        name: cds-website-docs
        path: ./apps/website/production.Dockerfile
        autobuild: true
    - BaldurECR:
        name: cds-website-docs-development
        path: ./apps/website/development.Dockerfile
        autobuild: false
    - BaldurECR:
        name: figma-athena
        path: ./apps/figma-athena-plugin/Dockerfile
        autobuild: false

    # Packages
    - BaldurNode:
        name: package-cds-common
        path: ./packages/common/publish.Dockerfile
        autobuild_files:
          - packages/common/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-fonts
        path: ./packages/fonts/publish.Dockerfile
        autobuild_files:
          - packages/fonts/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-icons
        path: ./packages/icons/publish.Dockerfile
        autobuild_files:
          - packages/icons/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-illustrations
        path: ./packages/illustrations/publish.Dockerfile
        autobuild_files:
          - packages/illustrations/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-lottie-files
        path: ./packages/lottie-files/publish.Dockerfile
        autobuild_files:
          - packages/lottie-files/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-migrator
        path: ./packages/cds-migrator/publish.Dockerfile
        autobuild_files:
          - packages/cds-migrator/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-mobile
        path: ./packages/mobile/publish.Dockerfile
        autobuild_files:
          - packages/mobile/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-utils
        path: ./packages/utils/publish.Dockerfile
        autobuild_files:
          - packages/utils/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-web
        path: ./packages/web/publish.Dockerfile
        autobuild_files:
          - packages/web/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-cds-web-visualization
        path: ./packages/web-visualization/publish.Dockerfile
        autobuild_files:
          - packages/web-visualization/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-d3
        path: ./packages/d3/publish.Dockerfile
        autobuild_files:
          - packages/d3/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-eslint-plugin-cds
        path: ./packages/eslint-plugin-cds/publish.Dockerfile
        autobuild_files:
          - packages/eslint-plugin-cds/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-mobile-visualization
        path: ./packages/mobile-visualization/publish.Dockerfile
        autobuild_files:
          - packages/mobile-visualization/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-ui-mobile-playground
        path: ./packages/ui-mobile-playground/publish.Dockerfile
        autobuild_files:
          - packages/ui-mobile-playground/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-ui-mobile-visreg
        path: ./packages/ui-mobile-visreg/publish.Dockerfile
        autobuild_files:
          - packages/ui-mobile-visreg/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-ui-scorecard
        path: ./packages/ui-scorecard/publish.Dockerfile
        autobuild_files:
          - packages/ui-scorecard/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2

    # Static assets
    - BaldurECR:
        name: static-assets
        path: ./apps/cds-figma-sync/static-assets.Dockerfile
        autobuild_files:
          - packages/illustrations/package.json
