secure:
  required_reviews: 1
  codeowners_enabled: true
  branches:
    - master
    - v7
  auto_assign_reviewers: true
build:
  engines:
    # Apps
    - BaldurECR:
        name: cds-v7-docs
        path: ./apps/docs/production.Dockerfile
        autobuild: false
    # Packages
    - BaldurNode:
        name: package-fonts
        path: ./packages/fonts/publish.Dockerfile
        autobuild_files:
          - packages/fonts/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
    - BaldurNode:
        name: package-ui-scorecard
        path: ./packages/ui-scorecard/publish.Dockerfile
        autobuild_files:
          - packages/ui-scorecard/package.json
        expire_keep_tags_after_days: 1
        expire_tmp_tags_after_days: 1
        expire_all_after_days: 2
