enableGlobalCache: true

enableTelemetry: false

# Commenting out to see if it will resolve a buildkite error: Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
# https://buildkite.com/coinbase/frontend-cds/builds/4314#0182d046-c30d-4cee-a178-b596f4b153d9
# nodeLinker: node-modules

npmRegistryServer: 'https://registry-npm.cbhq.net'

npmScopes:
  cbhq:
    npmRegistryServer: 'https://registry-npm.cbhq.net'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
