compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry-npm.cbhq.net"

npmScopes:
  bufteam:
    npmAuthToken: 4057d7dfd176628f518b8dd5646768f2a1b4920cb37c028553d69081f130f9ec
    npmRegistryServer: "https://buf.cbhq.net/gen/npm/v1/"
  cbhq:
    npmRegistryServer: "https://registry-npm.cbhq.net"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
