apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/name: frontend-cds
  strategy:
    {{- if $.Values.services.app.trafficCanary }}
    canary: {{- include "infra.common.trafficCanary" $.Values.services.app.trafficCanary | indent 6 }}
    {{- else }}
    blueGreen:
      activeService: app
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: frontend-cds
    spec:
      containers:
        - image: {{ $.Values.services.app.containers.app.image }}
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 120
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /_health
              port: 3001
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: app
          ports:
            - containerPort: 3001
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /_health
              port: 3001
            periodSeconds: 10
            successThreshold: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: {{ $.Values.services.app.containers.app.resources.limits.memory }}
            requests:
              cpu: {{ $.Values.services.app.containers.app.resources.requests.cpu }}
              memory: {{ $.Values.services.app.containers.app.resources.requests.memory }}
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /_health
              port: 3001
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 150
