apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app
spec:
  maxReplicas: {{ $.Values.services.app.scaling.max }}
  minReplicas: {{ $.Values.services.app.scaling.min }}
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: app
  targetCPUUtilizationPercentage: {{ $.Values.services.app.scaling.targetcpu }}
