apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $service_port_name, $target_group := $.Values.services.app.target_group_bindings }}
    target-group.aws.infra.coinbase.com/{{ $service_port_name }}: {{ $target_group }}
    {{- end }}
  name: app
spec:
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: frontend-cds
