/**
 * DO NOT MODIFY
 * Generated from yarn nx run icons:sync
 */

export type NavIconName =
  | 'account'
  | 'activity'
  | 'addPeople'
  | 'application'
  | 'appSwitcher'
  | 'astronautHelmet'
  | 'bell'
  | 'browser'
  | 'caret'
  | 'cash'
  | 'chartBar'
  | 'chartCandles'
  | 'chartPie'
  | 'cloud'
  | 'collection'
  | 'comment'
  | 'copy'
  | 'crystalBall'
  | 'dashboard'
  | 'defi'
  | 'diamond'
  | 'directDeposit'
  | 'documentation'
  | 'drops'
  | 'earn'
  | 'eye'
  | 'faces'
  | 'gab'
  | 'ghost'
  | 'giftBox'
  | 'hammer'
  | 'heart'
  | 'hiddenEye'
  | 'home'
  | 'interest'
  | 'invoice'
  | 'light'
  | 'magnifyingGlass'
  | 'menu'
  | 'moon'
  | 'moreVertical'
  | 'newsfeed'
  | 'participate'
  | 'pay'
  | 'paymentCard'
  | 'pencil'
  | 'peopleGroup'
  | 'planet'
  | 'queryTransact'
  | 'rocketShip'
  | 'royalty'
  | 'scanQrCode'
  | 'securityShield'
  | 'settings'
  | 'shoppingCart'
  | 'sun'
  | 'support'
  | 'tag'
  | 'taxes'
  | 'trading'
  | 'trophyCup'
  | 'wallet';
