import type { ThemeConfig } from '../core/theme';

import { coinbaseTheme } from './coinbaseTheme';

export const coinbaseDenseThemeId = 'coinbase-dense';

/** @deprecated This theme was created to test backwards compatibility, it is not officially supported by CDS. Please copy it into your own repo and modify it as needed. Do not import it directly from CDS. */
export const coinbaseDenseTheme = {
  ...coinbaseTheme,
  id: coinbaseDenseThemeId,
  space: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 10,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
  },
  iconSize: {
    xs: 8,
    s: 12,
    m: 16,
    l: 24,
  },
  avatarSize: {
    s: 16,
    m: 20,
    l: 24,
    xl: 36,
    xxl: 44,
    xxxl: 48,
  },
  controlSize: {
    checkboxSize: 16,
    radioSize: 16,
    switchWidth: 42,
    switchHeight: 24,
    switchThumbSize: 22,
    tileSize: 92,
  },
  fontFamily: {
    display1: 'CoinbaseDisplay-Regular',
    display2: 'CoinbaseDisplay-Regular',
    display3: 'CoinbaseDisplay-Regular',
    title1: 'CoinbaseDisplay-Medium',
    title2: 'CoinbaseDisplay-Regular',
    title3: 'CoinbaseSans-Medium',
    title4: 'CoinbaseSans-Regular',
    headline: 'CoinbaseSans-Medium',
    body: 'CoinbaseSans-Regular',
    label1: 'CoinbaseText-Medium',
    label2: 'CoinbaseText-Regular',
    caption: 'CoinbaseText-Medium',
    legal: 'CoinbaseText-Regular',
  },
  fontFamilyMono: {
    display1: 'CoinbaseMono-Regular',
    display2: 'CoinbaseMono-Regular',
    display3: 'CoinbaseMono-Regular',
    title1: 'CoinbaseMono-Medium',
    title2: 'CoinbaseMono-Regular',
    title3: 'CoinbaseMono-Medium',
    title4: 'CoinbaseMono-Regular',
    headline: 'CoinbaseMono-Medium',
    body: 'CoinbaseMono-Regular',
    label1: 'CoinbaseMono-Medium',
    label2: 'CoinbaseMono-Regular',
    caption: 'CoinbaseMono-Medium',
    legal: 'CoinbaseMono-Regular',
  },
  fontSize: {
    display1: 61,
    display2: 45,
    display3: 37,
    title1: 25,
    title2: 25,
    title3: 17,
    title4: 17,
    headline: 14,
    body: 14,
    label1: 11,
    label2: 11,
    caption: 10,
    legal: 10,
  },
  fontWeight: {
    display1: '400',
    display2: '400',
    display3: '400',
    title1: '600',
    title2: '400',
    title3: '600',
    title4: '400',
    headline: '600',
    body: '400',
    label1: '600',
    label2: '400',
    caption: '600',
    legal: '400',
  },
  lineHeight: {
    display1: 68,
    display2: 52,
    display3: 44,
    title1: 32,
    title2: 32,
    title3: 24,
    title4: 24,
    headline: 20,
    body: 20,
    label1: 16,
    label2: 16,
    caption: 12,
    legal: 12,
  },
} as const satisfies ThemeConfig;
