// Routes whose stories open an overlay (modal, alert, tray, drawer, etc.)
// via an "Open" button. These use a separate sub-flow that taps Open before
// the screenshot and Cancel after.
export const overlayRoutes = new Set([
  'AlertBasic',
  'DrawerLeft',
  'DrawerTop',
  'StickyFooter',
  'TrayBasic',
  'ModalBasic',
]);

export const enabledRoutes = [
  'Accordion',
  'AlertBasic',
  'AlphaSelect',
  'AlphaSelectChip',
  'AlphaTabbedChips',
  'AreaChart',
  'Avatar',
  'AvatarButton',
  'Axis',
  'Banner',
  'BarChart',
  'Box',
  'BrowserBar',
  'Button',
  'ButtonGroup',
  'Card',
  'Carousel',
  'CartesianChart',
  'Checkbox',
  'CheckboxCell',
  'Chip',
  'Coachmark',
  'Combobox',
  'ControlGroup',
  'Divider',
  'Dot',
  'DrawerLeft',
  'DrawerTop',
  'Group',
  'InputChip',
  'InputStack',
  'Legend',
  'Link',
  'ListCell',
  'ModalBasic',
  'Pressable',
  'RadioCell',
  'SelectChip',
  'SlideButton',
  'StepperHorizontal',
  'StepperVertical',
  'StickyFooter',
  'TrayBasic',
  'Switch',
  'Tabs',
  'Tag',
  'Text',
];
