/**
 * DO NOT MODIFY
 * Generated from yarn nx run figma-styles:sync-illustration-dark-styles
 */

/** style name mapped to style details */
const colorStyleMap = {
  'accent-1': {
    key: '0ff77d80426791f2267b75fa305db8df42874b01',
    name: 'accent-1',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#ECD069' },
    cssVarSetter: '--illustration-accent-1',
    cssVarGetter: 'var(--illustration-accent-1)',
  },
  'accent-2': {
    key: '7883d117fd4b77a93a8e2c8ec8c0fed767a4ed06',
    name: 'accent-2',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#45DAF6' },
    cssVarSetter: '--illustration-accent-2',
    cssVarGetter: 'var(--illustration-accent-2)',
  },
  'accent-3': {
    key: 'bdcbce298e4f0de070cf94d51e5dd8b55248b2ec',
    name: 'accent-3',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#F07836' },
    cssVarSetter: '--illustration-accent-3',
    cssVarGetter: 'var(--illustration-accent-3)',
  },
  'accent-4': {
    key: 'a7fbb6f0b37327245d5ca844d7faa8fe7871076c',
    name: 'accent-4',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#A5C1FD' },
    cssVarSetter: '--illustration-accent-4',
    cssVarGetter: 'var(--illustration-accent-4)',
  },
  black: {
    key: '5c08db6b126da225319e68fd2fc8a42a57b2f4ed',
    name: 'black',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#0A0B0D' },
    cssVarSetter: '--illustration-black',
    cssVarGetter: 'var(--illustration-black)',
  },
  gray: {
    key: '903ba6ea7726d298c6fbdb015782d31cab16af4d',
    name: 'gray',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#464B55' },
    cssVarSetter: '--illustration-gray',
    cssVarGetter: 'var(--illustration-gray)',
  },
  'gray-2': {
    key: '6e4137308f5abb84113dc106cf94fcdfd1b444a5',
    name: 'gray-2',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#464B55' },
    cssVarSetter: '--illustration-gray-2',
    cssVarGetter: 'var(--illustration-gray-2)',
  },
  invert: {
    key: '52a47a0d4d526aa348f891acd6a6fdc160350b20',
    name: 'invert',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#FFFFFF' },
    cssVarSetter: '--illustration-invert',
    cssVarGetter: 'var(--illustration-invert)',
  },
  'invert-2': {
    key: 'c2c47f4e91ef106db0b240c07b20941c556e849c',
    name: 'invert-2',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#0A0B0D' },
    cssVarSetter: '--illustration-invert-2',
    cssVarGetter: 'var(--illustration-invert-2)',
  },
  negative: {
    key: '65f8c9ac76bf54c47866eeee77cb9531aabd1763',
    name: 'negative',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#F0616D' },
    cssVarSetter: '--illustration-negative',
    cssVarGetter: 'var(--illustration-negative)',
  },
  positive: {
    key: '0ef092ea18cd11b0eac5bb4ab27c6034ac129411',
    name: 'positive',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#44C28D' },
    cssVarSetter: '--illustration-positive',
    cssVarGetter: 'var(--illustration-positive)',
  },
  primary: {
    key: 'be3e3bd2911fc0f0a72c734c7151ba79ecf27b47',
    name: 'primary',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#588AF5' },
    cssVarSetter: '--illustration-primary',
    cssVarGetter: 'var(--illustration-primary)',
  },
  white: {
    key: '0451b1902be1d63b4f15db21aa9399d8d0193e61',
    name: 'white',
    type: 'dark',
    prefix: 'illustration',
    paint: { type: 'solid', value: '#FFFFFF' },
    cssVarSetter: '--illustration-white',
    cssVarGetter: 'var(--illustration-white)',
  },
};

export default colorStyleMap;
