/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const xSmall = {
  typography: {
    display1: { fontSize: 61, lineHeight: 68, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 31, lineHeight: 40, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 25, lineHeight: 32, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 25, lineHeight: 32, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 17, lineHeight: 24, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter-Regular' },
    label1: {
      fontSize: 11,
      lineHeight: 12,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    label2: {
      fontSize: 11,
      lineHeight: 12,
      textTransform: 'uppercase',
      fontFamily: 'Inter-Regular',
    },
    caption: {
      fontSize: 10,
      lineHeight: 12,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    legal: { fontSize: 10, lineHeight: 12, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
    '0.5': 4,
  },
  control: { checkboxSize: 16, radioSize: 16 },
} as const;

export const small = {
  typography: {
    display1: { fontSize: 62, lineHeight: 72, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 32, lineHeight: 40, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 26, lineHeight: 32, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 26, lineHeight: 32, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 18, lineHeight: 24, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 14, lineHeight: 20, fontFamily: 'Inter-Regular' },
    label1: {
      fontSize: 12,
      lineHeight: 16,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    label2: {
      fontSize: 12,
      lineHeight: 16,
      textTransform: 'uppercase',
      fontFamily: 'Inter-Regular',
    },
    caption: {
      fontSize: 11,
      lineHeight: 12,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    legal: { fontSize: 11, lineHeight: 16, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
    '0.5': 4,
  },
  control: { checkboxSize: 16, radioSize: 16 },
} as const;

export const medium = {
  typography: {
    display1: { fontSize: 63, lineHeight: 72, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 33, lineHeight: 40, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 27, lineHeight: 36, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 27, lineHeight: 36, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 19, lineHeight: 24, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 15, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 15, lineHeight: 20, fontFamily: 'Inter-Regular' },
    label1: {
      fontSize: 13,
      lineHeight: 16,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    label2: {
      fontSize: 13,
      lineHeight: 16,
      textTransform: 'uppercase',
      fontFamily: 'Inter-Regular',
    },
    caption: {
      fontSize: 12,
      lineHeight: 16,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    legal: { fontSize: 12, lineHeight: 16, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
    '0.5': 4,
  },
  control: { checkboxSize: 16, radioSize: 16 },
} as const;

export const large = {
  typography: {
    display1: { fontSize: 64, lineHeight: 72, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 34, lineHeight: 44, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 28, lineHeight: 36, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 28, lineHeight: 36, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 20, lineHeight: 28, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 16, lineHeight: 24, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 16, lineHeight: 24, fontFamily: 'Inter-Regular' },
    label1: { fontSize: 14, lineHeight: 16, fontFamily: 'Inter-SemiBold' },
    label2: { fontSize: 14, lineHeight: 16, fontFamily: 'Inter-Regular' },
    caption: {
      fontSize: 13,
      lineHeight: 16,
      textTransform: 'uppercase',
      fontFamily: 'Inter-SemiBold',
    },
    legal: { fontSize: 13, lineHeight: 16, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
    '0.5': 4,
  },
  control: { checkboxSize: 20, radioSize: 20 },
} as const;

export const xLarge = {
  typography: {
    display1: { fontSize: 66, lineHeight: 76, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 36, lineHeight: 44, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 30, lineHeight: 36, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 30, lineHeight: 36, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 22, lineHeight: 28, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 18, lineHeight: 24, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 18, lineHeight: 24, fontFamily: 'Inter-Regular' },
    label1: { fontSize: 16, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    label2: { fontSize: 16, lineHeight: 20, fontFamily: 'Inter-Regular' },
    caption: { fontSize: 15, lineHeight: 16, fontFamily: 'Inter-SemiBold' },
    legal: { fontSize: 15, lineHeight: 20, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
    '0.5': 4,
  },
  control: { checkboxSize: 20, radioSize: 20 },
} as const;

export const xxLarge = {
  typography: {
    display1: { fontSize: 68, lineHeight: 76, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 38, lineHeight: 48, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 32, lineHeight: 40, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 32, lineHeight: 40, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 24, lineHeight: 32, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 20, lineHeight: 28, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 20, lineHeight: 28, fontFamily: 'Inter-Regular' },
    label1: { fontSize: 18, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    label2: { fontSize: 18, lineHeight: 20, fontFamily: 'Inter-Regular' },
    caption: { fontSize: 17, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    legal: { fontSize: 17, lineHeight: 20, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
    '0.5': 4,
  },
  control: { checkboxSize: 20, radioSize: 20 },
} as const;

export const xxxLarge = {
  typography: {
    display1: { fontSize: 70, lineHeight: 80, fontFamily: 'Graphik-Regular' },
    display2: { fontSize: 40, lineHeight: 48, fontFamily: 'Graphik-Regular' },
    title1: { fontSize: 34, lineHeight: 40, fontFamily: 'Graphik-Medium' },
    title2: { fontSize: 34, lineHeight: 40, fontFamily: 'Graphik-Regular' },
    title3: { fontSize: 26, lineHeight: 32, fontFamily: 'Graphik-Medium' },
    headline: { fontSize: 22, lineHeight: 28, fontFamily: 'Inter-SemiBold' },
    body: { fontSize: 22, lineHeight: 28, fontFamily: 'Inter-Regular' },
    label1: { fontSize: 20, lineHeight: 24, fontFamily: 'Inter-SemiBold' },
    label2: { fontSize: 20, lineHeight: 24, fontFamily: 'Inter-Regular' },
    caption: { fontSize: 19, lineHeight: 20, fontFamily: 'Inter-SemiBold' },
    legal: { fontSize: 19, lineHeight: 24, fontFamily: 'Inter-Regular' },
  },
  spacing: {
    '1': 8,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
    '0.5': 4,
  },
  control: { checkboxSize: 20, radioSize: 20 },
} as const;
