export { default as getDevicePlatform } from './getDevicePlatform';
export { default as getSimulatorType } from './getSimulatorType';
export { default as isExpectedAndroidDevice } from './isExpectedAndroidDevice';
export { default as isExpectedIosDevice } from './isExpectedIosDevice';
export { default as launchApp } from './launchApp';
export { default as navigateToRoute } from './navigateToRoute';
export { default as reloadApp } from './reloadApp';
export { default as takeRouteScreenshots } from './takeRouteScreenshots';
export { default as takeScreenshot } from './takeScreenshot';
