import templateBuilder, { TemplateBuilderOptions } from '@babel/template';
import * as t from '@babel/types';

type SVGRProps = {
  /* lint exception for Pro design system migration */
  /* eslint-disable-next-line */
  imports: t.ImportDeclaration[];
  props: t.ObjectPattern[];
  componentName: { name: string };
  jsx: t.JSXElement;
  /* lint exception for Pro design system migration */
  /* eslint-disable-next-line */
  exports: t.Statement[];
};

const iconReactTemplate = (
  { template }: { template: typeof templateBuilder },
  _opts: TemplateBuilderOptions,
  { props, componentName, jsx }: SVGRProps
) => {
  const typeScriptTpl = template.smart({
    plugins: ['jsx', 'typescript'],
    preserveComments: true,
  });

  // Add fill to props
  props[0].properties.unshift(
    t.objectProperty(
      t.identifier('fill'),
      t.assignmentPattern(t.identifier('fill'), t.stringLiteral('#1652F0')),
      false,
      true
    )
  );
  // Update props' type annotation
  if (props[0].typeAnnotation) {
    props[0].typeAnnotation = t.tsTypeAnnotation(
      t.tsTypeReference(t.identifier('InternalIconProps'))
    );
  }

  return typeScriptTpl.ast`
        /**
         * DO NOT MODIFY
         * Generated by svgr
         */
        import * as React from 'react';

        import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps'
        import '../styles.css';

        const ${componentName} = (${props}) => {
            const role = title ? 'img' : 'presentation';

            return ${jsx};
        }

        export default React.memo(${componentName})
    `;
};

module.exports = iconReactTemplate;
