export const CDS_RULE_PREFIXES = ['@coinbase/cds/', '@cbhq/cds/'];

export const FLUSH_DELAY_MS = 5000;

export const CDS_COMPONENTS = [
  'AreaChart',
  'BarChart',
  'Button',
  'Calendar',
  'CartesianChart',
  'Checkbox',
  'Chip',
  'Collapsible',
  'Combobox',
  'DatePicker',
  'Drawer',
  'Dropdown',
  'FeedCard',
  'IconButton',
  'IconCounterButton',
  'InputChip',
  'LineChart',
  'Link',
  'ListCell',
  'MediaChip',
  'ModalHeader',
  'NavigationBar',
  'NudgeCard',
  'Popover',
  'Pressable',
  'ProgressBar',
  'Scrubber',
  'SearchInput',
  'SegmentedTabs',
  'Select',
  'SelectChip',
  'SelectStack',
  'Sidebar',
  'StickyFooter',
  'Switch',
  'TabNavigation',
  'Table',
  'Text',
  'TextInput',
  'Tooltip',
  'Tray',
  'UpsellCard',
] as const;

export const COMPONENT_PATTERN = new RegExp(`\\b(${CDS_COMPONENTS.join('|')})\\b`);
