_percy_ios_shared: &percy_ios_shared
  parallelism: 1
  commands:
    # TODO: Remove the first line once the macos-metal agent upgrade is implemented
    # https://coinbase.slack.com/archives/C02QNP7BLER/p1658527386390829
    - nvm install 16.16.0 && nvm use 16.16.0 && npm install -g yarn
    - tools/ci/setup.sh
    - export LANG=en_US.UTF-8
    - mkdir -p percy-artifacts
    - buildkite-agent artifact download "percy-artifacts/$$PERCY_NONCE_FILE_NAME" percy-artifacts/
    - export PERCY_PARALLEL_NONCE=$(cat percy-artifacts/$$PERCY_NONCE_FILE_NAME)
    - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$PERCY_TOKEN_SECRET_ID --query SecretString --output text)
    - yarn nx run mobile-playground:build-ios-e2e
    - yarn nx run mobile-playground:ios-e2e
  agents:
    queue: macos-metal
  retry:
    automatic:
      limit: 1

env:
  LANG: en_US.UTF-8
  CI: true
  NX_CAPTURE_METRICS: true
  NX_CAPTURE_TEST_METRICS: true
  OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: master
  ANDROID_NDK_HOME: '$$ANDROID_HOME/ndk/$$NDK_VERSION'
  PERCY_NONCE_FILE_NAME: 'percy_nonce.txt'
  PERCY_TOKEN_SECRET_ID: 'infra/buildkite/cds-percy-token-ios'
  DETOX_TOTAL_JOBS: 8

steps:
  - group: 'Percy Tests (iOS)'
    steps:
      - label: 'Percy (iOS) 1'
        key: 'percy-ios-1'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 1

      - label: 'Percy (iOS) 2'
        key: 'percy-ios-2'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 2

      - label: 'Percy (iOS) 3'
        key: 'percy-ios-3'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 3

      - label: 'Percy (iOS) 4'
        key: 'percy-ios-4'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 4

      - label: 'Percy (iOS) 5'
        key: 'percy-ios-5'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 5

      - label: 'Percy (iOS) 6'
        key: 'percy-ios-6'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 6

      - label: 'Percy (iOS) 7'
        key: 'percy-ios-7'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 7

      - label: 'Percy (iOS) 8'
        key: 'percy-ios-8'
        <<: *percy_ios_shared
        env:
          DETOX_JOB_NUMBER: 8

      - label: 'Finish Percy (iOS)'
        parallelism: 1
        depends_on:
          - 'percy-ios-1'
          - 'percy-ios-2'
          - 'percy-ios-3'
          - 'percy-ios-4'
          - 'percy-ios-5'
          - 'percy-ios-6'
          - 'percy-ios-7'
          - 'percy-ios-8'
        # TODO: Remove once iOS is stable
        allow_dependency_failure: true
        commands:
          - tools/ci/setup.sh
          - export LANG=en_US.UTF-8
          - mkdir -p percy-artifacts
          - buildkite-agent artifact download "percy-artifacts/$$PERCY_NONCE_FILE_NAME" percy-artifacts/
          - export PERCY_PARALLEL_NONCE=$(cat percy-artifacts/$$PERCY_NONCE_FILE_NAME)
          - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$PERCY_TOKEN_SECRET_ID --query SecretString --output text)
          - cd apps/mobile-playground
          - yarn percy:finalize
        env:
          OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: master
        agents:
          queue: macos-metal
