_percy_android_shared: &percy_android_shared
  parallelism: 1
  commands:
    # TODO: Remove the first line once the macos-metal agent upgrade is implemented
    # https://coinbase.slack.com/archives/C02QNP7BLER/p1658527386390829
    - nvm install 16.16.0 && nvm use 16.16.0 && npm install -g yarn
    - tools/ci/setup.sh
    - export LANG=en_US.UTF-8
    - mkdir -p percy-artifacts
    - buildkite-agent artifact download "percy-artifacts/$$PERCY_NONCE_FILE_NAME" percy-artifacts/
    - export PERCY_PARALLEL_NONCE=$(cat percy-artifacts/$$PERCY_NONCE_FILE_NAME)
    - yarn nx run mobile-playground:android-e2e-emulator
    - yarn nx run mobile-playground:build-android-e2e
    - yarn nx run mobile-playground:android-e2e
  plugins: &android_plugins
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:android
        wait-network: true
        privileged: true
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - PLAYSTORE_AUTH
          - KEY_PASSWORD
          - KEY_ALIAS
          - BUGSNAG_KEY
          - ANDROID_KEYSTORE
          - PLAYSTORE_PACKAGE_NAME
          - 'PERCY_TOKEN'
          - 'PERCY_TARGET_BRANCH'
    - ssh://git@github.cbhq.net/frontend/aws-sm-buildkite-plugin:
        env:
          PERCY_TOKEN: infra/buildkite/cds-percy-token-android
  timeout_in_minutes: 60
  env:
    OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: master
    DETOX_TOTAL_JOBS: 1
    DETOX_JOB_NUMBER: 1
  agents:
    queue: metal
  retry:
    automatic:
      limit: 2

_finish_percy_android_shared: &finish_percy_android_shared
  parallelism: 1
  commands:
    - tools/ci/setup.sh
    - export LANG=en_US.UTF-8
    - mkdir -p percy-artifacts
    - buildkite-agent artifact download "percy-artifacts/$$PERCY_NONCE_FILE_NAME" percy-artifacts/
    - export PERCY_PARALLEL_NONCE=$(cat percy-artifacts/$$PERCY_NONCE_FILE_NAME)
    - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$PERCY_TOKEN_SECRET_ID --query SecretString --output text)
    - cd apps/mobile-playground
    - yarn percy:finalize
  env:
    OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: master
    PERCY_TOKEN_SECRET_ID: 'infra/buildkite/cds-percy-token-android'
  agents:
    queue: macos-metal

env:
  LANG: en_US.UTF-8
  CI: true
  NX_CAPTURE_METRICS: true
  NX_CAPTURE_TEST_METRICS: true
  OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: master
  ANDROID_NDK_HOME: '$$ANDROID_HOME/ndk/$$NDK_VERSION'
  PERCY_NONCE_FILE_NAME: 'percy_nonce.txt'
  DETOX_TOTAL_JOBS: 8

steps:
  - group: Percy Tests (Android)
    steps:
      - label: 'Percy (Android) Test 1'
        key: 'percy-android-1'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 1

      - label: 'Percy (Android) Test 2'
        key: 'percy-android-2'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 2

      - label: 'Percy (Android) Test 3'
        key: 'percy-android-3'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 3

      - label: 'Percy (Android) Test 4'
        key: 'percy-android-4'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 4

      - label: 'Percy (Android) Test 5'
        key: 'percy-android-5'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 5

      - label: 'Percy (Android) Test 6'
        key: 'percy-android-6'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 6

      - label: 'Percy (Android) Test 7'
        key: 'percy-android-7'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 7

      - label: 'Percy (Android) Test 8'
        key: 'percy-android-8'
        <<: *percy_android_shared
        env:
          DETOX_JOB_NUMBER: 8

      - label: 'Finish Percy (Android)'
        depends_on:
          - 'percy-android-1'
          - 'percy-android-2'
          - 'percy-android-3'
          - 'percy-android-4'
          - 'percy-android-5'
          - 'percy-android-6'
          - 'percy-android-7'
          - 'percy-android-8'
        allow_dependency_failure: true
        <<: *finish_percy_android_shared
