_shared_step: &shared_step
  commands:
    - tools/ci/setup.sh
  plugins:
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - 'BUILDKITE_API_TOKEN'
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
  agents:
    queue: docker
    resource_class: large
  retry:
    automatic:
      limit: 1

env:
  LANG: en_US.UTF-8
  CI: true
  NX_CAPTURE_METRICS: true
  NX_CAPTURE_TEST_METRICS: true
  ANDROID_NDK_HOME: '$$ANDROID_HOME/ndk/$$NDK_VERSION'
  PERCY_NONCE_FILE_NAME: 'percy_nonce.txt'
  PERCY_TARGET_BRANCH: master

steps:
  - label: Validate
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - yarn nx workspace-lint
      - yarn mono-pipeline validate-codeowners
      - yarn mono-pipeline validate-lockfile

  - label: Build
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci build
    env:
      STORYBOOK_SKIP_ANIMATION: true
    plugins:
      - file:///buildkite/plugins/docker:
          <<: *docker_plugin
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16-chrome
          environment:
            - 'BUILDKITE_API_TOKEN'
            - 'STORYBOOK_SKIP_ANIMATION'
      - file:///buildkite/plugins/cache: *cache_plugin

  - label: Lint
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci lint

  - label: Format
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci format

  - label: Test
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci test

  - label: Typecheck
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci typecheck

  - label: 'A11y'
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci other --targets=a11y
    env:
      STORYBOOK_SKIP_ANIMATION: true
    plugins:
      - file:///buildkite/plugins/docker:
          <<: *docker_plugin
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16-chrome
          environment:
            - 'BUILDKITE_API_TOKEN'
            - 'STORYBOOK_SKIP_ANIMATION'
      - file:///buildkite/plugins/cache: *cache_plugin

  - label: 'Percy (Web)'
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-percy storybook
    env:
      CONFIG_SERVICE_CONTEXT: percy-cds
      STORYBOOK_SKIP_ANIMATION: true
    plugins:
      - file:///buildkite/plugins/docker:
          <<: *docker_plugin
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16-chrome
          environment:
            - 'BUILDKITE_API_TOKEN'
            - 'PERCY_TOKEN'
            - 'STORYBOOK_SKIP_ANIMATION'
            - 'PERCY_TARGET_BRANCH'
      - file:///buildkite/plugins/cache: *cache_plugin

  - label: 'Visreg Tests (Mobile)'
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci other --targets=visreg
    artifact_paths:
      - percy-artifacts/**/*
    retry:
      automatic: false
