_shared_step: &shared_step
  env:
    OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: develop
    PERCY_TARGET_BRANCH: develop
  commands:
    - tools/ci/setup.sh
  plugins:
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - 'BUILDKITE_API_TOKEN'
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
  agents:
    queue: docker
    resource_class: large
  retry:
    automatic:
      limit: 1

steps:
  - label: Validate
    <<: *shared_step
    commands:
      - tools/ci/setup.sh
      - yarn nx workspace-lint
      - yarn mono-pipeline validate-codeowners
      - yarn mono-pipeline validate-lockfile

  - label: Build
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci build
      - tools/ci/uploadStorybookArtifacts.sh
    env:
      CONFIG_SERVICE_CONTEXT: cds-build
      STORYBOOK_SKIP_ANIMATION: true
      OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: develop
    plugins:
      - file:///buildkite/plugins/docker:
          <<: *docker_plugin
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16-chrome
          environment:
            - 'BUILDKITE_API_TOKEN'
            - 'STORYBOOK_SKIP_ANIMATION'
      - file:///buildkite/plugins/cache: *cache_plugin

  - label: Lint
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci lint

  - label: Format
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci format

  - label: Test
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci test

  - label: Typecheck
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - yarn mono-pipeline run-ci typecheck

  # Steps described below this line will not run in parallel. They will wait for the steps above to finish before running
  - wait

  - label: 'A11y'
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - tools/ci/downloadStorybookArtifacts.sh
      - yarn nx run storybook:a11y
    env:
      CONFIG_SERVICE_CONTEXT: cds-a11y
      STORYBOOK_SKIP_ANIMATION: true
      OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: develop
    plugins:
      - file:///buildkite/plugins/docker:
          <<: *docker_plugin
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16-chrome
          environment:
            - 'BUILDKITE_API_TOKEN'
            - 'STORYBOOK_SKIP_ANIMATION'
      - file:///buildkite/plugins/cache: *cache_plugin

  - label: 'Percy.io - CDS visual diff tests'
    <<: *shared_step
    parallelism: 1
    commands:
      - tools/ci/setup.sh
      - tools/ci/downloadStorybookArtifacts.sh
      - yarn nx run storybook:percy
    env:
      CONFIG_SERVICE_CONTEXT: percy-cds
      STORYBOOK_SKIP_ANIMATION: true
      OVERRIDE_BUILDKITE_PULL_REQUEST_BASE_BRANCH: develop
      PERCY_TARGET_BRANCH: develop
    plugins:
      - file:///buildkite/plugins/docker:
          <<: *docker_plugin
          image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:v16-chrome
          environment:
            - 'BUILDKITE_API_TOKEN'
            - 'PERCY_TOKEN'
            - 'STORYBOOK_SKIP_ANIMATION'
            - 'PERCY_TARGET_BRANCH'
      - file:///buildkite/plugins/cache: *cache_plugin
