_prebuild_shared_step: &prebuild_shared_step
  plugins:
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:android
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - BUILDKITE_API_TOKEN
  timeout_in_minutes: 45
  retry:
    automatic: true
  artifact_paths:
    - 'apps/mobile-playground/artifacts/**/*'
  agents:
    queue: metal

_visreg_android_shared: &visreg_android_shared
  plugins: &android_plugins
    - file:///buildkite/plugins/cache: &cache_plugin
        key: yarn-node-modules-{{ checksum "yarn.lock" }}-v1
        paths:
          - ./.yarn/cache
          - ./.yarn/install-state.gz
    - file:///buildkite/plugins/docker: &docker_plugin
        image: 652969937640.dkr.ecr.us-east-1.amazonaws.com/containers/node:android
        wait-network: true
        privileged: true
        always-pull: true
        propagate-environment: true
        propagate-uid-gid: true
        volumes:
          # Allow git operations to work
          - ${HOME}/.ssh:/root/.ssh
          - ${HOME}/.git:/root/.git
        environment:
          - PLAYSTORE_AUTH
          - KEY_PASSWORD
          - KEY_ALIAS
          - BUGSNAG_KEY
          - ANDROID_KEYSTORE
          - PLAYSTORE_PACKAGE_NAME
          - PERCY_TOKEN
          - PERCY_TARGET_BRANCH
    - ssh://git@github.cbhq.net/frontend/aws-sm-buildkite-plugin:
        env:
          PERCY_TOKEN: infra/buildkite/cds-percy-token-android
  timeout_in_minutes: 60
  agents:
    queue: metal
  retry:
    automatic:
      limit: 2

env:
  LANG: en_US.UTF-8
  CI: true
  NX_CAPTURE_METRICS: true
  NX_CAPTURE_TEST_METRICS: true
  ANDROID_NDK_HOME: '$$ANDROID_HOME/ndk/$$NDK_VERSION'
  PERCY_TOKEN_SECRET_ID: 'infra/buildkite/cds-percy-token-android'

steps:
  - label: Android - Prebuild - visreg
    key: 'visreg_android_prebuild'
    <<: *prebuild_shared_step
    commands:
      - tools/ci/visreg.sh android build

  - label: 'Visreg Test (Android) %N'
    <<: *visreg_android_shared
    depends_on: 'visreg_android_prebuild'
    key: 'visreg_android'
    parallelism: 8
    commands:
      - tools/ci/visreg.sh android test

  - label: 'Finish Visreg Tests (Android)'
    allow_dependency_failure: true
    depends_on: 'visreg_android'
    parallelism: 1
    <<: *visreg_android_shared
    commands:
      - npm install -g @percy/cli
      - npx percy build:finalize
