env:
  LANG: en_US.UTF-8
  CI: true
  NX_CAPTURE_METRICS: true
  NX_CAPTURE_TEST_METRICS: true
  IOS_PERCY_SECRET: 'infra/buildkite/cds-percy-token-ios'

steps:
  - label: 'Visreg Test (iOS) %N'
    key: 'visreg_ios'
    parallelism: 5
    agents:
      queue: macos-metal
    commands:
      - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$IOS_PERCY_SECRET --query SecretString --output text)
      - tools/ci/setup.sh
      - yarn nx run mobile-app:detox:ios-release
    retry:
      automatic:
        limit: 1

  - label: 'Finish Visreg Tests (iOS)'
    depends_on: 'visreg_ios'
    allow_dependency_failure: true
    agents:
      queue: macos-metal
    commands:
      - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$IOS_PERCY_SECRET --query SecretString --output text)
      - npm install -g @percy/cli
      - npx percy build:finalize
