env:
  LANG: en_US.UTF-8
  CI: true
  NX_CAPTURE_METRICS: true
  NX_CAPTURE_TEST_METRICS: true
  PERCY_TOKEN_SECRET_ID: 'infra/buildkite/cds-percy-token-ios'

steps:
  - label: 'Visreg Test (iOS) %n'
    cancel_on_build_failing: true
    key: 'visreg_ios'
    parallelism: 8
    agents:
      queue: macos-metal
    commands:
      - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$PERCY_TOKEN_SECRET_ID --query SecretString --output text)
      - tools/ci/visreg-ios.sh
    retry:
      automatic:
        limit: 1

  - label: 'Finish Visreg Tests (iOS)'
    depends_on: 'visreg_ios'
    allow_dependency_failure: true
    agents:
      queue: macos-metal
    commands:
      - export PERCY_TOKEN=$(aws secretsmanager get-secret-value --secret-id $$PERCY_TOKEN_SECRET_ID --query SecretString --output text)
      - tools/ci/visreg-finalize.sh
