/**
 * DO NOT MODIFY
 * @danger This file is generated by the icon-tasks:sync-icons script.
*/
import type { IconName } from './IconName';

/** Mapping of descriptions to associated icons. */ 
export const descriptionMap: Record<string, IconName[]> = {
  '0': [
    'step0'
  ],
  '1': [
    'step1'
  ],
  '2': [
    'step2'
  ],
  '3': [
    'step3'
  ],
  '4': [
    'step4'
  ],
  '5': [
    'step5'
  ],
  '6': [
    'step6'
  ],
  '7': [
    'step7'
  ],
  '8': [
    'step8'
  ],
  '9': [
    'step9'
  ],
  'navigation': [
    'hiddenEye',
    'trading',
    'queryTransact',
    'taxes',
    'appSwitcher',
    'collection',
    'light',
    'planet',
    'shoppingCart',
    'peopleGroup',
    'trophyCup',
    'moreVertical',
    'participate',
    'moon',
    'securityShield',
    'invoice',
    'gab',
    'heart',
    'account',
    'hammer',
    'tag',
    'giftBox',
    'support',
    'eye',
    'earn',
    'directDeposit',
    'crystalBall',
    'diamond',
    'comment',
    'chartPie',
    'chartCandles',
    'royalty',
    'cash',
    'caret',
    'browser',
    'documentation',
    'settings',
    'astronautHelmet',
    'newsFeed',
    'home',
    'sun',
    'pay',
    'defi',
    'paymentCard',
    'scanQrCode',
    'pencil',
    'cloud',
    'bell',
    'interest',
    'chartBar',
    'faces',
    'dashboard',
    'application',
    'addPeople',
    'ghost',
    'activity',
    'drops',
    'copy',
    'menu',
    'hamburger',
    'base',
    'walletLogo',
    'coinbaseOneLogo',
    'diamondIncentives'
  ],
  'speciality': [
    'hiddenEye',
    'trading',
    'taxes',
    'appSwitcher',
    'light',
    'planet',
    'shoppingCart',
    'peopleGroup',
    'trophyCup',
    'moreVertical',
    'moon',
    'securityShield',
    'invoice',
    'gab',
    'account',
    'tag',
    'giftBox',
    'support',
    'eye',
    'earn',
    'directDeposit',
    'crystalBall',
    'comment',
    'chartPie',
    'chartCandles',
    'cash',
    'caret',
    'browser',
    'documentation',
    'settings',
    'astronautHelmet',
    'newsFeed',
    'home',
    'sun',
    'pay',
    'defi',
    'paymentCard',
    'scanQrCode',
    'bell',
    'interest',
    'chartBar',
    'faces',
    'dashboard',
    'application',
    'addPeople',
    'coinbaseOne'
  ],
  'closed': [
    'hiddenEye',
    'invisible',
    'orderBook'
  ],
  'eye': [
    'hiddenEye',
    'eye',
    'invisible',
    'visible'
  ],
  'unwatch': [
    'hiddenEye',
    'invisible'
  ],
  'not visible': [
    'hiddenEye',
    'invisible'
  ],
  '👀': [
    'hiddenEye',
    'invisible',
    'visible'
  ],
  '👁': [
    'hiddenEye',
    'invisible',
    'visible'
  ],
  'average': [
    'trading',
    'continuous'
  ],
  'trading': [
    'trading',
    'gab',
    'chartCandles',
    'verticalLine',
    'rectangle',
    'pulse',
    'fib',
    'horizontalLine',
    'diagonalRightArrow',
    'crossTrade',
    'average',
    'continuous',
    'chartLine',
    'chartLine',
    'advancedTradeProduct',
    'candlesticks',
    'orderBook'
  ],
  'math': [
    'trading',
    'continuous',
    'calculator',
    'plusMinus'
  ],
  'graph': [
    'trading',
    'chartPie',
    'chartCandles',
    'chartBar',
    'chartVolume',
    'pyramid',
    'continuous'
  ],
  'mean': [
    'trading',
    'continuous'
  ],
  'median': [
    'trading',
    'continuous'
  ],
  'midpoint': [
    'trading',
    'continuous'
  ],
  'center': [
    'trading',
    'reCenter',
    'continuous',
    'helpCenterProduct',
    'helpCenterQuestionMark'
  ],
  'norm': [
    'trading',
    'continuous'
  ],
  'standard': [
    'trading',
    'continuous'
  ],
  'specialty': [
    'queryTransact',
    'participate',
    'heart',
    'hammer',
    'diamond',
    'royalty',
    'pencil',
    'cloud',
    'ghost',
    'activity',
    'drops',
    'copy',
    'diamondIncentives'
  ],
  'cloud': [
    'queryTransact',
    'participate',
    'cloud',
    'cloudProduct',
    'cloudPartial',
    'cloudPartial',
    'singlecloud'
  ],
  'query': [
    'queryTransact'
  ],
  'transact': [
    'queryTransact',
    'sendReceive',
    'baseTransact'
  ],
  'diamond': [
    'queryTransact',
    'diamond',
    'diamondIncentives',
    'earnRewards'
  ],
  'vibes': [
    'queryTransact',
    'participate'
  ],
  'percentage': [
    'taxes',
    'royalty',
    'interest',
    'percentage',
    'leadCoin'
  ],
  'tax': [
    'taxes',
    'royalty'
  ],
  'tax season': [
    'taxes'
  ],
  'document': [
    'taxes',
    'documentation',
    'application',
    'smartContract',
    'paperclip',
    'list',
    'document',
    'birthcertificate'
  ],
  '📄': [
    'taxes',
    'documentation',
    'application',
    'smartContract',
    'list',
    'document'
  ],
  '📃': [
    'taxes',
    'documentation',
    'application',
    'smartContract',
    'document'
  ],
  '📜': [
    'taxes',
    'documentation',
    'application',
    'smartContract',
    'document'
  ],
  '📑': [
    'taxes',
    'documentation',
    'application',
    'smartContract',
    'document'
  ],
  'switcher': [
    'appSwitcher'
  ],
  'apps': [
    'appSwitcher',
    'planet',
    'baseApps'
  ],
  'products': [
    'appSwitcher'
  ],
  'brand': [
    'appSwitcher',
    'sofort',
    'paypal',
    'ideal',
    'base',
    'walletLogo',
    'coinbaseOneLogo',
    'coinbaseOneCard'
  ],
  'grid': [
    'appSwitcher',
    'grid'
  ],
  'specialty collection': [
    'collection'
  ],
  'gallery': [
    'collection'
  ],
  'library': [
    'collection'
  ],
  'artworks': [
    'collection'
  ],
  'picture': [
    'collection',
    'paperclip',
    'image'
  ],
  'frame': [
    'collection'
  ],
  '🖼': [
    'collection'
  ],
  '📸': [
    'collection',
    'camera'
  ],
  'light': [
    'light',
    'sun',
    'flame'
  ],
  'beam': [
    'light'
  ],
  'glow': [
    'light',
    'flame'
  ],
  'moment': [
    'light'
  ],
  'sunshine': [
    'light'
  ],
  'best day': [
    'light',
    'sun'
  ],
  'summer': [
    'light',
    'sun'
  ],
  'daylight': [
    'light',
    'sun'
  ],
  'daytime': [
    'light',
    'sun'
  ],
  'rise and shine': [
    'light',
    'sun'
  ],
  '☀️': [
    'light',
    'sun'
  ],
  '🌞': [
    'light',
    'sun'
  ],
  '🌻': [
    'light',
    'sun'
  ],
  '🌅': [
    'light',
    'sun'
  ],
  'planet': [
    'planet'
  ],
  'space': [
    'planet',
    'astronautHelmet',
    'rocket'
  ],
  'crypto': [
    'planet',
    'pay',
    'ethereum',
    'currencies',
    'stake',
    'crypto',
    'baseQuickBuy',
    'coinsCrypto',
    'tokenLaunchCoin',
    'tokenLaunchRocket',
    'stablecoinStack',
    'airdropCoins',
    'airdropAlt',
    'airdropParachute'
  ],
  'adventure': [
    'planet',
    'airdropAlt'
  ],
  'stars': [
    'planet'
  ],
  'astronomy': [
    'planet'
  ],
  'orbit': [
    'planet'
  ],
  'gravity': [
    'planet'
  ],
  '🪐': [
    'planet',
    'astronautHelmet'
  ],
  '🔭': [
    'planet',
    'astronautHelmet'
  ],
  '🛸': [
    'planet',
    'astronautHelmet'
  ],
  '👽': [
    'planet',
    'astronautHelmet'
  ],
  '🌎': [
    'planet',
    'browser',
    'globe',
    'passport'
  ],
  '🌍': [
    'planet',
    'browser',
    'globe',
    'passport'
  ],
  '🌏': [
    'planet',
    'browser',
    'globe',
    'passport'
  ],
  'shopping': [
    'shoppingCart',
    'tag',
    'commerceProduct'
  ],
  'cart': [
    'shoppingCart',
    'commerceProduct'
  ],
  'checkout': [
    'shoppingCart',
    'tag'
  ],
  'trolley': [
    'shoppingCart'
  ],
  'groceries': [
    'shoppingCart'
  ],
  '🛒': [
    'shoppingCart'
  ],
  'faces': [
    'peopleGroup',
    'faces',
    'group'
  ],
  'humans': [
    'peopleGroup',
    'faces',
    'group'
  ],
  'people': [
    'peopleGroup',
    'faces',
    'addPeople',
    'followAdd',
    'following',
    'group',
    'peopleStar'
  ],
  'community': [
    'peopleGroup',
    'faces',
    'group'
  ],
  'circles': [
    'peopleGroup',
    'faces',
    'group',
    'verifiedPools'
  ],
  'friends': [
    'peopleGroup',
    'faces',
    'group'
  ],
  'family': [
    'peopleGroup',
    'faces',
    'group'
  ],
  '👯‍♀️': [
    'peopleGroup',
    'faces',
    'addPeople',
    'group'
  ],
  '👯': [
    'peopleGroup',
    'faces',
    'group'
  ],
  '👯‍♂️': [
    'peopleGroup',
    'faces',
    'group'
  ],
  '👨‍👩‍👧‍👦': [
    'peopleGroup',
    'faces',
    'group'
  ],
  '👨‍👩‍👦': [
    'peopleGroup',
    'faces',
    'group'
  ],
  '👨‍👩‍👧': [
    'peopleGroup',
    'faces',
    'group'
  ],
  'winner': [
    'trophyCup',
    'trophy'
  ],
  'win': [
    'trophyCup',
    'trophy',
    'medal',
    'ribbon',
    'starTrophy',
    'starAward'
  ],
  'reward': [
    'trophyCup',
    'interest',
    'percentage',
    'trophy',
    'peopleStar',
    'medal',
    'ribbon',
    'starTrophy',
    'starAward'
  ],
  'triumph': [
    'trophyCup',
    'trophy'
  ],
  'medal': [
    'trophyCup',
    'earn',
    'trophy'
  ],
  'first': [
    'trophyCup',
    'trophy',
    'coinbaseOne'
  ],
  'prize': [
    'trophyCup',
    'trophy'
  ],
  '🏆': [
    'trophyCup',
    'earn',
    'trophy'
  ],
  '🥇': [
    'trophyCup',
    'earn',
    'trophy'
  ],
  '🥈': [
    'trophyCup',
    'trophy'
  ],
  '🥉': [
    'trophyCup',
    'trophy'
  ],
  '🏅': [
    'trophyCup',
    'trophy'
  ],
  'more': [
    'moreVertical',
    'more',
    'derivatives'
  ],
  'kebab': [
    'moreVertical',
    'more'
  ],
  'mochi': [
    'moreVertical',
    'more'
  ],
  'additional': [
    'moreVertical',
    'more'
  ],
  'added': [
    'moreVertical',
    'more'
  ],
  'extra': [
    'moreVertical',
    'more'
  ],
  'filter': [
    'moreVertical',
    'sortUpCenter',
    'sortUp',
    'sortDownCenter',
    'sortDown',
    'more',
    'sortDoubleArrow',
    'filterLineStack'
  ],
  '🍡': [
    'moreVertical'
  ],
  'hexagon': [
    'participate'
  ],
  'developer': [
    'participate',
    'cloudProduct',
    'developerAPIProduct'
  ],
  'moon': [
    'moon',
    'scienceMoon'
  ],
  'night': [
    'moon'
  ],
  'dark mode': [
    'moon'
  ],
  'star': [
    'moon',
    'earn',
    'star',
    'crypto',
    'peopleStar',
    'creatorCoin',
    'baseQuickBuy'
  ],
  '🌕': [
    'moon'
  ],
  '🌖': [
    'moon'
  ],
  '🌗': [
    'moon'
  ],
  '🌘': [
    'moon'
  ],
  '🌑': [
    'moon'
  ],
  '🌒': [
    'moon'
  ],
  '🌓': [
    'moon'
  ],
  '🌔': [
    'moon'
  ],
  '🌙': [
    'moon'
  ],
  '🌛': [
    'moon'
  ],
  '🌜': [
    'moon'
  ],
  '🌝': [
    'moon'
  ],
  'shield': [
    'securityShield',
    'shield',
    'protection',
    'shieldOutline'
  ],
  'protection': [
    'securityShield',
    'eye',
    'setPinCode',
    'shield',
    'safe',
    'protection',
    'visible',
    'fscsProtection'
  ],
  'guard': [
    'securityShield',
    'shield',
    'protection'
  ],
  'defense': [
    'securityShield',
    'shield',
    'protection'
  ],
  'cover': [
    'securityShield',
    'shield',
    'protection'
  ],
  'safety': [
    'securityShield',
    'shield',
    'safe',
    'protection',
    'shieldOutline'
  ],
  'security': [
    'securityShield',
    'setPinCode',
    'shield',
    'safe',
    'fingerprint',
    'faceScan',
    'protection',
    'key',
    'securityKey',
    'shieldOutline'
  ],
  'invoice': [
    'invoice'
  ],
  'commerce': [
    'invoice',
    'tag',
    'commerceProduct'
  ],
  'paper': [
    'invoice',
    'document'
  ],
  'receipt': [
    'invoice'
  ],
  '🧾': [
    'invoice'
  ],
  'undo': [
    'undo'
  ],
  'mistake': [
    'undo'
  ],
  'arrow': [
    'undo',
    'collapse',
    'reCenter',
    'expand',
    'expandAll',
    'downArrow',
    'diagonalUpArrow',
    'diagonalDownArrow',
    'upArrow',
    'logout',
    'login',
    'sendReceive',
    'socialShare',
    'socialReshare',
    'beginningArrow',
    'endArrow',
    'overPredictions',
    'underPredictions'
  ],
  'reverse': [
    'undo',
    'backArrow',
    'arrowLeft'
  ],
  'side by side': [
    'gab',
    'arrowsHorizontal'
  ],
  'left': [
    'gab',
    'caretLeft',
    'arrowsHorizontal',
    'beginningArrow'
  ],
  'right': [
    'gab',
    'doubleChevronRight',
    'caretRight',
    'arrowsHorizontal',
    'logout',
    'login',
    'endArrow'
  ],
  'opposite': [
    'gab',
    'arrowsHorizontal'
  ],
  'retrieve': [
    'gab',
    'cash'
  ],
  'sell': [
    'gab',
    'minus',
    'crossTrade'
  ],
  'convert': [
    'gab',
    'convert'
  ],
  '↔️': [
    'gab',
    'arrowsHorizontal'
  ],
  'heart': [
    'heart',
    'support'
  ],
  'like': [
    'heart'
  ],
  'special': [
    'heart',
    'drops'
  ],
  '❤️': [
    'heart'
  ],
  '': [
    'heart',
    'magnifyingGlass',
    'wallet',
    'rocketShip',
    'wrapToken',
    'chartPieCircle',
    'book',
    'blog',
    'cryptobasics',
    'megaphone',
    'lightbulb',
    'pFPS',
    'refresh',
    'taxesReceipt',
    'newsletter',
    'sparkle',
    'cashBrazillianReal',
    'institute',
    'payouts',
    'qrCodeAlt',
    'outline',
    'affiliates',
    'collectibles',
    'cashPolishZloty',
    'cashUSD',
    'add',
    'cashEUR',
    'generalCharacter',
    'cashGBP',
    'cashBrazilianReal',
    'arrowsVertical',
    'artwork',
    'transactions',
    'arrowUp',
    'filter',
    'dex',
    'cashJPY',
    'eventContracts',
    'perpetualSwap',
    'rollingSpot',
    'folderArrow',
    'folder',
    'regulatedFutures',
    'options',
    'compass',
    'waasProduct',
    'signinProduct',
    'rosettaProduct',
    'exchangeProduct',
    'primePoduct',
    'staking',
    'noRocket',
    'crypto',
    'developerPlatformProduct',
    'priceAlerts',
    'verifiedPools',
    'barChartWindow',
    'concierge',
    'conciergeBell',
    'peopleStar',
    'coinbaseOneCard',
    'plane',
    'compose',
    'dataStack',
    'beaker',
    'block',
    'chatRequests',
    'leadChart',
    'grid',
    'fscsProtection',
    'config',
    'baseQuickBuy',
    'moneyCardCoin',
    'crystalBallInsight',
    'football',
    'basketball',
    'pillBottle',
    'needle',
    'scienceMoon',
    'microscope',
    'greenEnergy',
    'umbrella',
    'hurricane',
    'barChartSimple',
    'computerChip',
    'cloudPartial',
    'apothecary',
    'briefcaseAlt',
    'pillCapsule',
    'singlecloud',
    'rain',
    'autoCar',
    'column'
  ],
  'profile': [
    'account',
    'identityCard',
    'profile',
    'avatar'
  ],
  'account': [
    'account',
    'logout',
    'login',
    'gaugeHigh',
    'gaugeHighMid'
  ],
  'person': [
    'account',
    'followAdd',
    'following',
    'profile',
    'chatBotAgent',
    'avatar'
  ],
  'individual': [
    'account',
    'profile',
    'avatar'
  ],
  'minting': [
    'hammer'
  ],
  'creating': [
    'hammer'
  ],
  'making': [
    'hammer'
  ],
  'building': [
    'hammer',
    'home',
    'bank',
    'city',
    'factory',
    'corporation',
    'building'
  ],
  'mint': [
    'hammer',
    'mint'
  ],
  'pickaxe': [
    'hammer'
  ],
  '🔨': [
    'hammer'
  ],
  '⚒': [
    'hammer'
  ],
  '⚒️': [
    'hammer'
  ],
  'tag': [
    'tag'
  ],
  '🏷': [
    'tag'
  ],
  '🔖': [
    'tag',
    'bookmark'
  ],
  'gift box': [
    'giftBox'
  ],
  'present': [
    'giftBox',
    'giftCard'
  ],
  'rewards': [
    'giftBox',
    'earn',
    'learningRewardsProduct',
    'rewardsProduct',
    'coinbaseRewards',
    'earnRewards',
    'medal',
    'ribbon',
    'starTrophy',
    'starAward'
  ],
  'joy': [
    'giftBox'
  ],
  'contribution': [
    'giftBox'
  ],
  'perk': [
    'giftBox'
  ],
  'giving': [
    'giftBox'
  ],
  '🎁': [
    'giftBox',
    'giftCard'
  ],
  '🎉': [
    'giftBox',
    'giftCard'
  ],
  '🎊': [
    'giftBox',
    'giftCard'
  ],
  '🥳': [
    'giftBox',
    'giftCard'
  ],
  'support': [
    'support',
    'chatBotAgent'
  ],
  'help': [
    'support',
    'exclamationMark',
    'info',
    'chatBotAgent',
    'helpCenterProduct',
    'helpCenterQuestionMark'
  ],
  'communication': [
    'support',
    'chatBubble',
    'telephone',
    'disabledPhone'
  ],
  'chat': [
    'support',
    'comment',
    'chatBotAgent',
    'discordLogo',
    'socialChat',
    'chatRequests'
  ],
  'assist': [
    'support'
  ],
  'aid': [
    'support'
  ],
  '💕': [
    'support'
  ],
  '💙': [
    'support'
  ],
  '💜': [
    'support'
  ],
  '💗': [
    'support'
  ],
  '🖤': [
    'support'
  ],
  '💛': [
    'support'
  ],
  '💖': [
    'support'
  ],
  '💚': [
    'support'
  ],
  '🧡': [
    'support'
  ],
  '💬': [
    'support',
    'comment',
    'chatBubble',
    'chatBotAgent',
    'socialChat'
  ],
  '🎗': [
    'support'
  ],
  '📞': [
    'support',
    'telephone',
    'disabledPhone'
  ],
  '☎️': [
    'support',
    'telephone',
    'disabledPhone'
  ],
  'privacy': [
    'eye',
    'visible'
  ],
  'personal': [
    'eye',
    'identityCard',
    'visible'
  ],
  'earn': [
    'earn',
    'earnProduct',
    'earnRewards'
  ],
  '✨': [
    'earn',
    'crystalBall',
    'drops',
    'nft'
  ],
  '❇️': [
    'earn',
    'crystalBall',
    'pulse',
    'nft'
  ],
  'direct': [
    'directDeposit',
    'directDepositIcon'
  ],
  'deposit': [
    'directDeposit',
    'deposit',
    'stake',
    'directDepositIcon'
  ],
  'money': [
    'directDeposit',
    'paymentCard',
    'cashRupee',
    'cashThaiBaht',
    'cashVietnameseDong',
    'cashUaeDirham',
    'cashTurkishLira',
    'cashSwissFranc',
    'cashPhilippinePeso',
    'directDepositIcon',
    'card',
    'bank',
    'cashIndonesianRupiah',
    'cashAustralianDollar',
    'cashSingaporeDollar',
    'cashCanadianDollar',
    'payments',
    'earnRewards'
  ],
  'transfer': [
    'directDeposit',
    'doubleChevronRight',
    'directDepositIcon',
    'sendReceive',
    'distribution',
    'pieChartWithArrow'
  ],
  'payment': [
    'directDeposit',
    'pay',
    'sofort',
    'paypal',
    'directDepositIcon',
    'ideal',
    'calendarMoney'
  ],
  'pay': [
    'directDeposit',
    'cash',
    'pay',
    'paymentCard',
    'nftOffer',
    'currencies',
    'directDepositIcon',
    'card',
    'payProduct',
    'payments'
  ],
  '💰': [
    'directDeposit',
    'cash',
    'cashRupee',
    'directDepositIcon',
    'payments'
  ],
  '💵': [
    'directDeposit',
    'cash',
    'cashRupee',
    'cashThaiBaht',
    'cashVietnameseDong',
    'cashUaeDirham',
    'cashTurkishLira',
    'cashSwissFranc',
    'cashPhilippinePeso',
    'directDepositIcon',
    'bank',
    'cashIndonesianRupiah',
    'cashAustralianDollar',
    'cashSingaporeDollar',
    'cashCanadianDollar',
    'payments'
  ],
  '💸': [
    'directDeposit',
    'cash',
    'cashRupee',
    'cashThaiBaht',
    'cashVietnameseDong',
    'cashUaeDirham',
    'cashTurkishLira',
    'cashSwissFranc',
    'cashPhilippinePeso',
    'directDepositIcon',
    'bank',
    'cashIndonesianRupiah',
    'cashAustralianDollar',
    'cashSingaporeDollar',
    'cashCanadianDollar'
  ],
  '💴': [
    'directDeposit',
    'directDepositIcon',
    'bank'
  ],
  '💷': [
    'directDeposit',
    'directDepositIcon',
    'bank'
  ],
  '💶': [
    'directDeposit',
    'directDepositIcon',
    'bank'
  ],
  'non fungible token': [
    'crystalBall',
    'nft'
  ],
  'blockchain': [
    'crystalBall',
    'defi',
    'nft',
    'ethereum',
    'blockchain'
  ],
  'certify': [
    'crystalBall',
    'nft'
  ],
  'magical': [
    'crystalBall',
    'nft'
  ],
  'audio': [
    'crystalBall',
    'crystalBall',
    'nft',
    'nft',
    'entertainment',
    'entertainment',
    'tv',
    'filmStrip',
    'singleNote',
    'singleNote',
    'playbutton',
    'playbutton',
    'musicArticles',
    'musicArticles',
    'microphoneCordless',
    'microphoneCordless',
    'tvStand'
  ],
  'photos': [
    'crystalBall',
    'nft',
    'instagramLogo'
  ],
  'digital': [
    'crystalBall',
    'nft'
  ],
  'art': [
    'crystalBall',
    'nft'
  ],
  'items': [
    'crystalBall',
    'list',
    'nft'
  ],
  '🪄': [
    'crystalBall',
    'nft'
  ],
  '🔮': [
    'crystalBall',
    'nft'
  ],
  'rare': [
    'diamond',
    'drops',
    'diamondIncentives'
  ],
  'crystal': [
    'diamond',
    'diamondIncentives'
  ],
  'gem': [
    'diamond',
    'diamondIncentives'
  ],
  'hold': [
    'diamond',
    'diamondIncentives'
  ],
  '💎': [
    'diamond',
    'diamondIncentives'
  ],
  'comment': [
    'comment',
    'annotation',
    'commentPlus'
  ],
  'speak': [
    'comment',
    'microphone'
  ],
  'bubble': [
    'comment',
    'socialChat',
    'commentPlus'
  ],
  'thread': [
    'comment'
  ],
  'message': [
    'comment',
    'error',
    'email',
    'chatBubble',
    'warning'
  ],
  '🗣': [
    'comment'
  ],
  'chart pie': [
    'chartPie'
  ],
  'data': [
    'chartPie',
    'chartCandles',
    'chartBar',
    'upload',
    'chartVolume',
    'pyramid',
    'api',
    'download',
    'dataMarketplaceProduct',
    'dataStack',
    'beaker',
    'allocation',
    'config'
  ],
  'visualization': [
    'chartPie',
    'chartCandles',
    'chartBar',
    'chartVolume',
    'pyramid'
  ],
  'numbers': [
    'chartPie',
    'chartCandles',
    'chartBar',
    'step7',
    'step5',
    'step4',
    'step3',
    'step2',
    'step1',
    'step0',
    'step8',
    'step6',
    'chartVolume',
    'pyramid',
    'step9',
    'calculator'
  ],
  '📊': [
    'chartPie',
    'chartCandles',
    'chartBar',
    'fib',
    'chartVolume',
    'crossTrade',
    'pyramid'
  ],
  '📉': [
    'chartPie',
    'chartCandles',
    'chartBar',
    'pulse',
    'marketCap',
    'fib',
    'chartVolume',
    'crossTrade',
    'pyramid',
    'chartLine'
  ],
  '📈': [
    'chartPie',
    'chartCandles',
    'chartBar',
    'pulse',
    'marketCap',
    'fib',
    'chartVolume',
    'crossTrade',
    'pyramid',
    'chartLine'
  ],
  '🥧': [
    'chartPie'
  ],
  'chart': [
    'chartCandles',
    'fib',
    'pyramid',
    'chartLine',
    'lineChartCrypto',
    'candlesticks',
    'leadChart'
  ],
  'candles': [
    'chartCandles'
  ],
  'passive': [
    'royalty'
  ],
  'income': [
    'royalty'
  ],
  'royalties': [
    'royalty'
  ],
  'crown': [
    'royalty'
  ],
  '👑': [
    'royalty'
  ],
  'wallet': [
    'cash',
    'walletLogo',
    'walletProduct',
    'payments',
    'baseWallet',
    'baseApps',
    'baseSquare',
    'baseTransact'
  ],
  'cash': [
    'cash',
    'cashRupee'
  ],
  'see more': [
    'caret'
  ],
  'chevron': [
    'caret',
    'doubleChevronRight',
    'expandAddress',
    'caretDown',
    'caretUp',
    'caretLeft',
    'caretRight'
  ],
  'caret': [
    'caret',
    'expandAddress',
    'caretDown',
    'caretUp',
    'caretLeft',
    'caretRight'
  ],
  '🔽': [
    'caret',
    'sortDownCenter',
    'sortDown',
    'sortDoubleArrow'
  ],
  '👇': [
    'caret',
    'downArrow',
    'drag'
  ],
  'globe': [
    'browser',
    'globe'
  ],
  'earth': [
    'browser',
    'globe',
    'passport'
  ],
  'international': [
    'browser',
    'cashRupee',
    'globe',
    'cashThaiBaht',
    'cashVietnameseDong',
    'cashUaeDirham',
    'cashTurkishLira',
    'cashSwissFranc',
    'cashPhilippinePeso',
    'cashIndonesianRupiah',
    'cashAustralianDollar',
    'cashSingaporeDollar',
    'cashCanadianDollar',
    'passport'
  ],
  'continents': [
    'browser',
    'globe'
  ],
  'global': [
    'browser',
    'globe',
    'passport'
  ],
  'internet': [
    'browser',
    'noWifi',
    'wifi'
  ],
  'browsing': [
    'browser'
  ],
  'surfing': [
    'browser'
  ],
  '🌐': [
    'browser',
    'globe',
    'passport'
  ],
  'smart': [
    'documentation',
    'application',
    'smartContract'
  ],
  'contract': [
    'documentation',
    'application',
    'smartContract',
    'document'
  ],
  'rules': [
    'documentation',
    'application',
    'smartContract'
  ],
  'policy': [
    'documentation',
    'application',
    'smartContract'
  ],
  'list': [
    'documentation',
    'application',
    'smartContract',
    'list',
    'staggeredList',
    'orderBook'
  ],
  'agreement': [
    'documentation',
    'application',
    'smartContract'
  ],
  'commitment': [
    'documentation',
    'application',
    'smartContract'
  ],
  'arrangement': [
    'documentation',
    'application',
    'smartContract'
  ],
  'settlement': [
    'documentation',
    'application',
    'smartContract'
  ],
  'settings': [
    'settings',
    'gear'
  ],
  'cog': [
    'settings',
    'gear'
  ],
  'machine': [
    'settings',
    'gauge',
    'gear',
    'gaugeEmpty',
    'gaugeLow',
    'gaugeMedium',
    'gaugeHigh',
    'gaugeHighMid',
    'gaugeLowMid',
    'gaugeHighLow',
    'gaugeLowHigh',
    'dataStack'
  ],
  '⚙️': [
    'settings',
    'gear'
  ],
  'helmet': [
    'astronautHelmet',
    'motorsport'
  ],
  'astronaut': [
    'astronautHelmet'
  ],
  'galaxy': [
    'astronautHelmet'
  ],
  '👩‍🚀': [
    'astronautHelmet'
  ],
  '🧑‍🚀': [
    'astronautHelmet'
  ],
  '👨‍🚀': [
    'astronautHelmet'
  ],
  'newsfeed': [
    'newsFeed',
    'baseFeed'
  ],
  'news': [
    'newsFeed',
    'bell'
  ],
  'articles': [
    'newsFeed'
  ],
  'layout': [
    'newsFeed'
  ],
  '📰': [
    'newsFeed'
  ],
  '🗞': [
    'newsFeed'
  ],
  'home': [
    'home',
    'dashboard'
  ],
  'hub': [
    'home',
    'assetHubProduct'
  ],
  'central': [
    'home'
  ],
  'homepage': [
    'home'
  ],
  '🏡': [
    'home'
  ],
  '🏠': [
    'home'
  ],
  'sun': [
    'sun',
    'image'
  ],
  'sunny': [
    'sun'
  ],
  'sunlight': [
    'sun'
  ],
  'finance': [
    'pay',
    'defi',
    'calendarMoney'
  ],
  'assets': [
    'pay',
    'assetHubProduct'
  ],
  'coin': [
    'pay',
    'coinbase',
    'coinbaseCardProduct',
    'crypto',
    'leadCoin',
    'leadChart',
    'savingsBank',
    'creatorCoin',
    'distribution',
    'baseQuickBuy',
    'stableCoin',
    'usdc'
  ],
  'defi': [
    'defi'
  ],
  'c crypto': [
    'defi'
  ],
  'arrow down': [
    'deposit',
    'download'
  ],
  '⬇️': [
    'deposit',
    'arrowDown',
    'sortDownCenter',
    'sortDown',
    'downArrow',
    'download',
    'sortDoubleArrow'
  ],
  'card': [
    'paymentCard',
    'giftCard',
    'identityCard',
    'card',
    'coinbaseCardProduct',
    'coinbaseOneCard'
  ],
  'credit': [
    'paymentCard',
    'wireTransfer',
    'card'
  ],
  'debit': [
    'paymentCard',
    'card'
  ],
  '💳': [
    'paymentCard',
    'sofort',
    'paypal',
    'card',
    'ideal'
  ],
  '🏦': [
    'paymentCard',
    'sofort',
    'paypal',
    'card',
    'bank',
    'ideal'
  ],
  '🏧': [
    'paymentCard',
    'card',
    'bank'
  ],
  'qr code': [
    'scanQrCode',
    'qrCode'
  ],
  'scan': [
    'scanQrCode',
    'qrCode',
    'fingerprint',
    'faceScan',
    'camera'
  ],
  'matrix': [
    'scanQrCode',
    'qrCode'
  ],
  'barcode': [
    'scanQrCode',
    'qrCode'
  ],
  'label': [
    'scanQrCode',
    'qrCode'
  ],
  'readable': [
    'scanQrCode',
    'qrCode'
  ],
  'information': [
    'scanQrCode',
    'qrCode',
    'info',
    'closeCaption'
  ],
  'pencil': [
    'pencil',
    'compose',
    'educationPencil'
  ],
  'pen': [
    'pencil'
  ],
  'edit': [
    'pencil'
  ],
  'correct': [
    'pencil'
  ],
  'check': [
    'pencil',
    'circleCross',
    'circleCheckmark',
    'checkmark',
    'checkboxChecked',
    'verifiedBadge',
    'priceAlertsCheck',
    'bellCheck',
    'bellPlus',
    'gitHubLogo',
    'baseVerification'
  ],
  'copyedit': [
    'pencil'
  ],
  'improve': [
    'pencil'
  ],
  '✏️': [
    'pencil',
    'compose'
  ],
  '📝': [
    'pencil',
    'annotation',
    'compose'
  ],
  '✍️': [
    'pencil'
  ],
  '🖊': [
    'pencil',
    'compose'
  ],
  '🖋': [
    'pencil'
  ],
  '✒️': [
    'pencil'
  ],
  'condensation': [
    'cloud'
  ],
  'water': [
    'cloud',
    'faucet'
  ],
  'droplets': [
    'cloud'
  ],
  'vapor': [
    'cloud'
  ],
  'science rules': [
    'cloud'
  ],
  'nature': [
    'cloud'
  ],
  '☁️': [
    'cloud'
  ],
  '🌤': [
    'cloud'
  ],
  '🌥': [
    'cloud'
  ],
  '⛅️': [
    'cloud'
  ],
  '🌧': [
    'cloud'
  ],
  '🌨': [
    'cloud'
  ],
  '⛈': [
    'cloud',
    'lightningBolt'
  ],
  '🌩': [
    'cloud',
    'lightningBolt'
  ],
  '💦': [
    'cloud',
    'faucet'
  ],
  '💧': [
    'cloud',
    'faucet'
  ],
  'notification': [
    'bell',
    'warning'
  ],
  'update': [
    'bell'
  ],
  'new': [
    'bell'
  ],
  'bell': [
    'bell',
    'concierge',
    'conciergeBell',
    'baseNotification'
  ],
  '🔔': [
    'bell',
    'priceAlerts',
    'priceAlertsCheck',
    'bellCheck',
    'bellPlus',
    'conciergeBell'
  ],
  '🛎': [
    'bell'
  ],
  'interest': [
    'interest',
    'percentage'
  ],
  'rate': [
    'interest',
    'percentage'
  ],
  'ratio': [
    'interest',
    'percentage'
  ],
  'pct': [
    'interest',
    'percentage'
  ],
  'measurement': [
    'interest',
    'percentage'
  ],
  '%': [
    'interest',
    'percentage',
    'leadCoin'
  ],
  'chart bar': [
    'chartBar',
    'chartVolume'
  ],
  'dashboard': [
    'dashboard'
  ],
  'everything': [
    'dashboard'
  ],
  'graphs': [
    'dashboard'
  ],
  'content': [
    'dashboard'
  ],
  'add': [
    'addPeople',
    'followAdd',
    'following',
    'calculator',
    'bellCheck',
    'bellPlus',
    'commentPlus'
  ],
  'invite': [
    'addPeople',
    'followAdd',
    'following'
  ],
  'refer': [
    'addPeople'
  ],
  'follow': [
    'addPeople',
    'followAdd',
    'following'
  ],
  '➕': [
    'addPeople',
    'followAdd',
    'following',
    'mint',
    'plusMinus'
  ],
  '👨‍👩‍👦‍👦': [
    'addPeople',
    'addPeople'
  ],
  '👨‍👩‍👧‍👧': [
    'addPeople'
  ],
  'ghost': [
    'ghost'
  ],
  'hide': [
    'ghost'
  ],
  'hidden': [
    'ghost'
  ],
  'unseen': [
    'ghost'
  ],
  '👻': [
    'ghost'
  ],
  'activities': [
    'activity'
  ],
  'history': [
    'activity',
    'orderHistory',
    'recurring'
  ],
  'trending': [
    'activity',
    'flame'
  ],
  'sparkles': [
    'drops'
  ],
  'drops': [
    'drops'
  ],
  'copy': [
    'copy'
  ],
  'mimic': [
    'copy'
  ],
  'duplicate': [
    'copy'
  ],
  'identical': [
    'copy'
  ],
  'another': [
    'copy'
  ],
  'hamburger': [
    'menu',
    'hamburger'
  ],
  'menu': [
    'menu',
    'hamburger'
  ],
  '🍔': [
    'menu',
    'hamburger'
  ],
  '🥪': [
    'menu',
    'hamburger'
  ],
  'spin': [
    'setPinCode'
  ],
  'password': [
    'setPinCode'
  ],
  'code': [
    'setPinCode'
  ],
  'device': [
    'setPinCode',
    'laptop',
    'keyboard',
    'telephone',
    'disabledPhone'
  ],
  'phone': [
    'setPinCode',
    'phone',
    'telephone',
    'disabledPhone',
    'disabledPhone'
  ],
  'laptop': [
    'setPinCode'
  ],
  '🔐': [
    'setPinCode',
    'lock',
    'unlock',
    'baseLock'
  ],
  'order': [
    'orderHistory',
    'step7',
    'step5',
    'step4',
    'step3',
    'step2',
    'step1',
    'step0',
    'step8',
    'step6',
    'step9',
    'orderBook'
  ],
  'past': [
    'orderHistory'
  ],
  'inventory': [
    'orderHistory'
  ],
  'records': [
    'orderHistory'
  ],
  '🕦': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕐': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕚': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕥': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕧': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕙': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕣': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕠': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕝': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕢': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕟': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕜': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕤': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕡': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕞': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕘': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕒': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕗': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕔': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕑': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕖': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕓': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕛': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '⏰': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '⏱': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🕰': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '🔄': [
    'orderHistory',
    'recurring',
    'convert',
    'clockOutline',
    'clock'
  ],
  '⏳': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  '⌛️': [
    'orderHistory',
    'recurring',
    'clockOutline',
    'clock'
  ],
  'collapse': [
    'collapse'
  ],
  'shrink': [
    'collapse'
  ],
  'lessen': [
    'collapse'
  ],
  'vertical': [
    'verticalLine'
  ],
  'line': [
    'verticalLine',
    'pulse',
    'horizontalLine',
    'chartLine',
    'chartLine',
    'lineChartCrypto',
    'filterLineStack'
  ],
  'calendar': [
    'calendar',
    'calendarEmpty',
    'calendarBlank',
    'calendarDates',
    'calendarMoney',
    'calendarStar',
    'calendarHeart'
  ],
  'date': [
    'calendar',
    'calendarEmpty',
    'calendarDates',
    'calendarMoney',
    'calendarStar',
    'calendarHeart'
  ],
  'year': [
    'calendar',
    'calendarEmpty'
  ],
  'month': [
    'calendar',
    'calendarEmpty'
  ],
  'week': [
    'calendar',
    'calendarEmpty'
  ],
  'schedule': [
    'calendar',
    'calendarEmpty',
    'calendarDates'
  ],
  '📆': [
    'calendar',
    'calendarEmpty'
  ],
  '📅': [
    'calendar',
    'calendarEmpty'
  ],
  '🗓': [
    'calendar',
    'calendarEmpty'
  ],
  'withdraw': [
    'withdraw'
  ],
  'arrow up': [
    'withdraw',
    'arrowDown'
  ],
  'extract': [
    'withdraw'
  ],
  'draw out': [
    'withdraw'
  ],
  'take': [
    'withdraw'
  ],
  '⬆️': [
    'withdraw',
    'upload',
    'sortUpCenter',
    'sortUp',
    'upArrow',
    'allTimeHigh'
  ],
  '🔝': [
    'withdraw',
    'sortUpCenter',
    'sortUp',
    'upArrow'
  ],
  'receive': [
    'arrowDown',
    'sendReceive'
  ],
  'downwards': [
    'arrowDown',
    'downArrow'
  ],
  'decrease': [
    'arrowDown',
    'soundOff'
  ],
  '⬇': [
    'arrowDown'
  ],
  '₹': [
    'cashRupee'
  ],
  'currency': [
    'cashRupee',
    'cashThaiBaht',
    'currencies',
    'cashVietnameseDong',
    'cashUaeDirham',
    'cashTurkishLira',
    'cashSwissFranc',
    'cashPhilippinePeso',
    'bank',
    'cashIndonesianRupiah',
    'cashAustralianDollar',
    'cashSingaporeDollar',
    'cashCanadianDollar'
  ],
  'india': [
    'cashRupee'
  ],
  'indonesia': [
    'cashRupee'
  ],
  'the maldives': [
    'cashRupee'
  ],
  'mauritius': [
    'cashRupee'
  ],
  'nepal': [
    'cashRupee'
  ],
  'pakistan': [
    'cashRupee'
  ],
  'seychelles': [
    'cashRupee'
  ],
  'sri lanka': [
    'cashRupee'
  ],
  '🇮🇳': [
    'cashRupee'
  ],
  '🇮🇩': [
    'cashRupee',
    'cashIndonesianRupiah'
  ],
  '🇲🇻': [
    'cashRupee'
  ],
  '🇲🇺': [
    'cashRupee'
  ],
  '🇳🇵': [
    'cashRupee'
  ],
  '🇵🇰': [
    'cashRupee'
  ],
  '🇸🇨': [
    'cashRupee'
  ],
  '🇱🇰': [
    'cashRupee'
  ],
  'minus': [
    'minus',
    'calculator',
    'plusMinus'
  ],
  'subtract': [
    'minus',
    'calculator'
  ],
  '➖': [
    'minus',
    'plusMinus'
  ],
  'search': [
    'search'
  ],
  'magnifying glass': [
    'search',
    'regulated'
  ],
  'look': [
    'search'
  ],
  'explore': [
    'search'
  ],
  '🔎': [
    'search',
    'regulated'
  ],
  '🔍': [
    'search',
    'regulated'
  ],
  '🕵️': [
    'search'
  ],
  '🕵️‍♀️': [
    'search'
  ],
  '🕵️‍♂️': [
    'search'
  ],
  'wire transfer': [
    'wireTransfer'
  ],
  'send': [
    'wireTransfer',
    'share',
    'paperAirplane',
    'airdrop',
    'bridging',
    'sendReceive',
    'payments'
  ],
  'bank': [
    'wireTransfer',
    'bank',
    'savingsBank'
  ],
  'electronic': [
    'wireTransfer'
  ],
  'inactive': [
    'invisible'
  ],
  'recurring': [
    'recurring'
  ],
  'clock': [
    'recurring',
    'clockOutline',
    'clock',
    'instantUnstakingClock'
  ],
  'time': [
    'recurring',
    'recurring',
    'clockOutline',
    'clock',
    'chatRequests',
    'calendarDates'
  ],
  'back': [
    'recurring'
  ],
  'upload': [
    'upload'
  ],
  'transmit': [
    'upload'
  ],
  'file': [
    'upload',
    'paperclip'
  ],
  'uploading': [
    'upload'
  ],
  '🔼': [
    'upload',
    'sortUpCenter',
    'sortUp',
    'upArrow'
  ],
  '⏫': [
    'upload'
  ],
  '📎': [
    'upload',
    'paperclip'
  ],
  '🖇': [
    'upload',
    'paperclip',
    'chainLink'
  ],
  '🗃': [
    'upload',
    'paperclip'
  ],
  '📁': [
    'upload',
    'paperclip'
  ],
  '📂': [
    'upload',
    'paperclip'
  ],
  '🗂': [
    'upload',
    'paperclip'
  ],
  'unknown': [
    'unknown',
    'checkboxEmpty',
    'questionMark'
  ],
  'question': [
    'unknown',
    'questionMark',
    'helpCenterQuestionMark'
  ],
  'question mark': [
    'unknown'
  ],
  '?': [
    'unknown',
    'unknown'
  ],
  'mystery': [
    'unknown'
  ],
  '❓': [
    'unknown',
    'questionMark'
  ],
  '❔': [
    'unknown'
  ],
  '⁇': [
    'unknown'
  ],
  '﹖': [
    'unknown'
  ],
  '︖': [
    'unknown'
  ],
  'trash': [
    'trashCan'
  ],
  'rubbish': [
    'trashCan'
  ],
  'remove': [
    'trashCan',
    'circleCross'
  ],
  'junk': [
    'trashCan'
  ],
  'waste': [
    'trashCan'
  ],
  'delete': [
    'trashCan',
    'circleCross'
  ],
  '🗑': [
    'trashCan'
  ],
  '🚮': [
    'trashCan'
  ],
  'yes': [
    'thumbsUpOutline',
    'thumbsUp'
  ],
  'thumbs up': [
    'thumbsUpOutline',
    'thumbsUp'
  ],
  'thumb': [
    'thumbsUpOutline',
    'thumbsDown',
    'thumbsDownOutline',
    'thumbsUp'
  ],
  'up': [
    'thumbsUpOutline',
    'sortUpCenter',
    'sortUp',
    'diagonalUpArrow',
    'thumbsUp',
    'caretUp',
    'upArrow',
    'allTimeHigh',
    'sendReceive',
    'candlesticks',
    'arrowsUpDown'
  ],
  '👍': [
    'thumbsUpOutline',
    'thumbsUp'
  ],
  'no': [
    'thumbsDown',
    'thumbsDownOutline'
  ],
  'thumbs down': [
    'thumbsDown',
    'thumbsDownOutline'
  ],
  'down': [
    'thumbsDown',
    'sortDownCenter',
    'sortDown',
    'downArrow',
    'thumbsDownOutline',
    'caretDown',
    'diagonalDownArrow',
    'sortDoubleArrow',
    'sendReceive',
    'candlesticks',
    'arrowsUpDown'
  ],
  '👎': [
    'thumbsDown',
    'thumbsDownOutline'
  ],
  'step seven': [
    'step7'
  ],
  'sequence': [
    'step7',
    'step5',
    'step4',
    'step3',
    'step2',
    'step1',
    'step0',
    'step8',
    'step6',
    'step9'
  ],
  'instructions': [
    'step7',
    'step5',
    'step4',
    'step3',
    'step2',
    'step1',
    'step0',
    'step8',
    'step6',
    'step9'
  ],
  'step five': [
    'step5'
  ],
  'step four': [
    'step4'
  ],
  'step three': [
    'step3'
  ],
  'step two': [
    'step2'
  ],
  'step one': [
    'step1'
  ],
  'step zero': [
    'step0'
  ],
  'favorite': [
    'star',
    'calendarHeart'
  ],
  '⭐️': [
    'star'
  ],
  '🌟': [
    'star'
  ],
  '💫': [
    'star'
  ],
  '🤩': [
    'star'
  ],
  'active': [
    'star',
    'bookmark'
  ],
  'sound': [
    'soundOn',
    'soundOff',
    'play',
    'pause',
    'speaker',
    'entertainment',
    'singleNote',
    'musicArticles'
  ],
  'on': [
    'soundOn',
    'passKey'
  ],
  'volume': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  'increase': [
    'soundOn'
  ],
  'loud': [
    'soundOn'
  ],
  'music': [
    'soundOn',
    'soundOff',
    'play',
    'music',
    'pause',
    'speaker',
    'entertainment',
    'singleNote',
    'musicArticles'
  ],
  'songs': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  'amplification': [
    'soundOn',
    'speaker'
  ],
  '🔈': [
    'soundOn',
    'speaker'
  ],
  '🔊': [
    'soundOn',
    'speaker'
  ],
  '🔉': [
    'soundOn',
    'speaker'
  ],
  '🎚': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🎶': [
    'soundOn',
    'soundOff',
    'play',
    'music',
    'pause',
    'speaker'
  ],
  '🎼': [
    'soundOn',
    'soundOff',
    'play',
    'pause',
    'speaker'
  ],
  '🎵': [
    'soundOn',
    'soundOff',
    'music',
    'speaker'
  ],
  '🎤': [
    'soundOn',
    'soundOff',
    'music',
    'speaker'
  ],
  '🎸': [
    'soundOn',
    'soundOff',
    'music',
    'speaker'
  ],
  '🥁': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🎹': [
    'soundOn',
    'soundOff',
    'music',
    'keyboard',
    'speaker'
  ],
  '🎺': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🎻': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🎷': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🪗': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🪘': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🪕': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '💿': [
    'soundOn',
    'soundOff',
    'speaker'
  ],
  '🎥': [
    'soundOn',
    'soundOff',
    'play',
    'pause',
    'speaker',
    'camera'
  ],
  'mute': [
    'soundOff'
  ],
  'off': [
    'soundOff'
  ],
  'soft': [
    'soundOff'
  ],
  'quiet': [
    'soundOff'
  ],
  'silence': [
    'soundOff'
  ],
  '🔇': [
    'soundOff'
  ],
  'sort': [
    'sortUpCenter',
    'sortUp',
    'sortDownCenter',
    'sortDown',
    'sortDoubleArrow'
  ],
  'table': [
    'sortUpCenter',
    'sortUp',
    'sortDownCenter',
    'sortDown',
    'sortDoubleArrow'
  ],
  '⏬': [
    'sortDownCenter',
    'sortDown',
    'sortDoubleArrow'
  ],
  'sofort': [
    'sofort'
  ],
  'share': [
    'share',
    'socialShare'
  ],
  'connect': [
    'share',
    'chainLink',
    'wifi',
    'apiPlug',
    'apiPlug'
  ],
  'saving': [
    'save',
    'savingsBank'
  ],
  'floppy': [
    'save'
  ],
  'disk': [
    'save'
  ],
  'hard': [
    'save'
  ],
  'drive': [
    'save'
  ],
  'storage': [
    'save',
    'safe',
    'folderOpen'
  ],
  'backup': [
    'save'
  ],
  '🛟': [
    'save'
  ],
  '😅': [
    'save'
  ],
  '💾': [
    'save'
  ],
  'safe': [
    'safe'
  ],
  'crypt': [
    'safe'
  ],
  'flag': [
    'report'
  ],
  'report': [
    'report',
    'document'
  ],
  '🏳': [
    'report'
  ],
  'rectangle': [
    'rectangle'
  ],
  'shape': [
    'rectangle'
  ],
  'draw': [
    'rectangle'
  ],
  '⬛️': [
    'rectangle'
  ],
  '🟩': [
    'rectangle'
  ],
  '🟥': [
    'rectangle'
  ],
  '🟪': [
    'rectangle'
  ],
  '🟨': [
    'rectangle'
  ],
  '🟦': [
    'rectangle',
    'baseFeed',
    'baseNotification',
    'baseWallet',
    'baseApps',
    'baseSquare',
    'baseTransact'
  ],
  '🟧': [
    'rectangle'
  ],
  '🟫': [
    'rectangle'
  ],
  'recenter': [
    'reCenter'
  ],
  'middle': [
    'reCenter'
  ],
  'core': [
    'reCenter'
  ],
  'pulse': [
    'pulse'
  ],
  'activity': [
    'pulse',
    'chartLine'
  ],
  'spark': [
    'pulse',
    'chartLine'
  ],
  '⚡️': [
    'pulse',
    'lightningBolt'
  ],
  'play': [
    'play',
    'auto',
    'gaming',
    'playbutton',
    'tvStand'
  ],
  'continue': [
    'play'
  ],
  'progress': [
    'play',
    'diagonalUpArrow',
    'pyramid',
    'diagonalDownArrow',
    'pause'
  ],
  'video': [
    'play',
    'metaverse',
    'games',
    'pause',
    'tv',
    'filmStrip',
    'playbutton',
    'tvStand'
  ],
  '▶️': [
    'play'
  ],
  '⏯': [
    'play',
    'pause'
  ],
  '🔜': [
    'play',
    'forwardArrow',
    'arrowRight'
  ],
  '🎞': [
    'play',
    'pause',
    'camera'
  ],
  '📀': [
    'play',
    'pause'
  ],
  '🎦': [
    'play',
    'pause'
  ],
  '📼': [
    'play',
    'pause'
  ],
  'attach': [
    'pin',
    'paperclip',
    'chainLink'
  ],
  'location': [
    'pin',
    'location'
  ],
  'mark': [
    'pin',
    'dot',
    'helpCenterQuestionMark'
  ],
  'marker': [
    'pin'
  ],
  'push pin': [
    'pin'
  ],
  'remember': [
    'pin'
  ],
  '📍': [
    'pin'
  ],
  '📌': [
    'pin'
  ],
  '🧷': [
    'pin'
  ],
  'mobile': [
    'phone'
  ],
  'cellphone': [
    'phone'
  ],
  '📲': [
    'phone'
  ],
  '📱': [
    'phone'
  ],
  '🤳': [
    'phone',
    'camera'
  ],
  'paypal': [
    'paypal'
  ],
  'paperclip': [
    'paperclip'
  ],
  'attachment': [
    'paperclip'
  ],
  'movie': [
    'paperclip',
    'filmStrip',
    'tvStand'
  ],
  'sound file': [
    'paperclip'
  ],
  'spreadsheet': [
    'paperclip'
  ],
  'paper airplane': [
    'paperAirplane'
  ],
  'plane': [
    'paperAirplane',
    'plane'
  ],
  '✈️': [
    'paperAirplane',
    'passport'
  ],
  '🛩': [
    'paperAirplane'
  ],
  'gears': [
    'ultility'
  ],
  'block': [
    'ultility',
    'disabledPhone'
  ],
  'chain': [
    'ultility'
  ],
  'multifaceted': [
    'ultility'
  ],
  'disconnect': [
    'noWifi'
  ],
  'disconnection': [
    'noWifi'
  ],
  'wireless': [
    'noWifi',
    'wifi'
  ],
  'sale': [
    'nftSale'
  ],
  'auction': [
    'nftSale'
  ],
  'market': [
    'nftSale',
    'advancedMarketSelector'
  ],
  'selling': [
    'nftSale'
  ],
  'give': [
    'nftOffer'
  ],
  'estimate': [
    'nftOffer'
  ],
  'value': [
    'nftOffer'
  ],
  'step eight': [
    'step8'
  ],
  'external link': [
    'externalLink'
  ],
  'link out': [
    'externalLink'
  ],
  'tab': [
    'externalLink'
  ],
  'hyperlink': [
    'externalLink'
  ],
  'link': [
    'externalLink',
    'chainLink'
  ],
  'musical': [
    'music'
  ],
  'note': [
    'music',
    'annotation',
    'entertainment',
    'singleNote',
    'musicArticles'
  ],
  'notes': [
    'music',
    'clipboard'
  ],
  'beamed': [
    'music'
  ],
  'octave': [
    'music'
  ],
  'ottava': [
    'music'
  ],
  'signs': [
    'music'
  ],
  'signing': [
    'music'
  ],
  'step six': [
    'step6'
  ],
  '3D': [
    'metaverse'
  ],
  'virtual': [
    'metaverse'
  ],
  'reality': [
    'metaverse'
  ],
  'controller': [
    'metaverse',
    'games',
    'gaming'
  ],
  'game': [
    'metaverse',
    'games'
  ],
  '🎮': [
    'metaverse',
    'games'
  ],
  '👾': [
    'metaverse',
    'games'
  ],
  '🕹': [
    'metaverse',
    'games'
  ],
  'market cap': [
    'marketCap'
  ],
  'capitalization': [
    'marketCap'
  ],
  'stock market': [
    'marketCap'
  ],
  'shares': [
    'marketCap'
  ],
  'share price': [
    'marketCap'
  ],
  'traded': [
    'marketCap'
  ],
  'fibonacci': [
    'fib'
  ],
  'fib': [
    'fib'
  ],
  'peak': [
    'fib'
  ],
  'trough': [
    'fib'
  ],
  'annotation': [
    'annotation'
  ],
  'gloss': [
    'annotation'
  ],
  'footnote': [
    'annotation'
  ],
  'commentary': [
    'annotation'
  ],
  'bullet point': [
    'list',
    'dot'
  ],
  'actions': [
    'list'
  ],
  'tasks': [
    'list'
  ],
  '•': [
    'list'
  ],
  'computer': [
    'laptop'
  ],
  'screen': [
    'laptop',
    'tv'
  ],
  '💻': [
    'laptop'
  ],
  '👩‍💻': [
    'laptop'
  ],
  '🧑‍💻': [
    'laptop'
  ],
  '👨‍💻': [
    'laptop'
  ],
  '💼': [
    'laptop',
    'briefcase'
  ],
  'chart volume': [
    'chartVolume'
  ],
  'double': [
    'doubleChevronRight'
  ],
  'error': [
    'error'
  ],
  'alert': [
    'error',
    'exclamationMark',
    'bellCheck',
    'bellPlus'
  ],
  'crucial': [
    'error',
    'exclamationMark'
  ],
  '🚨': [
    'error',
    'bellCheck',
    'bellPlus'
  ],
  '❗️': [
    'error',
    'exclamationMark'
  ],
  'buttons': [
    'games'
  ],
  'dpad': [
    'games'
  ],
  'remote': [
    'games'
  ],
  'gamer': [
    'games'
  ],
  '🙍‍♀️': [
    'followAdd',
    'following'
  ],
  '🙎‍♂️': [
    'followAdd',
    'following'
  ],
  'giftcard': [
    'giftCard'
  ],
  'gift': [
    'giftCard'
  ],
  'sharing': [
    'giftCard'
  ],
  'celebration': [
    'giftCard'
  ],
  'donate': [
    'giftCard'
  ],
  '✅': [
    'following',
    'circleCheckmark',
    'checkmark',
    'checkboxChecked',
    'seen',
    'regulated'
  ],
  'social media': [
    'twitterLogo',
    'discordLogo',
    'instagramLogo'
  ],
  'logo': [
    'twitterLogo',
    'discordLogo',
    'instagramLogo',
    'coinbaseOne',
    'base',
    'walletLogo',
    'coinbase',
    'coinbaseOneLogo',
    'googleLogo',
    'coinbaseRewards',
    'baseFeed',
    'baseNotification',
    'baseWallet',
    'baseSquare',
    'xLogo',
    'appleLogo',
    'fscsProtection'
  ],
  'bird app': [
    'twitterLogo'
  ],
  '🐦': [
    'twitterLogo'
  ],
  'finger': [
    'fingerprint'
  ],
  'print': [
    'fingerprint'
  ],
  'access': [
    'fingerprint',
    'faceScan',
    'unlock'
  ],
  'gauge': [
    'gauge',
    'gaugeEmpty',
    'gaugeLow',
    'gaugeMedium',
    'gaugeHigh',
    'gaugeHighMid',
    'gaugeLowMid',
    'gaugeHighLow',
    'gaugeLowHigh'
  ],
  'measure': [
    'gauge',
    'gaugeEmpty',
    'gaugeLow',
    'gaugeMedium',
    'gaugeHigh',
    'gaugeHighMid',
    'gaugeLowMid',
    'gaugeHighLow',
    'gaugeLowHigh'
  ],
  'size': [
    'gauge',
    'derivatives',
    'gaugeEmpty',
    'gaugeLow',
    'gaugeMedium',
    'gaugeHigh',
    'gaugeHighMid',
    'gaugeLowMid',
    'gaugeHighLow',
    'gaugeLowHigh'
  ],
  'scope': [
    'gauge',
    'gaugeEmpty',
    'gaugeLow',
    'gaugeMedium',
    'gaugeHigh',
    'gaugeHighMid',
    'gaugeLowMid',
    'gaugeHighLow',
    'gaugeLowHigh'
  ],
  'calculate': [
    'gauge',
    'gaugeEmpty',
    'gaugeLow',
    'gaugeMedium',
    'gaugeHigh',
    'calculator',
    'gaugeHighMid',
    'gaugeLowMid',
    'gaugeHighLow',
    'gaugeLowHigh'
  ],
  '🇹🇭': [
    'cashThaiBaht'
  ],
  '🪙': [
    'cashThaiBaht',
    'cashVietnameseDong',
    'cashUaeDirham',
    'cashTurkishLira',
    'cashSwissFranc',
    'cashPhilippinePeso',
    'cashIndonesianRupiah',
    'cashAustralianDollar',
    'cashSingaporeDollar',
    'cashCanadianDollar'
  ],
  'face': [
    'faceScan'
  ],
  'fork': [
    'fork'
  ],
  '🍴': [
    'fork'
  ],
  '⑂': [
    'fork'
  ],
  '⑃': [
    'fork'
  ],
  '⋔': [
    'fork'
  ],
  '⫚': [
    'fork'
  ],
  'horizontal': [
    'horizontalLine'
  ],
  'arrow right': [
    'forwardArrow',
    'arrowRight'
  ],
  'forward': [
    'forwardArrow',
    'initiator',
    'arrowRight'
  ],
  'ahead': [
    'forwardArrow',
    'arrowRight'
  ],
  '➡️': [
    'forwardArrow',
    'arrowRight',
    'socialShare',
    'socialReshare',
    'payments'
  ],
  '→': [
    'forwardArrow'
  ],
  '➡': [
    'forwardArrow',
    'arrowRight'
  ],
  'expand address': [
    'expandAddress'
  ],
  'arrows': [
    'expandAddress',
    'initiator',
    'arrowsHorizontal',
    'sendReceive',
    'arrowsUpDown'
  ],
  'gear': [
    'gear',
    'auto',
    'config',
    'mma'
  ],
  'tool': [
    'gear',
    'powerTool'
  ],
  'expand all': [
    'expand',
    'expandAll'
  ],
  'full': [
    'expand',
    'expandAll'
  ],
  'outwards': [
    'expand',
    'expandAll'
  ],
  'exclamation mark': [
    'exclamationMark'
  ],
  'warning': [
    'exclamationMark',
    'warning'
  ],
  'indication': [
    'exclamationMark'
  ],
  'emphasis': [
    'exclamationMark'
  ],
  '!': [
    'exclamationMark'
  ],
  'decentralized': [
    'ethereum'
  ],
  'open-source': [
    'ethereum'
  ],
  'cryptocurrency': [
    'ethereum',
    'currencies'
  ],
  'envelope': [
    'email'
  ],
  'letter': [
    'email'
  ],
  'email': [
    'email'
  ],
  '💌': [
    'email'
  ],
  '✉️': [
    'email'
  ],
  '📨': [
    'email'
  ],
  '📩': [
    'email'
  ],
  '📧': [
    'email'
  ],
  'bookmark': [
    'bookmark'
  ],
  'save': [
    'bookmark',
    'calendarHeart'
  ],
  'keys': [
    'keyboard'
  ],
  'computing': [
    'keyboard'
  ],
  'panel': [
    'keyboard',
    'advancedMarketSelector'
  ],
  '⌨️': [
    'keyboard'
  ],
  '⌨': [
    'keyboard'
  ],
  'identity card': [
    'identityCard'
  ],
  'ID': [
    'identityCard'
  ],
  '🆔': [
    'identityCard'
  ],
  'info': [
    'info'
  ],
  'resource': [
    'info'
  ],
  'guide': [
    'info',
    'sendReceive'
  ],
  'details': [
    'info'
  ],
  'facts': [
    'info'
  ],
  'ℹ️': [
    'info'
  ],
  'direction': [
    'downArrow',
    'drag',
    'upArrow'
  ],
  '🔻': [
    'downArrow'
  ],
  'dot': [
    'dot'
  ],
  'spot': [
    'dot'
  ],
  'point': [
    'dot',
    'sendReceive'
  ],
  'round': [
    'dot'
  ],
  '🔴': [
    'dot'
  ],
  '⚫️': [
    'dot'
  ],
  '🔵': [
    'dot'
  ],
  '⚪️': [
    'dot'
  ],
  'documentation': [
    'document'
  ],
  'record': [
    'document',
    'clockOutline',
    'clock',
    'allTimeHigh',
    'camera'
  ],
  'form': [
    'document'
  ],
  'diagonal': [
    'diagonalRightArrow',
    'diagonalUpArrow',
    'diagonalDownArrow'
  ],
  'right arrow': [
    'diagonalRightArrow'
  ],
  '↗️': [
    'diagonalRightArrow',
    'diagonalUpArrow'
  ],
  'positive': [
    'diagonalUpArrow',
    'circleCheckmark',
    'checkmark'
  ],
  'rocket': [
    'rocket'
  ],
  '🚀': [
    'rocket'
  ],
  'rocketship': [
    'rocket'
  ],
  'travel': [
    'rocket',
    'car',
    'airdropAlt'
  ],
  'flame': [
    'flame'
  ],
  'hot': [
    'flame'
  ],
  'fire': [
    'flame'
  ],
  'burn': [
    'flame'
  ],
  'inferno': [
    'flame'
  ],
  'blaze': [
    'flame'
  ],
  'popular': [
    'flame'
  ],
  'fresh': [
    'flame'
  ],
  '🔥': [
    'flame'
  ],
  '☄️': [
    'flame'
  ],
  '🧑‍🚒': [
    'flame'
  ],
  '👨‍🚒': [
    'flame'
  ],
  '👩‍🚒': [
    'flame'
  ],
  'tokens': [
    'currencies'
  ],
  'cross': [
    'crossTrade',
    'circleCross',
    'close',
    'cross',
    'hospitalCross'
  ],
  'trade': [
    'crossTrade',
    'advancedTradeProduct',
    'derivativesProduct',
    'apiPlug',
    'candlesticks',
    'orderBook'
  ],
  'buy': [
    'crossTrade'
  ],
  'offset': [
    'crossTrade'
  ],
  'exchange': [
    'crossTrade',
    'bridging'
  ],
  'stake': [
    'stake'
  ],
  'collateral': [
    'stake',
    'gaugeHigh',
    'gaugeHighMid'
  ],
  'verify': [
    'stake'
  ],
  'human': [
    'profile',
    'avatar'
  ],
  'change': [
    'convert',
    'bridging'
  ],
  'turn': [
    'convert',
    'convert'
  ],
  'transform': [
    'convert'
  ],
  'close caption': [
    'closeCaption'
  ],
  'cc': [
    'closeCaption'
  ],
  'subtitles': [
    'closeCaption'
  ],
  'text': [
    'closeCaption'
  ],
  'helper': [
    'closeCaption'
  ],
  'pending': [
    'statusDot'
  ],
  'waiting': [
    'statusDot',
    'chatRequests'
  ],
  'meatballs': [
    'statusDot'
  ],
  '🍝': [
    'statusDot'
  ],
  'minute': [
    'clockOutline',
    'clock'
  ],
  'hour': [
    'clockOutline',
    'clock'
  ],
  'day': [
    'clockOutline',
    'clock'
  ],
  '24 hours': [
    'clockOutline',
    'clock'
  ],
  'gavel': [
    'gavel'
  ],
  'hammer': [
    'gavel'
  ],
  'mallet': [
    'gavel'
  ],
  'attention': [
    'gavel'
  ],
  '🧑‍⚖️': [
    'gavel'
  ],
  '👨‍⚖️': [
    'gavel'
  ],
  '👩‍⚖️': [
    'gavel'
  ],
  'paste': [
    'clipboard'
  ],
  'clip': [
    'clipboard'
  ],
  'board': [
    'clipboard'
  ],
  '📋': [
    'clipboard'
  ],
  'circle': [
    'circleCross',
    'circleCheckmark',
    'cluster',
    'mint',
    'allocation'
  ],
  'x': [
    'circleCross',
    'close'
  ],
  'decline': [
    'circleCross'
  ],
  'rejection': [
    'circleCross'
  ],
  'removal': [
    'circleCross'
  ],
  'unsuccessful': [
    'circleCross'
  ],
  '❌': [
    'circleCross',
    'close'
  ],
  '🙅': [
    'circleCross',
    'close'
  ],
  '🙅‍♂️': [
    'circleCross',
    'close'
  ],
  '🙅‍♀️': [
    'circleCross',
    'close'
  ],
  '🚫': [
    'circleCross',
    'close',
    'block'
  ],
  '❎': [
    'circleCross',
    'close'
  ],
  'checkmark': [
    'circleCheckmark',
    'checkmark',
    'checkboxChecked',
    'seen'
  ],
  'tick': [
    'circleCheckmark',
    'checkmark',
    'checkboxChecked'
  ],
  'confirmation': [
    'circleCheckmark',
    'checkmark',
    'checkboxChecked',
    'regulated'
  ],
  'success': [
    'circleCheckmark',
    'checkmark'
  ],
  '✔️': [
    'circleCheckmark',
    'checkmark',
    'checkboxChecked'
  ],
  'accept': [
    'checkmark',
    'checkboxChecked'
  ],
  'confirm': [
    'checkmark',
    'checkboxChecked'
  ],
  'uncheck': [
    'checkboxEmpty'
  ],
  'empty': [
    'checkboxEmpty'
  ],
  'unselected': [
    'checkboxEmpty'
  ],
  '☑️': [
    'checkboxEmpty'
  ],
  'select': [
    'checkboxChecked'
  ],
  'triangle': [
    'pyramid'
  ],
  'levels': [
    'pyramid'
  ],
  'important': [
    'pyramid',
    'calendarStar'
  ],
  'pyramid': [
    'pyramid'
  ],
  '🔺': [
    'pyramid',
    'upArrow',
    'allTimeHigh'
  ],
  'chat bubble': [
    'chatBubble'
  ],
  'speech': [
    'chatBubble',
    'microphone',
    'socialChat',
    'commentPlus'
  ],
  'social': [
    'chatBubble',
    'mint',
    'socialShare',
    'socialChat',
    'socialReshare',
    'payments',
    'baseFeed',
    'baseNotification',
    'baseWallet',
    'baseApps',
    'baseSquare',
    'baseTransact'
  ],
  'interaction': [
    'chatBubble'
  ],
  'bot': [
    'chatBotAgent'
  ],
  'agent': [
    'chatBotAgent'
  ],
  '👩‍💼': [
    'chatBotAgent'
  ],
  '🧑‍💼': [
    'chatBotAgent'
  ],
  '👨‍💼': [
    'chatBotAgent'
  ],
  'initiator': [
    'initiator'
  ],
  '🇻🇳': [
    'cashVietnameseDong'
  ],
  '🇦🇪': [
    'cashUaeDirham'
  ],
  '🇹🇷': [
    'cashTurkishLira'
  ],
  '🇨🇭': [
    'cashSwissFranc'
  ],
  '🇱🇮': [
    'cashSwissFranc'
  ],
  '🇵🇭': [
    'cashPhilippinePeso'
  ],
  'linkage': [
    'chainLink'
  ],
  'connection': [
    'chainLink',
    'wifi'
  ],
  '⛓': [
    'chainLink'
  ],
  '🔗': [
    'chainLink'
  ],
  'filled': [
    'visible'
  ],
  '🧿': [
    'visible'
  ],
  '👁‍🗨': [
    'visible'
  ],
  'seen': [
    'seen'
  ],
  'read': [
    'seen'
  ],
  'double checkmark': [
    'seen'
  ],
  'send receipts': [
    'seen'
  ],
  '🤓': [
    'seen'
  ],
  'own': [
    'nftBuy'
  ],
  'bought': [
    'nftBuy'
  ],
  'purchased': [
    'nftBuy'
  ],
  'collected': [
    'nftBuy'
  ],
  'arrow left': [
    'backArrow',
    'arrowLeft'
  ],
  'backwards': [
    'backArrow',
    'arrowLeft'
  ],
  'behind': [
    'backArrow',
    'arrowLeft'
  ],
  '🔙': [
    'backArrow',
    'arrowLeft'
  ],
  '⏮': [
    'backArrow',
    'arrowLeft'
  ],
  '⏪': [
    'backArrow',
    'arrowLeft'
  ],
  '⬅️': [
    'backArrow',
    'arrowLeft'
  ],
  '⬅': [
    'backArrow',
    'arrowLeft'
  ],
  'continuous': [
    'average'
  ],
  'transactions': [
    'average'
  ],
  'orders': [
    'average',
    'orderBook'
  ],
  'conversation': [
    'discordLogo',
    'telephone',
    'disabledPhone'
  ],
  'lightning bolt': [
    'lightningBolt'
  ],
  'thunder': [
    'lightningBolt',
    'instantUnstakingClock',
    'lightning'
  ],
  'fast': [
    'lightningBolt'
  ],
  'speed': [
    'lightningBolt',
    'car'
  ],
  'api': [
    'api',
    'developerAPIProduct',
    'folderOpen'
  ],
  'functions': [
    'api'
  ],
  'procedures': [
    'api'
  ],
  'applications': [
    'api'
  ],
  'features': [
    'api'
  ],
  'service': [
    'api',
    'helpCenterQuestionMark',
    'concierge',
    'conciergeBell'
  ],
  '⏭': [
    'arrowRight'
  ],
  '⏩': [
    'arrowRight'
  ],
  'airdrop': [
    'airdrop',
    'airdropCoins',
    'airdropAlt',
    'airdropParachute'
  ],
  '🪂': [
    'airdrop'
  ],
  'parachute': [
    'airdrop'
  ],
  'fund': [
    'bank'
  ],
  'stock': [
    'bank'
  ],
  'institution': [
    'bank'
  ],
  'step nine': [
    'step9'
  ],
  'gram': [
    'instagramLogo'
  ],
  'drag': [
    'drag'
  ],
  'move': [
    'drag'
  ],
  '👆': [
    'drag',
    'upArrow'
  ],
  '👉': [
    'drag'
  ],
  '👈': [
    'drag'
  ],
  '🗺': [
    'drag'
  ],
  'avatar': [
    'avatar',
    'passKey'
  ],
  'regulated': [
    'regulated'
  ],
  'lock': [
    'lock',
    'key',
    'baseLock'
  ],
  'no access': [
    'lock',
    'baseLock'
  ],
  'latch': [
    'lock',
    'unlock',
    'baseLock'
  ],
  'blocked': [
    'lock',
    'block',
    'baseLock'
  ],
  '🔒': [
    'lock',
    'unlock',
    'baseLock'
  ],
  '🔑': [
    'lock',
    'unlock',
    'key',
    'securityKey',
    'baseLock'
  ],
  '🗝': [
    'lock',
    'unlock',
    'baseLock'
  ],
  'peer to peer': [
    'blockchain'
  ],
  'network': [
    'blockchain'
  ],
  'call': [
    'telephone',
    'disabledPhone',
    'disabledPhone'
  ],
  'communicate': [
    'telephone',
    'disabledPhone'
  ],
  'negative': [
    'diagonalDownArrow'
  ],
  '↙️': [
    'diagonalDownArrow'
  ],
  'download': [
    'download'
  ],
  'receiving': [
    'download'
  ],
  'caution': [
    'warning'
  ],
  'notice': [
    'warning'
  ],
  'hint': [
    'warning'
  ],
  '⚠️': [
    'warning'
  ],
  'upwards': [
    'upArrow'
  ],
  '☝️': [
    'upArrow'
  ],
  '🆙': [
    'upArrow'
  ],
  'examine': [
    'questionMark'
  ],
  'curious': [
    'questionMark'
  ],
  '🙋‍♀️': [
    'questionMark'
  ],
  '🙋‍♂️': [
    'questionMark'
  ],
  'all time high': [
    'allTimeHigh'
  ],
  'highest': [
    'allTimeHigh'
  ],
  '⤴️': [
    'allTimeHigh',
    'socialShare',
    'socialReshare'
  ],
  'close': [
    'close'
  ],
  'business': [
    'briefcase',
    'briefcaseAlt'
  ],
  'briefcase': [
    'briefcase',
    'briefcaseAlt'
  ],
  'careers': [
    'briefcase'
  ],
  'work': [
    'briefcase',
    'briefcaseAlt'
  ],
  'bag': [
    'briefcase',
    'mma'
  ],
  'pause': [
    'pause'
  ],
  'on hold': [
    'pause'
  ],
  '⏸': [
    'pause'
  ],
  'ideal': [
    'ideal'
  ],
  'speaker': [
    'speaker'
  ],
  'circulating supply': [
    'circulatingSupply'
  ],
  'remainder': [
    'circulatingSupply'
  ],
  'availability': [
    'circulatingSupply'
  ],
  'coins': [
    'circulatingSupply',
    'derivatives',
    'cashCoins',
    'coinsCrypto'
  ],
  'amount': [
    'circulatingSupply'
  ],
  'dollarydoos': [
    'cashAustralianDollar'
  ],
  '🇦🇺': [
    'cashAustralianDollar'
  ],
  '🐨': [
    'cashAustralianDollar'
  ],
  '🦘': [
    'cashAustralianDollar'
  ],
  '🍻': [
    'cashAustralianDollar'
  ],
  'camera': [
    'camera'
  ],
  'snap': [
    'camera'
  ],
  'photo': [
    'camera'
  ],
  'photography': [
    'camera'
  ],
  '📷': [
    'camera'
  ],
  '📹': [
    'camera'
  ],
  '📽': [
    'camera'
  ],
  'unlock': [
    'unlock',
    'key'
  ],
  'open': [
    'unlock',
    'orderBook'
  ],
  'freedom.': [
    'unlock'
  ],
  '🔓': [
    'unlock'
  ],
  'bridge': [
    'bridging'
  ],
  '🌁': [
    'bridging'
  ],
  '🌉': [
    'bridging'
  ],
  'cb1': [
    'coinbaseOne',
    'coinbaseOneCard'
  ],
  'one': [
    'coinbaseOne',
    'coinbaseOneCard'
  ],
  'coinbase': [
    'coinbaseOne',
    'payProduct',
    'coinbase',
    'coinbaseCardProduct',
    'coinbaseOneLogo'
  ],
  '🇸🇬': [
    'cashSingaporeDollar'
  ],
  '🇨🇦': [
    'cashCanadianDollar'
  ],
  'faucet': [
    'faucet'
  ],
  'drip': [
    'faucet'
  ],
  'droplet': [
    'faucet'
  ],
  'hydration': [
    'faucet'
  ],
  '🚰': [
    'faucet'
  ],
  'mr worldwide': [
    'passport'
  ],
  'book': [
    'passport',
    'orderBook',
    'educationBook'
  ],
  'world': [
    'passport'
  ],
  'identity': [
    'passport'
  ],
  'transport': [
    'passport'
  ],
  '🛂': [
    'passport'
  ],
  '📕': [
    'passport'
  ],
  '📗': [
    'passport'
  ],
  '📘': [
    'passport'
  ],
  '📙': [
    'passport'
  ],
  '🛫': [
    'passport'
  ],
  '🛬': [
    'passport'
  ],
  '🛩️': [
    'passport'
  ],
  'derivatives': [
    'derivatives',
    'derivativesProduct',
    'gaugeHigh',
    'derivativesProductNew',
    'gaugeHighMid'
  ],
  'fulcrum': [
    'derivatives'
  ],
  'lever': [
    'derivatives'
  ],
  'leverage': [
    'derivatives'
  ],
  'scale': [
    'derivatives'
  ],
  'for less': [
    'derivatives'
  ],
  'yours': [
    'derivatives'
  ],
  'is': [
    'derivatives'
  ],
  'not': [
    'derivatives'
  ],
  'nav': [
    'base',
    'walletLogo',
    'payProduct',
    'custodyProduct',
    'learningRewardsProduct',
    'privateClientProduct',
    'earnProduct',
    'nftProduct',
    'borrowProduct',
    'coinbaseOneLogo',
    'developerAPIProduct',
    'folderOpen',
    'verifiedPools'
  ],
  'icon': [
    'base',
    'walletLogo',
    'key',
    'securityKey',
    'payProduct',
    'venturesProduct',
    'coinbaseOneLogo',
    'developerAPIProduct',
    'folderOpen'
  ],
  'base': [
    'base',
    'payments',
    'baseFeed',
    'baseNotification',
    'baseWallet',
    'baseApps',
    'baseSquare',
    'baseTransact',
    'creatorCoin',
    'baseVerification'
  ],
  'product': [
    'commerceProduct',
    'advancedTradeProduct',
    'payProduct',
    'coinbase',
    'nodeProduct',
    'walletProduct',
    'coinbaseCardProduct',
    'custodyProduct',
    'learningRewardsProduct',
    'rewardsProduct',
    'venturesProduct',
    'assetManagementProduct',
    'helpCenterProduct',
    'institutionalProduct',
    'complianceProduct',
    'delegateProduct',
    'cloudProduct',
    'assetHubProduct',
    'privateClientProduct',
    'participateProduct',
    'earnProduct',
    'nftProduct',
    'dataMarketplaceProduct',
    'derivativesProduct',
    'proProduct',
    'helpCenterQuestionMark',
    'borrowProduct',
    'developerPlatformProduct',
    'developerAPIProduct'
  ],
  'key': [
    'key',
    'securityKey',
    'passKey'
  ],
  'secure': [
    'key',
    'securityKey'
  ],
  'skeleton': [
    'key'
  ],
  '🗝️': [
    'key'
  ],
  'gas': [
    'gasFees',
    'greenEnergy',
    'gasFeesAlt',
    'gasFeesAlt',
    'oil'
  ],
  'fees': [
    'gasFees'
  ],
  'gas fees': [
    'gasFees'
  ],
  'eth': [
    'gasFees'
  ],
  'ethereum': [
    'gasFees'
  ],
  'low': [
    'gasFees'
  ],
  'high': [
    'gasFees'
  ],
  'cost': [
    'gasFees',
    'usdc'
  ],
  'pump': [
    'gasFees',
    'gasFeesAlt'
  ],
  'handle': [
    'gasFees'
  ],
  'gasoline': [
    'gasFees'
  ],
  'car': [
    'gasFees',
    'car',
    'autoCar'
  ],
  '⛽️': [
    'gasFees'
  ],
  'usb': [
    'securityKey'
  ],
  '2fa': [
    'securityKey'
  ],
  'yubikey': [
    'securityKey'
  ],
  'advanced': [
    'advancedTradeProduct',
    'apiPlug',
    'advancedMarketSelector',
    'candlesticks',
    'orderBook',
    'plusMinus'
  ],
  'advance': [
    'advancedTradeProduct'
  ],
  'C': [
    'coinbase'
  ],
  'node': [
    'nodeProduct'
  ],
  'custody': [
    'custodyProduct'
  ],
  'ventures': [
    'venturesProduct'
  ],
  'venture': [
    'venturesProduct'
  ],
  'CBAM': [
    'assetManagementProduct'
  ],
  'Asset': [
    'assetManagementProduct'
  ],
  'Management': [
    'assetManagementProduct'
  ],
  'Manage': [
    'assetManagementProduct'
  ],
  'institutional': [
    'institutionalProduct'
  ],
  'insto': [
    'institutionalProduct'
  ],
  'compliance': [
    'complianceProduct'
  ],
  'delegate': [
    'delegateProduct'
  ],
  'portal': [
    'cloudProduct'
  ],
  'asset': [
    'assetHubProduct'
  ],
  'private': [
    'privateClientProduct'
  ],
  'client': [
    'privateClientProduct'
  ],
  'participate': [
    'participateProduct'
  ],
  'nft': [
    'nftProduct',
    'mint'
  ],
  'marketplace': [
    'dataMarketplaceProduct'
  ],
  'derivative': [
    'derivativesProduct'
  ],
  'pro': [
    'proProduct'
  ],
  'FAQ': [
    'helpCenterQuestionMark'
  ],
  'find': [
    'helpCenterQuestionMark'
  ],
  'customer': [
    'helpCenterQuestionMark'
  ],
  'CEX': [
    'helpCenterQuestionMark'
  ],
  'cluster': [
    'cluster'
  ],
  'pizza': [
    'cluster'
  ],
  'pie': [
    'cluster'
  ],
  'clusters': [
    'cluster'
  ],
  'clustering': [
    'cluster'
  ],
  'app': [
    'cluster'
  ],
  'engineering': [
    'cluster'
  ],
  'borrow': [
    'borrowProduct',
    'leadCoin',
    'leadChart'
  ],
  'ui': [
    'crypto',
    'verifiedBadge',
    'verifiedBadge',
    'staggeredList',
    'gitHubLogo',
    'gitHubLogo',
    'baseQuickBuy'
  ],
  'login': [
    'logout',
    'login'
  ],
  'logout': [
    'logout',
    'login'
  ],
  'door': [
    'logout',
    'login'
  ],
  'doorway': [
    'logout',
    'login'
  ],
  'signin': [
    'logout',
    'login'
  ],
  'signout': [
    'logout',
    'login'
  ],
  'exit': [
    'logout'
  ],
  'enter': [
    'login'
  ],
  'linechart': [
    'lineChartCrypto'
  ],
  'Cash': [
    'cashCoins'
  ],
  'RAT': [
    'apiPlug'
  ],
  'API': [
    'apiPlug'
  ],
  'plug': [
    'apiPlug'
  ],
  'plugin': [
    'apiPlug'
  ],
  'Nav': [
    'developerPlatformProduct'
  ],
  'dev': [
    'developerPlatformProduct'
  ],
  'platform': [
    'developerPlatformProduct',
    'developerAPIProduct'
  ],
  'squares': [
    'developerAPIProduct',
    'baseApps'
  ],
  'selector': [
    'advancedMarketSelector'
  ],
  'side': [
    'advancedMarketSelector'
  ],
  'slide': [
    'advancedMarketSelector'
  ],
  'out': [
    'advancedMarketSelector',
    'advancedMarketSelector'
  ],
  'pop': [
    'advancedMarketSelector'
  ],
  'Price': [
    'priceAlerts',
    'priceAlertsCheck'
  ],
  'Price alerts': [
    'priceAlerts',
    'priceAlertsCheck'
  ],
  '🔕': [
    'priceAlerts',
    'priceAlertsCheck'
  ],
  'plus': [
    'priceAlerts',
    'calculator',
    'priceAlertsCheck',
    'bellCheck',
    'bellPlus',
    'plusMinus',
    'distribution'
  ],
  'folder': [
    'folderOpen'
  ],
  'files': [
    'folderOpen'
  ],
  'documents': [
    'folderOpen'
  ],
  'drop': [
    'folderOpen'
  ],
  'box': [
    'folderOpen',
    'gif',
    'ballotbox',
    'ballot'
  ],
  'filezilla': [
    'folderOpen'
  ],
  'architecture': [
    'folderOpen'
  ],
  'docs': [
    'folderOpen'
  ],
  'dox': [
    'folderOpen'
  ],
  'verified': [
    'verifiedBadge',
    'verifiedPools',
    'gitHubLogo'
  ],
  'badge': [
    'verifiedBadge',
    'gitHubLogo',
    'baseVerification'
  ],
  'health': [
    'gaugeHigh',
    'gaugeHighMid',
    'cross',
    'pillBottle',
    'needle',
    'hospital',
    'bug',
    'bandage',
    'hospitalCross',
    'apothecary',
    'virus',
    'pillCapsule'
  ],
  'futures': [
    'gaugeHigh',
    'gaugeHighMid'
  ],
  'balance': [
    'gaugeHigh',
    'gaugeHighMid'
  ],
  'staggered': [
    'staggeredList'
  ],
  'lines': [
    'staggeredList'
  ],
  'candle': [
    'candlesticks'
  ],
  'stick': [
    'candlesticks'
  ],
  'sticks': [
    'candlesticks'
  ],
  'candlesticks': [
    'candlesticks'
  ],
  'prime': [
    'candlesticks',
    'orderBook'
  ],
  'green': [
    'candlesticks'
  ],
  'red': [
    'candlesticks'
  ],
  'books': [
    'orderBook'
  ],
  'review': [
    'orderBook'
  ],
  'completed': [
    'orderBook'
  ],
  'microphone': [
    'microphone'
  ],
  'mic': [
    'microphone',
    'microphoneCordless'
  ],
  'talk': [
    'microphone'
  ],
  'into': [
    'microphone'
  ],
  'calculator': [
    'calculator'
  ],
  'maths': [
    'calculator'
  ],
  'multiply': [
    'calculator'
  ],
  'divide': [
    'calculator'
  ],
  'gif': [
    'gif'
  ],
  'GIF': [
    'gif'
  ],
  'G': [
    'gif'
  ],
  'JIFF': [
    'gif'
  ],
  'image': [
    'image'
  ],
  'mountain': [
    'image'
  ],
  'pools': [
    'verifiedPools'
  ],
  'Bell': [
    'bellCheck',
    'bellPlus'
  ],
  'price': [
    'bellCheck',
    'bellPlus'
  ],
  '🛎️': [
    'bellCheck',
    'bellPlus'
  ],
  'trust': [
    'shieldOutline'
  ],
  'ouline': [
    'shieldOutline'
  ],
  'google': [
    'googleLogo'
  ],
  'g': [
    'googleLogo'
  ],
  'suite': [
    'googleLogo'
  ],
  'social share': [
    'socialShare',
    'socialReshare'
  ],
  '↪️': [
    'socialShare',
    'socialReshare'
  ],
  'chatbubble': [
    'socialChat'
  ],
  'Reshare': [
    'socialReshare'
  ],
  'payments': [
    'payments'
  ],
  '👥': [
    'concierge'
  ],
  'concierge': [
    'concierge',
    'conciergeBell',
    'peopleStar'
  ],
  'CB1': [
    'concierge',
    'conciergeBell'
  ],
  'Coinbase': [
    'coinbaseRewards'
  ],
  'Coinbaserewards': [
    'coinbaseRewards'
  ],
  'trophy': [
    'coinbaseRewards',
    'medal',
    'ribbon',
    'starTrophy',
    'starAward'
  ],
  'ribbon': [
    'coinbaseRewards'
  ],
  'coinbaseonecard': [
    'coinbaseOneCard'
  ],
  'TBA': [
    'baseFeed',
    'baseNotification',
    'baseWallet',
    'baseApps',
    'baseSquare',
    'baseTransact'
  ],
  'feed': [
    'baseFeed'
  ],
  'dinner': [
    'dinnerPlate'
  ],
  'plate': [
    'dinnerPlate'
  ],
  'food': [
    'dinnerPlate',
    'rottenTomato'
  ],
  'eat': [
    'dinnerPlate'
  ],
  'wellness': [
    'wellness'
  ],
  'peace': [
    'wellness'
  ],
  'love': [
    'wellness'
  ],
  'tea': [
    'wellness'
  ],
  'healthcare': [
    'cross',
    'needle',
    'hospital'
  ],
  'nurse': [
    'cross'
  ],
  'transportation': [
    'car'
  ],
  'flight': [
    'plane',
    'airdropAlt'
  ],
  'flying': [
    'plane'
  ],
  'jet': [
    'plane'
  ],
  'clothing': [
    'clothing',
    'tshirt',
    'shoe'
  ],
  'hanger': [
    'clothing'
  ],
  'fashion': [
    'clothing',
    'tshirt',
    'shoe'
  ],
  'clothes': [
    'clothing'
  ],
  'powertool': [
    'powerTool'
  ],
  'drill': [
    'powerTool'
  ],
  'equipment': [
    'powerTool',
    'mma'
  ],
  'compose': [
    'compose'
  ],
  '🖍': [
    'compose'
  ],
  'datastack': [
    'dataStack'
  ],
  'stack': [
    'dataStack',
    'filterLineStack'
  ],
  '✖️': [
    'plusMinus'
  ],
  'X': [
    'xLogo'
  ],
  'Twitter': [
    'xLogo'
  ],
  'Elon': [
    'xLogo'
  ],
  'Jack': [
    'xLogo'
  ],
  'Social': [
    'xLogo'
  ],
  'Bird': [
    'xLogo'
  ],
  'Dead': [
    'xLogo'
  ],
  'Space': [
    'xLogo'
  ],
  'pass': [
    'passKey'
  ],
  'passkey': [
    'passKey'
  ],
  'sign': [
    'passKey',
    'passKey'
  ],
  'in': [
    'passKey'
  ],
  'user': [
    'passKey'
  ],
  'begin': [
    'beginningArrow'
  ],
  'all': [
    'beginningArrow',
    'endArrow'
  ],
  'the': [
    'beginningArrow'
  ],
  'way': [
    'beginningArrow'
  ],
  'end': [
    'endArrow'
  ],
  'the way': [
    'endArrow'
  ],
  'apple': [
    'appleLogo',
    'apple'
  ],
  'jobs': [
    'appleLogo'
  ],
  'wozniak': [
    'appleLogo'
  ],
  'pc': [
    'appleLogo'
  ],
  'blueberry': [
    'appleLogo'
  ],
  'imac': [
    'appleLogo'
  ],
  'iphone': [
    'appleLogo'
  ],
  'ifruit': [
    'appleLogo'
  ],
  'beaker. science': [
    'beaker'
  ],
  '🧪': [
    'beaker'
  ],
  '🦠': [
    'beaker'
  ],
  '🧫': [
    'beaker'
  ],
  'nope': [
    'block'
  ],
  'requests': [
    'chatRequests'
  ],
  'chatting': [
    'chatRequests'
  ],
  'lead': [
    'leadCoin',
    'leadChart'
  ],
  'boxes': [
    'grid'
  ],
  'square': [
    'grid'
  ],
  '☐': [
    'grid'
  ],
  'plue': [
    'commentPlus'
  ],
  'piggy': [
    'savingsBank'
  ],
  'fscs': [
    'fscsProtection'
  ],
  'unstack': [
    'instantUnstakingClock'
  ],
  'instant': [
    'instantUnstakingClock'
  ],
  'auto': [
    'auto',
    'autoCar'
  ],
  'creator': [
    'creatorCoin'
  ],
  'allocation': [
    'allocation'
  ],
  'piechart': [
    'allocation',
    'pieChartData',
    'pieChartWithArrow'
  ],
  'Verification': [
    'baseVerification'
  ],
  'distribution': [
    'distribution'
  ],
  'disabled': [
    'disabledPhone'
  ],
  'config': [
    'config'
  ],
  'pin': [
    'location'
  ],
  'map': [
    'location'
  ],
  'unfollow': [
    'unfollowPeople'
  ],
  'People': [
    'unfollowPeople'
  ],
  'token': [
    'tokenSales'
  ],
  'sales': [
    'tokenSales'
  ],
  'quick buy': [
    'baseQuickBuy'
  ],
  'single Coin': [
    'singleCoin'
  ],
  'loop': [
    'loop'
  ],
  'robot': [
    'robot'
  ],
  'test': [
    'test'
  ],
  'Predictions': [
    'tokenLaunchCoin',
    'football',
    'mma',
    'hockey',
    'chess',
    'soccer',
    'tennis',
    'cricket',
    'baseball',
    'strategy',
    'motorsport',
    'golf',
    'basketball',
    'tokenLaunchRocket',
    'boxing',
    'ballotbox',
    'speechBubble',
    'starBubble',
    'atSign',
    'medal',
    'ribbon',
    'starTrophy',
    'calendarDates',
    'calendarMoney',
    'stableCoin',
    'politicsGavel',
    'politicsBuilding',
    'politicsStar',
    'politicsPodium',
    'apple',
    'educationPencil',
    'ratingsStar',
    'podiumStar',
    'ratingsCheck',
    'pillBottle',
    'needle',
    'hospital',
    'bug',
    'bandage',
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'city',
    'factory',
    'corporation',
    'greenEnergy',
    'thermometer',
    'umbrella',
    'hurricane',
    'stablecoinStack',
    'entertainment',
    'tshirt',
    'rottenTomato',
    'tv',
    'filmStrip',
    'singleNote',
    'educationBook',
    'gaming',
    'ratingsChecks',
    'playbutton',
    'scienceAtom',
    'earthquake',
    'shoe',
    'quotation',
    'musicArticles',
    'politicsFlag',
    'building',
    'tornado',
    'computerChip',
    'cloudPartial',
    'airdropCoins',
    'gasFeesAlt',
    'atomScience',
    'hospitalCross',
    'airdropAlt',
    'oil',
    'apothecary',
    'briefcaseAlt',
    'virus',
    'pillCapsule',
    'starAward',
    'calendarStar',
    'calendarHeart',
    'singlecloud',
    'lightning',
    'microphoneCordless',
    'snow',
    'tvStand',
    'wind',
    'politicsCandidate',
    'ballot',
    'rain',
    'airdropParachute'
  ],
  'token launch': [
    'tokenLaunchCoin',
    'tokenLaunchRocket'
  ],
  'football': [
    'football',
    'soccer'
  ],
  'nfl': [
    'football'
  ],
  'touchdown': [
    'football'
  ],
  'sport': [
    'football',
    'football',
    'hockey',
    'chess',
    'soccer',
    'tennis',
    'cricket',
    'baseball',
    'motorsport',
    'golf',
    'basketball',
    'boxing'
  ],
  'boxing': [
    'mma',
    'boxing'
  ],
  'gym': [
    'mma'
  ],
  'sports': [
    'mma',
    'hockey',
    'chess',
    'soccer',
    'tennis',
    'cricket',
    'baseball',
    'strategy',
    'motorsport',
    'golf',
    'basketball',
    'boxing'
  ],
  'Hokey': [
    'hockey'
  ],
  'NHL': [
    'hockey'
  ],
  'chess': [
    'chess'
  ],
  'soccer': [
    'soccer'
  ],
  'match': [
    'soccer',
    'tennis',
    'cricket'
  ],
  'ball': [
    'soccer',
    'cricket',
    'baseball'
  ],
  'Tennis': [
    'tennis'
  ],
  'racket': [
    'tennis'
  ],
  'court': [
    'tennis'
  ],
  'cricket': [
    'cricket'
  ],
  'baseball': [
    'baseball'
  ],
  'mlb': [
    'baseball'
  ],
  'strategy': [
    'strategy'
  ],
  'tactics': [
    'strategy'
  ],
  'playbook': [
    'strategy'
  ],
  'coaching': [
    'strategy'
  ],
  'planning': [
    'strategy'
  ],
  'Motor sport': [
    'motorsport'
  ],
  'Bike': [
    'motorsport'
  ],
  'golf': [
    'golf'
  ],
  'pGA': [
    'golf'
  ],
  'basketball': [
    'basketball'
  ],
  'nba': [
    'basketball'
  ],
  'hoop': [
    'basketball'
  ],
  'voting': [
    'ballotbox',
    'politicsGavel',
    'politicsBuilding',
    'politicsStar',
    'politicsPodium',
    'ratingsStar',
    'podiumStar',
    'ratingsCheck',
    'ratingsChecks',
    'politicsFlag',
    'politicsCandidate',
    'ballot'
  ],
  'politics': [
    'ballotbox',
    'politicsGavel',
    'politicsBuilding',
    'politicsStar',
    'politicsPodium',
    'politicsFlag',
    'politicsCandidate',
    'ballot'
  ],
  'vote': [
    'ballotbox',
    'politicsGavel',
    'politicsBuilding',
    'politicsStar',
    'politicsPodium',
    'politicsFlag',
    'politicsCandidate',
    'ballot'
  ],
  'democracy': [
    'ballotbox',
    'politicsGavel',
    'politicsBuilding',
    'politicsStar',
    'politicsPodium',
    'politicsFlag',
    'politicsCandidate',
    'ballot'
  ],
  'politic': [
    'ballotbox',
    'politicsGavel',
    'politicsBuilding',
    'politicsStar',
    'politicsPodium',
    'politicsFlag',
    'ballot'
  ],
  'ballot': [
    'ballotbox',
    'ballot'
  ],
  'ballot box': [
    'ballotbox',
    'ballot'
  ],
  'mentions': [
    'speechBubble',
    'starBubble',
    'atSign',
    'quotation'
  ],
  'mention': [
    'speechBubble',
    'starBubble',
    'atSign',
    'quotation'
  ],
  'award': [
    'medal',
    'ribbon',
    'starTrophy',
    'starAward'
  ],
  'achievement': [
    'medal',
    'ribbon',
    'starTrophy',
    'starAward'
  ],
  'event': [
    'calendarDates',
    'calendarStar',
    'calendarHeart'
  ],
  'dates': [
    'calendarMoney',
    'calendarStar',
    'calendarHeart'
  ],
  'billing': [
    'calendarMoney'
  ],
  'Stablecoin': [
    'stableCoin'
  ],
  'stable': [
    'stableCoin',
    'stablecoinStack'
  ],
  'podium': [
    'politicsPodium'
  ],
  'education': [
    'apple',
    'educationPencil',
    'educationBook'
  ],
  'teaching': [
    'educationPencil',
    'educationBook'
  ],
  'ratings': [
    'ratingsStar',
    'podiumStar',
    'ratingsCheck',
    'ratingsChecks'
  ],
  'rating': [
    'ratingsStar',
    'podiumStar',
    'ratingsCheck',
    'ratingsChecks'
  ],
  'medicine': [
    'pillBottle',
    'pillBottle',
    'bug',
    'bandage',
    'hospitalCross',
    'apothecary',
    'virus',
    'pillCapsule',
    'pillCapsule'
  ],
  'medical': [
    'pillBottle',
    'needle',
    'hospital',
    'hospitalCross',
    'apothecary',
    'pillCapsule'
  ],
  'pharmacy': [
    'pillBottle',
    'bandage',
    'apothecary',
    'pillCapsule'
  ],
  'apothecary': [
    'pillBottle',
    'apothecary',
    'pillCapsule'
  ],
  'pill': [
    'pillBottle',
    'pillCapsule'
  ],
  'capsule': [
    'pillBottle',
    'pillCapsule'
  ],
  'hospital': [
    'needle',
    'hospital',
    'hospitalCross'
  ],
  'clinic': [
    'needle',
    'hospital'
  ],
  'syringe': [
    'needle'
  ],
  'injection': [
    'needle'
  ],
  'vaccine': [
    'needle',
    'bug',
    'virus'
  ],
  'virus': [
    'bug',
    'virus'
  ],
  'bug': [
    'bug',
    'virus'
  ],
  'drug': [
    'bandage'
  ],
  'bandaid': [
    'bandage'
  ],
  'bandage': [
    'bandage'
  ],
  'tech': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'technology': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'Science': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'lab': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'experiment': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'chemistry': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'research': [
    'scienceMoon',
    'alien',
    'microscope',
    'scienceBeaker',
    'scienceAtom',
    'computerChip',
    'atomScience'
  ],
  'alien': [
    'alien'
  ],
  'Beaker': [
    'scienceBeaker'
  ],
  'Markets': [
    'city',
    'factory',
    'corporation',
    'building'
  ],
  'Economics': [
    'city',
    'factory',
    'corporation',
    'greenEnergy',
    'building',
    'oil',
    'briefcaseAlt'
  ],
  'companies': [
    'city',
    'factory',
    'corporation',
    'building'
  ],
  'energy': [
    'greenEnergy',
    'gasFeesAlt',
    'oil'
  ],
  'Green Energy': [
    'greenEnergy'
  ],
  'growth': [
    'greenEnergy'
  ],
  'weather': [
    'thermometer',
    'umbrella',
    'hurricane',
    'earthquake',
    'tornado',
    'cloudPartial',
    'singlecloud',
    'lightning',
    'snow',
    'snow',
    'wind',
    'rain'
  ],
  'temperature': [
    'thermometer'
  ],
  'heat': [
    'thermometer'
  ],
  'cold': [
    'thermometer',
    'snow'
  ],
  'climate': [
    'thermometer',
    'earthquake',
    'lightning',
    'wind'
  ],
  'Climate': [
    'umbrella',
    'hurricane',
    'cloudPartial',
    'singlecloud',
    'snow',
    'rain'
  ],
  'rain': [
    'umbrella',
    'rain'
  ],
  'Raining': [
    'umbrella',
    'rain'
  ],
  'hurricane': [
    'hurricane'
  ],
  'stablecoin': [
    'stablecoinStack'
  ],
  'Music': [
    'entertainment',
    'tv',
    'filmStrip',
    'singleNote',
    'playbutton',
    'musicArticles',
    'microphoneCordless',
    'tvStand'
  ],
  'entertainment': [
    'entertainment',
    'rottenTomato',
    'tv',
    'filmStrip',
    'singleNote',
    'gaming',
    'playbutton',
    'musicArticles',
    'microphoneCordless',
    'tvStand'
  ],
  'media': [
    'entertainment',
    'tv',
    'filmStrip',
    'singleNote',
    'playbutton',
    'musicArticles',
    'microphoneCordless',
    'tvStand'
  ],
  'shirt': [
    'tshirt'
  ],
  'apparel': [
    'tshirt',
    'shoe'
  ],
  'retail': [
    'tshirt',
    'shoe'
  ],
  'rotten': [
    'rottenTomato'
  ],
  'rotten tomato': [
    'rottenTomato'
  ],
  'vegetable': [
    'rottenTomato'
  ],
  'produce': [
    'rottenTomato'
  ],
  'cooking': [
    'rottenTomato'
  ],
  'tomato': [
    'rottenTomato'
  ],
  'tv': [
    'tv'
  ],
  'broadcast': [
    'tv'
  ],
  'film': [
    'filmStrip',
    'tvStand'
  ],
  'cinema': [
    'filmStrip',
    'tvStand'
  ],
  'games': [
    'gaming'
  ],
  'gaming': [
    'gaming'
  ],
  'console': [
    'gaming'
  ],
  'esports': [
    'gaming'
  ],
  'start': [
    'playbutton'
  ],
  'atom': [
    'scienceAtom',
    'atomScience'
  ],
  'earthquake': [
    'earthquake'
  ],
  'shoe': [
    'shoe'
  ],
  'sneakers': [
    'shoe'
  ],
  'tornado': [
    'tornado'
  ],
  'chip': [
    'computerChip'
  ],
  'Partially': [
    'cloudPartial'
  ],
  'fuel': [
    'gasFeesAlt'
  ],
  'station': [
    'gasFeesAlt'
  ],
  'care': [
    'hospitalCross'
  ],
  'balloon': [
    'airdropAlt'
  ],
  'leisure': [
    'airdropAlt'
  ],
  'oil': [
    'oil'
  ],
  'job': [
    'briefcaseAlt'
  ],
  'featured': [
    'calendarStar'
  ],
  'lighting': [
    'lightning'
  ],
  'recording': [
    'microphoneCordless'
  ],
  'voice': [
    'microphoneCordless'
  ],
  'winter': [
    'snow'
  ],
  'snow': [
    'snow'
  ],
  'ice': [
    'snow'
  ],
  'wind': [
    'wind'
  ],
  'air': [
    'wind'
  ],
  'breeze': [
    'wind'
  ],
  'flow': [
    'wind'
  ],
  'candidate': [
    'politicsCandidate'
  ],
  'birthcertificate': [
    'birthcertificate'
  ],
  'birth': [
    'birthcertificate'
  ],
  'certificate': [
    'birthcertificate'
  ],
  'doc': [
    'birthcertificate'
  ],
  'webhooks': [
    'webhooks'
  ],
  'web': [
    'webhooks'
  ],
  'hooks': [
    'webhooks'
  ],
  'usdc': [
    'usdc'
  ],
  'fixed': [
    'usdc'
  ],
  'transferStocks': [
    'pieChartWithArrow'
  ],
  'stocks': [
    'pieChartWithArrow'
  ],
  'over': [
    'overPredictions'
  ],
  'predictions': [
    'overPredictions',
    'underPredictions'
  ],
  'column': [
    'column'
  ],
  'editing': [
    'column'
  ],
  'under': [
    'underPredictions'
  ]
};
