node_modules = "../../../../../node_modules"

require_relative "#{node_modules}/react-native/scripts/react_native_pods"
require_relative "#{node_modules}/@react-native-community/cli-platform-ios/native_modules"

platform(:ios, '11.0')

target 'cds' do
  use_native_modules!

  use_react_native!({ path: "#{node_modules}/react-native" })

  use_flipper!({ 'Flipper' => '0.62.0' })

  post_install do |installer|
    flipper_post_install(installer)

    # https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
      end
    end
  end
end
