/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconMore24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 5a2.5 2.5 0 110-5 2.5 2.5 0 010 5zm-2.5 7a2.5 2.5 0 105 0 2.5 2.5 0 00-5 0zm0 9.5a2.5 2.5 0 105 0 2.5 2.5 0 00-5 0z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconMore24Heavy);
