/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconTrxReward16Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M2.805 15l8.658-15 1.732 1-8.658 15-1.732-1zM3.5 2C4.33 2 5 2.67 5 3.5S4.33 5 3.5 5 2 4.33 2 3.5 2.67 2 3.5 2zm0-2C1.57 0 0 1.57 0 3.5S1.57 7 3.5 7 7 5.43 7 3.5 5.43 0 3.5 0zm9 11c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5-1.5-.67-1.5-1.5.67-1.5 1.5-1.5zm0-2C10.57 9 9 10.57 9 12.5s1.57 3.5 3.5 3.5 3.5-1.57 3.5-3.5S14.43 9 12.5 9z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTrxReward16Light);
