/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconGlobe24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M12 0C5.37 0 0 5.37 0 12s5.37 12 12 12 12-5.37 12-12S18.63 0 12 0zm9.41 10.75h-3.94c-.14-2.93-.77-5.55-1.7-7.46 3 1.3 5.19 4.11 5.64 7.46zm-18.82 2.5h3.94c.14 2.93.77 5.55 1.7 7.46-3-1.3-5.19-4.11-5.64-7.46zm3.94-2.5H2.59a9.527 9.527 0 015.64-7.46c-.93 1.91-1.56 4.53-1.7 7.46zM12 21.5c-.69 0-2.69-2.92-2.97-8.25h5.93c-.27 5.33-2.27 8.25-2.96 8.25zM9.03 10.75C9.31 5.42 11.31 2.5 12 2.5c.69 0 2.69 2.92 2.97 8.25H9.03zm6.74 9.96c.93-1.92 1.56-4.53 1.7-7.46h3.94a9.527 9.527 0 01-5.64 7.46z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGlobe24Heavy);
