/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconBank16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fill={fill}
        d="M0 13.5h16V16H0zM8 0L0 5.5h16L8 0zM5 6.5H3v6h2v-6zM9 6.5H7v6h2v-6zM13 6.5h-2v6h2v-6z"
      />
    </svg>
  );
};

export default React.memo(SvgIconBank16Heavy);
