/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconGiftBox12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M8.5 3c.83 0 1.5-.67 1.5-1.5S9.33 0 8.5 0C6.64 0 6 3 6 3s-.64-3-2.5-3C2.67 0 2 .67 2 1.5S2.67 3 3.5 3H0v9h12V3H8.5zm-7 7.5v-6h3.75v6H1.5zm9 0H6.75v-6h3.75v6z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGiftBox12Light);
