/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconGear12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M12 6.75v-1.5l-1.72-.57c-.08-.27-.19-.52-.32-.77l.81-1.62-1.06-1.06-1.62.81c-.24-.13-.5-.24-.77-.32L6.75 0h-1.5l-.57 1.72c-.27.08-.53.19-.77.32l-1.62-.81-1.06 1.06.81 1.62c-.13.24-.24.5-.32.77L0 5.25v1.5l1.72.57c.08.27.19.53.32.77l-.81 1.62 1.06 1.06 1.62-.81c.24.13.5.23.77.32L5.25 12h1.5l.57-1.72c.27-.08.52-.19.77-.32l1.62.81 1.06-1.06-.81-1.62c.13-.24.23-.5.32-.77L12 6.75zM6 8.5a2.5 2.5 0 010-5 2.5 2.5 0 010 5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGear12Heavy);
