/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconTradingVertLine16Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M7 16h2V0H7v16z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconTradingVertLine16Light);
