/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconCashGbp24Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M5.38 11.09h1.37c-.22-.77-.37-1.61-.37-2.59 0-3.31 2.66-5.3 6.12-5.3 3.94 0 5.86 2.14 6.05 5.33h-3.58c-.26-1.56-.91-2.35-2.38-2.35-1.39 0-2.35.98-2.35 2.5 0 .86.1 1.66.24 2.42h4.58v2.38h-4.1c.1.62.17 1.3.17 1.99 0 .55-.12 1.03-.29 1.46 1.15.34 2.11.82 2.9.82 1.03 0 1.68-.46 1.75-1.66h3.46c-.14 2.71-1.68 4.73-4.51 4.73-2.3 0-3.91-1.34-5.14-1.34-.86 0-1.25.53-1.32 1.13H5.04c.12-1.58.91-3.22 2.54-3.77.12-.38.22-.82.22-1.37 0-.67-.14-1.32-.34-1.99H5.38v-2.39z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCashGbp24Heavy);
