/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconSoundOff16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 4.5h4L10 0v16l-6-4.5H0v-7zm14.94.97L16 6.53 14.53 8 16 9.47l-1.06 1.06-1.47-1.47L12 10.53l-1.06-1.06L12.41 8l-1.47-1.47L12 5.47l1.47 1.47 1.47-1.47z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconSoundOff16Heavy);
