/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconHeart16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M14.83 2.82a3.996 3.996 0 00-5.65 0L8 4 6.82 2.82a3.996 3.996 0 00-5.65 5.65L8 15l6.83-6.53a3.996 3.996 0 000-5.65z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconHeart16Heavy);
