/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconCheckbox24Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M21.5 21.5v-19h-19v19h19zM0 0h24v24H0V0zm5.42 12.99l4.67 4.67L18.75 9l-1.76-1.77-6.9 6.89-2.9-2.9-1.77 1.77z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCheckbox24Light);
