/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconCashEur16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M2.86 6.48h1.07C4.27 3.95 6 2.11 8.66 2.11c2.56 0 4.13 1.38 4.39 3.91h-2.42c-.16-1.25-.86-1.94-1.99-1.94-1.28 0-1.98.94-2.19 2.4h2.98l-.2 1.06H6.4v.99h2.66l-.2 1.05H6.45c.21 1.46.9 2.29 2.21 2.29 1.23 0 1.9-.72 2.1-2.14h2.38c-.3 2.62-1.84 4.16-4.53 4.16-2.74 0-4.35-1.79-4.67-4.31H2.86V8.53h1.01v-.99H2.86V6.48z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCashEur16Heavy);
