/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconVisible24Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={25}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M.142 12.64C2.583 17.8 7.133 21 12.002 21c4.88 0 9.42-3.2 11.86-8.36.19-.4.19-.87 0-1.28C21.422 6.2 16.883 3 12.003 3c-4.87 0-9.42 3.2-11.86 8.36-.19.4-.19.87 0 1.28zM12.002 18c-3.56 0-6.81-2.23-8.82-6 2-3.77 5.26-6 8.82-6 3.56 0 6.82 2.23 8.82 6-2 3.77-5.26 6-8.82 6zm3.5-6a3.5 3.5 0 11-7 0 3.5 3.5 0 017 0z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconVisible24Heavy);
