/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../../styles.css';

const SvgIconList12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M12 .5H4v2h8v-2zM1.5 3a1.5 1.5 0 100-3 1.5 1.5 0 000 3zM1.5 7.5a1.5 1.5 0 100-3 1.5 1.5 0 000 3zM1.5 12a1.5 1.5 0 100-3 1.5 1.5 0 000 3zM12 5H4v2h8V5zM12 9.5H4v2h8v-2z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconList12Heavy);
