services:
  app:
    containers:
      app:
        resources:
          limits:
            memory: 500M
          requests:
            cpu: 50m
            memory: 500M
        image: frontend/cds/cds-figma-sync
      envmapper:
        resources:
          limits:
            memory: 500M
          requests:
            cpu: 50m
            memory: 500M
        image: ""
    target_group_bindings:
      http: frontend-cds-app-cds-figma-s-k8s
    scaling:
      min: 1
      max: 1
      targetcpu: 80
