// Add ignorable files to the bottom of this list
// Example: "!**/*.native.(ts|tsx)" would ignore *.native.ts or *.native.tsx files
export const fileIgnorePatterns = [
  '!**/*.md',
  '!**/*.ejs.t',
  '!**/*.test.(ts|tsx)',
  '!**/*.stories.(ts|tsx)',
  '!**/*.d.(ts|tsx)',
  '!**/dangerfile.ts',
  '!**/dangerfile-coverage.ts',
  '!**/types/*.ts',
];

export const overlayWebMovedComponents = [
  'packages/web/__stories__/AppSwitcher.stories.tsx',
  'packages/web/__stories__/AppSwitcherContent.tsx',
  'packages/web/__stories__/Navigation.stories.tsx',
  'packages/web/tabs/__stories__/TabNavigation.stories.tsx',
  'packages/web/__stories__/UserSwitcher.stories.tsx',
  'packages/web/__stories__/UserSwitcherContent.tsx',
  'packages/web/dropdown/Dropdown.tsx',
  'packages/web/dropdown/DropdownContent.tsx',
  'packages/web/dropdown/DropdownProps.ts',
  'packages/web/dropdown/MenuItem.tsx',
  'packages/web/dropdown/__stories__/Dropdown.stories.tsx',
  'packages/web/dropdown/__stories__/DropdownContent.stories.tsx',
  'packages/web/dropdown/__stories__/DropdownInteractive.stories.tsx',
  'packages/web/dropdown/__tests__/Dropdown.test.tsx',
  'packages/web/dropdown/__tests__/MenuItem.test.tsx',
  'packages/web/dropdown/index.ts',
  'packages/web/index.ts',
  'packages/web/navigation/__stories__/ComposedSystem.stories.mdx',
  'packages/web/navigation/__stories__/NavLink.stories.mdx',
  'packages/web/navigation/__stories__/NavigationBar.stories.mdx',
  'packages/web/navigation/__stories__/NavigationStorySetup.tsx',
  'packages/web/navigation/__stories__/Sidebar.stories.mdx',
  'packages/web/navigation/__tests__/SidebarMoreMenu.test.tsx',
  'packages/web/overlays/__stories__/AllOverlays.stories.tsx',
  'packages/web/overlays/__stories__/SearchInputMenu.stories.tsx',
  'packages/web/overlays/__tests__/FocusTrap.test.tsx',
  'packages/web/overlays/popover/Popover.tsx',
  'packages/web/overlays/popover/PopoverProps.ts',
  'packages/web/overlays/__tests__/Popover.test.tsx',
  'packages/web/overlays/popover/usePopper.ts',
  'packages/web/controls/Select.tsx',
  'packages/web/controls/SelectOption.tsx',
  'packages/web/controls/__stories__/Select.stories.tsx',
  'packages/web/controls/__stories__/SelectInteraction.stories.tsx',
  'packages/web/controls/__stories__/SelectOption.stories.tsx',
  'packages/web/controls/__tests__/Select.test.tsx',
  'packages/web/navigation/SidebarMoreMenu.tsx',
  'packages/web/overlays/Tooltip/Tooltip.tsx',
  'packages/web/overlays/Tooltip/TooltipContent.tsx',
  'packages/web/overlays/Tooltip/TooltipProps.ts',
  'packages/web/overlays/__stories__/Tooltip.stories.tsx',
  'packages/web/overlays/__stories__/TooltipContent.stories.tsx',
  'packages/web/overlays/Tooltip/useTooltipState.ts',
];

export const sparklineWebMovedComponents = [
  'packages/web/visualizations/Counter.tsx',
  'packages/web/visualizations/Sparkline.tsx',
  'packages/web/visualizations/SparklineArea.tsx',
  'packages/web/visualizations/SparklineAreaPattern.tsx',
  'packages/web/visualizations/SparklineGradient.tsx',
  'packages/web/visualizations/SparklinePath.tsx',
  'packages/web/visualizations/VisualizationContainer.tsx',
  'packages/web/visualizations/sparkline-interactive-header/SparklineInteractiveHeader.tsx',
  'packages/web/visualizations/sparkline-interactive-header/__stories__/SparklineInteractiveHeader.stories.tsx',
  'packages/web/visualizations/sparkline-interactive/InnerSparklineInteractiveProvider.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractive.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveAnimatedPath.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveHoverDate.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveLineVertical.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveMarkerDates.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractivePaths.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractivePeriodSelector.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveProvider.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveScrubHandler.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveScrubProvider.tsx',
  'packages/web/visualizations/sparkline-interactive/SparklineInteractiveTimeseriesPaths.tsx',
  'packages/web/visualizations/sparkline-interactive/useSparklineInteractiveConstants.ts',
];

export const sparklineMobileMovedComponents = [
  'packages/mobile/visualizations/Sparkline.tsx',
  'packages/mobile/visualizations/Sparkline.tsx',
  'packages/mobile/visualizations/SparklineArea.tsx',
  'packages/mobile/visualizations/SparklineAreaPattern.tsx',
  'packages/mobile/visualizations/SparklineGradient.tsx',
  'packages/mobile/visualizations/VisualizationContainer.tsx',
  'packages/mobile/visualizations/VisualizationContainer.tsx',
  'packages/mobile/visualizations/__stories__/SparklineGradient_Deprecated.stories.tsx',
  'packages/mobile/visualizations/__stories__/Sparkline_Deprecated.stories.tsx',
  'packages/mobile/visualizations/sparkline-interactive-header/SparklineInteractiveHeader.tsx',
  'packages/mobile/visualizations/sparkline-interactive-header/__stories__/SparklineInteractiveHeader_Deprecated.stories.tsx',
  'packages/mobile/visualizations/sparkline-interactive-header/useSparklineInteractiveHeaderStyles.ts',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractive.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveAnimatedPath.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveHoverDate.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveLineVertical.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveMarkerDates.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveMinMax.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractivePanGestureHandler.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractivePaths.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractivePeriodSelector.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveProvider.tsx',
  'packages/mobile/visualizations/sparkline-interactive/SparklineInteractiveTimeseriesPaths.tsx',
  'packages/mobile/visualizations/sparkline-interactive/__stories__/SparklineInteractive_Deprecated.stories.tsx',
  'packages/mobile/visualizations/sparkline-interactive/useInterruptiblePathAnimation.ts',
  'packages/mobile/visualizations/sparkline-interactive/useMinMaxTransform.ts',
  'packages/mobile/visualizations/sparkline-interactive/useOpacityAnimation.ts',
  'packages/mobile/visualizations/sparkline-interactive/useSparklineInteractiveConstants.ts',
  'packages/mobile/visualizations/sparkline-interactive/useSparklineInteractiveLineStyles.ts',
];

/** See go/frozen-components for more info */
export const frozenComponentPatterns = [
  'packages/mobile/visualizations/sparkline-interactive/*.(ts|tsx)',
  'packages/mobile/visualizations/sparkline-interactive-header/*.(ts|tsx)',
  'packages/web/dropdown/*.(ts|tsx)',
  'packages/web/overlays/popover/*.(ts|tsx)',
  'packages/common/animation/dropdown.ts',
  ...overlayWebMovedComponents,
  ...sparklineWebMovedComponents,
  ...sparklineMobileMovedComponents,
];

export const componentPatterns = [
  'packages/web/**/*.tsx',
  'packages/mobile/**/*.tsx',
  'packages/web-visualization/**/*.tsx',
  'packages/mobile-visualization/**/*.tsx',
  'packages/cds-web-overlays/**/*.tsx',
];

// publicly facing packages that are related to CDS components
export const cdsPackagesPatterns = [
  'packages/web/**/*.(tsx|ts)',
  'packages/mobile/**/*.(tsx|ts)',
  'packages/common/**/*.(tsx|ts)',
  'packages/web-visualization/**/*.(tsx|ts)',
  'packages/mobile-visualization/**/*.(tsx|ts)',
  'packages/cds-web-overlays/**/*.(tsx|ts)',
];
