/**
 * DO NOT MODIFY
 * Generated from yarn nx run illustrations:sync
 */

export type SpotIconName =
  | 'advancedTradeProduct'
  | 'assetHubProduct'
  | 'assetManagementProduct'
  | 'base'
  | 'borrowProduct'
  | 'cloudProduct'
  | 'coinbase'
  | 'coinbaseOneProduct'
  | 'commerceProduct'
  | 'custodyProduct'
  | 'dataMarketplace'
  | 'delegateProduct'
  | 'derivativesProduct'
  | 'exchangeProduct'
  | 'helpCenterProduct'
  | 'institutionalProduct'
  | 'internationalExchangeProduct'
  | 'learningRewardsProduct'
  | 'nftProduct'
  | 'nodeProduct'
  | 'participateProduct'
  | 'paySDKProduct'
  | 'primeProduct'
  | 'privateClientProduct'
  | 'productCoinbaseCard'
  | 'productCompliance'
  | 'productEarn'
  | 'productPro'
  | 'productWallet'
  | 'rewardsProduct'
  | 'rosettaProduct'
  | 'signInProduct'
  | 'stakingProduct'
  | 'venturesProduct'
  | 'wallet'
  | 'walletAsAServiceProduct';
