/**
 * DO NOT MODIFY
 * Generated from yarn nx run illustrations:sync
 */

export type SpotIconName =
  | '2fa'
  | 'advancedTradeProduct'
  | 'assetHubProduct'
  | 'assetManagementProduct'
  | 'authenticator'
  | 'bank'
  | 'base'
  | 'borrowProduct'
  | 'cb1Cash'
  | 'chat'
  | 'cloudProduct'
  | 'coinbase'
  | 'coinbaseOneChart'
  | 'coinbaseOneEarn'
  | 'coinbaseOneProduct'
  | 'commerceProduct'
  | 'creditCard'
  | 'custodyProduct'
  | 'dataMarketplace'
  | 'delegate'
  | 'delegateProduct'
  | 'derivativesProduct'
  | 'done'
  | 'email'
  | 'error'
  | 'exchangeProduct'
  | 'fast'
  | 'helpCenterProduct'
  | 'idVerification'
  | 'institutionalProduct'
  | 'internationalExchangeProduct'
  | 'learningRewardsProduct'
  | 'multiCoin'
  | 'nftProduct'
  | 'nodeProduct'
  | 'noFees'
  | 'outage'
  | 'participateProduct'
  | 'paySDKProduct'
  | 'pieChart'
  | 'primeProduct'
  | 'privateClientProduct'
  | 'productCoinbaseCard'
  | 'productCompliance'
  | 'productEarn'
  | 'productPro'
  | 'productWallet'
  | 'recurringPurchases'
  | 'rewardsProduct'
  | 'rosettaProduct'
  | 'send'
  | 'shield'
  | 'signInProduct'
  | 'stakingProduct'
  | 'venturesProduct'
  | 'wallet'
  | 'walletAsAServiceProduct'
  | 'walletLogo'
  | 'warning';
