/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconPencil12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={13}
      height={13}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M9 1.883L2.279 8.604 4.4 10.727l6.721-6.722L9 1.883zM11.827 3.304l.88-.88a.996.996 0 000-1.41l-.7-.721a.996.996 0 00-1.41 0l-.891.89 2.12 2.121zM1.761 9.508l-.76 2.501 2.501-.76-1.741-1.741z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconPencil12Heavy);
