/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconCashJpy16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M4.17 8.02h2.3L3.31 2.28h2.82L8.2 6.54l2.02-4.26h2.48l-3 5.74h2.32V9.1H9.39v.98h2.62v1.06H9.39v2.59H6.8v-2.59H4.17v-1.06H6.8V9.1H4.17V8.02z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCashJpy16Heavy);
