/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconLock24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.5 6.5V9h-3V6.5C5.5 2.92 8.42 0 12 0s6.5 2.92 6.5 6.5V9h-3V6.5C15.5 4.57 13.93 3 12 3S8.5 4.57 8.5 6.5zM2 24V10h20v14H2zm11-3v-4.28c.6-.34 1-.98 1-1.72 0-1.1-.9-2-2-2s-2 .9-2 2c0 .74.4 1.38 1 1.72V21h2z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconLock24Heavy);
