/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconExternalLink12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M8 10.5H1.5V4h3.67l1.5-1.5H0V12h9.5V5.33L8 6.83v3.67z" fill={fill} />
      <path d="M7 0v1.5h2.44L3.97 6.97l1.06 1.06 5.47-5.47V5H12V0H7z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconExternalLink12Heavy);
