/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconStep312Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M2.65 7.56H4.4c.07.83.52 1.43 1.55 1.43.97 0 1.43-.47 1.43-1.24 0-.82-.46-1.24-1.38-1.24h-.67V5.22h.62c.9 0 1.31-.41 1.31-1.14 0-.61-.4-1.07-1.19-1.07-.82 0-1.32.49-1.42 1.29H2.94c.1-1.57 1.21-2.72 3.17-2.72 1.88 0 2.99.98 2.99 2.33 0 .96-.56 1.56-1.42 1.86 1 .22 1.67.92 1.67 2.02 0 1.61-1.24 2.63-3.32 2.63-2.19-.01-3.3-1.12-3.38-2.86z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep312Heavy);
