/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconCashJpy12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M3.3 6.1h1.79L2.64 1.71h1.74l1.76 3.45 1.69-3.45h1.54L7.06 6.1h1.8v.76H6.87v.8h1.99v.77H6.87v1.86H5.29V8.43H3.3v-.77h1.99v-.8H3.3V6.1z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCashJpy12Heavy);
