/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconApi12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 4l6 4 6-4-6-4-6 4zm9.3 4l-.9-.6 1.35-.9L12 8l-6 4-6-4 2.25-1.5 1.35.9-.9.6L6 10.2 9.3 8z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconApi12Heavy);
