/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconClose16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M15.63 2.13L13.87.37 8 6.23 2.13.37.37 2.13 6.23 8 .37 13.87l1.76 1.76L8 9.77l5.87 5.86 1.76-1.76L9.77 8l5.86-5.87z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconClose16Heavy);
