/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconMarketCap16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 1v14h16V1H0zm14 6.16l-4.48 4.48-4.27-4.02L2 10.69V7.94l3.25-3.07 4.23 3.98L14 4.34v2.82z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconMarketCap16Heavy);
