/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconTradingChartCandles12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3.5 0H5v7H3.5V0zM0 2.5h1.5v7H0v-7zM8.5 5H7v7h1.5V5zm2-2.5H12v7h-1.5v-7z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTradingChartCandles12Light);
