/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconChartPie16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M7.25 1.5C3.25 1.5 0 4.75 0 8.75S3.25 16 7.25 16s7.25-3.25 7.25-7.25H7.25V1.5z"
        fill={fill}
      />
      <path d="M8.75 0v7.25H16C16 3.25 12.75 0 8.75 0z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconChartPie16Heavy);
