/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconExternalLink16Light = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M10.5 9.04V14H2V5.5h4.96l2-2H0V16h12.5V7.04l-2 2z" fill={fill} />
      <path d="M9 0v2h3.59L5.11 9.47l1.42 1.42L14 3.41V7h2V0H9z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconExternalLink16Light);
