/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconInitiator12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.04 6L.5 2.46l1.41-1.41L6.86 6l-4.95 4.95L.5 9.54 4.04 6zm5.13 0L5.64 2.46l1.41-1.41L12 6l-4.95 4.95-1.41-1.41L9.17 6z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconInitiator12Heavy);
