/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconStep624Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M5.17 12.65v-.43c0-5.81 3.14-9.05 7.34-9.05 3.41 0 5.57 1.61 5.95 4.75h-3.6c-.24-1.13-.82-1.82-2.3-1.82-2.14 0-3.46 1.87-3.55 5.4.79-1.27 2.09-2.14 4.15-2.14 3.24 0 5.66 2.11 5.66 5.57 0 3.53-2.52 5.9-6.6 5.9-5.18 0-7.05-3.5-7.05-8.18zm9.84 2.33c0-1.8-1.08-3.05-2.83-3.05-1.73 0-2.93 1.22-2.93 2.93 0 1.97 1.2 3.17 2.93 3.17 1.7-.01 2.83-1.25 2.83-3.05z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep624Heavy);
