/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconHeart12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M11.12 1.88a3 3 0 00-4.24 0L6 2.76l-.88-.88a3 3 0 00-4.24 0 3 3 0 000 4.24L6 11l5.12-4.88a3 3 0 000-4.24z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconHeart12Heavy);
