/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconGear24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M24 13.5v-3l-3.39-1.13c-.17-.56-.39-1.09-.66-1.59l1.6-3.2-2.12-2.12-3.2 1.6c-.5-.27-1.04-.49-1.59-.66L13.5 0h-3L9.37 3.39c-.56.17-1.09.4-1.59.66l-3.2-1.6-2.13 2.13 1.6 3.2c-.27.5-.49 1.04-.66 1.59L0 10.5v3l3.39 1.13c.17.56.39 1.09.66 1.59l-1.6 3.2 2.12 2.12 3.2-1.6c.5.27 1.04.49 1.59.66L10.5 24h3l1.13-3.39c.56-.17 1.09-.39 1.59-.66l3.2 1.6 2.12-2.12-1.6-3.2c.27-.5.49-1.04.66-1.59L24 13.5zM17.5 12c0 3.03-2.47 5.5-5.5 5.5A5.51 5.51 0 016.5 12c0-3.03 2.47-5.5 5.5-5.5s5.5 2.47 5.5 5.5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGear24Heavy);
