/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconCopy16Light = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M4.5 0v3h2V2h7v8h-1v2h3V0h-11z" fill={fill} />
      <path d="M9.5 6v8h-7V6h7zm2-2H.5v12h11V4z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconCopy16Light);
