/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconNotVisible16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={17}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M15.893 7.48c-.58-1.28-1.36-2.38-2.25-3.26l-1.3 2.25c.38.45.72.96 1.02 1.53-.96 1.83-2.37 3.07-3.95 3.53l-1.56 2.7c.05 0 .1.01.15.01 3.25 0 6.28-2.2 7.89-5.73.15-.32.15-.7 0-1.03zM12.242 0l-1.37 2.37c-.91-.39-1.88-.62-2.87-.62-3.25 0-6.28 2.2-7.89 5.73-.15.33-.15.71 0 1.04 1.01 2.22 2.59 3.89 4.42 4.84l-.96 1.66 1.7.98L13.942.98l-1.7-.98zm-9.6 8c1.25-2.36 3.22-3.75 5.36-3.75.56 0 1.1.11 1.62.29l-.92 1.6a2.03 2.03 0 00-.7-.14c-1.1 0-2 .9-2 2 0 .62.29 1.17.74 1.54l-.97 1.68c-1.24-.61-2.33-1.71-3.13-3.22z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconNotVisible16Heavy);
