/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconUndo16Light = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M8.35 15.65c-3.11 0-5.88-1.85-7.07-4.72l1.85-.77a5.64 5.64 0 005.22 3.49C11.46 13.65 14 11.11 14 8c0-3.11-2.53-5.65-5.65-5.65-2.43 0-4.61 1.6-5.36 3.9l2.51 2.5H0v-5.5L1.45 4.7C2.71 2.09 5.39.36 8.35.36 12.57.35 16 3.78 16 8s-3.43 7.65-7.65 7.65z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconUndo16Light);
