/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconBank24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M24 21H0v3h24v-3zM21 6l-9-6-9 6H0v3h24V6h-3zM7.5 10h-3v10h3V10zM13.5 10h-3v10h3V10zM19.5 10h-3v10h3V10z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconBank24Heavy);
