/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconStep216Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M3.68 13.39l4.19-4.43c1.1-1.17 1.81-2.18 1.81-3.22 0-.94-.53-1.55-1.52-1.55-1.01 0-1.65.59-1.82 2.1H3.98C4.11 3.64 5.71 2.2 8.27 2.2c2.53 0 3.97 1.41 3.97 3.47 0 1.52-.88 2.77-2.21 4.05l-2.16 2.11h4.45v1.97H3.68v-.41z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep216Heavy);
