/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconTradingChartLine12Light = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M7.19 9.31l-3.99-3-2.05 2.45L0 7.8l2.96-3.55 4 3.01 3.9-4.57 1.14.98-4.81 5.64z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTradingChartLine12Light);
