/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconApi16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 5.33l8 5.34 8-5.34L8 0 0 5.33zm12.39 5.34l-1.07-.72 1.8-1.2L16 10.67 8 16l-8-5.33 2.88-1.92 1.8 1.2-1.07.72L8 13.6l4.39-2.93z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconApi16Heavy);
