/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconCheckboxChecked12Light = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M10.5 1.5v9h-9v-9h9zM12 0H0v12h12V0z" fill={fill} />
      <path d="M5.05 9L2.62 6.58l1.06-1.06 1.37 1.36L8.4 3.53l1.06 1.06L5.05 9z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconCheckboxChecked12Light);
