/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconGear16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M16 9V7l-2.26-.75c-.11-.37-.26-.73-.44-1.06l1.07-2.13-1.41-1.41-2.14 1.05a5.78 5.78 0 00-1.06-.44L9 0H7l-.75 2.26c-.37.12-.73.26-1.07.44L3.05 1.64 1.64 3.05 2.7 5.18c-.18.34-.32.7-.44 1.07L0 7v2l2.26.75c.11.37.26.73.44 1.06l-1.07 2.13 1.41 1.41 2.13-1.07c.34.18.69.33 1.06.44L7 16h2l.75-2.26c.37-.11.73-.26 1.06-.44l2.13 1.07 1.41-1.41-1.07-2.13c.18-.34.33-.69.44-1.06L16 9zm-4.5-1c0 1.93-1.57 3.5-3.5 3.5S4.5 9.93 4.5 8 6.07 4.5 8 4.5s3.5 1.57 3.5 3.5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGear16Heavy);
