/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconQuestionMark12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M6 0C2.69 0 0 2.69 0 6s2.69 6 6 6 6-2.69 6-6-2.69-6-6-6zm-.18 9.38c-.46 0-.83-.34-.83-.78s.37-.78.83-.78c.45 0 .82.34.82.78a.81.81 0 01-.82.78zm1.55-3.72c-.43.41-.89.78-.94 1.26v.22H5.22v-.27c0-.7.47-1.14.89-1.56.33-.31.61-.6.61-.96 0-.41-.22-.67-.69-.67-.5 0-.83.36-.89.93H3.89c.05-1.25.95-1.99 2.22-1.99 1.32 0 2 .67 2 1.62 0 .63-.35 1.04-.74 1.42z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconQuestionMark12Heavy);
