/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconTrxConvert12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6 .5c1.77 0 3.35.84 4.35 2.15L12 1v5H7l1.92-1.92A3.5 3.5 0 006 2.5c-1.46 0-2.7.89-3.23 2.17L.92 3.9C1.75 1.9 3.71.5 6 .5zM3.08 7.92A3.5 3.5 0 006 9.5c1.46 0 2.7-.89 3.23-2.16l1.85.76c-.83 2-2.79 3.4-5.08 3.4-1.77 0-3.35-.84-4.35-2.15L0 11V6h5L3.08 7.92z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTrxConvert12Heavy);
