/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconCheckboxChecked16Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M6.75 11.84L3.68 8.77l1.41-1.41 1.66 1.66 4.16-4.16 1.41 1.42-5.57 5.56z"
        fill={fill}
      />
      <path d="M14 2v12H2V2h12zm2-2H0v16h16V0z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconCheckboxChecked16Light);
