/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconStake24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 0C7.31 0 3.5 3.81 3.5 8.5c0 4.69 3.81 8.5 8.5 8.5 4.69 0 8.5-3.81 8.5-8.5C20.5 3.81 16.69 0 12 0zm0 15a6.5 6.5 0 110-13 6.5 6.5 0 010 13zm12 1h-3.5v4.5h-17V16H0v8h24v-8zm-6.5-7.5a5.5 5.5 0 11-11 0 5.5 5.5 0 0111 0z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStake24Heavy);
