/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconStep616Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M3.45 8.43v-.29c0-3.87 2.1-6.03 4.9-6.03 2.27 0 3.71 1.07 3.97 3.17h-2.4c-.17-.75-.55-1.22-1.54-1.22-1.42 0-2.3 1.25-2.37 3.6.53-.85 1.39-1.42 2.77-1.42 2.16 0 3.78 1.41 3.78 3.71 0 2.35-1.68 3.94-4.4 3.94-3.47 0-4.71-2.34-4.71-5.46zm6.56 1.55c0-1.2-.72-2.03-1.89-2.03-1.15 0-1.95.82-1.95 1.95 0 1.31.8 2.11 1.95 2.11 1.14.01 1.89-.82 1.89-2.03z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep616Heavy);
