/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconCaretLeft16Light = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M11.39 3.05L6.44 8l4.95 4.95-1.42 1.41L3.61 8l6.36-6.36 1.42 1.41z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconCaretLeft16Light);
