/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconStep324Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M5.3 15.12h3.5c.14 1.66 1.03 2.86 3.1 2.86 1.94 0 2.86-.94 2.86-2.47 0-1.63-.91-2.47-2.76-2.47h-1.34v-2.59h1.25c1.8 0 2.62-.82 2.62-2.28 0-1.22-.79-2.14-2.38-2.14-1.63 0-2.64.98-2.83 2.59H5.88c.19-3.14 2.42-5.45 6.34-5.45 3.77 0 5.98 1.97 5.98 4.66 0 1.92-1.13 3.12-2.83 3.72 1.99.43 3.34 1.85 3.34 4.03 0 3.22-2.47 5.26-6.65 5.26-4.38-.01-6.61-2.24-6.76-5.72z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep324Heavy);
