/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconTradingCross16Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M16 9h-5V0H9v9H0v2h9v5h2v-5h5V9z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconTradingCross16Light);
