/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconTradingUpArrow16Light = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14 7h2V0H9v2h3.59L0 14.59 1.42 16 14 3.42V7z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTradingUpArrow16Light);
