/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconStep416Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M8.8 11.45H3.18v-.95l4.95-8.23h3.19v7.32h1.5v1.86h-1.5v2.27H8.8v-2.27zm.05-1.86V4.23L5.78 9.59h3.07z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep416Heavy);
