/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconStep916Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M3.56 10.64h2.42c.16.78.62 1.28 1.71 1.28 1.52 0 2.27-1.2 2.32-3.54-.53.84-1.36 1.4-2.74 1.4-2.21 0-3.83-1.38-3.83-3.7 0-2.37 1.7-3.97 4.43-3.97 3.15 0 4.67 2.13 4.67 5.43v.51c0 3.75-1.71 5.84-4.79 5.84-2.46 0-3.93-1.18-4.19-3.25zM9.8 6.13c0-1.33-.79-2.14-1.95-2.14-1.14 0-1.89.83-1.89 2.03 0 1.2.74 2.03 1.89 2.03 1.17 0 1.95-.8 1.95-1.92z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep916Heavy);
