/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconPortrait12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.75 2.75a2.75 2.75 0 11-5.5 0 2.75 2.75 0 015.5 0zm-.77 3.26c1.23.06 2.31.86 2.7 2.04L12 12H0l1.31-3.95a2.99 2.99 0 012.7-2.04l.01.007c.124.095.963.733 1.98.733 1.05 0 1.91-.68 1.98-.74z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconPortrait12Heavy);
