/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconClock12Light = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.5 6c0-2.48-2.02-4.5-4.5-4.5S1.5 3.52 1.5 6s2.02 4.5 4.5 4.5 4.5-2.02 4.5-4.5zM0 6c0-3.31 2.69-6 6-6s6 2.69 6 6-2.69 6-6 6-6-2.69-6-6zm5.25.81l2.22 2.22 1.06-1.06-1.78-1.78V2.5h-1.5v4.31z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconClock12Light);
