/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconWallet24Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M4 2h16v4H4c-1.1 0-2-.9-2-2s.9-2 2-2zM2 7v12c0 1.66 1.34 3 3 3h17V7H2zm16 9c-.83 0-1.5-.67-1.5-1.5S17.17 13 18 13s1.5.67 1.5 1.5S18.83 16 18 16z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconWallet24Heavy);
