/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconUndo24Light = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M12.5 23.5c-4.63 0-8.79-2.76-10.6-7.02l2.3-.97A9.009 9.009 0 0012.5 21c4.96 0 9-4.04 9-9s-4.04-9-9-9C8.96 3 5.84 5.04 4.38 8.13L8.25 12H0V3.75l2.53 2.53C4.53 2.77 8.29.5 12.5.5 18.84.5 24 5.66 24 12s-5.16 11.5-11.5 11.5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconUndo24Light);
