/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconChartPieCircle12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12 5.5H6.5V0c2.93.24 5.26 2.57 5.5 5.5zM5 .09V7h6.91c-.48 2.84-2.94 5-5.91 5-3.31 0-6-2.69-6-6C0 3.03 2.16.57 5 .09z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconChartPieCircle12Heavy);
