/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconTradingCross12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M12 6.75H8.25V0h-1.5v6.75H0v1.5h6.75V12h1.5V8.25H12v-1.5z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconTradingCross12Light);
