/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconLock16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M1 7v9h14V7H1zm7.5 4.39V14h-1v-2.61c-.44-.19-.75-.63-.75-1.14a1.25 1.25 0 012.5 0c0 .51-.31.95-.75 1.14zM5.67 6V4.33C5.67 3.05 6.71 2 8 2s2.33 1.05 2.33 2.33V6h2V4.33C12.33 1.94 10.39 0 8 0S3.67 1.94 3.67 4.33V6h2z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconLock16Heavy);
