/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconStatusDot16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M3.5 8A1.75 1.75 0 110 8a1.75 1.75 0 013.5 0zM8 9.75a1.75 1.75 0 100-3.5 1.75 1.75 0 000 3.5zm6.25 0a1.75 1.75 0 100-3.5 1.75 1.75 0 000 3.5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStatusDot16Heavy);
