/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconSoundOff12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 3.5h3L7 0v12L3 8.5H0v-5zm11.29.65l.71.7L10.85 6 12 7.15l-.71.7-1.14-1.14L9 7.85l-.71-.7L9.44 6 8.29 4.85l.71-.7 1.15 1.14 1.14-1.14z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconSoundOff12Heavy);
