/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconCashJpy24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M6.26 12.04h3.46L4.97 3.42h4.22l3.1 6.38 3.02-6.38h3.72l-4.49 8.62h3.48v1.61h-3.94v1.46h3.94v1.58h-3.94v3.89H10.2v-3.89H6.26v-1.58h3.94v-1.46H6.26v-1.61z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCashJpy24Heavy);
