/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconStep016Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M3.01 8.27v-.54c0-3.52 2.05-5.62 4.99-5.62 2.95 0 4.98 2.02 4.98 5.57v.53c0 3.51-1.9 5.68-4.99 5.68-3.04 0-4.98-2.11-4.98-5.62zm7.4-.05v-.51c0-2.3-.8-3.6-2.38-3.6-1.6 0-2.42 1.23-2.42 3.6v.54c0 2.4.85 3.6 2.45 3.6 1.61.01 2.35-1.23 2.35-3.63z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep016Heavy);
