/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconTrashCan12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M8.5 1.5V1c0-.55-.45-1-1-1h-3c-.55 0-1 .45-1 1v.5H0V3h12V1.5H8.5zM2.15 11.11c.06.51.49.89 1 .89h5.71c.51 0 .94-.38.99-.89L10.59 4H1.41l.74 7.11z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTrashCan12Heavy);
