/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconInitiator24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.78 12L3 4.22 5.12 2.1l9.9 9.9-9.9 9.9L3 19.78 10.78 12zm7.98 0l-7.78-7.78L13.1 2.1 23 12l-9.9 9.9-2.12-2.12L18.76 12z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconInitiator24Heavy);
