/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconApi24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 8l12 8 12-8-12-8L0 8zm19.49 8l-2.24-1.5L19.5 13l4.5 3-12 8-12-8 4.5-3 2.25 1.5L4.51 16 12 21l7.49-5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconApi24Heavy);
