/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconQrCode24Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 11h11V0H0v11zm2.5-8.5h6v6h-6v-6zM13 0v11h11V0H13zm8.5 8.5h-6v-6h6v6zM20 4h-3v3h3V4zM4 4h3v3H4V4zm0 13h3v3H4v-3zm-4 7h11V13H0v11zm2.5-8.5h6v6h-6v-6zm17.5 2h1.5V13H24v7h-6.5v-4.5h-2V24H13V13h7v4.5zm0 4h-2.5V24H20v-2.5zm1.5 0H24V24h-2.5v-2.5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconQrCode24Heavy);
