/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconStatusDot24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5 12a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zm7 2.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5zm9.5 0a2.5 2.5 0 100-5 2.5 2.5 0 000 5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStatusDot24Heavy);
