/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import React, { SVGProps } from 'react';
import '../styles.css';

interface Props
  extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height' | 'className' | 'height' | 'children'> {
  // TODO: update type to "typeof colors[keyof typeof colors]" when colors are defined
  fill?: string;
  title?: string;
  titleId?: string;
}
const SvgIconSoundOff24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: Props) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 7h6l8-7v24l-8-7H0V7zm22.23.62L24 9.38 21.38 12 24 14.62l-1.77 1.76-2.61-2.61L17 16.38l-1.77-1.76L17.85 12l-2.62-2.62L17 7.62l2.62 2.61 2.61-2.61z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconSoundOff24Heavy);
