/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconPlay24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M22 12L6 21V3l16 9z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconPlay24Heavy);
