/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '@cb/design-system-icons/Icon/IconProps';
import '../styles.css';

const SvgIconClose12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M11.71 1.71L10.29.29 6 4.59 1.71.29.29 1.71 4.59 6l-4.3 4.29 1.42 1.42L6 7.41l4.29 4.3 1.42-1.42L7.41 6l4.3-4.29z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconClose12Heavy);
