version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./apps/cds-adoption/Dockerfile
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.git:/root/.git
    ports:
      - 3001:3001
