# Ignore these files
node_modules

apps/*/**
docs/*/**
libs/*/**
packages/*/**
tools/*/**

.buildkite
.git
.github
.nx
.vscode

# Allow these files
!.yarn
!.yarnrc.yml
!yarn.lock
!**/package.json
!**/project.json
!apps/cds-adoption/**/*
!libs/codegen/**/*
!libs/script-utils/**/*

# Ignore these files
private-key.pem
.env
.env.*
lib
mjs
esm
dist
temp
*.log
