/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconSortUp16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M3 6.5L8 0l5 6.5H3z" fill={fill} />
    </svg>
  );
};

export default memo(SvgIconSortUp16Heavy);
