/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconExpand24Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9 0v2H3.41l6.23 6.22-1.42 1.42L2 3.41V9H0V0h9zm6 2V0h9v9h-2V3.41l-6.22 6.23-1.42-1.42L20.59 2H15zm7 18.59l-6.22-6.23-1.42 1.42L20.59 22H15v2h9v-9h-2v5.59zm-20 0l6.22-6.23 1.42 1.42L3.41 22H9v2H0v-9h2v5.59z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconExpand24Light);
