/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStep824Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M5.29 15.72c0-2.09 1.2-3.6 3.17-4.3-1.56-.65-2.5-1.85-2.5-3.58 0-2.98 2.86-4.68 6.07-4.68 3.29 0 6.02 1.73 6.02 4.66 0 1.73-.98 2.9-2.5 3.58 2.02.7 3.14 2.18 3.14 4.22 0 3.36-2.88 5.21-6.7 5.21-3.77 0-6.7-1.75-6.7-5.11zm9.58-.38c0-1.68-1.22-2.62-2.83-2.62-1.58 0-2.88.94-2.88 2.64 0 1.7 1.27 2.64 2.85 2.64 1.63 0 2.86-.96 2.86-2.66zm-.41-7.25c0-1.32-1.06-2.21-2.42-2.21-1.36 0-2.45.84-2.45 2.23 0 1.39 1.13 2.23 2.47 2.23 1.39 0 2.4-.84 2.4-2.25z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconStep824Heavy);
