/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconTradingAnnotation12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M10.5 1.5v6H8.32l-.44.45-1.89 1.92-1.92-1.93-.45-.44H1.5v-6h9zM12 0H0v9h3l3 3 2.95-3H12V0z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconTradingAnnotation12Light);
