/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconPaypal12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M10.6 3.31c-.08-.1-.18-.19-.28-.27v-.18-.25c-.01-.13-.02-.26-.05-.38-.01-.07-.03-.15-.04-.22-.04-.13-.08-.24-.14-.36-.03-.06-.04-.11-.07-.17-.09-.17-.2-.33-.34-.48-.6-.66-1.62-1-3.03-1H3.31c-.55 0-1 .39-1.09.93L.83 9.75c-.04.26.03.53.21.73.18.2.43.32.69.32h1.33l-.03.18A.881.881 0 003.9 12h1.74c.52 0 .95-.37 1.03-.86 0-.01.02-.1.02-.11L7 9.01h.09c2.21 0 3.6-1.1 4-3.17.21-1.07.05-1.92-.49-2.53zM2.13 9.56l1.31-8.31h3.22c1.02 0 1.74.21 2.08.6.07.08.14.17.19.27.02.03.03.07.04.1.03.07.06.15.08.23 0 .01 0 .03.01.04-.07-.01-.13-.02-.19-.03-.29-.05-.62-.07-.97-.07H5.28c-.16 0-.31.04-.45.1-.31.15-.52.44-.58.78l-.99 6.29H2.13zm6.79-5.81c-.4 1.51-1.41 2.22-3.18 2.22h-.65l.37-2.33H7.9c.28 0 .54.02.77.05.06.01.12.03.18.04.02.01.05.01.07.02zm.95 1.86C9.58 7.08 8.7 7.76 7.09 7.76h-.26c-.52 0-.95.37-1.03.87l-.34 2.12H4.34l.07-.47.48-3.06h.85c2.07 0 3.49-.87 4.16-2.5.05.25.03.54-.03.89z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconPaypal12Heavy);
