/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStep316Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M3.53 10.08h2.34c.1 1.1.69 1.91 2.06 1.91 1.3 0 1.9-.62 1.9-1.65 0-1.09-.61-1.65-1.84-1.65H7.1V6.96h.83c1.2 0 1.74-.54 1.74-1.52 0-.82-.53-1.42-1.58-1.42-1.09 0-1.76.66-1.89 1.73H3.92c.13-2.1 1.62-3.63 4.23-3.63 2.51 0 3.98 1.31 3.98 3.1 0 1.28-.75 2.08-1.89 2.48 1.33.29 2.22 1.23 2.22 2.69 0 2.15-1.65 3.51-4.43 3.51-2.91-.01-4.4-1.5-4.5-3.82z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep316Heavy);
