/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStep424Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M13.2 17.17H4.78v-1.42L12.2 3.41h4.78v10.97h2.26v2.78h-2.26v3.41H13.2v-3.4zm.07-2.78V6.35l-4.61 8.04h4.61z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep424Heavy);
