/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconTrxWithdraw16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M16 13.5H0V16h16v-2.5zM8 0L3.5 6.5h3.25v6h2.5v-6h3.25L8 0z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconTrxWithdraw16Heavy);
