/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconSafe12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M0 0v10h12V0H0zm6 7.5a2.5 2.5 0 010-5 2.5 2.5 0 010 5zM0 11h3v1H0v-1zm9 0h3v1H9v-1zM7.5 5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconSafe12Heavy);
