/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconInitiator24Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.78 12L3 4.22 5.12 2.1l9.9 9.9-9.9 9.9L3 19.78 10.78 12zm7.98 0l-7.78-7.78L13.1 2.1 23 12l-9.9 9.9-2.12-2.12L18.76 12z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconInitiator24Heavy);
