/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStar12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M6 .29l1.42 4.36H12l-3.71 2.7 1.42 4.36L6 9.01l-3.71 2.7 1.42-4.36L0 4.65h4.58L6 .29z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStar12Heavy);
