/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStep924Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M5.34 15.96h3.62c.24 1.18.94 1.92 2.57 1.92 2.28 0 3.41-1.8 3.48-5.3-.79 1.25-2.04 2.09-4.1 2.09-3.31 0-5.74-2.06-5.74-5.54 0-3.55 2.54-5.95 6.65-5.95 4.73 0 7.01 3.19 7.01 8.14v.77c0 5.62-2.57 8.76-7.18 8.76-3.72-.02-5.93-1.79-6.31-4.89zm9.36-6.77c0-1.99-1.18-3.22-2.93-3.22-1.7 0-2.83 1.25-2.83 3.05 0 1.8 1.1 3.05 2.83 3.05 1.75 0 2.93-1.2 2.93-2.88z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconStep924Heavy);
