/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconIdeal16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 1h8.252C13.853 1 16 4.059 16 7.917c0 4.627-2.998 6.948-7.748 6.948H0V1zm.8.8v12.266h7.452c4.5 0 6.947-2.097 6.947-6.149 0-4.164-2.653-6.117-6.947-6.117H.8z"
        fill={fill}
      />
      <path
        d="M1.8 8.82h2.385v4.245H1.8V8.819zM2.992 8.162a1.483 1.483 0 100-2.965 1.483 1.483 0 000 2.965zM9.188 7.373v.688h-1.7V5.302h1.646v.687h-.958v.32h.906v.687h-.906v.378h1.012zm.298.688l.831-2.76h.978l.832 2.76h-.716l-.156-.534h-.899l-.156.534h-.714zm1.072-1.22h.497l-.228-.78h-.042l-.227.78zm1.914-1.54h.688v2.073h1.018C13.898 3.614 10.94 2.8 8.252 2.8H5.387v2.502h.424c.773 0 1.253.524 1.253 1.368 0 .87-.468 1.39-1.253 1.39h-.424v5.006h2.866c4.37 0 5.89-2.03 5.945-5.006h-1.726V5.3zm-7.086.689v1.384h.425c.294 0 .566-.086.566-.703 0-.604-.303-.681-.566-.681h-.425z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconIdeal16Heavy);
