/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconNotVisible12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={13}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.753 6c0 .97-.78 1.75-1.75 1.75-.026 0-.048-.003-.07-.005a.615.615 0 00-.07-.005L3.402 12l-1.3-.75 1.01-1.75C1.872 8.83.792 7.75.083 6.34a.742.742 0 010-.68c1.22-2.41 3.49-3.91 5.92-3.91.5 0 .99.07 1.47.2L8.602 0l1.3.75-2.46 4.26c.19.28.31.62.31.99zm-1.75-2.75c-1.78 0-3.4 1.02-4.4 2.75.58.99 1.36 1.74 2.26 2.2l.7-1.21a1.746 1.746 0 011.44-2.74c.024 0 .047.003.07.005a.615.615 0 00.07.005l.54-.94c-.04-.005-.078-.01-.118-.017-.184-.026-.373-.053-.563-.053zm3.8-.16c.85.66 1.59 1.52 2.12 2.57.11.21.11.47 0 .67-1.22 2.41-3.49 3.91-5.92 3.91a3.138 3.138 0 01-.32-.02l.87-1.51c1.56-.19 2.95-1.16 3.85-2.71a5.98 5.98 0 00-1.35-1.62l.75-1.29z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconNotVisible12Light);
