/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconIdentityCard16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 2v11h16V2H0zm7.5 9H2V4h5.5v7zm6.5-1H9.5V8.5H14V10zm0-3.5H9.5V5H14v1.5z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconIdentityCard16Heavy);
