/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconHeart24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={25}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M22.245 4.23a6 6 0 00-8.48 0L12.005 6l-1.77-1.77a6 6 0 00-8.48 0 6 6 0 000 8.48l10.25 9.77 10.24-9.77a5.981 5.981 0 000-8.48z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconHeart24Heavy);
