/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconGauge16Light = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M8 1C3.58 1 0 4.58 0 9c0 2.19.88 4.17 2.3 5.61l1.42-1.42A5.97 5.97 0 012 9c0-3.31 2.69-6 6-6s6 2.69 6 6c0 1.63-.66 3.11-1.72 4.2l1.42 1.42A8.005 8.005 0 0016 9c0-4.42-3.58-8-8-8z"
        fill={fill}
      />
      <path
        d="M9.67 9c0-.92-.75-1.67-1.67-1.67-.92 0-1.67.75-1.67 1.67 0 .92.75 1.67 1.67 1.67.08 0 .15-.01.23-.02l2.4 2.4 1.41-1.41-2.4-2.4c.01-.09.03-.16.03-.24z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGauge16Light);
