/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconMarketCap16Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 1v14h16V1H0zm14 2v1.34L9.48 8.86 5.25 4.88 2 7.94V3h12zM2 13v-2.31l3.25-3.07 4.27 4.02L14 7.16V13H2z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconMarketCap16Light);
