/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconGauge12Light = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M2.82 10.18A4.457 4.457 0 011.5 7c0-2.48 2.02-4.5 4.5-4.5s4.5 2.02 4.5 4.5c0 1.24-.5 2.37-1.32 3.18l1.06 1.06A5.944 5.944 0 0012 7c0-3.31-2.69-6-6-6S0 3.69 0 7c0 1.66.67 3.16 1.76 4.24l1.06-1.06z"
        fill={fill}
      />
      <path
        d="M9.03 8.97L7.22 7.16c.01-.06.03-.1.03-.16A1.25 1.25 0 106 8.25c.06 0 .1-.02.16-.03l1.81 1.81 1.06-1.06z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconGauge12Light);
