/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconWallet16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M2.97 1.5H13.5v3H2.97c-.81 0-1.47-.66-1.47-1.47v-.06c0-.81.66-1.47 1.47-1.47zM1.5 5.5v6.9c0 1.16.94 2.1 2.1 2.1h10.9v-9h-13zm10 5c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconWallet16Heavy);
