/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconRecurring16Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M7 4v4.41l2.79 2.8 1.42-1.42L9 7.59V4H7z" fill={fill} />
      <path
        d="M8 .5C4.96.5 2.24 2.32 1.07 5.13l1.85.77C3.77 3.83 5.77 2.5 8 2.5c3.03 0 5.5 2.47 5.5 5.5s-2.47 5.5-5.5 5.5c-2.13 0-4.01-1.24-4.92-3.08L5.5 8H0v5.5l1.6-1.6A7.52 7.52 0 008 15.5c4.14 0 7.5-3.36 7.5-7.5C15.5 3.86 12.14.5 8 .5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconRecurring16Heavy);
