/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconReCenter16Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M11.38 2.75L8 6.25l-3.38-3.5h2.63V0h1.5v2.75h2.63zm3.12 4.5h-13v1.5h13v-1.5zM8 9.75l-3.38 3.5h2.63V16h1.5v-2.75h2.63L8 9.75z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconReCenter16Light);
