/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconTradingUpArrow24Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M13.75 0v2.5h5.98L0 22.23 1.77 24 21.5 4.27v5.98H24V0H13.75z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconTradingUpArrow24Light);
