/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconBank12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M6 0L0 4h12L6 0zM3.75 5h-1.5v4h1.5V5zM6.75 5h-1.5v4h1.5V5zM9.75 5h-1.5v4h1.5V5zM0 10h12v2H0z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconBank12Heavy);
