/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStep812Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M2.65 7.86c0-1.04.6-1.8 1.58-2.15-.78-.32-1.25-.92-1.25-1.78 0-1.49 1.43-2.34 3.03-2.34 1.64 0 3.01.86 3.01 2.33 0 .86-.49 1.45-1.25 1.79 1.01.35 1.57 1.09 1.57 2.11 0 1.68-1.44 2.6-3.35 2.6-1.88-.01-3.34-.88-3.34-2.56zm4.78-.19c0-.84-.61-1.31-1.42-1.31-.79 0-1.44.47-1.44 1.32C4.57 8.53 5.21 9 6 9c.82 0 1.43-.48 1.43-1.33zm-.2-3.62c0-.66-.53-1.1-1.21-1.1-.68 0-1.23.41-1.23 1.11 0 .7.56 1.12 1.24 1.12.69-.01 1.2-.43 1.2-1.13z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep812Heavy);
