/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconWireTransfer24Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M24 18.5L17 13v4H7v-4H4v7h13v4l7-5.5zM7 7h10v4h3V4H7V0L0 5.5 7 11V7z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconWireTransfer24Heavy);
