/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconIdeal12Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 .75h6.19C10.39.75 12 3.044 12 5.938c0 3.47-2.248 5.21-5.81 5.21H0V.75zm.6.6v9.2h5.59c3.373 0 5.21-1.573 5.21-4.612 0-3.123-1.99-4.588-5.21-4.588H.6z"
        fill={fill}
      />
      <path
        d="M1.35 6.614h1.789V9.8h-1.79V6.614zM2.244 6.122a1.112 1.112 0 100-2.224 1.112 1.112 0 000 2.224zM6.891 5.53v.516H5.616v-2.07H6.85v.516h-.718v.24h.68v.515h-.68v.283h.76zm.223.516l.624-2.07h.733l.624 2.07h-.537l-.117-.4h-.674l-.117.4h-.536zm.804-.916h.373l-.17-.584h-.032l-.17.584zm1.436-1.154h.516V5.53h.763C10.424 2.71 8.206 2.1 6.19 2.1H4.04v1.877h.318c.58 0 .94.393.94 1.026 0 .653-.351 1.043-.94 1.043H4.04V9.8h2.15c3.277 0 4.418-1.522 4.458-3.754H9.354v-2.07zm-5.314.517V5.53h.318c.22 0 .425-.064.425-.527 0-.453-.227-.51-.425-.51H4.04z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconIdeal12Heavy);
