/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconArrowsVertical12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M12 4L9 0 6 4h6z" fill={fill} />
      <path d="M10 3H8v5h2V3zM0 8l3 4 3-4H0z" fill={fill} />
      <path d="M4 4H2v5h2V4z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconArrowsVertical12Heavy);
