/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconMarketCap12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 1v10h12V1H0zm3.96 4.77L1.5 7.88V5.9l2.54-2.18L7 6.69l3.47-3.47.03.03v2.06L7 8.81 3.96 5.77z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconMarketCap12Heavy);
