/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconStep212Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M2.76 10.04L5.9 6.71c.83-.87 1.36-1.63 1.36-2.41 0-.71-.4-1.16-1.14-1.16-.76 0-1.24.44-1.37 1.57H2.99c.1-1.98 1.29-3.06 3.21-3.06 1.9 0 2.97 1.06 2.97 2.6 0 1.14-.66 2.08-1.66 3.04L5.9 8.87h3.33v1.47H2.76v-.3z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconStep212Heavy);
