/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconPaperAirplane12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path d="M12 6L0 12l2-4.96L7.3 6 2 4.96 0 0l12 6z" fill={fill} />
    </svg>
  );
};

export default React.memo(SvgIconPaperAirplane12Heavy);
