/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconList16Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={16}
      height={16}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M16 .75H5.5v2.5H16V.75zM2 4a2 2 0 100-4 2 2 0 000 4zM2 10a2 2 0 100-4 2 2 0 000 4zM2 16a2 2 0 100-4 2 2 0 000 4zM16 6.75H5.5v2.5H16v-2.5zM16 12.75H5.5v2.5H16v-2.5z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconList16Heavy);
