/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconIdeal24Heavy = ({ fill = '#1652F0', title, titleId, ...props }: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={24}
      height={24}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M0 1.5h12.378C20.78 1.5 24 6.088 24 11.876c0 6.94-4.497 10.422-11.622 10.422H0V1.5zm1.2 1.2v18.398h11.178c6.749 0 10.42-3.144 10.42-9.222 0-6.247-3.98-9.176-10.42-9.176H1.2z"
        fill={fill}
      />
      <path
        d="M2.7 13.229h3.578v6.368H2.7V13.23zM4.488 12.244a2.224 2.224 0 100-4.448 2.224 2.224 0 000 4.448zM13.782 11.06v1.031h-2.55V7.953h2.469v1.03h-1.438v.48h1.36v1.031h-1.36v.566h1.52zm.446 1.032l1.248-4.14h1.467l1.247 4.14h-1.073l-.234-.8h-1.349l-.234.8h-1.072zm1.609-1.831h.746l-.342-1.17h-.063l-.341 1.17zm2.871-2.309h1.032v3.108h1.527c-.42-5.64-4.855-6.858-8.888-6.858H8.08v3.752h.636c1.16 0 1.88.787 1.88 2.052 0 1.306-.703 2.086-1.88 2.086H8.08V19.6h4.299c6.554 0 8.837-3.044 8.918-7.509h-2.589V7.952zM8.08 8.985v2.075h.637c.442 0 .85-.127.85-1.054 0-.905-.454-1.021-.85-1.021H8.08z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconIdeal24Heavy);
