/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import { memo } from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconTrashCan12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.5 0h-3c-.41 0-.75.34-.75.75v.75H0V3h12V1.5H8.25V.75C8.25.34 7.91 0 7.5 0zm.9 10.5l.69-6.75h1.51l-.75 7.36c-.06.51-.49.89-1 .89H3.14c-.51 0-.94-.38-1-.89l-.75-7.36H2.9l.69 6.75H8.4z"
        fill={fill}
      />
    </svg>
  );
};

export default memo(SvgIconTrashCan12Light);
