/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconExpand12Light = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.5 1.25V0H0v4.5h1.25V2.13l2.77 2.78.89-.89-2.78-2.77H4.5zm3 0V0H12v4.5h-1.25V2.13L7.98 4.91l-.89-.89 2.78-2.77H7.5zm.48 5.84l2.77 2.78V7.5H12V12H7.5v-1.25h2.37L7.09 7.98l.89-.89zM1.25 9.87l2.77-2.78.89.89-2.78 2.77H4.5V12H0V7.5h1.25v2.37z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconExpand12Light);
