/**
 * DO NOT MODIFY
 * Generated by svgr
 */
import * as React from 'react';

import type { InternalIconProps } from '../props';
import '../styles.css';

const SvgIconCalendar12Heavy = ({
  fill = '#1652F0',
  title,
  titleId,
  ...props
}: InternalIconProps) => {
  const role = title ? 'img' : 'presentation';
  return (
    <svg
      width={12}
      height={12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="cds-icon"
      role={role}
      aria-labelledby={titleId}
      {...props}
    >
      {title ? <title id={titleId}>{title}</title> : null}
      <path
        d="M11.5 1V0h-1v1h-1V0h-1v1h-1V0h-1v1h-1V0h-1v1h-1V0h-1v1h-1V0h-1v1H0v11h12V1h-.5zM10 10H2V4h8v6z"
        fill={fill}
      />
    </svg>
  );
};

export default React.memo(SvgIconCalendar12Heavy);
