/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable global-require */

export const routes = {
  Accordion: () => require('../accordions/__stories__/Accordion.stories').default,
  Alert: () => require('../overlays/__stories__/Alert.stories').default,
  Avatar: () => require('../media/__stories__/Avatar.stories').default,
  AvatarButton: () => require('../buttons/__stories__/AvatarButton.stories').default,
  Box: () => require('../layout/__stories__/Box.stories').default,
  Button: () => require('../buttons/__stories__/Button.stories').default,
  ButtonGroup: () => require('../buttons/__stories__/ButtonGroup.stories').default,
  Card: () => require('../cards/__stories__/Card.stories').default,
  Carousel: () => require('../media/__stories__/Carousel.stories').default,
  Checkbox: () => require('../controls/__stories__/Checkbox.stories').default,
  ContentCell: () => require('../cells/__stories__/ContentCell.stories').default,
  ContentCellFallback: () => require('../cells/__stories__/ContentCellFallback.stories').default,
  DebugFrontier: () => require('../system/__stories__/DebugFrontier.stories').default,
  Divider: () => require('../layout/__stories__/Divider.stories').default,
  Dots: () => require('../dots/__stories__/Dots.stories').default,
  Drawer: () => require('../overlays/__stories__/Drawer.stories').default,
  Group: () => require('../layout/__stories__/Group.stories').default,
  HeroSquare: () => require('../illustrations/__stories__/HeroSquare.stories').default,
  Icon: () => require('../icons/__stories__/Icon.stories').default,
  IconButton: () => require('../buttons/__stories__/IconButton.stories').default,
  InputIcon: () => require('../controls/__stories__/InputIcon.stories').default,
  InputIconButton: () => require('../controls/__stories__/InputIconButton.stories').default,
  InputStack: () => require('../controls/__stories__/InputStack.stories').default,
  Link: () => require('../typography/__stories__/Link.stories').default,
  ListCell: () => require('../cells/__stories__/ListCell.stories').default,
  ListCellFallback: () => require('../cells/__stories__/ListCellFallback.stories').default,
  Logo: () => require('../icons/__stories__/Logo.stories').default,
  Lottie: () => require('../animation/__stories__/Lottie.stories').default,
  LottieStatusAnimation: () =>
    require('../animation/__stories__/LottieStatusAnimation.stories').default,
  Modal: () => require('../overlays/__stories__/Modal.stories').default,
  Overlay: () => require('../overlays/__stories__/Overlay.stories').default,
  Pictogram: () => require('../illustrations/__stories__/Pictogram.stories').default,
  Pressable: () => require('../system/__stories__/Pressable.stories').default,
  PressableOpacity: () => require('../system/__stories__/PressableOpacity.stories').default,
  ProgressBar: () => require('../visualizations/__stories__/ProgressBar.stories').default,
  ProgressCircle: () => require('../visualizations/__stories__/ProgressCircle.stories').default,
  RadioGroup: () => require('../controls/__stories__/RadioGroup.stories').default,
  RemoteImage: () => require('../media/__stories__/RemoteImage.stories').default,
  SearchInput: () => require('../controls/__stories__/SearchInput.stories').default,
  Select: () => require('../controls/__stories__/Select.stories').default,
  SelectOption: () => require('../controls/__stories__/SelectOption.stories').default,
  Spacer: () => require('../layout/__stories__/Spacer.stories').default,
  Sparkline: () => require('../visualizations/__stories__/Sparkline.stories').default,
  SparklineGradient: () =>
    require('../visualizations/__stories__/SparklineGradient.stories').default,
  SparklineInteractive: () =>
    require('../visualizations/sparkline-interactive/__stories__/SparklineInteractive.stories')
      .default,
  SparklineInteractiveHeader: () =>
    require('../visualizations/sparkline-interactive-header/__stories__/SparklineInteractiveHeader.stories')
      .default,
  Spectrum: () => require('../system/__stories__/Spectrum.stories').default,
  SpotRectangle: () => require('../illustrations/__stories__/SpotRectangle.stories').default,
  SpotSquare: () => require('../illustrations/__stories__/SpotSquare.stories').default,
  Switch: () => require('../controls/__stories__/Switch.stories').default,
  TabIndicator: () => require('../tabs/__stories__/TabIndicator.stories').default,
  TabNavigation: () => require('../tabs/__stories__/TabNavigation.stories').default,
  Tabs: () => require('../tabs/__stories__/Tabs.stories').default,
  Text: () => require('../typography/__stories__/Text.stories').default,
  TextBody: () => require('../typography/__stories__/TextBody.stories').default,
  TextCaption: () => require('../typography/__stories__/TextCaption.stories').default,
  TextDisplay1: () => require('../typography/__stories__/TextDisplay1.stories').default,
  TextDisplay2: () => require('../typography/__stories__/TextDisplay2.stories').default,
  TextDisplay3: () => require('../typography/__stories__/TextDisplay3.stories').default,
  TextHeadline: () => require('../typography/__stories__/TextHeadline.stories').default,
  TextInput: () => require('../controls/__stories__/TextInput.stories').default,
  TextLabel1: () => require('../typography/__stories__/TextLabel1.stories').default,
  TextLabel2: () => require('../typography/__stories__/TextLabel2.stories').default,
  TextLegal: () => require('../typography/__stories__/TextLegal.stories').default,
  TextTitle1: () => require('../typography/__stories__/TextTitle1.stories').default,
  TextTitle2: () => require('../typography/__stories__/TextTitle2.stories').default,
  TextTitle3: () => require('../typography/__stories__/TextTitle3.stories').default,
  TextTitle4: () => require('../typography/__stories__/TextTitle4.stories').default,
  Toast: () => require('../overlays/__stories__/Toast.stories').default,
  TooltipV2: () => require('../overlays/__stories__/TooltipV2.stories').default,
  Tray: () => require('../overlays/__stories__/Tray.stories').default,
} as const;
