/* -------------------------------------------------------------------------- */
/*                   Sidebar overrides for typed customProps                  */
/* -------------------------------------------------------------------------- */
import type {
  SidebarItemCategoryLinkConfig,
  SidebarItemDoc as SidebarItemDocOriginal,
  SidebarItemHtml as SidebarItemHtmlOriginal,
  SidebarItemLink as SidebarItemLinkOriginal,
} from '@docusaurus/plugin-content-docs/lib/sidebars/types.js';
import { Options as PresetClassicOptions } from '@docusaurus/preset-classic';
import type { SetOptional } from 'type-fest';
import type { Expand } from '@cbhq/cds-common/types';
import type {
  PluginOptions as KbarPluginOptions,
  SidebarItemCustomProps as KBarCustomProps,
} from '@cbhq/docusaurus-plugin-kbar';
import type { SidebarItemCustomProps as ThemeCustomProps } from '@cbhq/docusaurus-theme/theme/DocSidebarItem';

export type PresetOptions = {
  theme?: undefined;
  docgen?: import('@cbhq/docusaurus-plugin-docgen').PluginOptions;
  kbar?: KbarPluginOptions;
} & PresetClassicOptions;

type SidebarItemCustomProps = Expand<KBarCustomProps & ThemeCustomProps>;

type SidebarItemBase = {
  customProps?: SidebarItemCustomProps;
};

type SidebarItemCategoryBase = Expand<
  SidebarItemBase & {
    type: 'category';
    label: string;
    collapsed: boolean;
    collapsible: boolean;
  }
>;
type SidebarItemDoc = Expand<SidebarItemBase & Omit<SidebarItemDocOriginal, 'customProps'>>;
type SidebarItemHtml = Expand<SidebarItemBase & Omit<SidebarItemHtmlOriginal, 'customProps'>>;
type SidebarItemLink = Expand<SidebarItemBase & Omit<SidebarItemLinkOriginal, 'customProps'>>;
type SidebarItemAutogenerated = Expand<
  SidebarItemBase & {
    type: 'autogenerated';
    dirName: string;
  }
>;

// The user-given configuration in sidebars.js, before normalization
type SidebarItemCategoryConfig = Expand<
  SetOptional<SidebarItemCategoryBase, 'collapsed' | 'collapsible'> & {
    items: SidebarItemConfig[];
    link?: SidebarItemCategoryLinkConfig;
  }
>;

type SidebarItemConfig =
  | SidebarItemDoc
  | SidebarItemHtml
  | SidebarItemLink
  | SidebarItemAutogenerated
  | SidebarItemCategoryConfig
  | string;

export type SidebarsConfig = Record<string, SidebarItemConfig[]>;

export {};
