export type IconProps = {
  /** Identifies the icon */
  kind: IconKind;
  /**
   * Specifies the icon size. The actual icon size is determined based on this prop and the
   * current scale.
   */

  size: IconSize;
};

export type IconSize = 'L' | 'M' | 'S' | 'XS';
export type Pixels = 32 | 24 | 16 | 12 | 8;

type IconKind =
  | 'allTimeHigh'
  | 'api'
  | 'arrowsHorizontal'
  | 'arrowsVertical'
  | 'backspace'
  | 'bank'
  | 'bell'
  | 'blockchain'
  | 'calendar'
  | 'card'
  | 'caretDown'
  | 'caretLeft'
  | 'caretRight'
  | 'caretUp'
  | 'cashEUR'
  | 'cashGBP'
  | 'cashJPY'
  | 'cashUSD'
  | 'chartBar'
  | 'chartPie'
  | 'chartVolume'
  | 'checkboxChecked'
  | 'checkboxEmpty'
  | 'checkmark'
  | 'circulatingSupply'
  | 'clock'
  | 'close'
  | 'copy'
  | 'document'
  | 'dot'
  | 'exclamationMark'
  | 'externalLink'
  | 'forward'
  | 'gauge'
  | 'gavel'
  | 'gear'
  | 'globe'
  | 'heart'
  | 'home'
  | 'ideal'
  | 'identityCard'
  | 'indentityCard'
  | 'info'
  | 'initiator'
  | 'list'
  | 'lock'
  | 'marketCap'
  | 'minus'
  | 'notVisible'
  | 'paperAirplane'
  | 'pause'
  | 'paypal'
  | 'pencil'
  | 'phone'
  | 'play'
  | 'plus'
  | 'popularity'
  | 'portrait'
  | 'profile'
  | 'pulse'
  | 'qrCode'
  | 'questionMark'
  | 'recurring'
  | 'safe'
  | 'search'
  | 'sofort'
  | 'stake'
  | 'star'
  | 'statusDot'
  | 'step0'
  | 'step1'
  | 'step2'
  | 'step3'
  | 'step4'
  | 'step5'
  | 'step6'
  | 'step7'
  | 'step8'
  | 'step9'
  | 'tradingAnnotation'
  | 'tradingAverage'
  | 'tradingChartCandles'
  | 'tradingChartLine'
  | 'tradingContinuous'
  | 'tradingCross'
  | 'tradingFib'
  | 'tradingHorizLine'
  | 'tradingRectangle'
  | 'tradingUpArrow'
  | 'tradingVertLine'
  | 'trashCan'
  | 'trxBuy'
  | 'trxConvert'
  | 'trxDeposit'
  | 'trxReceive'
  | 'trxReward'
  | 'trxSell'
  | 'trxSend'
  | 'trxWithdraw'
  | 'undo'
  | 'visible'
  | 'wallet'
  | 'wireTransfer';
