import path from 'node:path';
import { getPath } from '@cbhq/script-utils';

import { ProductComponentConfig } from '../../components/AdoptionTracker/types';

import { flattenCategories, flattenConfig } from './utils/flattenConfig';
import { formatCUJSidebar, formatSidebar } from './utils/formatSidebar';
import type { AdoptersConfig, FeaturedComponentsConfig } from './types';

export const tempDir = getPath(`apps/website/.docusaurus/@cbhq/adoption`);
/**
 * The consumer facing url is based on folder structure and we don't want
 * to have to require the consumer facing URL to contain some variation of generated in the url
 * since this is an implementation detail.
 */
export const adoptionDocsDir = getPath(`apps/website/docs/adoption-tracker`);
export const generatedDataDir = getPath(`apps/website/data/__generated__/adoption`);
export const generatedStaticDataDir = {
  relativePath: `static/data/__generated__/adoption`,
  get absolutePath() {
    return getPath(`apps/website/${this.relativePath}`);
  },
};

const frontendWebGit = 'frontend/web';
const internationalUIGit = 'exchange/international-ui';
const assethubGit = 'c3/assethub-frontend';
const monorepoGit = 'mono/repo';
const retailMobileGit = 'consumer/react-native';
const retailWebGit = 'frontend/coinbase-www';
const walletGit = 'wallet/wallet-mobile';
const unifiedAccountsGit = 'frontend/unified-identity-accounts';
const mauiGit = 'frontend/maui';
const primeMobileGit = 'prime/mobile';
const primeWebGit = 'institutional/frontend';
const commerceWeb = 'commerce/www';
const commerceFE = 'commerce/frontend';
const identityGit = 'identity/frontend';
const paymentsOnRampGit = 'payments/onramp-widget';
const paymentsCbPayGit = 'payments/cbpay-rn-sdk';
const helpCenterGit = 'data/helpcenter-web';
const cbChatUIGit = 'data/cb-chat-ui';

const assethubConfig = {
  root: path.join(tempDir, assethubGit),
  github: assethubGit,
  tsconfigFileName: 'tsconfig.base.json',
};

const monorepoConfig = {
  root: path.join(tempDir, monorepoGit),
  github: monorepoGit,
  tsconfigFileName: 'tsconfig.options.json',
};

const primeWebConfig = {
  root: path.join(tempDir, primeWebGit),
  github: primeWebGit,
  tsconfigFileName: 'tsconfig.base.json',
};

export const hiddenProjects = ['commerce-merchant-mono'];
export const hiddenCUJs: string[] = [];

export const coreUserJourneyConfig: AdoptersConfig[] = [
  {
    type: 'category',
    label: 'Onboarding',
    collapsed: true,
    id: 'onboarding-cuj',
    items: [
      {
        root: path.join(tempDir, retailWebGit, 'onboarding'),
        github: retailWebGit,
        id: 'retail-web-identity-cuj',
        label: 'Retail Onboarding',
        type: 'doc',
        sourceGlob: ['(components|steps)/**/*.(ts|tsx)'],
        projectGitPath: 'onboarding',
      },
      {
        //  note: react-native/src/packages/onboarding has * in it's package.json (https://github.cbhq.net/consumer/react-native/blob/master/src/packages/onboarding/package.json)
        // we will use the dev dependency
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'umo-cuj',
        label: 'Unified Mobile Onboarding',
        projectTsAliases: ['@onboarding'],
        type: 'doc',
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/onboarding'),
        projectGitPath: 'src/packages/onboarding',
      },
    ],
  },
  {
    type: 'category',
    label: 'Send',
    collapsed: true,
    id: 'send-cuj',
    items: [
      // note send: https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1347070423
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-send-cuj',
        label: 'RN Send CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/Send/SendSelectRecipientScreen.(ts|tsx)',
          'screens/Send/SendRecipientTypeScreen.(ts|tsx)',
          'screens/Send/SendPreviewScreen.(ts|tsx)',
          'screens/Send/SendEnterNoteScreen.(ts|tsx)',
          'screens/Send/SendCompleteScreen.(ts|tsx)',
          'screens/Send/SendBlockedScreen.(ts|tsx)',
          'screens/Send/SendAccountSelectorScreen.(ts|tsx)',
          'screens/Send/Send2FAScreen.(ts|tsx)',
          'screens/Send/ScamWarningScreen.(ts|tsx)',
          'screens/Send/RecentContactsListScreen.(ts|tsx)',
          'screens/Send/ProcessingTransactionScreen.(ts|tsx)',
          'screens/Send/L2EducationScreen.(ts|tsx)',
          'screens/Send/L2Adoption/L2AdoptionSelection/L2AdoptionSelectionScreen.(ts|tsx)',
          'screens/Send/ContactManagement/ManageContacts/ManageContactsScreen.(ts|tsx)',
          'screens/Send/ContactManagement/Favorites/FavoritesScreen.(ts|tsx)',
          'screens/Send/ContactManagement/CreateOrEditContact/CreateOrEditContactScreen.(ts|tsx)',
          'screens/Send/ConnectWalletScreen.(ts|tsx)',
          'screens/Send/analytics/types.(ts|tsx)',
          'components/navigation/NavHeader.(ts|tsx)',
          'screens/Send/AmountEntryScreen/AmountEntryScreen.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // Send CUJ Web
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-send-cuj',
        label: 'Web Send CUJ',
        type: 'doc',
        sourceGlob: [
          'components/SendReceive/SendRedesign/SendRedesignSteps.(ts|tsx)',
          'components/SendReceive/SendRedesign/SendRedesignDefault.(ts|tsx)',
          'components/SendReceive/SendRedesign/SendReceiveRedesign.(ts|tsx)',
          'components/SendReceive/SendRedesign/ReceiveRedesignSteps.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/NetworkSelectionEntryButton.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/ReceiveRedesignAssetDisplay.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/AddNote/AddNote.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/DestinationTagStep/DestinationTagStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/L2SelectionStep/L2SelectionNuxStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/L2SelectionStep/L2SelectionStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/L2SelectionStep/NetworkCellDetailFee.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/MemoInfoStep/MemoInfoStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/RegenerateAddressStep/RegenerateAddressStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/SendFavoriteContactsStep/FavoriteContacts.(ts|tsx)x',
          'components/SendReceive/SendRedesign/steps/SendReceiveRedesignAssetSelector/SendReceiveRedesignAssetSelector.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/SendRedesignAmountEntry/SendRedesignAmountEntry.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/SendRedesignPreview/SendRedesignPreview.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/SendSelectRecipientStep/SendSelectRecipientStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/SendStatusStep/SendStatusStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/TransactionDetailsStep/TransactionDetailsStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/ViewMoreRecentsStep/ViewMoreRecents.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/ReceiveRedesignAssetInfo.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/ReceiveRedesignInlineWarning.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/RecipientSearchInput.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/RetailRedesignAssetDisplay.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/SendReceiveQRCode.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/SendRedesignHeader.(ts|tsx)',
        ],
        projectGitPath: 'app/src',
      },
    ],
  },
  {
    type: 'category',
    label: 'Receive',
    collapsed: true,
    id: 'receive-cuj',
    items: [
      // note receive: https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1347070423
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-receive-cuj',
        label: 'RN Receive CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'components/navigation/NavHeader.(ts|tsx)',
          'screens/GlobalTrade/components/AccountSelectors/ReceiveAccountSelector.(ts|tsx)',
          'screens/Receive/ReceiveScreen.(ts|tsx)',
          'screens/Receive/Requests/ReceiverRequestDeclinedScreen.(ts|tsx)',
          'screens/Receive/Requests/ReceiverSendConfirmationScreen.(ts|tsx)',
          'screens/Receive/Requests/RequestAmountEntryScreen.(ts|tsx)',
          'screens/Receive/Requests/RequestDetailsScreen.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // Send CUJ Web
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-receive-cuj',
        label: 'Web Receive CUJ',
        type: 'doc',
        sourceGlob: [
          'components/SendReceive/components/NetworkSelection/ChangeNetworkStep/ChangeNetworkStep.(ts|tsx)',
          'components/SendReceive/components/NetworkSelection/ChangeNetworkStep/SendReceiveBlockingMessage.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/ReceiveRedesignAssetDisplay.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/ReceiveRedesignAssetInfo.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/RegenerateAddressStep/RegenerateAddressStep.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/SendReceiveRedesignAssetSelector/SendReceiveRedesignAssetSelector.(ts|tsx)',
          'views/AdvancedPortfolio/components/MultiPortfolioDisclaimerV2/MultiPortfolioDisclaimerV2.(ts|tsx)',
          'components/SendReceive/SendRedesign/steps/ReceiveRedesignInlineWarning.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/NetworkSelectionEntryButton.(ts|tsx)',
          'components/SendReceive/SendRedesign/components/SendReceiveQRCode.(ts|tsx)',
        ],
        projectGitPath: 'app/src',
      },
    ],
  },
  {
    type: 'category',
    label: 'Account Recovery',
    collapsed: true,
    id: 'account-recovery-cuj',
    // Taken from https://docs.google.com/document/d/1v7WWBwZ_GmTRNdu5SeH0T_BfLFmBBxKv2aBsMioXYPw/edit
    items: [
      {
        // IDV - From Proofing Component @cbhq/id-capture: https://github.cbhq.net/frontend/coinbase-www/tree/master/packages/id-capture
        root: path.join(tempDir, retailWebGit, 'packages/id-capture'),
        github: retailWebGit,
        id: 'ar-id-capture-cuj',
        label: 'ID Capture CUJ',
        type: 'doc',
        projectGitPath: 'packages/id-capture',
      },
      {
        // IDV - From Two Factor Web @cbhq/two-factor-web: https://sourcegraph.cbhq.net/github.cbhq.net/identity/frontend/-/tree/packages/two-factor-web/src/flows/idv
        // SCQuestions - From Two Factor Web @cbhq/two-factor-web: https://sourcegraph.cbhq.net/github.cbhq.net/identity/frontend/-/tree/packages/two-factor-web/src/flows/SecurityQuestions
        // EmailOTP -  From Two Factor Web @cbhq/two-factor-web: https://sourcegraph.cbhq.net/github.cbhq.net/identity/frontend/-/tree/packages/two-factor-web/src/flows/email
        // Repo: https://github.cbhq.net/identity/frontend/tree/master/packages/two-factor-web/src/flows
        root: path.join(tempDir, identityGit, 'packages/two-factor-web'),
        github: identityGit,
        id: 'ar-two-factor-web-cuj',
        label: 'Two Factor Web CUJ',
        sourceGlob: [
          'packages/two-factor-web/src/flows/idv/**/*.(ts|tsx)',
          'packages/two-factor-web/src/flows/SecurityQuestions/**/*.(ts|tsx)',
          'packages/two-factor-web/src/flows/email/**/*.(ts|tsx)',
        ],
        type: 'doc',
        projectGitPath: 'packages/two-factor-web/src/flows',
      },
      {
        // Risk - From Risk Team (in UL): https://github.cbhq.net/identity/frontend/tree/master/apps/unified-login/src/risk
        root: path.join(tempDir, identityGit, 'apps/unified-login'),
        github: identityGit,
        id: 'ar-unified-login-risk-cuj',
        label: 'Unified Login Risk Web CUJ',
        sourceGlob: ['apps/unified-login/src/risk/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'apps/unified-login/src/risk',
      },
    ],
  },
  {
    type: 'category',
    label: 'Advanced Portfolio',
    collapsed: true,
    id: 'advanced-portfolio-cuj',
    // Adv Portfolio
    // Taken from https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1390434678
    items: [
      {
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-adv-portfolio-cuj',
        label: 'Web Adv Portfolio CUJ',
        type: 'doc',
        sourceGlob: ['views/AdvancedPortfolio/**/*.(ts|tsx)'],
        projectGitPath: 'app/src/views/AdvancedPortfolio',
      },
      {
        // RN Adv Portfolio
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-adv-portfolio-cuj',
        label: 'RN Adv Portfolio CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: ['screens/AdvancedTrade/Portfolio/**/*.(ts|tsx)'],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/screens/AdvancedTrade/Portfolio',
      },
    ],
  },
  {
    type: 'category',
    label: 'Get Support',
    collapsed: true,
    id: 'get-support-cuj',
    // Get Support
    // Taken from https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1729708519
    // Note: screens/Support/**/*.(ts|tsx) is set for deprecation by April
    items: [
      {
        // Get Support (Mobile)
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-adv-portfolio-cuj',
        label: 'RN Adv Portfolio CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/CoinbaseHelp/**/*.(ts|tsx)',
          'hooks/useSupportHomeNavigation/useSupportHomeNavigation.(ts|tsx)',
          'hooks/subscription/useNavigateToSupportScreen.(ts|tsx)',
          'screens/Support/**/*.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/screens/CoinbaseHelp',
      },
    ],
  },
  {
    type: 'category',
    label: 'Onchain Error States',
    collapsed: true,
    id: 'roc-cuj',
    // ROC  / Onchain Error States
    // Taken from https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1742921177
    items: [
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-roc-cuj',
        label: 'RN Onchain Error States CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'contexts/Defi/DefiProvider.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/DappWalletNux.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/Web3NuxSlide.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/DappNuxTray.(ts|tsx)',
          'screens/Defi/requirementScreens/DappWalletFunding.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/Web3NuxContent.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/DisclosureWithToS.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/Web3WalletCreationContext.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/DappNuxTraySlide.(ts|tsx)',
          'screens/Defi/requirementScreens/Web3WalletIneligible.(ts|tsx)',
          'screens/Defi/requirementScreens/nux/DisclosureWithToS.(ts|tsx)',
          'screens/Defi/DAppWallet/DAppWalletScreen.(ts|tsx)',
          'screens/Defi/DAppWallet/components/Web3WalletBalanceCell.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/components/Web3WalletPreviewBalanceCells.(ts|tsx)',
          'screens/Defi/DAppWallet/DAppWalletRestrictedAssets.(ts|tsx)',
          'screens/Defi/DAppWallet/DAppWalletNFTs.(ts|tsx)',
          'screens/Defi/DAppWallet/Web3WalletCryptoTab.(ts|tsx)',
          'screens/Defi/DAppWallet/Web3WalletActivityTab.(ts|tsx)',
          'screens/Defi/DAppWallet/DAppWalletRestrictedAssets.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletNoCrypto.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletNoActivity.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DefiNetworkSelectTray.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletQuickActions.(ts|tsx)',
          'screens/Defi/components/Web3WalletBalanceHeader.(ts|tsx)',
          'screens/Defi/DAppTransaction/Web3WalletAssetDetail.(ts|tsx)',
          'screens/Defi/CbPay/DappCbPayScreen.(ts|tsx)',
          'screens/Defi/Send/DAppWalletSendInputScreen.(ts|tsx)',
          'screens/Defi/Send/DAppWalletSendSelectRecipient.(ts|tsx)',
          'screens/Defi/Send/DAppWalletSendConfirmationScreen.(ts|tsx)',
          'screens/Defi/Send/DAppWalletSendCompleteScreen.(ts|tsx)',
          'screens/Defi/Send/DAppWalletSendBurnAssetScreen.(ts|tsx)',
          'screens/Defi/Receive/DAppReceiveScreen.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferInputScreen.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferAssetSelectorScreen/DeFiAssets.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferAssetSelectorScreen/CeFiAssets.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferConfirmationScreen/ConfirmWithdraw.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferAssetSelectorScreen/DAppWalletTransferAssetSelectorScreen.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferConfirmationScreen/DAppWalletTransferConfirmationScreen.(ts|tsx)',
          'screens/Defi/Transfer/DAppWalletTransferCompleteScreen.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/components/DappWalletPreviewBottomContent.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/components/DappWalletNFTCell.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/components/DappWalletPreviewButton.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/components/DappWalletPreviewDisclaimers.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/components/Web3WalletPreviewBalanceCells.(ts|tsx)',
          'screens/Defi/DAppWallet/components/DappWalletPreviewTray/PendingTxsBanner.(ts|tsx)',
          'screens/AccountRecovery/DAppWalletRecoveryScreen.(ts|tsx)',
          'screens/Defi/requirementScreens/DappWalletRecoveryTray/DappWalletRecoveryTray.(ts|tsx)',
          'screens/SimpleTrade/SimpleTradeInputScreen.(ts|tsx)',
          'screens/SimpleTrade/Mgx/components/MgxPreview.(ts|tsx)',
          'screens/SimpleTrade/Mgx/components/MgxConfirmation.(ts|tsx)',
          'screens/SimpleTrade/Mgx/components/MgxSwapAccountFetcher.(ts|tsx)',
          'screens/SimpleTrade/Mgx/components/MgxPaymentMethodsTray.(ts|tsx)',
          'screens/SimpleTrade/Mgx/components/MgxAccountFetcher.(ts|tsx)',
          'screens/SimpleTrade/SimpleTradeInputScreen.(ts|tsx)',
          'screens/SimpleTrade/Defi/DefiAccountFetcher.(ts|tsx)',
          'screens/Dex/DexPreviewScreen/DexPreviewScreen.(ts|tsx)',
          'screens/Dex/DexPreviewScreen/DexPreviewHeader.(ts|tsx)',
          'screens/Dex/DexPreviewScreen/NetworkFeeCell.(ts|tsx)',
          'screens/Dex/DexOrderStatusScreen/DexOrderSuccess.(ts|tsx)',
          'screens/Dex/DexOrderStatusScreen/DexOrderPending.(ts|tsx)',
          'screens/Dex/DexOrderStatusScreen/DexOrderFailure.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/screens',
      },
      {
        // web / app
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-roc-app-cuj',
        label: 'Web Onchain Error States CUJ (App)',
        type: 'doc',
        sourceGlob: [
          'views/WalletsBalances/components/DappWalletPrimaryContent.(ts|tsx)',
          'views/CollectibleDetail/CollectibleDetail.(ts|tsx)',
          'components/Collectible/CollectibleSection.(ts|tsx)',
          'components/Collectible/CollectibleList.(ts|tsx)',
          'components/Collectible/CollectibleItem.(ts|tsx)',
          'components/Collectible/CollectibleGrid.(ts|tsx)',
          'views/DappWallet/DappWalletCrypto.(ts|tsx)',
          'views/DappWallet/DappWalletContent.(ts|tsx)',
          'views/DappWallet/DappWalletActivity.(ts|tsx)',
          'views/DappWallet/DappWallet.(ts|tsx)',
          'views/DappWallet/components/WalletQRCodeSection.(ts|tsx)',
          'views/DappWallet/components/TabBar.(ts|tsx)',
          'views/DappWallet/components/NoActivitySection.(ts|tsx)',
          'views/DappWallet/components/DappWalletBalance.(ts|tsx)',
          'views/DappWallet/components/AboutSection.(ts|tsx)',
          'views/Assets/components/AccountTableV2/AccountTableV2.(ts|tsx)',
          'views/Web3/DappDetailsPageContent.(ts|tsx)',
          'views/Web3/DappIntakeLoggedInPageContent.(ts|tsx)',
          'views/Web3/DappIntakeLoggedInPage.(ts|tsx)',
          'views/Web3/Web3DiscoveryContent.(ts|tsx)',
          'views/Web3/Web3Discovery.(ts|tsx)',
          'views/AssetPage/components/AssetBalances/AssetBalances.(ts|tsx)',
          'views/AssetPagePortfolio/AssetPagePortfolioWallet.(ts|tsx)',
          'views/Assets/components/DappWalletTransactionRow/DappWalletTransactionStatusRow.(ts|tsx)',
          'views/Assets/components/DappWalletTransactionRow/DappWalletTransactionDetailModal.(ts|tsx)',
          'views/Assets/components/DappWalletTransactionRow/DappWalletTransactionRow.(ts|tsx)',
          'views/AssetsPrimaryBalance/AssetsPrimaryBalance.(ts|tsx)',
        ],
        projectGitPath: 'app/src/views',
      },
      {
        // web / marketing
        root: path.join(tempDir, retailWebGit, 'marketing'),
        github: retailWebGit,
        id: 'web-roc-marketing-cuj',
        label: 'Web Onchain Error States CUJ (Marketing)',
        type: 'doc',
        sourceGlob: [
          'pages/DappIntake/LoggedOutDappIntake.(ts|tsx)',
          'pages/DappDetails/DappDetails.(ts|tsx)',
          'pages/Web3/components/Web3Disclaimer.(ts|tsx)',
          'pages/Web3/components/Web3Banner.(ts|tsx)',
          'pages/Web3/Web3Page.(ts|tsx)',
        ],
        projectGitPath: 'marketing',
      },
      {
        // web / shared
        root: path.join(tempDir, retailWebGit, 'shared'),
        github: retailWebGit,
        id: 'web-roc-shared-cuj',
        label: 'Web Onchain Error States CUJ (Shared)',
        type: 'doc',
        sourceGlob: [
          'components/Web3/components/DappDetailsLoading.(ts|tsx)',
          'components/Web3/components/DappDetailsSection.(ts|tsx)',
        ],
        projectGitPath: 'shared',
      },
    ],
  },
  {
    type: 'category',
    label: 'USDC/Cash Surfaces',
    collapsed: true,
    id: 'stablecoin-cuj',
    // Stablecoin / USDC/Cash Surfaces
    // Taken from https://docs.google.com/spreadsheets/d/1ZaNVo7gbCAGovqowpillA9JMhEJvmVsmsRDMX9K0Dew/edit#gid=0
    items: [
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-stablecoin-cuj',
        label: 'RN USDC/Cash Surfaces CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/Stablecoin/**/*.(ts|tsx)',
          // USDC Add Cash/Cash Out
          // Reuses some components of 'components/SimpleTrade
          'screens/SimpleTrade/Cash/**/*.(ts|tsx)',
          'components/navigation/stacks/SimpleTradeCashStack.(ts|tsx)',
          'screens/SimpleTrade/Cash/SimpleTradeCashInputScreen.(ts|tsx)',
          'screens/SimpleTrade/Cash/useSimpleTradeCash.(ts|tsx)',
          'screens/Stablecoin/components/CashTargetSelector.(ts|tsx)',
          'components/SimpleTrade/BaseInput/components/SimpleTradeSourceTargetSelector/BaseSourceTargetSelector.(ts|tsx)',
          'screens/Stablecoin/components/TargetCashCell.(ts|tsx)',
          'screens/SimpleTrade/Cash/components/SimpleTradeCashInput.(ts|tsx)',
          'screens/SimpleTrade/hooks/useFetchQuotesDeprecated.(ts|tsx)',
          'components/SimpleTrade/BaseInput/components/SimpleTradeInputKeyboard/SimpleTradeInputKeyboard.(ts|tsx)',
          'screens/SimpleTrade/components/SimpleTradePreviewButtonDeprecated.(ts|tsx)',
          'screens/SimpleTrade/Buy/BuyPreview/BuyPreviewDeprecated.(ts|tsx)',
          'screens/SimpleTrade/Sell/SellPreview/SellPreview.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferPreviewScreen.(ts|tsx)',
          'screens/SimpleTrade/Buy/BuyConfirmation/BuyConfirmation.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferFinishedScreen.(ts|tsx)',
          'screens/SimpleTrade/Sell/SellConfirmation/SellConfirmation.(ts|tsx)',
          'screens/FiatTransfer/Withdraw/WithdrawTwoFactorAuthScreen.(ts|tsx)',

          // Buy/Sell with USDC
          // Almost all functionality supported by Simple Trade buy/sell flow
          'screens/SimpleTrade/SimpleTradeInputScreen.(ts|tsx)',
          'screens/SimpleTrade/components/SimpleTradePrimaryPaymentMethodFetcher/SimpleTradePrimaryPaymentMethodFetcher.(ts|tsx)',
          'components/Transfer/CryptoPayments/BuyUsdcPaymentMethod.(ts|tsx)',
          'components/Transfer/CryptoPayments/SellUsdcPaymentMethod.(ts|tsx)',

          // Recurring Buys with USDC
          // Functionality supported by Simple Trade buy/sell flow

          // Convert USD <> USDC
          'screens/Asset/StableAssetScreen/StableAssetScreen.(ts|tsx)',
          'screens/Asset/StableAssetScreen/components/StableAssetQuickActions.(ts|tsx)',
          'screens/Asset/StableAssetScreen/components/StableAssetConvertTray.(ts|tsx)',
          'screens/Stablecoin/hooks/useRouteToCashConvert.(ts|tsx)',
          'screens/SimpleTrade/SimpleTradeInputScreen.(ts|tsx)',

          // USDC ADP
          'screens/Asset/StableAssetScreen/**/*.(ts|tsx)',
          'screens/Asset/StableAssetScreen/StableAssetScreen.(ts|tsx)',

          // My Assets > Cash table (USDC)
          // Functionality supported by newest portfolio redesign
          'screens/AssetsTab/AssetsScreenContent.(ts|tsx)',
          'screens/AssetsTab/components/AssetsCashEquivalents/AssetsCashEquivalents.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/screens/',
      },
      {
        // web / app
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-stablecoin-cuj',
        label: 'Web USDC/Cash Surfaces CUJ',
        type: 'doc',
        sourceGlob: [
          'components/Stablecoin/**/*.(ts|tsx)',
          'utils/stableAsset.(ts|tsx)',

          // Buy/Sell with USDC
          'components/UsdcBuySell/**/*.(ts|tsx)',
          'components/SimpleTrade/**/*.(ts|tsx)',
          'components/SimpleTrade/SimpleTrade.(ts|tsx)',
          'components/UsdcBuySell/hooks/useInitialTradeValues/useInitialTradeValues.(ts|tsx)',
          'components/SimpleTrade/BuySell/BuySellProxyProvider.(ts|tsx)',
          'components/UsdcBuySell/BuySellProxy.(ts|tsx)',
          'components/SimpleTrade/SimpleTradeRedesign/steps/BuySellProxyEntryStep/BuySellProxyEntryStep.(ts|tsx)',
          'components/SimpleTrade/Convert/ConvertStepper.(ts|tsx)',
          'components/UsdcBuySell/UsdcEntryStep.(ts|tsx)',
          'components/SimpleTrade/BuySell/steps/SelectPaymentStep/SelectPaymentStep.(ts|tsx)',
          'components/UsdcBuySell/CryptoPaymentMethods.(ts|tsx)',
          'components/UsdcBuySell/AssetPaymentMethodCell.(ts|tsx)',
          'components/UsdcBuySell/BuySellProxySecondaryButton.(ts|tsx)',
          'components/SimpleTrade/components/TradeLimitsAndBalances/USDCEntrySelector.(ts|tsx)',
          'components/SimpleTrade/Convert/steps/PreviewStep/PreviewStep.(ts|tsx)',
          'components/UsdcBuySell/ProxyPreviewStep.(ts|tsx)',
          'hooks/useHasDefaultTradingV2BuyExperiment.(ts|tsx)',

          // USDC Add Cash/Cash Out
          'components/SimpleTrade/**/*.(ts|tsx)', // (uses same components as Simple Trade Buy/Sell)
          'views/Assets/components/StableAssetsTable/StableAssetsTableRow.(ts|tsx)',
          'views/Assets/components/QuickActionsCard/InlineQuickActions.(ts|tsx)',
          'views/Assets/components/QuickActionsCard/useInlineQuickActionsMap.(ts|tsx)',
          'components/Stablecoin/AddCashButton.(ts|tsx)',
          'components/Stablecoin/AddCashSelectModal.(ts|tsx)',
          'components/SimpleTrade/BuySell/hooks/useAssetSelector.(ts|tsx)',
          'components/SimpleTrade/BuySell/BuySell.(ts|tsx)',
          'components/SimpleTrade/BuySell/utils/getBuySellVariant.(ts|tsx)',
          'components/SimpleTrade/BuySell/utils/getBuySellVariant.(ts|tsx)',

          // USDC ADP
          'views/AssetPage/components/AssetOverview.(ts|tsx)', // (to hide balance chart for USDC)

          // My Assets > Cash table (USDC)
          'views/Assets/Assets.(ts|tsx)',
          'views/Assets/components/StableAssetsTable/StableAssetsTable.(ts|tsx)',
          'views/Assets/components/StableAssetsTable/StableAssetsLoadingTable.(ts|tsx)',
          'views/Assets/components/StableAssetsTable/StableAssetsTableHeader.(ts|tsx)',
          'views/Assets/components/StableAssetsTable/StableAssetsTableRow.(ts|tsx)',
          'components/Stablecoin/UsdcTableCell.(ts|tsx)',
          'views/Assets/components/StableAssetsTable/StableAssetsInformationModal.(ts|tsx)',
          'views/Assets/hooks/useStableBalancesEligible.(ts|tsx)',
        ],
        projectGitPath: 'app/src/views',
      },
    ],
  },
  {
    type: 'category',
    label: 'Home',
    collapsed: true,
    id: 'home-files-cuj',
    // Home files
    // Taken from  https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1068141241
    items: [
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-home-app-cuj',
        label: 'RN Home CUJ (App)',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/HomeTab/PortfolioBalanceSection/PortfolioBalanceSection.(ts|tsx)',
          'components/BalanceErrorBanner/BalanceErrorBanner.(ts|tsx)',
          'screens/HomeTab/components/HomeChartHeader.(ts|tsx)',
          'components/LiveBalanceHeader/LiveBalanceHeader.(ts|tsx)',
          'components/LiveTicker/LiveTicker.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit, 'libs/react-native-core'),
        github: retailMobileGit,
        id: 'rn-home-rn-core-cuj',
        label: 'RN Home CUJ (RN Core)',
        type: 'doc',
        sourceGlob: [
          'react-native-core/designSystem/src/core/chart/ChartHeaderAndNavBar/ChartHeader.(ts|tsx)',
          'react-native-core/designSystem/src/core/chart/ChartHeaderAndNavBar/FabricTextInput.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'libs/react-native-core',
      },
      {
        // web / app
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-home-cuj',
        label: 'Web Home CUJ',
        type: 'doc',
        sourceGlob: [
          'views/Home/HomeFeedBoundary.(ts|tsx)',
          'views/Home/components/HomeWatchlistTable/HomeWatchlistTable.(ts|tsx)',
          'components/WatchlistTableContainer/WatchlistTableContainer.(ts|tsx)',
          'views/Home/components/HomeWatchlistTable/WatchlistDisclaimer.(ts|tsx)',
          'components/AssetTableContainer/AssetTableContainer.(ts|tsx)',
          'views/Home/components/HomeWatchlistTable/HomeWatchlistRow.(ts|tsx)',
          'components/TradeTrigger/TradeTrigger.(ts|tsx)',
          'components/WatchListStar/WatchListStar.(ts|tsx)',
        ],
        projectGitPath: 'app/src',
      },
    ],
  },
  {
    type: 'category',
    label: 'Earn and Staking',
    collapsed: true,
    id: 'earn-staking-cuj',
    // Earn and Staking
    // Taken from  https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1686176736
    items: [
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-earn-staking-cuj',
        label: 'RN Earn and Staking CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'components/navigation/stacks/YieldCenterStack.(ts|tsx)',
          'screens/YieldCenter/AllEarningAssetsScreen.(ts|tsx)',
          'screens/YieldCenter/EarningDetailsScreen.(ts|tsx)',
          'screens/YieldCenter/ManageInterest/ManageInterestScreen.(ts|tsx)',
          'screens/YieldCenter/YieldCenterNuxScreen.(ts|tsx)',
          'screens/YieldCenter/YieldCenterScreen.(ts|tsx)',
          'components/FinPromFooter/FinPromFooter.(ts|tsx)',
          'screens/YieldCenter/components/EarnedSection/EarnedSection.(ts|tsx)',
          'screens/YieldCenter/components/NextForYou/NextForYou.(ts|tsx)',
          'screens/YieldCenter/components/UnearnedSection/UnearnedSection.(ts|tsx)',
          'screens/YieldCenter/components/YieldEarnedChart/YieldEarnedChart.(ts|tsx)',
          'screens/YieldCenter/components/YieldUpsellSection/YieldUpsellSection.(ts|tsx)',
          'screens/YieldCenter/SsnHeader/SsnHeaderSection.(ts|tsx)',
          'screens/YieldCenter/Upsells/YieldCenterCardUpsellSurface.(ts|tsx)',
          'screens/YieldCenter/Upsells/YieldCenterTakeoverUpsellSurface.(ts|tsx)',
          'screens/YieldCenter/components/MissedEarningsBanner/MissedEarningsBanner.(ts|tsx)',
          'screens/YieldCenter/components/MissedEarningsPromoCard/MissedEarningsPromoCard.(ts|tsx)',
          'screens/YieldCenter/components/AutoStakingAssetSetting/AutoStakingAssetSetting.(ts|tsx)',
          'screens/YieldCenter/components/AssetAPYCard/AssetAPYCard.(ts|tsx)',
          'screens/YieldCenter/components/AssetAllocationIcon/AssetAllocationIcon.(ts|tsx)',
          'screens/YieldCenter/components/AlertSection/EarnAlerts/EarnAlerts.(ts|tsx)',
          'screens/YieldCenter/components/AlertSection/EarnAlert/EarnAlert.(ts|tsx)',
          'screens/YieldCenter/components/EarningActionButtons/EarningActionButtons.(ts|tsx)',
          'screens/YieldCenter/components/EarningLinks/EarningLinks.(ts|tsx)',
          'screens/YieldCenter/components/EarningSectionCell/EarningSectionCell.(ts|tsx)',
          'screens/YieldCenter/components/EarningSectionList/EarningSectionList.(ts|tsx)',
          'screens/YieldCenter/components/EarningsLabel/EarningsLabel.(ts|tsx)',
          'screens/YieldCenter/components/EarningSummary/EarningSummary.(ts|tsx)',
          'screens/YieldCenter/components/StakingAllocationIcon/StakingAllocationIcon.(ts|tsx)',
          'screens/YieldCenter/components/StakingProgressBar/StakingProgressBar.(ts|tsx)',
          'screens/YieldCenter/SsnHeader/SpotSquareHeader.(ts|tsx)',
          'screens/YieldCenter/Trays/InterestEarnedDisclaimerTray.(ts|tsx)',
          'screens/YieldCenter/Trays/InterestRateDisclaimerTray.(ts|tsx)',
          'screens/YieldCenter/components/MissedEarningsBanner/MissedEarningsBanner.(ts|tsx)',
          'screens/YieldCenter/components/MissedEarningsPromoCard/MissedEarningsPromoCard.(ts|tsx)',
          'components/navigation/stacks/MissedEarningsStack.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsIntroScreen.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsProvider.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsStakingTrayScreen.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsInputScreen.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsErrorScreen.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsCustomizeAmountScreen.(ts|tsx)',
          'screens/StakingGrowth/MissedEarnings/MissedEarningsConfirmScreen.(ts|tsx)',
          'components/navigation/stacks/StakingV2Stack.(ts|tsx)',
          'components/navigation/stacks/StakingV2StakeFlow.(ts|tsx)',
          'screens/StakingV2/StakingNuxScreen.(ts|tsx)',
          'screens/StakingV2/StakePreviewAutopilotToggle.(ts|tsx)',
          'screens/StakingV2/StakingInputScreen.(ts|tsx)',
          'screens/StakingV2/StakingPreviewScreen.(ts|tsx)',
          'screens/StakingV2/StakingStatusScreen.(ts|tsx)',
          'screens/StakingV2/components/EducationInterstitialTray.(ts|tsx)',
          'screens/StakingV2/components/StakingPreviewDetails.(ts|tsx)',
          'screens/StakingV2/components/StakingPreviewUserWarnings.(ts|tsx)',
          'screens/StakingV2/components/StakingStatus.(ts|tsx)',
          'screens/StakingV2/components/StakingV2AccountActions.(ts|tsx)',
          'screens/StakingV2/components/StakingV2PendingRequests.(ts|tsx)',
          'screens/StakingV2/components/StakingV2Promotion.(ts|tsx)',
          'components/navigation/stacks/StakingV2Stack.(ts|tsx)',
          'components/navigation/stacks/StakingV2UnstakeFlow.(ts|tsx)',
          'screens/StakingV2/UnstakingInputScreen.(ts|tsx)',
          'screens/StakingV2/UnstakingPreviewScreen.(ts|tsx)',
          'screens/StakingV2/UnstakingStatusScreen.(ts|tsx)',
          'screens/StakingV2/components/UnstakeButton.(ts|tsx)',
          'screens/StakingV2/components/UnstakingOptionsTray.(ts|tsx)',
          'screens/StakingV2/components/Eth2UnstakingOptionsTray.(ts|tsx)',
          'screens/StakingV2/components/StakingStatus.(ts|tsx)',
          'components/navigation/stacks/WrappedAssetStack.(ts|tsx)',
          'components/navigation/stacks/WrappedAssetFlow.(ts|tsx)',
          'screens/WrappedAsset/WrapFlow/WrappedAssetInputScreen.(ts|tsx)',
          'screens/WrappedAsset/WrapFlow/WrappedAssetCashValueScreen.(ts|tsx)',
          'screens/WrappedAsset/WrapFlow/WrappedAssetPreviewScreen.(ts|tsx)',
          'screens/WrappedAsset/WrapFlow/WrappedAssetStatusScreen.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetGuide.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetEntryPointTray.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetCashValueWarning.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetBanner.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedActions.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetStatus.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetTradeButton.(ts|tsx)',
          'components/navigation/stacks/WrappedAssetStack.(ts|tsx)',
          'components/navigation/stacks/WrappedAssetFlow.(ts|tsx)',
          'screens/WrappedAsset/UnwrapFlow/UnwrapAssetInputScreen.(ts|tsx)',
          'screens/WrappedAsset/UnwrapFlow/UnwrapAssetPreviewScreen.(ts|tsx)',
          'screens/WrappedAsset/UnwrapFlow/UnwrapAssetStatusScreen.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedActions.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetBanner.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetCashValueWarning.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetUnstakingPeriod.(ts|tsx)',
          'screens/WrappedAsset/components/WrappedAssetUnwrapStatus.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // web / app
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-earn-staking-cuj',
        label: 'Web Earn and Staking CUJ',
        type: 'doc',
        sourceGlob: [
          'views/YieldCenter/YieldCenter.(ts|tsx)',
          'views/YieldCenter/components/AlertSection/AlertSection.(ts|tsx)',
          'views/YieldCenter/components/AlertSection/EarnAlert.(ts|tsx)',
          'views/YieldCenter/components/AlertSection/EarnAlerts.(ts|tsx)',
          'views/YieldCenter/components/ApyTooltip/ApyTooltip.(ts|tsx)',
          'views/YieldCenter/components/AssetAllocationIcon/AssetAllocationIcon.(ts|tsx)',
          'views/YieldCenter/components/AssetAPYCard/AssetAPYCard.(ts|tsx)',
          'views/YieldCenter/components/AutoStakingAssetSetting/AutoStakingAssetSetting.(ts|tsx)',
          'views/YieldCenter/components/EarningActionButtons/EarningActionButtons.(ts|tsx)',
          'views/YieldCenter/components/EarningAssetModal/EarningAssetModal.(ts|tsx)',
          'views/YieldCenter/components/EarningAssetModal/EarningAssetModalManageInterest.(ts|tsx)',
          'views/YieldCenter/components/EarningAssetModal/InterestChangeConfirmation.(ts|tsx)',
          'views/YieldCenter/components/EarningAssetModal/RewardsPreferenceOptionCell.(ts|tsx)',
          'views/YieldCenter/components/EarningAssetModal/StakingV2EthOptionsModal.(ts|tsx)',
          'views/YieldCenter/components/EarningLinks/EarningLinks.(ts|tsx)',
          'views/YieldCenter/components/EarningSectionCell/EarningSectionCell.(ts|tsx)',
          'views/YieldCenter/components/EarningSectionList/EarningSectionList.(ts|tsx)',
          'views/YieldCenter/components/EarningsLabel/EarningsLabel.(ts|tsx)',
          'views/YieldCenter/components/EarningStats/EarningStats.(ts|tsx)',
          'views/YieldCenter/components/EarningSummary/EarningSummary.(ts|tsx)',
          'views/YieldCenter/components/InterestStatusModal/InterestStatusModal.(ts|tsx)',
          'views/YieldCenter/components/LearnAboutInterestListCell/LearnAboutInterestListCell.(ts|tsx)',
          'views/YieldCenter/components/MissedEarningsBanner/MissedEarningsBanner.(ts|tsx)',
          'views/YieldCenter/components/MissedEarningsPromoCard/MissedEarningsPromoCard.(ts|tsx)',
          'views/YieldCenter/components/MoreSection/MoreSection.(ts|tsx)',
          'views/YieldCenter/components/NextForYou/NextForYou.(ts|tsx)',
          'views/YieldCenter/components/SsnHeader/SsnHeaderSection.(ts|tsx)',
          'views/YieldCenter/components/StakingActions/StakingActions.(ts|tsx)',
          'views/YieldCenter/components/StakingAllocationIcon/StakingAllocationIcon.(ts|tsx)',
          'views/YieldCenter/components/StakingProgressBar/StakingProgressBar.(ts|tsx)',
          'views/YieldCenter/components/UnearnedRewardsSection/UnearnedRewardsSection.(ts|tsx)',
          'views/YieldCenter/components/YieldCenterNuxCard/YieldCenterNuxCard.(ts|tsx)',
          'views/YieldCenter/components/YieldChart/YieldChart.(ts|tsx)',
          'views/YieldCenter/components/YieldSummary/YieldSummary.(ts|tsx)',
          'views/YieldCenter/components/YieldUpsellSection/YieldUpsellSection.(ts|tsx)',
          'views/YieldCenter/components/MissedEarningsBanner/MissedEarningsBanner.(ts|tsx)',
          'views/YieldCenter/components/MissedEarningsPromoCard/MissedEarningsPromoCard.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/MissedEarningsFlow.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/MissedEarningsProvider.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/ConfirmationStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/CustomizeAmountStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/ErrorStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/ExitConfirmationStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/FullyStakedStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/InputStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/IntroStep.(ts|tsx)',
          'views/YieldCenter/flows/MissedEarnings/steps/SuccessStep.(ts|tsx)',
          'components/StakingV2/Stake/StakingFlow.(ts|tsx)',
          'components/StakingV2/Stake/StakingFooter.(ts|tsx)',
          'components/StakingV2/Stake/StakingInfo.(ts|tsx)',
          'components/StakingV2/Stake/StakingInput.(ts|tsx)',
          'components/StakingV2/Stake/StakingIntro.(ts|tsx)',
          'components/StakingV2/Stake/StakingPreview.(ts|tsx)',
          'components/StakingV2/Stake/LazyStakingRedirect.(ts|tsx)',
          'components/StakingV2/Stake/components/StakingPreviewAutoStakingToggle.(ts|tsx)',
          'views/YieldCenter/components/StakingActions/StakingActions.(ts|tsx)',
          'views/YieldCenter/components/StakingActions/StakingActions.(ts|tsx)',
          'components/StakingV2/Unstake/LazyUnstakingRedirect.(ts|tsx)',
          'components/StakingV2/Unstake/UnstakingConfirmation.(ts|tsx)',
          'components/StakingV2/Unstake/UnstakingFlow.(ts|tsx)',
          'components/StakingV2/Unstake/UnstakingFooter.(ts|tsx)',
          'components/StakingV2/Unstake/UnstakingInfo.(ts|tsx)',
          'components/StakingV2/Unstake/UnstakingInput.(ts|tsx)',
          'components/StakingV2/Unstake/UnstakingPreview.(ts|tsx)',
          'components/WrappedAsset/WrapAssetModal.(ts|tsx)',
          'components/WrappedAsset/steps/WrappedInput/WrappedInput.(ts|tsx)',
          'components/WrappedAsset/steps/WrappedNux/WrappedNux.(ts|tsx)',
          'components/WrappedAsset/steps/WrappedPreview/WrappedPreviewV2.(ts|tsx)',
          'components/WrappedAsset/steps/WrappedStatus/WrappedStatus.(ts|tsx)',
          'components/WrappedAsset/steps/WrappedTradeOptions/WrappedTradeOptions.(ts|tsx)',
          'components/WrappedAsset/steps/WrapUnavailable/WrapUnavailable.(ts|tsx)',
          'components/WrappedAsset/components/CbEthWrapEntryPoint/CbEthWrapEntryPoint.(ts|tsx)',
          'components/WrappedAsset/components/Eth2Options/Eth2Options.(ts|tsx)',
          'components/WrappedAsset/components/WrapEntryPoint/WrapEntryPoint.(ts|tsx)',
          'components/WrappedAsset/components/WrappedActions/WrappedActions.(ts|tsx)',
          'components/WrappedAsset/components/WrapOrStakePromotion/WrapOrStakePromotion.(ts|tsx)',
          'components/WrappedAsset/components/WrappedAssetFAQ/WrappedAssetFAQ.(ts|tsx)',
          'components/WrappedAsset/components/WrappedActions/WrappedActions.(ts|tsx)',
          'components/UnwrappedAsset/UnwrapAssetModal.(ts|tsx)',
          'components/UnwrappedAsset/steps/UnwrapInput/UnwrapInput.(ts|tsx)',
          'components/UnwrappedAsset/steps/UnwrapPreview/UnwrapPreviewV2.(ts|tsx)',
          'components/UnwrappedAsset/steps/UnwrapStatus/UnwrapStatus.(ts|tsx)',
          'components/UnwrappedAsset/steps/UnwrapUnavailable/UnwrapUnavailable.(ts|tsx)',
          'components/UnwrappedAsset/components/UnwrapEntrypoint/UnwrapEntrypoint.(ts|tsx)',
        ],
        projectGitPath: 'app/src',
      },
    ],
  },
  {
    type: 'category',
    label: 'Check Asset Price/s',
    collapsed: true,
    id: 'check-asset-price-cuj',
    items: [
      // note check asset price: https://docs.google.com/spreadsheets/d/1MWZ8qq72b6xXr-g_Pmq3GErDKdTH-5re0jWJ3iS8W64/edit#gid=0
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-check-asset-price-cuj',
        label: 'RN Check Asset Price CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/HomeTab/HomeFeedScreenV2.(ts|tsx)',
          'screens/HomeTab/productGrid/ProductGrid.(ts|tsx)',
          'screens/HomeTab/PortfolioBalanceSection/PortfolioBalanceSection.(ts|tsx)',
          'screens/UniversalSearch/MultiCategorySearch/MultiCategorySearch.(ts|tsx)',
          'screens/UniversalSearch/MultiCategorySearch/MultiCategorySearchNullState.(ts|tsx)',
          'screens/UniversalSearch/MultiCategorySearch/MultiCategorySearchResults.(ts|tsx)',
          'screens/UniversalSearch/components/UniversalSearchResults.(ts|tsx)',
          'screens/Asset/AssetScreen.(ts|tsx)',
          'screens/Asset/AssetScreenDeprecated.(ts|tsx)',
          'screens/Asset/StableAssetScreen/StableAssetScreen.(ts|tsx)',
          'screens/Asset/components/AssetPriceChart.(ts|tsx)',
          'screens/Asset/components/AssetScreenBody.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // Check Asset CUJ Web (App)
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-check-asset-price-app-cuj',
        label: 'Web Check Asset Price CUJ (App)',
        type: 'doc',
        sourceGlob: [
          'views/Home/HomeFeedContent.(ts|tsx)',
          'views/Home/HomeFeedContentDesktop.(ts|tsx)',
          'views/Home/HomeFeedContentMobile.(ts|tsx)',
          'views/AssetPage/components/AssetOverview.(ts|tsx)',
          'views/AssetPage/components/AssetOverviewPriceChart.(ts|tsx)',
          'views/AssetPage/components/AssetChart.(ts|tsx)',
          'views/AssetPage/components/TopAssets/TopAssets.(ts|tsx)',
          'views/AssetPagePortfolio/AssetPagePortfolio.(ts|tsx)',
          'views/AssetPagePortfolio/AssetPagePortfolioWallet.(ts|tsx)',
        ],
        projectGitPath: 'app/',
      },
      {
        // Check Asset CUJ Web (Shared)
        root: path.join(tempDir, retailWebGit, 'shared'),
        github: retailWebGit,
        id: 'web-check-asset-price-shared-cuj',
        label: 'Web Check Asset Price CUJ (Shared)',
        type: 'doc',
        sourceGlob: ['components/Search/SearchBar.(ts|tsx)'],
        projectGitPath: 'shared/',
      },
    ],
  },
  {
    type: 'category',
    label: 'Check/View Portfolio',
    collapsed: true,
    id: 'check-view-portfolio-cuj',
    items: [
      // note check/view portfolio: https://docs.google.com/spreadsheets/d/1MWZ8qq72b6xXr-g_Pmq3GErDKdTH-5re0jWJ3iS8W64/edit#gid=0
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-check-view-portfolio-cuj',
        label: 'RN Check View Portfolio CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/HomeTab/HomeFeedScreenV2.(ts|tsx)',
          'screens/HomeTab/productGrid/ProductGrid.(ts|tsx)',
          'screens/HomeTab/PortfolioBalanceSection/PortfolioBalanceSection.(ts|tsx)',
          'screens/AssetsTab/AssetsScreen.(ts|tsx)',
          'screens/AssetsTab/AssetsScreenContent.(ts|tsx)',
          'screens/AssetsTab/AssetsScreenCell.(ts|tsx)',
          'screens/AssetsTab/components/AssetsNonCashEquivalents/AssetsNonCashEquivalents.(ts|tsx)',
          'screens/AssetsTab/components/AssetsQuickActions/AssetsQuickActions.(ts|tsx)',
          'screens/Asset/AssetScreen.(ts|tsx)',
          'screens/Asset/AssetScreenDeprecated.(ts|tsx)',
          'screens/Asset/StableAssetScreen/StableAssetScreen.(ts|tsx)',
          'screens/Asset/components/AssetPriceChart.(ts|tsx)',
          'screens/Asset/components/AssetScreenBody.(ts|tsx)',
          'screens/Account/AccountScreen.(ts|tsx)',
          'screens/Account/components/AccountQuickActions.(ts|tsx)',
          'screens/Account/components/TransactionList.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // Check Asset CUJ Web (App)
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-check-view-portfolio-cuj',
        label: 'Web Check View Portfolio CUJ',
        type: 'doc',
        sourceGlob: [
          'views/Home/HomeFeedContent.(ts|tsx)',
          'views/Home/HomeFeedContentDesktop.(ts|tsx)',
          'views/Home/HomeFeedContentMobile.(ts|tsx)',
          'views/Assets/Assets.(ts|tsx)',
          'views/Assets/components/AccountTableV2/AccountTableV2.(ts|tsx)',
          'views/Assets/components/StableAssetsTable/StableAssetsTable.(ts|tsx)',
        ],
        projectGitPath: 'app/',
      },
    ],
  },
  {
    type: 'category',
    label: 'Add Payment',
    collapsed: true,
    id: 'add-payment-cuj',
    items: [
      // note add payment: https://docs.google.com/spreadsheets/d/1RQnqdhTPapDMnOkb4dnsoMPYybGtM8O8Ww_T7AMA3ok/edit#gid=0
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-add-payment-cuj',
        label: 'RN Add Payment CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'components/navigation/stacks/AddPaymentMethodFlow/**/*.(ts|tsx)',
          'components/navigation/stacks/AddPaymentMethodStack.(ts|tsx)',
          'screens/AddPaymentMethod/**/*.(ts|tsx)',
          'screens/PaymentMethods/Cards/AddCardScreen.(ts|tsx)',
          'components/PaymentMethod/AddPaymentMethodButton.(ts|tsx)',
          'hooks/useInvalidatePaymentMethods.(ts|tsx)',
          'screens/PaymentMethods/**/*.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // web / coinbase-www
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-add-payment-cuj',
        label: 'Web Add Payment CUJ',
        type: 'doc',
        sourceGlob: [
          'components/AddLinkedAccountPickerModal/**/*.(ts|tsx)',
          'components/LinkAchBankAccount/**/*.(ts|tsx)',
          'components/LinkCardModal/**/*.(ts|tsx)',
          'components/LinkCard/**/*.(ts|tsx)',
          'components/LinkCardComponents/**/*.(ts|tsx)',
          'components/LinkCheckoutAccount/**/*.(ts|tsx)',
          'components/LinkFedWire/**/*.(ts|tsx)',
          'components/LinkPayPal/**/*.(ts|tsx)',
          'components/LinkSepa/**/*.(ts|tsx)',
          'components/LinkSwiftBankAccount/**/*.(ts|tsx)',
          'components/LinkUkBank/**/*.(ts|tsx)',
          'components/PayPal/**/*.(ts|tsx)',
          'components/PayPalTransfer/**/*.(ts|tsx)',
          'components/PlaidLink/**/*.(ts|tsx)',
          'components/PlaidLinkUpdate/**/*.(ts|tsx)',
          'components/PaymentMethodSelect/**/*.(ts|tsx)',
          'components/DepositVerificationModal/**/*.(ts|tsx)',
          'components/DepositVerificationPreAsk/**/*.(ts|tsx)',
          'components/LinkSgFast/**/*.(ts|tsx)',
          'components/LinkPixDepositModal/**/*.(ts|tsx)',
          'components/LinkPixWithdrawalModal/**/*.(ts|tsx)',
          'components/LinkSgPaynow/**/*.(ts|tsx)',
          'components/LinkSwiftBankAccountV2/**/*.(ts|tsx)',
        ],
        projectGitPath: 'app/',
      },
    ],
  },
  {
    type: 'category',
    label: 'Add Cash',
    collapsed: true,
    id: 'add-cash-cuj',
    items: [
      // note add cash / deposit: https://docs.google.com/spreadsheets/d/1RQnqdhTPapDMnOkb4dnsoMPYybGtM8O8Ww_T7AMA3ok/edit#gid=0
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-add-cash-cuj',
        label: 'RN Add Cash CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'components/PaymentMethodCellV2/**/*.(ts|tsx)',
          'components/PaymentMethod/WireTransferPaymentCell.(ts|tsx)',
          'components/navigation/stacks/DepositStack.(ts|tsx)',
          'components/PaymentMethod/PlaceholderPaymentMethodCell.(ts|tsx)',
          'components/PaymentMethod/Nux/**/*.(ts|tsx)',
          'components/PaymentMethod/PaymentsPromoTray.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodSubdetail.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodNewBadge.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodIcon.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodExpiration.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCellSubtitle.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCellDetail.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCell.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCell.test.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodBalance.(ts|tsx)',
          'components/PaymentMethod/DepositExplanationHStack.(ts|tsx)',
          'components/PaymentMethod/CardIcon.(ts|tsx)',
          'components/PaymentMethod/BankIcon.(ts|tsx)',
          'components/PaymentMethod/icons/BankConnectIcon.(ts|tsx)',
          'components/PaymentMethod/hooks/**/*.(ts|tsx)',
          'components/PaymentMethodsTray.(ts|tsx)',
          'components/Transfer/PaymentMethodSelector.(ts|tsx)',
          'hooks/resource/usePaymentMethods.(ts|tsx)',
          'screens/FiatTransfer/Deposit/**/*.(ts|tsx)',
          'screens/FiatTransfer/components/**/*.(ts|tsx)',
          'screens/FiatTransfer/hooks/**/*.(ts|tsx)',
          'screens/FiatTransfer/messages/DepositMessages.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferFinishedScreen.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferPreviewScreen.test.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferPreviewScreen.(ts|tsx)',
          'screens/FiatTransfer/TransferDetailsFallbackLoader.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit, 'libs/react-native-core'),
        github: retailMobileGit,
        id: 'rn-add-cash-lib-cuj',
        label: 'RN Add Cash CUJ (RN Core)',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: ['react-native-core/components/cells/PaymentMethodCell.(ts|tsx)'],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'libs/react-native-core',
      },
      {
        // web / coinbase-www
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-add-cash-cuj',
        label: 'Web Add Cash CUJ',
        type: 'doc',
        sourceGlob: [
          'components/DepositWithdraw/**/*.(ts|tsx)',
          'utils/formatPaymentMethod/**/*.(ts|tsx)',
          'components/DepositModal/**/*.(ts|tsx)',
          'components/DepositWithdraw/components/DepositWithdrawErrorFallback.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/analytics/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/Deposit/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/messages/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/sharedComponents/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/sharedUtils/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/LazyTransferWidgetModal.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/TransfersWidget.(ts|tsx)',
          'components/DepositWithdraw/DepositTrigger.(ts|tsx)',
          'components/DepositWithdraw/DepositWithdraw.(ts|tsx)',
          'components/DepositWithdraw/DepositWithdrawModal.(ts|tsx)',
          'components/DepositWithdraw/DepositWithdrawTrigger.(ts|tsx)',
          'components/DepositWithdraw/flow.(ts|tsx)',
          'components/DepositWithdraw/LazyDepositTrigger.(ts|tsx)',
          'components/DepositWithdraw/types.(ts|tsx)',
          'hooks/api/queries/usePaymentMethods/**/*.(ts|tsx)',
        ],
        projectGitPath: 'app/',
      },
    ],
  },
  {
    type: 'category',
    label: 'Withdraw',
    collapsed: true,
    id: 'withdraw-cuj',
    items: [
      // note Withdraw/ Cash out: https://docs.google.com/spreadsheets/d/1RQnqdhTPapDMnOkb4dnsoMPYybGtM8O8Ww_T7AMA3ok/edit#gid=0
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-withdraw-cuj',
        label: 'RN Withdraw CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'components/navigation/stacks/WithdrawStack.(ts|tsx)',
          'components/PaymentMethodCellV2/**/*.(ts|tsx)',
          'components/PaymentMethod/WireTransferPaymentCell.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodSubdetail.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodNewBadge.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodIcon.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodExpiration.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCellSubtitle.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCellDetail.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCell.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodCell.test.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodBalance.(ts|tsx)',
          'components/PaymentMethod/CardIcon.(ts|tsx)',
          'components/PaymentMethod/BankIcon.(ts|tsx)',
          'components/PaymentMethod/icons/BankConnectIcon.(ts|tsx)',
          'components/PaymentMethod/hooks/**/*.(ts|tsx)',
          'components/PaymentMethodsTray.(ts|tsx)',
          'components/Transfer/PaymentMethodSelector.(ts|tsx)',
          'contexts/Payments/PaymentMethodsUpdaterContext.(ts|tsx)',
          'hooks/resource/usePaymentMethods.(ts|tsx)',
          'screens/FiatTransfer/components/**/*.(ts|tsx)',
          'screens/FiatTransfer/hooks/**/*.(ts|tsx)',
          'screens/FiatTransfer/messages/WithdrawMessages.(ts|tsx)',
          'screens/FiatTransfer/Withdraw/**/*.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferFinishedScreen.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferPreviewScreen.test.(ts|tsx)',
          'screens/FiatTransfer/FiatTransferPreviewScreen.(ts|tsx)',
          'screens/FiatTransfer/TransferDetailsFallbackLoader.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit, 'libs/react-native-core'),
        github: retailMobileGit,
        id: 'rn-withdraw-lib-cuj',
        label: 'RN Withdraw CUJ (RN core)',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: ['react-native-core/components/cells/PaymentMethodCell.(ts|tsx)'],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'libs/react-native-core',
      },
      {
        // web / coinbase-www
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-withdraw-cuj',
        label: 'Web Withdraw CUJ',
        type: 'doc',
        sourceGlob: [
          'components/WithdrawablePaymentSelector/**/*.(ts|tsx)',
          'components/PaymentMethod/PaymentMethodBadge.(ts|tsx)',
          'utils/formatPaymentMethod/**/*.(ts|tsx)',
          'components/DepositWithdraw/components/Withdraw/**/*.(ts|tsx)',
          'components/DepositWithdraw/components/DepositWithdrawErrorFallback.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/analytics/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/messages/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/sharedComponents/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/sharedUtils/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/Withdraw/**/*.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/LazyTransferWidgetModal.(ts|tsx)',
          'components/DepositWithdraw/TransfersWidget/TransfersWidget.(ts|tsx)',
          'components/DepositWithdraw/DepositWithdraw.(ts|tsx)',
          'components/DepositWithdraw/DepositWithdrawModal.(ts|tsx)',
          'components/DepositWithdraw/DepositWithdrawTrigger.(ts|tsx)',
          'components/DepositWithdraw/flow.(ts|tsx)',
          'components/DepositWithdraw/types.(ts|tsx)',
          'components/DepositWithdraw/WithdrawTrigger.(ts|tsx)',
          'hooks/api/queries/usePaymentMethods/**/*.(ts|tsx)',
        ],
        projectGitPath: 'app/',
      },
    ],
  },
  {
    type: 'category',
    label: 'Buy / Sell / Convert',
    collapsed: true,
    id: 'buy-sell-convert-cuj',
    items: [
      // note buy sell convert : https://docs.google.com/spreadsheets/d/1QMd8qx4-e9DkxJcM0KXlvyZ8M030hyAuTq8t0j228Is/edit#gid=1297953191
      {
        // mobile / react-native
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'rn-buy-sell-convert-cuj',
        label: 'RN Buy Sell Convert CUJ',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/SimpleTrade/**/*.(ts|tsx)',
          'screens/GlobalTrade/AssetSelector/**/*.(ts|tsx)',
          'screens/Trade/**/*.(ts|tsx)',
          'components/navigation/stacks/SimpleTradeStack.(ts|tsx)',
          'components/Screen.(ts|tsx)',
          'screens/EditAddress/EditAddressProvider.(ts|tsx)',
          'components/PaymentMethodsTray.(ts|tsx)',
          'components/Transfer/PaymentMethodSelector.(ts|tsx)',
          'components/Transfer/PaymentMethodListWrapper.(ts|tsx)',
          'components/Transfer/SelectedPaymentMethodCell.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/',
      },
      {
        // web / coinbase-www
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'web-buy-sell-convert-cuj',
        label: 'Web Buy Sell Convert CUJ',
        type: 'doc',
        sourceGlob: [
          'components/SimpleTrade/**/*.(ts|tsx)',
          'components/BuySellModal/**/*.(ts|tsx)',
          'components/BuyModal/**/*.(ts|tsx)',
          'components/BuySellComponents/**/*.(ts|tsx)',
          'components/FolderTabs/**/*.(ts|tsx)',
          'components/UsdcBuySell/**/*.(ts|tsx)',
          'components/SimpleTradeLimitOrderDetailsModal/**/*.(ts|tsx)',
        ],
        projectGitPath: 'app/',
      },
    ],
  },
  {
    type: 'category',
    label: 'Prime - Transfer Funds',
    collapsed: true,
    id: 'prime-transfer-funds-cuj',
    items: [
      {
        root: path.join(tempDir, primeWebGit),
        github: primeWebGit,
        id: 'prime-web-transfer-funds-cuj',
        label: '[Web] Transfer Funds CUJ',
        tsconfigFileName: 'tsconfig.base.json',
        projectTsAliases: [':prime-ui'],
        type: 'doc',
        dependencyPath: path.join(tempDir, primeWebGit, 'apps/prime'),
        projectGitPath: 'apps/prime',
        sourceGlob: ['modals/transferFlow/**/*.(ts|tsx)'],
      },
    ],
  },
  {
    type: 'category',
    label: 'Prime - Action Activity',
    collapsed: true,
    id: 'prime-action-activity-cuj',
    items: [
      {
        root: path.join(tempDir, primeWebGit),
        github: primeWebGit,
        id: 'prime-web-action-activity-cuj',
        label: '[Web] Action Activity CUJ',
        tsconfigFileName: 'tsconfig.base.json',
        projectTsAliases: [':prime-ui'],
        type: 'doc',
        dependencyPath: path.join(tempDir, primeWebGit, 'apps/prime'),
        projectGitPath: 'apps/prime',
        sourceGlob: ['modals/fidoSigningFlow/**/*.(ts|tsx)', 'pages/activity/**/*.(ts|tsx)'],
      },
    ],
  },
  {
    type: 'category',
    label: 'Prime - Initiate Order',
    collapsed: true,
    id: 'prime-initiate-order-cuj',
    items: [
      {
        root: path.join(tempDir, primeWebGit),
        github: primeWebGit,
        id: 'prime-web-initiate-order-cuj',
        label: '[Web] Initiate Order CUJ',
        tsconfigFileName: 'tsconfig.base.json',
        projectTsAliases: [':prime-ui'],
        type: 'doc',
        dependencyPath: path.join(tempDir, primeWebGit, 'apps/prime'),
        projectGitPath: 'apps/prime',
        sourceGlob: ['pages/trade/**/*.(ts|tsx)'],
      },
    ],
  },
];

export const config: AdoptersConfig[] = [
  {
    type: 'category',
    label: 'Consumer',
    collapsed: true,
    items: [
      {
        ...monorepoConfig,
        id: 'commerce-merchant-mono',
        label: 'Commerce Merchant',
        projectTsAliases: ['@commerce/frontend'],
        type: 'doc',
        projectGitPath: 'apps/commerce-merchant',
      },
      {
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'retail-mobile',
        label: 'Retail Mobile',
        projectTsAliases: ['@app'],
        type: 'doc',
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app',
      },
      {
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'retail-web-logged-in',
        label: 'Retail Web Logged In',
        type: 'doc',
        projectGitPath: 'app',
      },
      {
        //  note: react-native-core has * in it's package.json (https://github.cbhq.net/consumer/react-native/blob/master/libs/react-native-core/package.json)
        // we will use the app package.json

        root: path.join(tempDir, retailMobileGit, 'libs/react-native-core'),
        github: retailMobileGit,
        id: 'react-native-core',
        label: 'React Native Core',
        type: 'doc',
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'libs/react-native-core',
      },
      {
        //  note: react-native/src/packages/onboarding has * in it's package.json (https://github.cbhq.net/consumer/react-native/blob/master/src/packages/onboarding/package.json)
        // we will use the dev dependency
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'umo',
        label: 'Unified Mobile Onboarding',
        projectTsAliases: ['@onboarding'],
        type: 'doc',
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/onboarding'),
        projectGitPath: 'src/packages/onboarding',
      },
      {
        root: path.join(tempDir, retailWebGit, 'marketing'),
        github: retailWebGit,
        id: 'retail-web-logged-out',
        label: 'Retail Web Logged Out',
        type: 'doc',
        projectGitPath: 'marketing',
      },
      {
        root: path.join(tempDir, retailWebGit, 'onboarding'),
        github: retailWebGit,
        id: 'retail-web-identity',
        label: 'Retail Onboarding',
        type: 'doc',
        sourceGlob: ['(components|steps)/**/*.(ts|tsx)'],
        projectGitPath: 'onboarding',
      },
      {
        root: path.join(tempDir, retailWebGit, 'libs/advanced-trade-web'),
        github: retailWebGit,
        id: 'advanced-trade-web',
        label: 'Advanced Trade Web Package',
        type: 'doc',
        projectGitPath: 'libs/advanced-trade-web',
      },
      {
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'advanced-web',
        label: 'Advanced Trade Web Components',
        type: 'doc',
        sourceGlob: [
          'views/Advanced/**/*.(ts|tsx)',
          'views/AdvancedFeeUpgrade/**/*.(ts|tsx)',
          'views/AdvancedFees/**/*.(ts|tsx)',
          'views/AdvancedFeesV2/**/*.(ts|tsx)',
          'views/AdvancedFills/**/*.(ts|tsx)',
          'views/AdvancedMarkets/**/*.(ts|tsx)',
          'views/AdvancedOrders/**/*.(ts|tsx)',
          'views/AdvancedPortfolio/**/*.(ts|tsx)',
          'views/AdvancedPositions/**/*.(ts|tsx)',
          'views/AdvancedTrade/**/*.(ts|tsx)',
          'views/AdvancedTradeApi/**/*.(ts|tsx)',
          'views/AdvancedTradeManagement/**/*.(ts|tsx)',
          'views/AdvancedTradeSpot/**/*.(ts|tsx)',
        ],
        projectGitPath: 'app/src/views',
      },
      {
        root: path.join(tempDir, retailMobileGit),
        github: retailMobileGit,
        tsconfigFileName: 'tsconfig.base.json',
        id: 'cs3-mobile',
        label: 'Subscription & Services Mobile',
        type: 'doc',
        projectTsAliases: ['@app'],
        sourceGlob: [
          'screens/AdvocacyContentHub/**/*.(ts|tsx)',
          'screens/AdvocacyTransparentScreenTakeover/**/*.(ts|tsx)',
          'screens/Borrow/**/*.(ts|tsx)',
          'screens/CbNFT/**/*.(ts|tsx)',
          'screens/CoinbaseCard/**/*.(ts|tsx)',
          'screens/DappsDefiYield/**/*.(ts|tsx)',
          'screens/Defi/**/*.(ts|tsx)',
          'screens/Dex/**/*.(ts|tsx)',
          'screens/DirectDeposit/**/*.(ts|tsx)',
          'screens/NFTs/**/*.(ts|tsx)',
          'screens/Receive/**/*.(ts|tsx)',
          'screens/Send/**/*.(ts|tsx)',
          'screens/StackingV2/**/*.(ts|tsx)',
          'screens/SubscriptionBoostedRatesScreen/**/*.(ts|tsx)',
          'screens/SubscriptionDeeplinkRouter/**/*.(ts|tsx)',
          'screens/SubscriptionEnableCryptoBackups/**/*.(ts|tsx)',
          'screens/SubscriptionManagement/**/*.(ts|tsx)',
          'screens/SubscriptionPreferences/**/*.(ts|tsx)',
          'screens/SubscriptionSignup/**/*.(ts|tsx)',
          'screens/SubscriptionStakingOptIn/**/*.(ts|tsx)',
          'screens/SubscriptionUsdcBoostedReward/**/*.(ts|tsx)',
          'screens/USDC/**/*.(ts|tsx)',
          'screens/Web3/**/*.(ts|tsx)',
          'screens/WrappedAsset/**/*.(ts|tsx)',
          'screens/Defi/**/*.(ts|tsx)',
          'screens/YieldCenter/**/*.(ts|tsx)',
          'screens/YieldMigrationNotice/**/*.(ts|tsx)',
        ],
        dependencyPath: path.join(tempDir, retailMobileGit, 'src/packages/app'),
        projectGitPath: 'src/packages/app/src/screens',
      },
      {
        root: path.join(tempDir, retailWebGit, 'app'),
        github: retailWebGit,
        id: 'cs3-web',
        label: 'Subscription & Services Web',
        type: 'doc',
        sourceGlob: [
          'views/AssetRecovery/**/*.(ts|tsx)',
          'views/Borrow/**/*.(ts|tsx)',
          'views/CoinbaseCard/**/*.(ts|tsx)',
          'views/DappWallet/**/*.(ts|tsx)',
          'views/DirectDepost/**/*.(ts|tsx)',
          'views/NftColection/**/*.(ts|tsx)',
          'views/Subscription/**/*.(ts|tsx)',
          'views/Web3/**/*.(ts|tsx)',
          'views/YieldCenter/**/*.(ts|tsx)',
        ],
        projectGitPath: 'app/src/views',
      },
      {
        root: path.join(tempDir, mauiGit, 'maui-frontend'),
        github: mauiGit,
        id: 'maui',
        label: 'Coinbase NFT',
        type: 'doc',
        projectGitPath: '',
      },
      {
        root: path.join(tempDir, walletGit, 'workspaces'),
        github: walletGit,
        id: 'wallet-extension',
        label: 'Wallet Chrome Extension',
        /**
         * https://github.cbhq.net/wallet/wallet-mobile/blob/master/workspaces/tsconfig.base.json#L24
         * tsconfig alias :extension has path for code to parse
         * which should point to
         * https://github.cbhq.net/wallet/wallet-mobile/tree/master/workspaces/apps/extension/src
         */
        projectTsAliases: [':extension'],
        /**
         * ignoreDirs should be relative to project path above so this should ignore this directory
         * https://github.cbhq.net/wallet/wallet-mobile/tree/master/workspaces/apps/extension/src/debug
         */
        ignoreDirs: ['debug/**'],
        type: 'doc',
        dependencyPath: path.join(tempDir, walletGit, 'workspaces/apps/extension'),
        projectGitPath: 'workspaces/apps/extension',
      },
      {
        root: path.join(tempDir, walletGit, 'workspaces'),
        github: walletGit,
        id: 'wallet-react-native',
        label: 'Wallet React Native',
        projectTsAliases: [':rn'],
        cdsAliases: [':rn/cds-wallet'],
        type: 'doc',
        dependencyPath: path.join(tempDir, walletGit, 'workspaces/apps/rn'),
        projectGitPath: 'workspaces/apps/rn',
      },
      {
        root: path.join(tempDir, walletGit, 'workspaces'),
        github: walletGit,
        id: 'wallet-dapp',
        label: 'Wallet Dapp',
        projectTsAliases: [':dapp'],
        cdsAliases: [':apps/dapp'],
        type: 'doc',
        dependencyPath: path.join(tempDir, walletGit, 'workspaces/apps/dapp'),
        projectGitPath: 'workspaces/apps/dapp',
      },
    ],
  },
  {
    type: 'category',
    label: 'Institutional',
    collapsed: true,
    items: [
      {
        root: path.join(tempDir, primeMobileGit),
        github: primeMobileGit,
        id: 'prime-mobile',
        label: 'Prime Mobile',
        projectTsAliases: ['@prime-mobile'],
        type: 'doc',
        projectGitPath: '',
      },
      {
        ...primeWebConfig,
        id: 'prime-web',
        label: 'Prime Web',
        projectTsAliases: [':prime-ui'],
        type: 'doc',
        dependencyPath: path.join(tempDir, primeWebGit, 'apps/prime'),
        projectGitPath: 'apps/prime',
      },
      {
        ...primeWebConfig,
        id: 'prime-admin',
        label: 'Prime Admin',
        projectTsAliases: [':prime-admin', ':prime/admin', ':prime-ui'],
        type: 'doc',
        dependencyPath: path.join(tempDir, primeWebGit, 'apps/prime-admin'),
        projectGitPath: 'apps/prime-admin',
      },
      {
        root: path.join(tempDir, unifiedAccountsGit),
        github: unifiedAccountsGit,
        id: 'unified-business-onboarding',
        label: 'Unified Business Onboarding',
        projectTsAliases: ['@ubo'],
        type: 'doc',
        projectGitPath: '',
      },
      {
        root: path.join(tempDir, internationalUIGit, 'apps/neptune'),
        github: internationalUIGit,
        id: 'neptune',
        label: 'Neptune',
        projectTsAliases: [':neptune/app', ':neptune/feature'],
        type: 'doc',
        projectGitPath: 'apps/neptune',
      },
    ],
  },
  {
    type: 'category',
    label: 'Platform',
    collapsed: true,
    items: [
      {
        root: path.join(tempDir, unifiedAccountsGit),
        github: unifiedAccountsGit,
        id: 'unified-accounts',
        label: 'Unified Accounts',
        projectTsAliases: ['@acc'],
        type: 'doc',
        projectGitPath: '',
      },
      {
        root: path.join(tempDir, identityGit, 'apps/unified-login'),
        github: identityGit,
        id: 'unified-login',
        label: 'Unified Login Web',
        sourceGlob: ['apps/unified-login/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'apps/unified-login',
      },
      {
        root: path.join(tempDir, identityGit, 'packages/two-factor-web'),
        github: identityGit,
        id: 'two-factor-web',
        label: 'Two Factor Web',
        sourceGlob: ['packages/two-factor-web/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'packages/two-factor-web',
      },
      {
        root: path.join(tempDir, identityGit, 'packages/two-factor-mobile'),
        github: identityGit,
        id: 'two-factor-mobile',
        label: 'Two Factor Mobile',
        sourceGlob: ['packages/two-factor-mobile/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'packages/two-factor-mobile',
      },
      {
        root: path.join(tempDir, unifiedAccountsGit),
        github: unifiedAccountsGit,
        id: 'tax-center',
        label: 'Tax Center',
        projectTsAliases: ['@taxcenter'],
        type: 'doc',
        projectGitPath: 'src/settings/TaxCenter',
      },
      {
        root: path.join(tempDir, cbChatUIGit, 'packages/cb-chat'),
        github: cbChatUIGit,
        id: 'cb-chat',
        label: 'Coinbase Chat Web',
        sourceGlob: ['packages/cb-chat/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'packages/cb-chat',
      },
      {
        root: path.join(tempDir, cbChatUIGit, 'packages/cb-chat-mobile'),
        github: cbChatUIGit,
        id: 'cb-chat-mobile',
        label: 'Coinbase Chat Mobile',
        sourceGlob: ['packages/cb-chat-mobile/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'packages/cb-chat-mobile',
      },
    ],
  },
  {
    type: 'category',
    label: 'Developer',
    collapsed: true,
    items: [
      {
        root: path.join(tempDir, frontendWebGit, 'apps/cloud-console'),
        github: frontendWebGit,
        id: 'cloud-console',
        label: 'Cloud Console',
        projectTsAliases: [':cloud'],
        type: 'doc',
        projectGitPath: 'apps/cloud-console',
      },
      {
        root: path.join(tempDir, commerceFE, 'apps/commerce-merchant'),
        github: commerceFE,
        tsconfigFileName: 'tsconfig.json',
        id: 'commerce-merchant',
        label: 'Commerce Merchant',
        sourceGlob: ['apps/commerce-merchant/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'apps/commerce-merchant',
      },
      {
        root: path.join(tempDir, commerceFE, 'apps/commerce-payer'),
        github: commerceFE,
        tsconfigFileName: 'tsconfig.json',
        id: 'commerce-payer',
        label: 'Commerce Payer',
        sourceGlob: ['apps/commerce-payer/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'apps/commerce-payer',
      },
      {
        root: path.join(tempDir, commerceFE, 'apps/donations'),
        github: commerceFE,
        tsconfigFileName: 'tsconfig.json',
        id: 'commerce-donations',
        label: 'Commerce Donations',
        sourceGlob: ['apps/donations/**/*.(ts|tsx)'],
        type: 'doc',
        projectGitPath: 'apps/donations',
      },
      {
        root: path.join(tempDir, paymentsOnRampGit),
        github: paymentsOnRampGit,
        tsconfigFileName: 'tsconfig.json',
        id: 'payments-onramp-widget',
        label: 'Payments On Ramp Widget',
        type: 'doc',
        projectGitPath: '',
      },
      {
        root: path.join(tempDir, paymentsCbPayGit, 'workspaces/cbpay-sdk-rn'),
        github: paymentsCbPayGit,
        tsconfigFileName: 'tsconfig.json',
        id: 'cbpay-sdk-rn',
        label: 'Payments CBPay SDK RN',
        type: 'doc',
        projectGitPath: 'workspaces/cbpay-sdk-rn',
      },
    ],
  },
  {
    type: 'category',
    label: 'Other',
    collapsed: true,
    items: [
      {
        ...assethubConfig,
        id: 'assethub-web',
        label: 'AssetHub Issuer',
        projectTsAliases: [':www', ':shared'],
        type: 'doc',
        dependencyPath: path.join(tempDir, assethubGit, 'apps/www'),
        projectGitPath: 'apps/www',
      },
      {
        ...assethubConfig,
        id: 'assethub-admin',
        label: 'AssetHub Admin',
        projectTsAliases: [':admin', ':shared'],
        type: 'doc',
        dependencyPath: path.join(tempDir, assethubGit, 'apps/admin'),
        projectGitPath: 'apps/admin',
      },
      {
        root: path.join(tempDir, frontendWebGit, 'apps/abor'),
        github: frontendWebGit,
        id: 'abor',
        label: 'Abor',
        projectTsAliases: [':abor'],
        type: 'doc',
        projectGitPath: 'apps/abor',
      },
      // Commerce Web is deprecated so moving to other.
      {
        root: path.join(tempDir, commerceWeb),
        github: commerceWeb,
        tsconfigFileName: 'tsconfig.json',
        id: 'commerce-web',
        label: 'Commerce Web',
        type: 'doc',
        projectGitPath: '',
      },
      {
        root: path.join(tempDir, helpCenterGit),
        github: helpCenterGit,
        tsconfigFileName: 'tsconfig.json',
        id: 'helpcenter-web',
        label: 'Help Center Web',
        type: 'doc',
        dependencyPath: path.join(tempDir, helpCenterGit, 'apps/helpcenter'),
        projectGitPath: 'apps/helpcenter',
      },
    ],
  },
];

export const productComponentConfig: ProductComponentConfig[] = [
  {
    productComponentName: 'AppSwitcher',
    owningTeam: 'Identity',
    packageImportPath: '@cbhq/app-switcher',
    doc: 'https://docs.cbhq.net/frontend/platform/identity/app-switcher/integration-guide',
    packagePath: path.join(tempDir, identityGit, 'packages/app-switcher/package.json'),
  },
  {
    productComponentName: 'NavigationBar',
    owningTeam: 'Identity',
    packageImportPath: '@cbhq/identity-navigation',
    packagePath: path.join(tempDir, identityGit, 'packages/identity-navigation/package.json'),
  },
];

/** Used for AST parser */
export const adopters = flattenConfig(config);
export const cujs = flattenConfig(coreUserJourneyConfig);
export const cujSummaries = flattenCategories(coreUserJourneyConfig);

/** Required for website sidebar. */
export const adoptersSidebar = formatSidebar(config, hiddenProjects);
export const cujsSidebar = formatCUJSidebar(coreUserJourneyConfig);

/** Required to associate adopters with their stats.json file for Adoption Overview page. */
export const adoptersWithPillar = adopters
  .filter((item) => !hiddenProjects.includes(item.id))
  .map((item) => ({
    id: item.id,
    pillar: item.pillar,
  }));

export const cujsWithCategory = cujs
  .filter((item) => !hiddenCUJs.includes(item.id))
  .map((item) => ({
    id: item.id,
    pillar: item.pillar,
    label: item.label,
  }));

/** Allows us to access these metrics without publishing them. */
export const hiddenAdoptersWithPillar = adopters
  .filter((item) => hiddenProjects.includes(item.id))
  .map((item) => ({
    id: item.id,
    pillar: item.pillar,
  }));

/** Adds an `isFeatured` flag to metadata of listed components */
export const featuredComponentsConfig: FeaturedComponentsConfig = {
  cds: [],
  presentational: [],
  other: [],
};
