import type { AccordionBaseProps } from '../accordion/Accordion';
import type { SelectBaseProps } from '../alpha';
import type { ComboboxBaseProps } from '../alpha/combobox/Combobox';
import type { SelectChipBaseProps } from '../alpha/select-chip/SelectChip';
import type { TabbedChipsBaseProps } from '../alpha/tabbed-chips/TabbedChips';
import type { BannerBaseProps } from '../banner/Banner';
import type { AvatarButtonBaseProps } from '../buttons/AvatarButton';
import type { ButtonBaseProps } from '../buttons/Button';
import type { ButtonGroupBaseProps } from '../buttons/ButtonGroup';
import type { IconButtonBaseProps } from '../buttons/IconButton';
import type { IconCounterButtonBaseProps } from '../buttons/IconCounterButton';
import type { SlideButtonBaseProps } from '../buttons/SlideButton';
import type { CardBaseProps } from '../cards/Card';
import type { CardBodyBaseProps } from '../cards/CardBody';
import type { CardFooterBaseProps } from '../cards/CardFooter';
import type { LikeButtonBaseProps } from '../cards/LikeButton';
import type { CarouselBaseProps } from '../carousel/Carousel';
import type { CellBaseProps } from '../cells/Cell';
import type { ListCellBaseProps } from '../cells/ListCell';
import type { ListCellFallbackBaseProps } from '../cells/ListCellFallback';
import type { ChipBaseProps, InputChipBaseProps } from '../chips/ChipProps';
import type { MediaChipBaseProps } from '../chips/MediaChip';
import type { CoachmarkBaseProps } from '../coachmark/Coachmark';
import type { CollapsibleBaseProps } from '../collapsible/Collapsible';
import type { CheckboxBaseProps } from '../controls/Checkbox';
import type { CheckboxCellBaseProps } from '../controls/CheckboxCell';
import type { ControlBaseProps } from '../controls/Control';
import type { ControlGroupBaseProps } from '../controls/ControlGroup';
import type { InputStackBaseProps } from '../controls/InputStack';
import type { RadioBaseProps } from '../controls/Radio';
import type { RadioCellBaseProps } from '../controls/RadioCell';
import type { SearchInputBaseProps } from '../controls/SearchInput';
import type { SelectOptionBaseProps } from '../controls/SelectOption';
import type { SwitchBaseProps } from '../controls/Switch';
import type { TextInputBaseProps } from '../controls/TextInput';
import type { CalendarBaseProps } from '../dates/Calendar';
import type { DateInputBaseProps } from '../dates/DateInput';
import type { DatePickerBaseProps } from '../dates/DatePicker';
import type { DotCountBaseProps } from '../dots/DotCount';
import type { DotStatusColorBaseProps } from '../dots/DotStatusColor';
import type { DotSymbolBaseProps } from '../dots/DotSymbol';
import type { IconBaseProps } from '../icons/Icon';
import type { DividerBaseProps } from '../layout/Divider';
import type { FallbackBaseProps } from '../layout/Fallback';
import type { AvatarBaseProps } from '../media/Avatar';
import type { RemoteImageBaseProps } from '../media/RemoteImage';
import type { RemoteImageGroupBaseProps } from '../media/RemoteImageGroup';
import type { BrowserBarBaseProps } from '../navigation/BrowserBar';
import type { NavigationTitleBaseProps } from '../navigation/NavigationTitle';
import type { NavigationTitleSelectBaseProps } from '../navigation/NavigationTitleSelect';
import type { NavigationBarBaseProps } from '../navigation/TopNavBar';
import type { RollingNumberBaseProps } from '../numbers/RollingNumber/RollingNumber';
import type { NumpadBaseProps } from '../numpad/Numpad';
import type { AlertBaseProps } from '../overlays/Alert';
import type { DrawerBaseProps } from '../overlays/drawer/Drawer';
import type { ModalBaseProps } from '../overlays/modal/Modal';
import type { ModalBodyBaseProps } from '../overlays/modal/ModalBody';
import type { ModalFooterBaseProps } from '../overlays/modal/ModalFooter';
import type { ModalHeaderBaseProps } from '../overlays/modal/ModalHeader';
import type { OverlayBaseProps } from '../overlays/overlay/Overlay';
import type { ToastBaseProps } from '../overlays/Toast';
import type { TooltipBaseProps } from '../overlays/tooltip/Tooltip';
import type { TrayBaseProps } from '../overlays/tray/Tray';
import type { PageFooterBaseProps } from '../page/PageFooter';
import type { PageHeaderBaseProps } from '../page/PageHeader';
import type { StepperBaseProps } from '../stepper/Stepper';
import type { SegmentedTabBaseProps } from '../tabs/SegmentedTab';
import type { SegmentedTabsBaseProps } from '../tabs/SegmentedTabs';
import type { TabsBaseProps } from '../tabs/Tabs';
import type { TagBaseProps } from '../tag/Tag';
import type { TourBaseProps } from '../tour/Tour';
import type { LinkBaseProps } from '../typography/Link';
import type { ProgressBaseProps } from '../visualizations/ProgressBar';
import type { ProgressBarWithFixedLabelsBaseProps } from '../visualizations/ProgressBarWithFixedLabels';
import type { ProgressBarWithFloatLabelBaseProps } from '../visualizations/ProgressBarWithFloatLabel';
import type { ProgressCircleBaseProps } from '../visualizations/ProgressCircle';

/**
 * Config resolver that supports either static partial props object
 * or a function that receives component props and returns partial props.
 */
export type ConfigResolver<P> = Partial<P> | ((props: P) => Partial<P>);

/**
 * Component config for customization of default ComponentBaseProps.
 *
 * @note components that aren't listed here are either primitives or sub-components with limited customization opportunities.
 */
export type ComponentConfig = {
  Accordion?: ConfigResolver<AccordionBaseProps>;
  Alert?: ConfigResolver<AlertBaseProps>;
  TabbedChips?: ConfigResolver<TabbedChipsBaseProps>;
  Avatar?: ConfigResolver<AvatarBaseProps>;
  AvatarButton?: ConfigResolver<AvatarButtonBaseProps>;
  Banner?: ConfigResolver<BannerBaseProps>;
  BrowserBar?: ConfigResolver<BrowserBarBaseProps>;
  Button?: ConfigResolver<ButtonBaseProps>;
  ButtonGroup?: ConfigResolver<ButtonGroupBaseProps>;
  Card?: ConfigResolver<CardBaseProps>;
  CardBody?: ConfigResolver<CardBodyBaseProps>;
  CardFooter?: ConfigResolver<CardFooterBaseProps>;
  Carousel?: ConfigResolver<CarouselBaseProps>;
  Cell?: ConfigResolver<CellBaseProps>;
  Chip?: ConfigResolver<ChipBaseProps>;
  Checkbox?: ConfigResolver<CheckboxBaseProps<string>>;
  CheckboxCell?: ConfigResolver<CheckboxCellBaseProps<string>>;
  Coachmark?: ConfigResolver<CoachmarkBaseProps>;
  Collapsible?: ConfigResolver<CollapsibleBaseProps>;
  Combobox?: ConfigResolver<ComboboxBaseProps>;
  Calendar?: ConfigResolver<CalendarBaseProps>;
  Control?: ConfigResolver<ControlBaseProps<string>>;
  ControlGroup?: ConfigResolver<ControlGroupBaseProps>;
  DateInput?: ConfigResolver<DateInputBaseProps>;
  DatePicker?: ConfigResolver<DatePickerBaseProps>;
  Divider?: ConfigResolver<DividerBaseProps>;
  DotCount?: ConfigResolver<DotCountBaseProps>;
  DotStatusColor?: ConfigResolver<DotStatusColorBaseProps>;
  DotSymbol?: ConfigResolver<DotSymbolBaseProps>;
  Drawer?: ConfigResolver<DrawerBaseProps>;
  Fallback?: ConfigResolver<FallbackBaseProps>;
  Icon?: ConfigResolver<IconBaseProps>;
  IconButton?: ConfigResolver<IconButtonBaseProps>;
  IconCounterButton?: ConfigResolver<IconCounterButtonBaseProps>;
  InputChip?: ConfigResolver<InputChipBaseProps>;
  InputStack?: ConfigResolver<InputStackBaseProps>;
  LikeButton?: ConfigResolver<LikeButtonBaseProps>;
  Link?: ConfigResolver<LinkBaseProps>;
  ListCell?: ConfigResolver<ListCellBaseProps>;
  ListCellFallback?: ConfigResolver<ListCellFallbackBaseProps>;
  MediaChip?: ConfigResolver<MediaChipBaseProps>;
  Modal?: ConfigResolver<ModalBaseProps>;
  ModalBody?: ConfigResolver<ModalBodyBaseProps>;
  ModalFooter?: ConfigResolver<ModalFooterBaseProps>;
  ModalHeader?: ConfigResolver<ModalHeaderBaseProps>;
  NavigationTitle?: ConfigResolver<NavigationTitleBaseProps>;
  NavigationTitleSelect?: ConfigResolver<NavigationTitleSelectBaseProps>;
  Numpad?: ConfigResolver<NumpadBaseProps>;
  Overlay?: ConfigResolver<OverlayBaseProps>;
  PageFooter?: ConfigResolver<PageFooterBaseProps>;
  PageHeader?: ConfigResolver<PageHeaderBaseProps>;
  ProgressBar?: ConfigResolver<ProgressBaseProps>;
  ProgressBarWithFixedLabels?: ConfigResolver<ProgressBarWithFixedLabelsBaseProps>;
  ProgressBarWithFloatLabel?: ConfigResolver<ProgressBarWithFloatLabelBaseProps>;
  ProgressCircle?: ConfigResolver<ProgressCircleBaseProps>;
  Radio?: ConfigResolver<RadioBaseProps<string>>;
  RadioCell?: ConfigResolver<RadioCellBaseProps<string>>;
  RemoteImage?: ConfigResolver<RemoteImageBaseProps>;
  RemoteImageGroup?: ConfigResolver<RemoteImageGroupBaseProps>;
  RollingNumber?: ConfigResolver<RollingNumberBaseProps>;
  SearchInput?: ConfigResolver<SearchInputBaseProps>;
  SegmentedTab?: ConfigResolver<SegmentedTabBaseProps>;
  SegmentedTabs?: ConfigResolver<SegmentedTabsBaseProps>;
  Select?: ConfigResolver<SelectBaseProps>;
  SelectChip?: ConfigResolver<SelectChipBaseProps>;
  SelectOption?: ConfigResolver<SelectOptionBaseProps>;
  SlideButton?: ConfigResolver<SlideButtonBaseProps>;
  Stepper?: ConfigResolver<StepperBaseProps>;
  Switch?: ConfigResolver<SwitchBaseProps<string>>;
  Tabs?: ConfigResolver<TabsBaseProps>;
  Tag?: ConfigResolver<TagBaseProps>;
  TextInput?: ConfigResolver<TextInputBaseProps>;
  Toast?: ConfigResolver<ToastBaseProps>;
  TopNavBar?: ConfigResolver<NavigationBarBaseProps>;
  Tour?: ConfigResolver<TourBaseProps>;
  Tray?: ConfigResolver<TrayBaseProps>;
  Tooltip?: ConfigResolver<TooltipBaseProps>;
};
