type PresetClassicOptions = import('@docusaurus/preset-classic/src/preset-classic').Options;
type LoadContext = import('@docusaurus/types').LoadContext;
type PluginConfigs = import('@docusaurus/types').PluginConfig[];

declare module '@docusaurus/preset-classic' {
  export default function preset(
    context: LoadContext,
    options: PresetClassicOptions,
  ): {
    themes: PluginConfigs;
    plugins: PluginConfigs;
  };
}

declare module '@cbhq/docusaurus-preset' {
  export type { LoadContext };
  export type PresetOptions = {
    theme?: undefined;
    docgen?: import('@cbhq/docusaurus-plugin-docgen').PluginOptions;
    kbar?: import('@cbhq/docusaurus-plugin-kbar').PluginOptions;
  } & PresetClassicOptions;

  export default function preset(
    context: LoadContext,
    options: PresetClassicOptions,
  ): {
    themes: (string | [string, undefined])[];
    plugins: PresetOptions[keyof PresetOptions][];
  };

  /* -------------------------------------------------------------------------- */
  /*                   Sidebar overrides for typed customProps                  */
  /* -------------------------------------------------------------------------- */
  import type { Expand } from '@cbhq/cds-common/types';
  import type {
    SidebarItemDoc as SidebarItemDocOriginal,
    SidebarItemHtml as SidebarItemHtmlOriginal,
    SidebarItemLink as SidebarItemLinkOriginal,
    SidebarItemCategoryLinkConfig,
  } from '@docusaurus/plugin-content-docs/lib/sidebars/types';
  import type { SetOptional } from 'type-fest';
  import type { SidebarItemCustomProps as KBarCustomProps } from '@cbhq/docusaurus-plugin-kbar';
  import type { SidebarItemCustomProps as ThemeCustomProps } from '@cbhq/docusaurus-theme';

  type SidebarItemCustomProps = Expand<KBarCustomProps & ThemeCustomProps>;

  type SidebarItemBase = {
    customProps?: SidebarItemCustomProps;
  };

  type SidebarItemCategoryBase = Expand<
    SidebarItemBase & {
      type: 'category';
      label: string;
      collapsed: boolean;
      collapsible: boolean;
    }
  >;
  type SidebarItemDoc = Expand<SidebarItemBase & Omit<SidebarItemDocOriginal, 'customProps'>>;
  type SidebarItemHtml = Expand<SidebarItemBase & Omit<SidebarItemHtmlOriginal, 'customProps'>>;
  type SidebarItemLink = Expand<SidebarItemBase & Omit<SidebarItemLinkOriginal, 'customProps'>>;
  type SidebarItemAutogenerated = Expand<
    SidebarItemBase & {
      type: 'autogenerated';
      dirName: string;
    }
  >;

  // The user-given configuration in sidebars.js, before normalization
  type SidebarItemCategoryConfig = Expand<
    SetOptional<SidebarItemCategoryBase, 'collapsed' | 'collapsible'> & {
      items: SidebarItemConfig[];
      link?: SidebarItemCategoryLinkConfig;
    }
  >;

  type SidebarItemConfig =
    | SidebarItemDoc
    | SidebarItemHtml
    | SidebarItemLink
    | SidebarItemAutogenerated
    | SidebarItemCategoryConfig
    | string;

  export type SidebarsConfig = Record<string, SidebarItemConfig[]>;
}
