node_modules = "../../../../../node_modules"

require_relative "#{node_modules}/react-native/scripts/react_native_pods"
require_relative "#{node_modules}/@react-native-community/cli-platform-ios/native_modules"

platform(:ios, '11.0')

target 'cds' do
  use_native_modules!

  use_react_native!({ path: "#{node_modules}/react-native", hermes_enabled: false })

  use_flipper!({ 'Flipper' => '0.99.0', 'Flipper-Folly' => '2.6.10', 'Flipper-RSocket' => '1.4.3' })

  post_install do |installer|
    react_native_post_install(installer)

    # https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
      end
    end

    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
  end
end
