/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustrationManifest = {
  svg: {
    '597:73': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'processing',
      spectrum: 'light',
    },
    '597:74': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'success',
      spectrum: 'light',
    },
    '597:64': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'bigWarning',
      spectrum: 'light',
    },
    '597:63': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'polling',
      spectrum: 'light',
    },
  },
  png: {
    '597:25': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'idBack',
      spectrum: 'light',
    },
    '597:26': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinsInWallet',
      spectrum: 'light',
    },
    '597:27': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'bigBtc',
      spectrum: 'light',
    },
    '597:28': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'myNameIsSatoshi',
      spectrum: 'light',
    },
    '597:40': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'limitOrders',
      spectrum: 'light',
    },
    '597:39': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'payUpFront',
      spectrum: 'light',
    },
    '597:38': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'cardAndPhone',
      spectrum: 'light',
    },
    '597:37': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'automaticPayments',
      spectrum: 'light',
    },
    '597:36': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'earnProgress',
      spectrum: 'light',
    },
    '597:35': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'earnSuccess',
      spectrum: 'light',
    },
    '597:34': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'emailNotification',
      spectrum: 'light',
    },
    '597:24': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'idFront',
      spectrum: 'light',
    },
    '597:23': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'idAngles',
      spectrum: 'light',
    },
    '597:22': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'sendToUsername',
      spectrum: 'light',
    },
    '597:21': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'idVerificationSecure',
      spectrum: 'light',
    },
    '597:14': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'tradeImmediately',
      spectrum: 'light',
    },
    '597:13': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'rocket',
      spectrum: 'light',
    },
    '597:15': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'addPhoneNumber',
      spectrum: 'light',
    },
    '597:16': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'japanVerifyId',
      spectrum: 'light',
    },
    '597:17': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'documentCertified',
      spectrum: 'light',
    },
    '597:18': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'onTheList',
      spectrum: 'light',
    },
    '597:19': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'addBankAccount',
      spectrum: 'light',
    },
    '597:20': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'addCreditCard',
      spectrum: 'light',
    },
    '597:8': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyIdDetails',
      spectrum: 'light',
    },
    '597:7': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'idIssue',
      spectrum: 'light',
    },
    '597:6': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyInfo',
      spectrum: 'light',
    },
    '597:5': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'readyToTrade',
      spectrum: 'light',
    },
    '597:4': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'idCard',
      spectrum: 'light',
    },
    '597:3': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'phoneNumber',
      spectrum: 'light',
    },
    '597:2': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'securityShield',
      spectrum: 'light',
    },
    '597:1': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyEmail',
      spectrum: 'light',
    },
    '597:41': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'freeBtc',
      spectrum: 'light',
    },
    '597:42': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyBankTransactions',
      spectrum: 'light',
    },
    '597:33': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'transactionLimit',
      spectrum: 'light',
    },
    '597:61': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'whyNotBoth',
      spectrum: 'light',
    },
    '597:57': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'notificationsAndUpdates',
      spectrum: 'light',
    },
    '597:62': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'yourContacts',
      spectrum: 'light',
    },
    '597:71': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'walletUi',
      spectrum: 'light',
    },
    '597:72': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'invite',
      spectrum: 'light',
    },
    '597:65': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'recurringReward',
      spectrum: 'light',
    },
    '597:66': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'sendCryptoFaster',
      spectrum: 'light',
    },
    '597:60': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'insufficientBalance',
      spectrum: 'light',
    },
    '597:59': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinbaseCardIssue',
      spectrum: 'light',
    },
    '597:70': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinbaseCardLock',
      spectrum: 'light',
    },
    '597:69': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'commerceInvoices',
      spectrum: 'light',
    },
    '597:58': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinbaseCardSpendCrypto',
      spectrum: 'light',
    },
    '597:54': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'earnIdVerification',
      spectrum: 'light',
    },
    '597:47': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'selectCorrectCrypto',
      spectrum: 'light',
    },
    '597:48': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinbaseIsDown',
      spectrum: 'light',
    },
    '597:43': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyCardTransactions',
      spectrum: 'light',
    },
    '597:44': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'accountUnderReview',
      spectrum: 'light',
    },
    '597:45': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'twoIdVerify',
      spectrum: 'light',
    },
    '597:46': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'buyFirstCrypto',
      spectrum: 'light',
    },
    '597:55': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'routingAccount',
      spectrum: 'light',
    },
    '597:30': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'earnMore',
      spectrum: 'light',
    },
    '597:29': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'holdingCrypto',
      spectrum: 'light',
    },
    '597:31': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'remittances',
      spectrum: 'light',
    },
    '597:9': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'documentSuccess',
      spectrum: 'light',
    },
    '597:32': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'docError',
      spectrum: 'light',
    },
    '597:12': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'errorWeb500',
      spectrum: 'light',
    },
    '597:49': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'errorWeb404',
      spectrum: 'light',
    },
    '597:11': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'errorWeb400',
      spectrum: 'light',
    },
    '597:10': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'advancedTradingUi',
      spectrum: 'light',
    },
    '597:67': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'openEmail',
      spectrum: 'light',
    },
    '597:68': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'commerceAccounting',
      spectrum: 'light',
    },
    '597:52': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'pending',
      spectrum: 'light',
    },
    '597:53': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinbaseIsDownMobile',
      spectrum: 'light',
    },
    '597:56': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'errorRefresh',
      spectrum: 'light',
    },
    '597:51': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'error400',
      spectrum: 'light',
    },
    '597:50': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'errorApp500',
      spectrum: 'light',
    },
    '600:13524': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'currency',
      spectrum: 'light',
    },
    '600:13525': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'creditCardExcitement',
      spectrum: 'light',
    },
    '600:13526': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'diamond',
      spectrum: 'light',
    },
    '600:13527': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'advancedTrading',
      spectrum: 'light',
    },
    '600:13528': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'trade',
      spectrum: 'light',
    },
    '600:13529': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'giftBoxRewards',
      spectrum: 'light',
    },
    '600:13635': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'orders',
      spectrum: 'light',
    },
    '600:13631': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'giftbox',
      spectrum: 'light',
    },
    '600:13636': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'worldwide',
      spectrum: 'light',
    },
    '600:13637': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'clock',
      spectrum: 'light',
    },
    '600:13563': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'predictionMarkets',
      spectrum: 'light',
    },
    '600:13564': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'waiting',
      spectrum: 'light',
    },
    '600:13565': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'madeInUSA',
      spectrum: 'light',
    },
    '600:13566': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'bitcoinPizza',
      spectrum: 'light',
    },
    '600:13567': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'bitcoinWhitePaper',
      spectrum: 'light',
    },
    '600:13568': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'pizza',
      spectrum: 'light',
    },
    '600:13575': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'contactInfo',
      spectrum: 'light',
    },
    '600:13576': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'addressBook',
      spectrum: 'light',
    },
    '600:13581': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'startToday',
      spectrum: 'light',
    },
    '600:13630': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'transistor',
      spectrum: 'light',
    },
    '600:13607': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'noAnnualFee',
      spectrum: 'light',
    },
    '600:13629': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'applyForHigherLimits',
      spectrum: 'light',
    },
    '600:13582': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'noWiFi',
      spectrum: 'light',
    },
    '600:13583': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'reviewAndAdd',
      spectrum: 'light',
    },
    '600:13590': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'fast',
      spectrum: 'light',
    },
    '600:13591': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'tryAgainLater',
      spectrum: 'light',
    },
    '600:13596': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'typeScript',
      spectrum: 'light',
    },
    '600:13597': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'multiPlatform',
      spectrum: 'light',
    },
    '600:13602': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'takeQuiz',
      spectrum: 'light',
    },
    '600:13603': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'chat',
      spectrum: 'light',
    },
    '600:13604': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'email',
      spectrum: 'light',
    },
    '600:13605': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'recurringPurchases',
      spectrum: 'light',
    },
    '600:13606': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'delegate',
      spectrum: 'light',
    },
    '600:13628': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'waitingForConsensus',
      spectrum: 'light',
    },
    '600:13633': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'enableVoting',
      spectrum: 'light',
    },
    '600:13634': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'formDownload',
      spectrum: 'light',
    },
    '600:13622': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'settings',
      spectrum: 'light',
    },
    '600:13621': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'priceTracking',
      spectrum: 'light',
    },
    '600:13551': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'authenticatorProgress',
      spectrum: 'light',
    },
    '600:13555': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'stateId',
      spectrum: 'light',
    },
    '600:13556': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'safe',
      spectrum: 'light',
    },
    '600:13557': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'smsAuthenticate',
      spectrum: 'light',
    },
    '600:13558': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'googleAuthenticator',
      spectrum: 'light',
    },
    '600:13571': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'authenticatorAlt',
      spectrum: 'light',
    },
    '600:13572': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'authenticator',
      spectrum: 'light',
    },
    '600:13573': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'idVerification',
      spectrum: 'light',
    },
    '600:13578': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'key',
      spectrum: 'light',
    },
    '600:13579': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'ubiKey',
      spectrum: 'light',
    },
    '600:13586': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'authenticationApp',
      spectrum: 'light',
    },
    '600:13585': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'shield',
      spectrum: 'light',
    },
    '600:13588': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'lock',
      spectrum: 'light',
    },
    '600:13593': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'security',
      spectrum: 'light',
    },
    '600:13601': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'institutions',
      spectrum: 'light',
    },
    '600:13562': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'moneySwift',
      spectrum: 'light',
    },
    '600:13553': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'transferSend',
      spectrum: 'light',
    },
    '600:13552': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'higherLimits',
      spectrum: 'light',
    },
    '600:13561': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'increaseLimits',
      spectrum: 'light',
    },
    '600:13560': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'fiat',
      spectrum: 'light',
    },
    '600:13559': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'walletExchange',
      spectrum: 'light',
    },
    '600:13570': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'addWallet',
      spectrum: 'light',
    },
    '600:13569': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'walletDeposit',
      spectrum: 'light',
    },
    '600:13574': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'wallet',
      spectrum: 'light',
    },
    '600:13554': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'cryptoCard',
      spectrum: 'light',
    },
    '600:13577': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'tokenBaskets',
      spectrum: 'light',
    },
    '600:13580': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'addToWatchlist',
      spectrum: 'light',
    },
    '600:13587': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'bundle',
      spectrum: 'light',
    },
    '600:13584': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'trading',
      spectrum: 'light',
    },
    '600:13589': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'multipleAssets',
      spectrum: 'light',
    },
    '600:13592': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'moreThanBitcoin',
      spectrum: 'light',
    },
    '600:13595': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'lowFees',
      spectrum: 'light',
    },
    '600:13598': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'listingFees',
      spectrum: 'light',
    },
    '600:13608': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'earnCoins',
      spectrum: 'light',
    },
    '600:13611': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'partialCoins',
      spectrum: 'light',
    },
    '600:13612': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'paypal',
      spectrum: 'light',
    },
    '600:13627': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'moneyEarn',
      spectrum: 'light',
    },
    '600:13626': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'creditCard',
      spectrum: 'light',
    },
    '600:13623': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'addCard',
      spectrum: 'light',
    },
    '600:13624': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'cardDeclined',
      spectrum: 'light',
    },
    '600:13625': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'cardBlocked',
      spectrum: 'light',
    },
    '600:13620': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'addPayment',
      spectrum: 'light',
    },
    '600:13599': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'laptopCharts',
      spectrum: 'light',
    },
    '600:13600': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'mobileCharts',
      spectrum: 'light',
    },
    '600:13609': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'addPhone',
      spectrum: 'light',
    },
    '600:13610': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'browser',
      spectrum: 'light',
    },
    '600:13613': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'internet',
      spectrum: 'light',
    },
    '600:13594': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'laptopVideo',
      spectrum: 'light',
    },
    '600:13614': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'mobileNotifcation',
      spectrum: 'light',
    },
    '600:13615': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'browserTransaction',
      spectrum: 'light',
    },
    '600:13616': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'laptop',
      spectrum: 'light',
    },
    '600:13617': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'successPhone',
      spectrum: 'light',
    },
    '600:13618': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'phone',
      spectrum: 'light',
    },
    '600:13619': {
      variant: 'IllustrationPictogram',
      description: '',
      name: '2fa',
      spectrum: 'light',
    },
    '600:13540': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'calendar',
      spectrum: 'light',
    },
    '600:13537': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'envelope',
      spectrum: 'light',
    },
    '600:13536': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'pieChart',
      spectrum: 'light',
    },
    '600:13535': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'warning',
      spectrum: 'light',
    },
    '600:13550': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'strongInfo',
      spectrum: 'light',
    },
    '600:13541': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'gem',
      spectrum: 'light',
    },
    '600:13538': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'chart',
      spectrum: 'light',
    },
    '600:13549': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'strongWarning',
      spectrum: 'light',
    },
    '600:13543': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'barChart',
      spectrum: 'light',
    },
    '600:13544': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'learn',
      spectrum: 'light',
    },
    '600:13545': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'explore',
      spectrum: 'light',
    },
    '600:13546': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'target',
      spectrum: 'light',
    },
    '600:13547': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'easyToUse',
      spectrum: 'light',
    },
    '600:13548': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'trusted',
      spectrum: 'light',
    },
    '600:13530': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'checkmark',
      spectrum: 'light',
    },
    '600:13531': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'add',
      spectrum: 'light',
    },
    '600:13534': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'done',
      spectrum: 'light',
    },
    '600:13532': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'settled',
      spectrum: 'light',
    },
    '600:13533': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'error',
      spectrum: 'light',
    },
    '600:13542': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'notifications',
      spectrum: 'light',
    },
    '600:13539': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'alerts',
      spectrum: 'light',
    },
    '1353:2': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'newUserChecklistCompleteAccount',
      spectrum: 'light',
    },
    '1353:1': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'newUserChecklistBuyCrypto',
      spectrum: 'light',
    },
    '1353:0': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'newUserChecklistVerifyId',
      spectrum: 'light',
    },
    '1353:47': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'commerceInvoice',
      spectrum: 'light',
    },
    '1353:46': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'commerceNoPayments',
      spectrum: 'light',
    },
    '1353:45': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'commerceCheckout',
      spectrum: 'light',
    },
    '1478:835': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'moneyRewards',
      spectrum: 'light',
    },
    '1478:840': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'interestForYou',
      spectrum: 'light',
    },
    '1478:839': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'giftBoxCrypto',
      spectrum: 'light',
    },
    '1478:838': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'starToken',
      spectrum: 'light',
    },
    '1478:842': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'addMultipleCrypto',
      spectrum: 'light',
    },
    '1478:841': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'phoneNotifications',
      spectrum: 'light',
    },
    '1478:843': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'darkModeIntroduction',
      spectrum: 'light',
    },
    '1478:844': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'cardShipped',
      spectrum: 'light',
    },
    '1478:845': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'refreshMobileApp',
      spectrum: 'light',
    },
    '1478:846': {
      variant: 'IllustrationSpotSquare',
      description: '',
      name: 'refreshMobileApp',
      spectrum: 'dark',
    },
  },
};
