/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustration_manifest = {
  svg: {
    '597:73': { variant: 'IllustrationHeroSquare', description: '', name: 'processing' },
    '597:74': { variant: 'IllustrationHeroSquare', description: '', name: 'success' },
    '597:64': { variant: 'IllustrationHeroSquare', description: '', name: 'bigWarning' },
    '597:63': { variant: 'IllustrationHeroSquare', description: '', name: 'polling' },
    '600:13635': { variant: 'IllustrationPictogram', description: '', name: 'orders' },
    '600:13631': { variant: 'IllustrationPictogram', description: '', name: 'giftbox' },
    '600:13636': { variant: 'IllustrationPictogram', description: '', name: 'worldwide' },
    '600:13637': { variant: 'IllustrationPictogram', description: '', name: 'clock' },
    '600:13563': { variant: 'IllustrationPictogram', description: '', name: 'predictionMarkets' },
    '600:13564': { variant: 'IllustrationPictogram', description: '', name: 'waiting' },
    '600:13565': { variant: 'IllustrationPictogram', description: '', name: 'madeInUSA' },
    '600:13566': { variant: 'IllustrationPictogram', description: '', name: 'bitcoinPizza' },
    '600:13567': { variant: 'IllustrationPictogram', description: '', name: 'bitcoinWhitePaper' },
    '600:13568': { variant: 'IllustrationPictogram', description: '', name: 'pizza' },
    '600:13575': { variant: 'IllustrationPictogram', description: '', name: 'contactInfo' },
    '600:13576': { variant: 'IllustrationPictogram', description: '', name: 'addressBook' },
    '600:13581': { variant: 'IllustrationPictogram', description: '', name: 'startToday' },
    '600:13630': { variant: 'IllustrationPictogram', description: '', name: 'transistor' },
    '600:13607': { variant: 'IllustrationPictogram', description: '', name: 'noAnnualFee' },
    '600:13629': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'applyForHigherLimits',
    },
    '600:13582': { variant: 'IllustrationPictogram', description: '', name: 'noWiFi' },
    '600:13583': { variant: 'IllustrationPictogram', description: '', name: 'reviewAndAdd' },
    '600:13590': { variant: 'IllustrationPictogram', description: '', name: 'fast' },
    '600:13591': { variant: 'IllustrationPictogram', description: '', name: 'tryAgainLater' },
    '600:13596': { variant: 'IllustrationPictogram', description: '', name: 'typeScript' },
    '600:13597': { variant: 'IllustrationPictogram', description: '', name: 'multiPlatform' },
    '600:13602': { variant: 'IllustrationPictogram', description: '', name: 'takeQuiz' },
    '600:13603': { variant: 'IllustrationPictogram', description: '', name: 'chat' },
    '600:13604': { variant: 'IllustrationPictogram', description: '', name: 'email' },
    '600:13605': { variant: 'IllustrationPictogram', description: '', name: 'recurringPurchases' },
    '600:13606': { variant: 'IllustrationPictogram', description: '', name: 'delegate' },
    '600:13628': { variant: 'IllustrationPictogram', description: '', name: 'waitingForConsensus' },
    '600:13633': { variant: 'IllustrationPictogram', description: '', name: 'enableVoting' },
    '600:13634': { variant: 'IllustrationPictogram', description: '', name: 'formDownload' },
    '600:13622': { variant: 'IllustrationPictogram', description: '', name: 'settings' },
    '600:13621': { variant: 'IllustrationPictogram', description: '', name: 'priceTracking' },
    '600:13551': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'authenticatorProgress',
    },
    '600:13555': { variant: 'IllustrationPictogram', description: '', name: 'stateId' },
    '600:13556': { variant: 'IllustrationPictogram', description: '', name: 'safe' },
    '600:13557': { variant: 'IllustrationPictogram', description: '', name: 'smsAuthenticate' },
    '600:13558': { variant: 'IllustrationPictogram', description: '', name: 'googleAuthenticator' },
    '600:13571': { variant: 'IllustrationPictogram', description: '', name: 'authenticatorAlt' },
    '600:13572': { variant: 'IllustrationPictogram', description: '', name: 'authenticator' },
    '600:13573': { variant: 'IllustrationPictogram', description: '', name: 'idVerification' },
    '600:13578': { variant: 'IllustrationPictogram', description: '', name: 'key' },
    '600:13579': { variant: 'IllustrationPictogram', description: '', name: 'ubiKey' },
    '600:13586': { variant: 'IllustrationPictogram', description: '', name: 'authenticationApp' },
    '600:13585': { variant: 'IllustrationPictogram', description: '', name: 'shield' },
    '600:13588': { variant: 'IllustrationPictogram', description: '', name: 'lock' },
    '600:13593': { variant: 'IllustrationPictogram', description: '', name: 'security' },
    '600:13601': { variant: 'IllustrationPictogram', description: '', name: 'institutions' },
    '600:13562': { variant: 'IllustrationPictogram', description: '', name: 'moneySwift' },
    '600:13553': { variant: 'IllustrationPictogram', description: '', name: 'transferSend' },
    '600:13552': { variant: 'IllustrationPictogram', description: '', name: 'higherLimits' },
    '600:13561': { variant: 'IllustrationPictogram', description: '', name: 'increaseLimits' },
    '600:13560': { variant: 'IllustrationPictogram', description: '', name: 'fiat' },
    '600:13559': { variant: 'IllustrationPictogram', description: '', name: 'walletExchange' },
    '600:13570': { variant: 'IllustrationPictogram', description: '', name: 'addWallet' },
    '600:13569': { variant: 'IllustrationPictogram', description: '', name: 'walletDeposit' },
    '600:13574': { variant: 'IllustrationPictogram', description: '', name: 'wallet' },
    '600:13554': { variant: 'IllustrationPictogram', description: '', name: 'cryptoCard' },
    '600:13577': { variant: 'IllustrationPictogram', description: '', name: 'tokenBaskets' },
    '600:13580': { variant: 'IllustrationPictogram', description: '', name: 'addToWatchlist' },
    '600:13587': { variant: 'IllustrationPictogram', description: '', name: 'bundle' },
    '600:13584': { variant: 'IllustrationPictogram', description: '', name: 'trading' },
    '600:13589': { variant: 'IllustrationPictogram', description: '', name: 'multipleAssets' },
    '600:13592': { variant: 'IllustrationPictogram', description: '', name: 'moreThanBitcoin' },
    '600:13595': { variant: 'IllustrationPictogram', description: '', name: 'lowFees' },
    '600:13598': { variant: 'IllustrationPictogram', description: '', name: 'listingFees' },
    '600:13608': { variant: 'IllustrationPictogram', description: '', name: 'earnCoins' },
    '600:13611': { variant: 'IllustrationPictogram', description: '', name: 'partialCoins' },
    '600:13612': { variant: 'IllustrationPictogram', description: '', name: 'paypal' },
    '600:13627': { variant: 'IllustrationPictogram', description: '', name: 'moneyEarn' },
    '600:13626': { variant: 'IllustrationPictogram', description: '', name: 'creditCard' },
    '600:13623': { variant: 'IllustrationPictogram', description: '', name: 'addCard' },
    '600:13624': { variant: 'IllustrationPictogram', description: '', name: 'cardDeclined' },
    '600:13625': { variant: 'IllustrationPictogram', description: '', name: 'cardBlocked' },
    '600:13620': { variant: 'IllustrationPictogram', description: '', name: 'addPayment' },
    '600:13599': { variant: 'IllustrationPictogram', description: '', name: 'laptopCharts' },
    '600:13600': { variant: 'IllustrationPictogram', description: '', name: 'mobileCharts' },
    '600:13609': { variant: 'IllustrationPictogram', description: '', name: 'addPhone' },
    '600:13610': { variant: 'IllustrationPictogram', description: '', name: 'browser' },
    '600:13613': { variant: 'IllustrationPictogram', description: '', name: 'internet' },
    '600:13594': { variant: 'IllustrationPictogram', description: '', name: 'laptopVideo' },
    '600:13614': { variant: 'IllustrationPictogram', description: '', name: 'mobileNotifcation' },
    '600:13615': { variant: 'IllustrationPictogram', description: '', name: 'browserTransaction' },
    '600:13616': { variant: 'IllustrationPictogram', description: '', name: 'laptop' },
    '600:13617': { variant: 'IllustrationPictogram', description: '', name: 'successPhone' },
    '600:13618': { variant: 'IllustrationPictogram', description: '', name: 'phone' },
    '600:13619': { variant: 'IllustrationPictogram', description: '', name: '2fa' },
    '600:13540': { variant: 'IllustrationPictogram', description: '', name: 'calendar' },
    '600:13537': { variant: 'IllustrationPictogram', description: '', name: 'envelope' },
    '600:13536': { variant: 'IllustrationPictogram', description: '', name: 'pieChart' },
    '600:13535': { variant: 'IllustrationPictogram', description: '', name: 'warning' },
    '600:13550': { variant: 'IllustrationPictogram', description: '', name: 'strongInfo' },
    '600:13541': { variant: 'IllustrationPictogram', description: '', name: 'gem' },
    '600:13538': { variant: 'IllustrationPictogram', description: '', name: 'chart' },
    '600:13549': { variant: 'IllustrationPictogram', description: '', name: 'strongWarning' },
    '600:13543': { variant: 'IllustrationPictogram', description: '', name: 'barChart' },
    '600:13544': { variant: 'IllustrationPictogram', description: '', name: 'learn' },
    '600:13545': { variant: 'IllustrationPictogram', description: '', name: 'explore' },
    '600:13546': { variant: 'IllustrationPictogram', description: '', name: 'target' },
    '600:13547': { variant: 'IllustrationPictogram', description: '', name: 'easyToUse' },
    '600:13548': { variant: 'IllustrationPictogram', description: '', name: 'trusted' },
    '600:13530': { variant: 'IllustrationPictogram', description: '', name: 'checkmark' },
    '600:13531': { variant: 'IllustrationPictogram', description: '', name: 'add' },
    '600:13534': { variant: 'IllustrationPictogram', description: '', name: 'done' },
    '600:13532': { variant: 'IllustrationPictogram', description: '', name: 'settled' },
    '600:13533': { variant: 'IllustrationPictogram', description: '', name: 'error' },
    '600:13542': { variant: 'IllustrationPictogram', description: '', name: 'notifications' },
    '600:13539': { variant: 'IllustrationPictogram', description: '', name: 'alerts' },
    '1353:2': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'newUserChecklistCompleteAccount',
    },
    '1353:1': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'newUserChecklistBuyCrypto',
    },
    '1353:0': {
      variant: 'IllustrationPictogram',
      description: '',
      name: 'newUserChecklistVerifyId',
    },
    '1353:47': { variant: 'IllustrationPictogram', description: '', name: 'commerceInvoice' },
    '1353:46': { variant: 'IllustrationPictogram', description: '', name: 'commerceNoPayments' },
    '1353:45': { variant: 'IllustrationPictogram', description: '', name: 'commerceCheckout' },
  },
  png: {
    '597:25': { variant: 'IllustrationHeroSquare', description: '', name: 'idBack' },
    '597:26': { variant: 'IllustrationHeroSquare', description: '', name: 'coinsInWallet' },
    '597:27': { variant: 'IllustrationHeroSquare', description: '', name: 'bigBtc' },
    '597:28': { variant: 'IllustrationHeroSquare', description: '', name: 'myNameIsSatoshi' },
    '597:40': { variant: 'IllustrationHeroSquare', description: '', name: 'limitOrders' },
    '597:39': { variant: 'IllustrationHeroSquare', description: '', name: 'payUpFront' },
    '597:38': { variant: 'IllustrationHeroSquare', description: '', name: 'cardAndPhone' },
    '597:37': { variant: 'IllustrationHeroSquare', description: '', name: 'automaticPayments' },
    '597:36': { variant: 'IllustrationHeroSquare', description: '', name: 'earnProgress' },
    '597:35': { variant: 'IllustrationHeroSquare', description: '', name: 'earnSuccess' },
    '597:34': { variant: 'IllustrationHeroSquare', description: '', name: 'emailNotification' },
    '597:24': { variant: 'IllustrationHeroSquare', description: '', name: 'idFront' },
    '597:23': { variant: 'IllustrationHeroSquare', description: '', name: 'idAngles' },
    '597:22': { variant: 'IllustrationHeroSquare', description: '', name: 'sendToUsername' },
    '597:21': { variant: 'IllustrationHeroSquare', description: '', name: 'idVerificationSecure' },
    '597:14': { variant: 'IllustrationHeroSquare', description: '', name: 'tradeImmediately' },
    '597:13': { variant: 'IllustrationHeroSquare', description: '', name: 'rocket' },
    '597:15': { variant: 'IllustrationHeroSquare', description: '', name: 'addPhoneNumber' },
    '597:16': { variant: 'IllustrationHeroSquare', description: '', name: 'japanVerifyId' },
    '597:17': { variant: 'IllustrationHeroSquare', description: '', name: 'documentCertified' },
    '597:18': { variant: 'IllustrationHeroSquare', description: '', name: 'onTheList' },
    '597:19': { variant: 'IllustrationHeroSquare', description: '', name: 'addBankAccount' },
    '597:20': { variant: 'IllustrationHeroSquare', description: '', name: 'addCreditCard' },
    '597:8': { variant: 'IllustrationHeroSquare', description: '', name: 'verifyIdDetails' },
    '597:7': { variant: 'IllustrationHeroSquare', description: '', name: 'idIssue' },
    '597:6': { variant: 'IllustrationHeroSquare', description: '', name: 'verifyInfo' },
    '597:5': { variant: 'IllustrationHeroSquare', description: '', name: 'readyToTrade' },
    '597:4': { variant: 'IllustrationHeroSquare', description: '', name: 'idCard' },
    '597:3': { variant: 'IllustrationHeroSquare', description: '', name: 'phoneNumber' },
    '597:2': { variant: 'IllustrationHeroSquare', description: '', name: 'securityShield' },
    '597:1': { variant: 'IllustrationHeroSquare', description: '', name: 'verifyEmail' },
    '597:41': { variant: 'IllustrationHeroSquare', description: '', name: 'freeBtc' },
    '597:42': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyBankTransactions',
    },
    '597:33': { variant: 'IllustrationHeroSquare', description: '', name: 'transactionLimit' },
    '597:61': { variant: 'IllustrationHeroSquare', description: '', name: 'whyNotBoth' },
    '597:57': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'notificationsAndUpdates',
    },
    '597:62': { variant: 'IllustrationHeroSquare', description: '', name: 'yourContacts' },
    '597:71': { variant: 'IllustrationHeroSquare', description: '', name: 'walletUi' },
    '597:72': { variant: 'IllustrationHeroSquare', description: '', name: 'invite' },
    '597:65': { variant: 'IllustrationHeroSquare', description: '', name: 'recurringReward' },
    '597:66': { variant: 'IllustrationHeroSquare', description: '', name: 'sendCryptoFaster' },
    '597:60': { variant: 'IllustrationHeroSquare', description: '', name: 'insufficientBalance' },
    '597:59': { variant: 'IllustrationHeroSquare', description: '', name: 'coinbaseCardIssue' },
    '597:70': { variant: 'IllustrationHeroSquare', description: '', name: 'coinbaseCardLock' },
    '597:69': { variant: 'IllustrationHeroSquare', description: '', name: 'commerceInvoices' },
    '597:58': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'coinbaseCardSpendCrypto',
    },
    '597:54': { variant: 'IllustrationHeroSquare', description: '', name: 'earnIdVerification' },
    '597:47': { variant: 'IllustrationHeroSquare', description: '', name: 'selectCorrectCrypto' },
    '597:48': { variant: 'IllustrationHeroSquare', description: '', name: 'coinbaseIsDown' },
    '597:43': {
      variant: 'IllustrationHeroSquare',
      description: '',
      name: 'verifyCardTransactions',
    },
    '597:44': { variant: 'IllustrationHeroSquare', description: '', name: 'accountUnderReview' },
    '597:45': { variant: 'IllustrationHeroSquare', description: '', name: 'twoIdVerify' },
    '597:46': { variant: 'IllustrationHeroSquare', description: '', name: 'buyFirstCrypto' },
    '597:55': { variant: 'IllustrationHeroSquare', description: '', name: 'routingAccount' },
    '597:30': { variant: 'IllustrationHeroSquare', description: '', name: 'earnMore' },
    '597:29': { variant: 'IllustrationHeroSquare', description: '', name: 'holdingCrypto' },
    '597:31': { variant: 'IllustrationHeroSquare', description: '', name: 'remittances' },
    '597:9': { variant: 'IllustrationHeroSquare', description: '', name: 'documentSuccess' },
    '597:32': { variant: 'IllustrationHeroSquare', description: '', name: 'docError' },
    '597:12': { variant: 'IllustrationHeroSquare', description: '', name: 'errorWeb500' },
    '597:49': { variant: 'IllustrationHeroSquare', description: '', name: 'errorWeb404' },
    '597:11': { variant: 'IllustrationHeroSquare', description: '', name: 'errorWeb400' },
    '597:10': { variant: 'IllustrationHeroSquare', description: '', name: 'advancedTradingUi' },
    '597:67': { variant: 'IllustrationHeroSquare', description: '', name: 'openEmail' },
    '597:68': { variant: 'IllustrationHeroSquare', description: '', name: 'commerceAccounting' },
    '597:52': { variant: 'IllustrationHeroSquare', description: '', name: 'pending' },
    '597:53': { variant: 'IllustrationHeroSquare', description: '', name: 'coinbaseIsDownMobile' },
    '597:56': { variant: 'IllustrationHeroSquare', description: '', name: 'errorRefresh' },
    '597:51': { variant: 'IllustrationHeroSquare', description: '', name: 'error400' },
    '597:50': { variant: 'IllustrationHeroSquare', description: '', name: 'errorApp500' },
    '600:13524': { variant: 'IllustrationSpotRectangle', description: '', name: 'currency' },
    '600:13525': {
      variant: 'IllustrationSpotRectangle',
      description: '',
      name: 'creditCardExcitement',
    },
    '600:13526': { variant: 'IllustrationSpotRectangle', description: '', name: 'diamond' },
    '600:13527': { variant: 'IllustrationSpotRectangle', description: '', name: 'advancedTrading' },
    '600:13528': { variant: 'IllustrationSpotRectangle', description: '', name: 'trade' },
    '600:13529': { variant: 'IllustrationSpotRectangle', description: '', name: 'giftBoxRewards' },
  },
};
