/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustrationMetadata = {
  numIllustrations: 577,
  heroSquareCount: 106,
  pictogramCount: 121,
  spotRectangleCount: 17,
  spotSquareCount: 51,
  newIllustration: [
    'addMoreCrypto-dark',
    'addMoreCrypto-light',
    'bitcoinAndOtherCrypto-dark',
    'bitcoinAndOtherCrypto-light',
    'cardAnnouncement-dark',
    'cardAnnouncement-light',
    'coinbaseCardPocket-dark',
    'coinbaseCardPocket-light',
    'coinbaseCardSpend-dark',
    'coinbaseCardSpend-light',
    'cryptoApps-dark',
    'cryptoApps-light',
    'cryptoAppsWallet-dark',
    'cryptoAppsWallet-light',
    'directDepositExcitement-dark',
    'directDepositExcitement-light',
    'directDepositPhone-dark',
    'directDepositPhone-light',
    'highFees-dark',
    'highFees-light',
    'noNotificationsGray-dark',
    'noTransactions-dark',
    'noTransactions-light',
    'transferEth-dark',
    'transferEth-light',
    'tru-dark',
    'tru-light',
    'walletLoading-dark',
    'walletLoading-light',
    'walletReconnect-dark',
    'walletReconnect-light',
    'walletReconnectSuccess-dark',
    'walletReconnectSuccess-light',
  ],
  modifiedIllustrations: [],
};
