/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustrationMetadata = {
  numIllustrations: 724,
  spotSquareCount: 52,
  spotRectangleCount: 27,
  heroSquareCount: 141,
  pictogramCount: 141,
  newIllustration: [
    'bigError-dark',
    'bigError-light',
    'camera-dark',
    'camera-dark',
    'camera-light',
    'camera-light',
    'coinbaseOneWaitlist-dark',
    'coinbaseOneWaitlist-light',
    'doneGray-light',
    'guideBullCase-dark',
    'guideBullCase-light',
    'guideCryptoBeginner-dark',
    'guideCryptoBeginner-light',
    'guideFiveThings-dark',
    'guideFiveThings-light',
    'guideNftDefi-dark',
    'guideNftDefi-light',
    'guideStartInvesting-dark',
    'guideStartInvesting-light',
    'mic-dark',
    'mic-light',
    'priceAlerts-dark',
    'priceAlerts-light',
    'reviewInfo-dark',
    'reviewInfo-light',
    'videoRequest-dark',
    'videoRequest-light',
    'videoReview-dark',
    'videoReview-light',
    'videoUpload-dark',
    'videoUpload-light',
    'yourContacts-dark',
  ],
  modifiedIllustrations: ['collectableNfts-dark', 'collectableNfts-light'],
};
