/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const manifestData = {
  png: {},
  svg: {
    '1705:3424': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardPocket',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8277': {
      variant: 'pictogram',
      description: '',
      name: 'orders',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8278': {
      variant: 'pictogram',
      description: '',
      name: 'giftbox',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8279': {
      variant: 'pictogram',
      description: '',
      name: 'worldwide',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8280': {
      variant: 'pictogram',
      description: '',
      name: 'clock',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8281': {
      variant: 'pictogram',
      description: '',
      name: 'predictionMarkets',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8282': {
      variant: 'pictogram',
      description: '',
      name: 'waiting',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8283': {
      variant: 'pictogram',
      description: '',
      name: 'usaProduct',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8284': {
      variant: 'pictogram',
      description: '',
      name: 'bitcoinPizza',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8285': {
      variant: 'pictogram',
      description: '',
      name: 'bitcoinWhitePaper',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8286': {
      variant: 'pictogram',
      description: '',
      name: 'pizza',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8287': {
      variant: 'pictogram',
      description: '',
      name: 'contactInfo',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8288': {
      variant: 'pictogram',
      description: '',
      name: 'addressBook',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8289': {
      variant: 'pictogram',
      description: '',
      name: 'startToday',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8290': {
      variant: 'pictogram',
      description: '',
      name: 'transistor',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8291': {
      variant: 'pictogram',
      description: '',
      name: 'noAnnualFee',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8292': {
      variant: 'pictogram',
      description: '',
      name: 'applyForHigherLimits',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8293': {
      variant: 'pictogram',
      description: '',
      name: 'noWiFi',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8294': {
      variant: 'pictogram',
      description: '',
      name: 'reviewAndAdd',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8295': {
      variant: 'pictogram',
      description: '',
      name: 'fast',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8296': {
      variant: 'pictogram',
      description: '',
      name: 'tryAgainLater',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8297': {
      variant: 'pictogram',
      description: '',
      name: 'typeScript',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8298': {
      variant: 'pictogram',
      description: '',
      name: 'multiPlatform',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8299': {
      variant: 'pictogram',
      description: '',
      name: 'takeQuiz',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8300': {
      variant: 'pictogram',
      description: '',
      name: 'chat',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8301': {
      variant: 'pictogram',
      description: '',
      name: 'email',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8302': {
      variant: 'pictogram',
      description: '',
      name: 'recurringPurchases',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8303': {
      variant: 'pictogram',
      description: '',
      name: 'delegate',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8304': {
      variant: 'pictogram',
      description: '',
      name: 'waitingForConsensus',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8305': {
      variant: 'pictogram',
      description: '',
      name: 'enableVoting',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8306': {
      variant: 'pictogram',
      description: '',
      name: 'formDownload',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8307': {
      variant: 'pictogram',
      description: '',
      name: 'settings',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8308': {
      variant: 'pictogram',
      description: '',
      name: 'priceTracking',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8309': {
      variant: 'pictogram',
      description: '',
      name: 'authenticatorProgress',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8310': {
      variant: 'pictogram',
      description: '',
      name: 'stateID',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8311': {
      variant: 'pictogram',
      description: '',
      name: 'safe',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8312': {
      variant: 'pictogram',
      description: '',
      name: 'smsAuthenticate',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8313': {
      variant: 'pictogram',
      description: '',
      name: 'googleAuthenticator',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8314': {
      variant: 'pictogram',
      description: '',
      name: 'authenticatorAlt',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8315': {
      variant: 'pictogram',
      description: '',
      name: 'authenticator',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8316': {
      variant: 'pictogram',
      description: '',
      name: 'idVerification',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8317': {
      variant: 'pictogram',
      description: '',
      name: 'key',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8318': {
      variant: 'pictogram',
      description: '',
      name: 'ubiKey',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8319': {
      variant: 'pictogram',
      description: '',
      name: 'authenticationApp',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8320': {
      variant: 'pictogram',
      description: '',
      name: 'shield',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8321': {
      variant: 'pictogram',
      description: '',
      name: 'lock',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8322': {
      variant: 'pictogram',
      description: '',
      name: 'security',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8323': {
      variant: 'pictogram',
      description: '',
      name: 'institutions',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8324': {
      variant: 'pictogram',
      description: '',
      name: 'moneySwift',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8325': {
      variant: 'pictogram',
      description: '',
      name: 'transferSend',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8326': {
      variant: 'pictogram',
      description: '',
      name: 'higherLimits',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8327': {
      variant: 'pictogram',
      description: '',
      name: 'increaseLimits',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8328': {
      variant: 'pictogram',
      description: '',
      name: 'fiat',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8329': {
      variant: 'pictogram',
      description: '',
      name: 'walletExchange',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8330': {
      variant: 'pictogram',
      description: '',
      name: 'addWallet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8331': {
      variant: 'pictogram',
      description: '',
      name: 'walletDeposit',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8332': {
      variant: 'pictogram',
      description: '',
      name: 'wallet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8333': {
      variant: 'pictogram',
      description: '',
      name: 'cryptoCard',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8334': {
      variant: 'pictogram',
      description: '',
      name: 'tokenBaskets',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8335': {
      variant: 'pictogram',
      description: '',
      name: 'addToWatchlist',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8336': {
      variant: 'pictogram',
      description: '',
      name: 'bundle',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8337': {
      variant: 'pictogram',
      description: '',
      name: 'trading',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8338': {
      variant: 'pictogram',
      description: '',
      name: 'multipleAssets',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8339': {
      variant: 'pictogram',
      description: '',
      name: 'moreThanBitcoin',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8340': {
      variant: 'pictogram',
      description: '',
      name: 'lowFees',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8341': {
      variant: 'pictogram',
      description: '',
      name: 'listingFees',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8342': {
      variant: 'pictogram',
      description: '',
      name: 'earnCoins',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8343': {
      variant: 'pictogram',
      description: '',
      name: 'partialCoins',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8344': {
      variant: 'pictogram',
      description: '',
      name: 'paypal',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8345': {
      variant: 'pictogram',
      description: '',
      name: 'moneyEarn',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8346': {
      variant: 'pictogram',
      description: '',
      name: 'creditCard',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8347': {
      variant: 'pictogram',
      description: '',
      name: 'addCard',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8348': {
      variant: 'pictogram',
      description: '',
      name: 'cardDeclined',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8349': {
      variant: 'pictogram',
      description: '',
      name: 'cardBlocked',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8350': {
      variant: 'pictogram',
      description: '',
      name: 'addPayment',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8351': {
      variant: 'pictogram',
      description: '',
      name: 'laptopCharts',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8352': {
      variant: 'pictogram',
      description: '',
      name: 'mobileCharts',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8353': {
      variant: 'pictogram',
      description: '',
      name: 'addPhone',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8354': {
      variant: 'pictogram',
      description: '',
      name: 'browser',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8355': {
      variant: 'pictogram',
      description: '',
      name: 'internet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8356': {
      variant: 'pictogram',
      description: '',
      name: 'laptopVideo',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8357': {
      variant: 'pictogram',
      description: '',
      name: 'mobileNotifcation',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8358': {
      variant: 'pictogram',
      description: '',
      name: 'browserTransaction',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8359': {
      variant: 'pictogram',
      description: '',
      name: 'laptop',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8360': {
      variant: 'pictogram',
      description: '',
      name: 'successPhone',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8361': {
      variant: 'pictogram',
      description: '',
      name: 'phone',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8362': {
      variant: 'pictogram',
      description: '',
      name: '2fa',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8363': {
      variant: 'pictogram',
      description: '',
      name: 'calendar',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8364': {
      variant: 'pictogram',
      description: '',
      name: 'envelope',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8365': {
      variant: 'pictogram',
      description: '',
      name: 'pieChart',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8366': {
      variant: 'pictogram',
      description: '',
      name: 'strongInfo',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8367': {
      variant: 'pictogram',
      description: '',
      name: 'gem',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8368': {
      variant: 'pictogram',
      description: '',
      name: 'chart',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8369': {
      variant: 'pictogram',
      description: '',
      name: 'barChart',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8370': {
      variant: 'pictogram',
      description: '',
      name: 'learn',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8371': {
      variant: 'pictogram',
      description: '',
      name: 'explore',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8372': {
      variant: 'pictogram',
      description: '',
      name: 'target',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8373': {
      variant: 'pictogram',
      description: '',
      name: 'easyToUse',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8374': {
      variant: 'pictogram',
      description: '',
      name: 'trusted',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8375': {
      variant: 'pictogram',
      description: '',
      name: 'checkmark',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8376': {
      variant: 'pictogram',
      description: '',
      name: 'newUserChecklistCompleteAccount',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8377': {
      variant: 'pictogram',
      description: '',
      name: 'newUserChecklistBuyCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8378': {
      variant: 'pictogram',
      description: '',
      name: 'newUserChecklistVerifyId',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8379': {
      variant: 'pictogram',
      description: '',
      name: 'add',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8515': {
      variant: 'pictogram',
      description: '',
      name: 'checkmark',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8514': {
      variant: 'pictogram',
      description: '',
      name: 'settled',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8513': {
      variant: 'pictogram',
      description: '',
      name: 'error',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8512': {
      variant: 'pictogram',
      description: '',
      name: 'done',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8511': {
      variant: 'pictogram',
      description: '',
      name: 'warning',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8507': {
      variant: 'pictogram',
      description: '',
      name: 'commerceInvoice',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8506': {
      variant: 'pictogram',
      description: '',
      name: 'commerceCheckout',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8505': {
      variant: 'pictogram',
      description: '',
      name: 'commerceNoPaymentsGray',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8504': {
      variant: 'pictogram',
      description: '',
      name: 'advancedTradingDesktop',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8510': {
      variant: 'pictogram',
      description: '',
      name: 'alerts',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8508': {
      variant: 'pictogram',
      description: '',
      name: 'strongWarning',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8502': {
      variant: 'pictogram',
      description: '',
      name: 'bundleGray',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8503': {
      variant: 'pictogram',
      description: '',
      name: 'exploreGray',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2072:8471': {
      variant: 'pictogram',
      description: '',
      name: 'bundleGray',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8497': {
      variant: 'pictogram',
      description: '',
      name: 'orders',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8494': {
      variant: 'pictogram',
      description: '',
      name: 'giftbox',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8498': {
      variant: 'pictogram',
      description: '',
      name: 'worldwide',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8501': {
      variant: 'pictogram',
      description: '',
      name: 'clock',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8461': {
      variant: 'pictogram',
      description: '',
      name: 'predictionMarkets',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8462': {
      variant: 'pictogram',
      description: '',
      name: 'waiting',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8463': {
      variant: 'pictogram',
      description: '',
      name: 'usaProduct',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8464': {
      variant: 'pictogram',
      description: '',
      name: 'bitcoinPizza',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8465': {
      variant: 'pictogram',
      description: '',
      name: 'bitcoinWhitePaper',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8466': {
      variant: 'pictogram',
      description: '',
      name: 'pizza',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8467': {
      variant: 'pictogram',
      description: '',
      name: 'contactInfo',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8468': {
      variant: 'pictogram',
      description: '',
      name: 'addressBook',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8469': {
      variant: 'pictogram',
      description: '',
      name: 'startToday',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8490': {
      variant: 'pictogram',
      description: '',
      name: 'transistor',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8489': {
      variant: 'pictogram',
      description: '',
      name: 'noAnnualFee',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8493': {
      variant: 'pictogram',
      description: '',
      name: 'applyForHigherLimits',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8470': {
      variant: 'pictogram',
      description: '',
      name: 'noWiFi',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8473': {
      variant: 'pictogram',
      description: '',
      name: 'reviewAndAdd',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8474': {
      variant: 'pictogram',
      description: '',
      name: 'fast',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8477': {
      variant: 'pictogram',
      description: '',
      name: 'tryAgainLater',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8478': {
      variant: 'pictogram',
      description: '',
      name: 'typeScript',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8483': {
      variant: 'pictogram',
      description: '',
      name: 'multiPlatform',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8482': {
      variant: 'pictogram',
      description: '',
      name: 'takeQuiz',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8484': {
      variant: 'pictogram',
      description: '',
      name: 'chat',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8487': {
      variant: 'pictogram',
      description: '',
      name: 'email',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8488': {
      variant: 'pictogram',
      description: '',
      name: 'recurringPurchases',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8491': {
      variant: 'pictogram',
      description: '',
      name: 'delegate',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8492': {
      variant: 'pictogram',
      description: '',
      name: 'waitingForConsensus',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8495': {
      variant: 'pictogram',
      description: '',
      name: 'enableVoting',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8496': {
      variant: 'pictogram',
      description: '',
      name: 'formDownload',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8499': {
      variant: 'pictogram',
      description: '',
      name: 'settings',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8500': {
      variant: 'pictogram',
      description: '',
      name: 'priceTracking',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8405': {
      variant: 'pictogram',
      description: '',
      name: 'authenticatorProgress',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8409': {
      variant: 'pictogram',
      description: '',
      name: 'stateId',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8410': {
      variant: 'pictogram',
      description: '',
      name: 'safe',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8411': {
      variant: 'pictogram',
      description: '',
      name: 'smsAuthenticate',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8412': {
      variant: 'pictogram',
      description: '',
      name: 'googleAuthenticator',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8413': {
      variant: 'pictogram',
      description: '',
      name: 'authenticatorAlt',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8414': {
      variant: 'pictogram',
      description: '',
      name: 'authenticator',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8415': {
      variant: 'pictogram',
      description: '',
      name: 'idVerification',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8416': {
      variant: 'pictogram',
      description: '',
      name: 'key',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8417': {
      variant: 'pictogram',
      description: '',
      name: 'ubiKey',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8429': {
      variant: 'pictogram',
      description: '',
      name: 'authenticationApp',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8428': {
      variant: 'pictogram',
      description: '',
      name: 'shield',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8427': {
      variant: 'pictogram',
      description: '',
      name: 'lock',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8426': {
      variant: 'pictogram',
      description: '',
      name: 'security',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8445': {
      variant: 'pictogram',
      description: '',
      name: 'institutions',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8460': {
      variant: 'pictogram',
      description: '',
      name: 'moneySwift',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8407': {
      variant: 'pictogram',
      description: '',
      name: 'transferSend',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8406': {
      variant: 'pictogram',
      description: '',
      name: 'higherLimits',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8459': {
      variant: 'pictogram',
      description: '',
      name: 'increaseLimits',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8458': {
      variant: 'pictogram',
      description: '',
      name: 'fiat',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8457': {
      variant: 'pictogram',
      description: '',
      name: 'walletExchange',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8456': {
      variant: 'pictogram',
      description: '',
      name: 'addWallet',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8455': {
      variant: 'pictogram',
      description: '',
      name: 'walletDeposit',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8454': {
      variant: 'pictogram',
      description: '',
      name: 'wallet',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8408': {
      variant: 'pictogram',
      description: '',
      name: 'cryptoCard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8453': {
      variant: 'pictogram',
      description: '',
      name: 'tokenBaskets',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8452': {
      variant: 'pictogram',
      description: '',
      name: 'addToWatchlist',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8451': {
      variant: 'pictogram',
      description: '',
      name: 'bundle',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8450': {
      variant: 'pictogram',
      description: '',
      name: 'trading',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8449': {
      variant: 'pictogram',
      description: '',
      name: 'multipleAssets',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8448': {
      variant: 'pictogram',
      description: '',
      name: 'moreThanBitcoin',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8447': {
      variant: 'pictogram',
      description: '',
      name: 'lowFees',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8446': {
      variant: 'pictogram',
      description: '',
      name: 'listingFees',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8444': {
      variant: 'pictogram',
      description: '',
      name: 'earnCoins',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8443': {
      variant: 'pictogram',
      description: '',
      name: 'partialCoins',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8442': {
      variant: 'pictogram',
      description: '',
      name: 'paypal',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8441': {
      variant: 'pictogram',
      description: '',
      name: 'moneyEarn',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8440': {
      variant: 'pictogram',
      description: '',
      name: 'creditCard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8437': {
      variant: 'pictogram',
      description: '',
      name: 'addCard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8438': {
      variant: 'pictogram',
      description: '',
      name: 'cardDeclined',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8439': {
      variant: 'pictogram',
      description: '',
      name: 'cardBlocked',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8436': {
      variant: 'pictogram',
      description: '',
      name: 'addPayment',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8424': {
      variant: 'pictogram',
      description: '',
      name: 'laptopCharts',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8423': {
      variant: 'pictogram',
      description: '',
      name: 'mobileCharts',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8422': {
      variant: 'pictogram',
      description: '',
      name: 'addPhone',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8421': {
      variant: 'pictogram',
      description: '',
      name: 'browser',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8420': {
      variant: 'pictogram',
      description: '',
      name: 'internet',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8425': {
      variant: 'pictogram',
      description: '',
      name: 'laptopVideo',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8430': {
      variant: 'pictogram',
      description: '',
      name: 'mobileNotifcation',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8431': {
      variant: 'pictogram',
      description: '',
      name: 'browserTransaction',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8432': {
      variant: 'pictogram',
      description: '',
      name: 'laptop',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8433': {
      variant: 'pictogram',
      description: '',
      name: 'successPhone',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8434': {
      variant: 'pictogram',
      description: '',
      name: 'phone',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8435': {
      variant: 'pictogram',
      description: '',
      name: '2fa',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8394': {
      variant: 'pictogram',
      description: '',
      name: 'calendar',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8391': {
      variant: 'pictogram',
      description: '',
      name: 'envelope',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8390': {
      variant: 'pictogram',
      description: '',
      name: 'pieChart',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8389': {
      variant: 'pictogram',
      description: '',
      name: 'warning',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8404': {
      variant: 'pictogram',
      description: '',
      name: 'strongInfo',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8395': {
      variant: 'pictogram',
      description: '',
      name: 'gem',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8392': {
      variant: 'pictogram',
      description: '',
      name: 'chart',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8403': {
      variant: 'pictogram',
      description: '',
      name: 'strongWarning',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8397': {
      variant: 'pictogram',
      description: '',
      name: 'barChart',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8398': {
      variant: 'pictogram',
      description: '',
      name: 'learn',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8399': {
      variant: 'pictogram',
      description: '',
      name: 'explore',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8400': {
      variant: 'pictogram',
      description: '',
      name: 'target',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8401': {
      variant: 'pictogram',
      description: '',
      name: 'easyToUse',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8402': {
      variant: 'pictogram',
      description: '',
      name: 'trusted',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8383': {
      variant: 'pictogram',
      description: '',
      name: 'checkmark',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8384': {
      variant: 'pictogram',
      description: '',
      name: 'add',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8388': {
      variant: 'pictogram',
      description: '',
      name: 'done',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8385': {
      variant: 'pictogram',
      description: '',
      name: 'settled',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8386': {
      variant: 'pictogram',
      description: '',
      name: 'error',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8396': {
      variant: 'pictogram',
      description: '',
      name: 'notifications',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8393': {
      variant: 'pictogram',
      description: '',
      name: 'alerts',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8485': {
      variant: 'pictogram',
      description: '',
      name: 'newUserChecklistCompleteAccount',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8486': {
      variant: 'pictogram',
      description: '',
      name: 'newUserChecklistBuyCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8481': {
      variant: 'pictogram',
      description: '',
      name: 'newUserChecklistVerifyId',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8480': {
      variant: 'pictogram',
      description: '',
      name: 'commerceInvoice',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8476': {
      variant: 'pictogram',
      description: '',
      name: 'commerceNoPaymentsGray',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8479': {
      variant: 'pictogram',
      description: '',
      name: 'commerceCheckout',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8475': {
      variant: 'pictogram',
      description: '',
      name: 'advancedTradingDesktop',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8472': {
      variant: 'pictogram',
      description: '',
      name: 'exploreGray',
      spectrum: 'light',
      versionNum: 0,
    },
    '2072:8509': {
      variant: 'pictogram',
      description: '',
      name: 'notifications',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9128': {
      variant: 'heroSquare',
      description: '',
      name: 'idBack',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9129': {
      variant: 'heroSquare',
      description: '',
      name: 'coinsInWallet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9131': {
      variant: 'heroSquare',
      description: '',
      name: 'myNameIsSatoshi',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9132': {
      variant: 'heroSquare',
      description: '',
      name: 'limitOrders',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9133': {
      variant: 'heroSquare',
      description: '',
      name: 'payUpFront',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9134': {
      variant: 'heroSquare',
      description: '',
      name: 'cardAndPhone',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9135': {
      variant: 'heroSquare',
      description: '',
      name: 'automaticPayments',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9136': {
      variant: 'heroSquare',
      description: '',
      name: 'earnProgress',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9137': {
      variant: 'heroSquare',
      description: '',
      name: 'earnSuccess',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9138': {
      variant: 'heroSquare',
      description: '',
      name: 'emailNotification',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9139': {
      variant: 'heroSquare',
      description: '',
      name: 'idFront',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9140': {
      variant: 'heroSquare',
      description: '',
      name: 'idAngles',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9165': {
      variant: 'heroSquare',
      description: '',
      name: 'sendToUsername',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9164': {
      variant: 'heroSquare',
      description: '',
      name: 'idVerificationSecure',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9157': {
      variant: 'heroSquare',
      description: '',
      name: 'tradeImmediately',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9156': {
      variant: 'heroSquare',
      description: '',
      name: 'rocket',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9158': {
      variant: 'heroSquare',
      description: '',
      name: 'addPhoneNumber',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9159': {
      variant: 'heroSquare',
      description: '',
      name: 'japanVerifyId',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9160': {
      variant: 'heroSquare',
      description: '',
      name: 'documentCertified',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9161': {
      variant: 'heroSquare',
      description: '',
      name: 'onTheList',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9162': {
      variant: 'heroSquare',
      description: '',
      name: 'addBankAccount',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9163': {
      variant: 'heroSquare',
      description: '',
      name: 'addCreditCard',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9151': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyIdDetails',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9150': {
      variant: 'heroSquare',
      description: '',
      name: 'idIssue',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9147': {
      variant: 'heroSquare',
      description: '',
      name: 'readyToTrade',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9146': {
      variant: 'heroSquare',
      description: '',
      name: 'idCard',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9145': {
      variant: 'heroSquare',
      description: '',
      name: 'phoneNumber',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9144': {
      variant: 'heroSquare',
      description: '',
      name: 'securityShield',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9193': {
      variant: 'heroSquare',
      description: '',
      name: 'receivedCard',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9192': {
      variant: 'heroSquare',
      description: '',
      name: 'notificationsAlt',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9201': {
      variant: 'heroSquare',
      description: '',
      name: 'freeBtc',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9200': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyBankTransactions',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9170': {
      variant: 'heroSquare',
      description: '',
      name: 'transactionLimit',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9199': {
      variant: 'heroSquare',
      description: '',
      name: 'processing',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9183': {
      variant: 'heroSquare',
      description: '',
      name: 'whyNotBoth',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9179': {
      variant: 'heroSquare',
      description: '',
      name: 'notificationsAndUpdates',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9184': {
      variant: 'heroSquare',
      description: '',
      name: 'yourContacts',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9202': {
      variant: 'heroSquare',
      description: '',
      name: 'success',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9203': {
      variant: 'heroSquare',
      description: '',
      name: 'walletUi',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9197': {
      variant: 'heroSquare',
      description: '',
      name: 'invite',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9198': {
      variant: 'heroSquare',
      description: '',
      name: 'recurringReward',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9189': {
      variant: 'heroSquare',
      description: '',
      name: 'sendCryptoFaster',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9190': {
      variant: 'heroSquare',
      description: '',
      name: 'insufficientBalance',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9191': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardIssue',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9204': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardLock',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9196': {
      variant: 'heroSquare',
      description: '',
      name: 'commerceInvoices',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9178': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardSpendCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9175': {
      variant: 'heroSquare',
      description: '',
      name: 'earnIdVerification',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9188': {
      variant: 'heroSquare',
      description: '',
      name: 'bigWarning',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9185': {
      variant: 'heroSquare',
      description: '',
      name: 'polling',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9180': {
      variant: 'heroSquare',
      description: '',
      name: 'selectCorrectCrypto',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9209': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseIsDown',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9187': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyCardTransactions',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9186': {
      variant: 'heroSquare',
      description: '',
      name: 'accountUnderReview',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9182': {
      variant: 'heroSquare',
      description: '',
      name: 'twoIdVerify',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9181': {
      variant: 'heroSquare',
      description: '',
      name: 'buyFirstCrypto',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9176': {
      variant: 'heroSquare',
      description: '',
      name: 'routingAccount',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9167': {
      variant: 'heroSquare',
      description: '',
      name: 'earnMore',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9166': {
      variant: 'heroSquare',
      description: '',
      name: 'holdingCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9168': {
      variant: 'heroSquare',
      description: '',
      name: 'remittances',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9169': {
      variant: 'heroSquare',
      description: '',
      name: 'docError',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9155': {
      variant: 'heroSquare',
      description: '',
      name: 'errorWeb500',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9208': {
      variant: 'heroSquare',
      description: '',
      name: 'errorWeb404',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9154': {
      variant: 'heroSquare',
      description: '',
      name: 'errorWeb400',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9153': {
      variant: 'heroSquare',
      description: '',
      name: 'advancedTradingUi',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9194': {
      variant: 'heroSquare',
      description: '',
      name: 'openEmail',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9195': {
      variant: 'heroSquare',
      description: '',
      name: 'commerceAccounting',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9173': {
      variant: 'heroSquare',
      description: '',
      name: 'pending',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9174': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseIsDownMobile',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9177': {
      variant: 'heroSquare',
      description: '',
      name: 'errorRefresh',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9172': {
      variant: 'heroSquare',
      description: '',
      name: 'error400',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9171': {
      variant: 'heroSquare',
      description: '',
      name: 'errorApp500',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9152': {
      variant: 'heroSquare',
      description: '',
      name: 'documentSuccess',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9148': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyInfo',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:9207': {
      variant: 'heroSquare',
      description: '',
      name: 'earnInterest',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9206': {
      variant: 'heroSquare',
      description: '',
      name: 'contactsListWarning',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9205': {
      variant: 'heroSquare',
      description: '',
      name: 'walletNotifications',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:9143': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyEmail',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:10189': {
      variant: 'spotRectangle',
      description: '',
      name: 'currency',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:10190': {
      variant: 'spotRectangle',
      description: '',
      name: 'creditCardExcitement',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:10191': {
      variant: 'spotRectangle',
      description: '',
      name: 'diamond',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:10193': {
      variant: 'spotRectangle',
      description: '',
      name: 'trade',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2074:10194': {
      variant: 'spotRectangle',
      description: '',
      name: 'giftBoxRewards',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2074:10192': {
      variant: 'spotRectangle',
      description: '',
      name: 'ratDashboard',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2094:545': {
      variant: 'heroSquare',
      description: '',
      name: 'bigBtc',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2094:30294': {
      variant: 'heroSquare',
      description: '',
      name: 'idBack',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30295': {
      variant: 'heroSquare',
      description: '',
      name: 'coinsInWallet',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30296': {
      variant: 'heroSquare',
      description: '',
      name: 'bigBtc',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30297': {
      variant: 'heroSquare',
      description: '',
      name: 'myNameIsSatoshi',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30309': {
      variant: 'heroSquare',
      description: '',
      name: 'limitOrders',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30308': {
      variant: 'heroSquare',
      description: '',
      name: 'payUpFront',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30307': {
      variant: 'heroSquare',
      description: '',
      name: 'cardAndPhone',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30306': {
      variant: 'heroSquare',
      description: '',
      name: 'automaticPayments',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30305': {
      variant: 'heroSquare',
      description: '',
      name: 'earnProgress',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30304': {
      variant: 'heroSquare',
      description: '',
      name: 'earnSuccess',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30303': {
      variant: 'heroSquare',
      description: '',
      name: 'emailNotification',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30293': {
      variant: 'heroSquare',
      description: '',
      name: 'idFront',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30292': {
      variant: 'heroSquare',
      description: '',
      name: 'idAngles',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30291': {
      variant: 'heroSquare',
      description: '',
      name: 'sendToUsername',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30290': {
      variant: 'heroSquare',
      description: '',
      name: 'idVerificationSecure',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30283': {
      variant: 'heroSquare',
      description: '',
      name: 'tradeImmediately',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30282': {
      variant: 'heroSquare',
      description: '',
      name: 'rocket',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30284': {
      variant: 'heroSquare',
      description: '',
      name: 'addPhoneNumber',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30285': {
      variant: 'heroSquare',
      description: '',
      name: 'japanVerifyId',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30286': {
      variant: 'heroSquare',
      description: '',
      name: 'documentCertified',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30287': {
      variant: 'heroSquare',
      description: '',
      name: 'onTheList',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30288': {
      variant: 'heroSquare',
      description: '',
      name: 'addBankAccount',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30289': {
      variant: 'heroSquare',
      description: '',
      name: 'addCreditCard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30277': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyIdDetails',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30276': {
      variant: 'heroSquare',
      description: '',
      name: 'idIssue',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30275': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyInfo',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30336': {
      variant: 'heroSquare',
      description: '',
      name: 'appTrackingTransparency',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30274': {
      variant: 'heroSquare',
      description: '',
      name: 'readyToTrade',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30273': {
      variant: 'heroSquare',
      description: '',
      name: 'idCard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30272': {
      variant: 'heroSquare',
      description: '',
      name: 'phoneNumber',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30271': {
      variant: 'heroSquare',
      description: '',
      name: 'securityShield',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30270': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyEmail',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30310': {
      variant: 'heroSquare',
      description: '',
      name: 'freeBtc',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30311': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyBankTransactions',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30302': {
      variant: 'heroSquare',
      description: '',
      name: 'transactionLimit',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30347': {
      variant: 'heroSquare',
      description: '',
      name: 'processing',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30333': {
      variant: 'heroSquare',
      description: '',
      name: 'whyNotBoth',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30331': {
      variant: 'heroSquare',
      description: '',
      name: 'notificationsAndUpdates',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30332': {
      variant: 'heroSquare',
      description: '',
      name: 'yourContacts',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30348': {
      variant: 'heroSquare',
      description: '',
      name: 'success',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30349': {
      variant: 'heroSquare',
      description: '',
      name: 'walletUi',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30346': {
      variant: 'heroSquare',
      description: '',
      name: 'invite',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30345': {
      variant: 'heroSquare',
      description: '',
      name: 'recurringReward',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30339': {
      variant: 'heroSquare',
      description: '',
      name: 'sendCryptoFaster',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30334': {
      variant: 'heroSquare',
      description: '',
      name: 'insufficientBalance',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30335': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardIssue',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30350': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardLock',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30351': {
      variant: 'heroSquare',
      description: '',
      name: 'commerceInvoices',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30330': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardSpendCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30321': {
      variant: 'heroSquare',
      description: '',
      name: 'earnIdVerification',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30341': {
      variant: 'heroSquare',
      description: '',
      name: 'bigWarning',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30340': {
      variant: 'heroSquare',
      description: '',
      name: 'polling',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30316': {
      variant: 'heroSquare',
      description: '',
      name: 'selectCorrectCrypto',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30317': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseIsDown',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30312': {
      variant: 'heroSquare',
      description: '',
      name: 'verifyCardTransactions',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30313': {
      variant: 'heroSquare',
      description: '',
      name: 'accountUnderReview',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30314': {
      variant: 'heroSquare',
      description: '',
      name: 'twoIdVerify',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30315': {
      variant: 'heroSquare',
      description: '',
      name: 'buyFirstCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30322': {
      variant: 'heroSquare',
      description: '',
      name: 'routingAccount',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30299': {
      variant: 'heroSquare',
      description: '',
      name: 'earnMore',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30298': {
      variant: 'heroSquare',
      description: '',
      name: 'holdingCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30300': {
      variant: 'heroSquare',
      description: '',
      name: 'remittances',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30278': {
      variant: 'heroSquare',
      description: '',
      name: 'documentSuccess',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30301': {
      variant: 'heroSquare',
      description: '',
      name: 'docError',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30281': {
      variant: 'heroSquare',
      description: '',
      name: 'errorWeb500',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30318': {
      variant: 'heroSquare',
      description: '',
      name: 'errorWeb404',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30280': {
      variant: 'heroSquare',
      description: '',
      name: 'errorWeb400',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30279': {
      variant: 'heroSquare',
      description: '',
      name: 'advancedTradingUi',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30338': {
      variant: 'heroSquare',
      description: '',
      name: 'openEmail',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30342': {
      variant: 'heroSquare',
      description: '',
      name: 'commerceAccounting',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30323': {
      variant: 'heroSquare',
      description: '',
      name: 'pending',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30324': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseIsDownMobile',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30325': {
      variant: 'heroSquare',
      description: '',
      name: 'errorRefresh',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30320': {
      variant: 'heroSquare',
      description: '',
      name: 'error400',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30319': {
      variant: 'heroSquare',
      description: '',
      name: 'errorApp500',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30337': {
      variant: 'heroSquare',
      description: '',
      name: 'notificationsAlt',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30329': {
      variant: 'heroSquare',
      description: '',
      name: 'earnInterest',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30326': {
      variant: 'heroSquare',
      description: '',
      name: 'contactsListWarning',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30327': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardPocket',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30353': {
      variant: 'heroSquare',
      description: '',
      name: 'accessToAdvancedCharts',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30352': {
      variant: 'heroSquare',
      description: '',
      name: 'focusLimitOrders',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30344': {
      variant: 'heroSquare',
      description: '',
      name: 'switchAdvancedToSimpleTrading',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30328': {
      variant: 'heroSquare',
      description: '',
      name: 'walletNotifications',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30343': {
      variant: 'heroSquare',
      description: '',
      name: 'advancedTrading',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30258': {
      variant: 'spotRectangle',
      description: '',
      name: 'currency',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30267': {
      variant: 'spotRectangle',
      description: '',
      name: 'cardWaitlist',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30259': {
      variant: 'spotRectangle',
      description: '',
      name: 'creditCardExcitement',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30260': {
      variant: 'spotRectangle',
      description: '',
      name: 'diamond',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30261': {
      variant: 'spotRectangle',
      description: '',
      name: 'ratDashboard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30262': {
      variant: 'spotRectangle',
      description: '',
      name: 'trade',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30263': {
      variant: 'spotRectangle',
      description: '',
      name: 'giftBoxRewards',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30268': {
      variant: 'spotRectangle',
      description: '',
      name: 'linkCoinbaseWallet',
      spectrum: 'light',
      versionNum: 1,
    },
    '2094:30266': {
      variant: 'spotRectangle',
      description: '',
      name: 'accessToAdvancedChartsAlt',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30265': {
      variant: 'spotRectangle',
      description: '',
      name: 'focusLimitOrdersAlt',
      spectrum: 'light',
      versionNum: 0,
    },
    '2094:30264': {
      variant: 'spotRectangle',
      description: '',
      name: 'switchAdvancedToSimpleTradingAlt',
      spectrum: 'light',
      versionNum: 0,
    },
    '2126:322': {
      variant: 'pictogram',
      description: '',
      name: 'pendingApprovalGray',
      spectrum: 'light',
      versionNum: 0,
    },
    '2126:323': {
      variant: 'pictogram',
      description: '',
      name: 'noNotificationsGray',
      spectrum: 'light',
      versionNum: 0,
    },
    '2126:320': {
      variant: 'pictogram',
      description: '',
      name: 'pendingApprovalGray',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2126:321': {
      variant: 'pictogram',
      description: '',
      name: 'noNotificationsGray',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2128:230': {
      variant: 'heroSquare',
      description: '',
      name: 'downloadCoinbaseWallet',
      spectrum: 'light',
      versionNum: 0,
    },
    '2128:373': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseWalletToTrade',
      spectrum: 'light',
      versionNum: 0,
    },
    '2128:466': {
      variant: 'heroSquare',
      description: '',
      name: 'downloadCoinbaseWallet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2128:610': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseWalletToTrade',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20629': {
      variant: 'spotSquare',
      description: '',
      name: 'moneyRewards',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20628': {
      variant: 'spotSquare',
      description: '',
      name: 'interestForYou',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20627': {
      variant: 'spotSquare',
      description: '',
      name: 'giftBoxCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20626': {
      variant: 'spotSquare',
      description: '',
      name: 'starToken',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20631': {
      variant: 'spotSquare',
      description: '',
      name: 'addMultipleCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20630': {
      variant: 'spotSquare',
      description: '',
      name: 'phoneNotifications',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20632': {
      variant: 'spotSquare',
      description: '',
      name: 'darkModeIntroduction',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20633': {
      variant: 'spotSquare',
      description: '',
      name: 'cardShipped',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20642': {
      variant: 'spotSquare',
      description: '',
      name: 'refreshMobileApp',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20671': {
      variant: 'spotSquare',
      description: '',
      name: 'refreshMobileApp',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20645': {
      variant: 'spotSquare',
      description: '',
      name: 'sparkleToken',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20665': {
      variant: 'spotSquare',
      description: '',
      name: 'sparkleToken',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2266:20640': {
      variant: 'spotSquare',
      description: '',
      name: 'saveTheDate',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20655': {
      variant: 'spotSquare',
      description: '',
      name: 'saveTheDate',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20639': {
      variant: 'spotSquare',
      description: '',
      name: 'assetRefresh',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20635': {
      variant: 'spotSquare',
      description: '',
      name: 'cosmosStaking',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20656': {
      variant: 'spotSquare',
      description: '',
      name: 'assetRefresh',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20660': {
      variant: 'spotSquare',
      description: '',
      name: 'cosmosStaking',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20638': {
      variant: 'spotSquare',
      description: '',
      name: 'cardAnnouncement',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20636': {
      variant: 'spotSquare',
      description: '',
      name: 'daiRewards',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20644': {
      variant: 'spotSquare',
      description: '',
      name: 'assetForward',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20637': {
      variant: 'spotSquare',
      description: '',
      name: 'tezosStakingRewards',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20657': {
      variant: 'spotSquare',
      description: '',
      name: 'cardAnnouncement',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20659': {
      variant: 'spotSquare',
      description: '',
      name: 'daiRewards',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2266:20669': {
      variant: 'spotSquare',
      description: '',
      name: 'assetForward',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20658': {
      variant: 'spotSquare',
      description: '',
      name: 'tezosStakingRewards',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20643': {
      variant: 'spotSquare',
      description: '',
      name: 'yieldCenter',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20670': {
      variant: 'spotSquare',
      description: '',
      name: 'yieldCenter',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20646': {
      variant: 'spotSquare',
      description: '',
      name: 'coinbaseCardSparkle',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20664': {
      variant: 'spotSquare',
      description: '',
      name: 'coinbaseCardSparkle',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2266:20647': {
      variant: 'spotSquare',
      description: '',
      name: 'borrowLimitsAddressed',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20663': {
      variant: 'spotSquare',
      description: '',
      name: 'borrowLimitsAddressed',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20648': {
      variant: 'spotSquare',
      description: '',
      name: 'algoStaking',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20662': {
      variant: 'spotSquare',
      description: '',
      name: 'algoStaking',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20641': {
      variant: 'spotSquare',
      description: '',
      name: 'ethereumStaking',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20654': {
      variant: 'spotSquare',
      description: '',
      name: 'ethereumStaking',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20634': {
      variant: 'spotSquare',
      description: '',
      name: 'announcementAdvancedTrading',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20653': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxPopularAssets',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20652': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxRecurringBuys',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20651': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxEarnYield',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20650': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxEarnCrypto',
      spectrum: 'light',
      versionNum: 1,
    },
    '2266:20672': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxPopularAssets',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2266:20668': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxRecurringBuys',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2266:20667': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxEarnYield',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2266:20666': {
      variant: 'spotSquare',
      description: '',
      name: 'nuxEarnCrypto',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2266:20649': {
      variant: 'spotSquare',
      description: '',
      name: 'transferringCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '2266:20661': {
      variant: 'spotSquare',
      description: '',
      name: 'transferringCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2502:86': {
      variant: 'heroSquare',
      description: '',
      name: 'downloadCoinbaseWallet',
      spectrum: 'dark',
      versionNum: 1,
    },
    '2556:1608': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseRedesigned',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1609': {
      variant: 'heroSquare',
      description: '',
      name: 'cashExcitement',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1611': {
      variant: 'heroSquare',
      description: '',
      name: 'givingToOthers',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1610': {
      variant: 'heroSquare',
      description: '',
      name: 'givingTogether',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1604': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseRedesigned',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2556:1605': {
      variant: 'heroSquare',
      description: '',
      name: 'cashExcitement',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2556:1607': {
      variant: 'heroSquare',
      description: '',
      name: 'givingToOthers',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2556:1606': {
      variant: 'heroSquare',
      description: '',
      name: 'givingTogether',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2556:1603': {
      variant: 'spotRectangle',
      description: '',
      name: 'portfolioOverview',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1602': {
      variant: 'spotRectangle',
      description: '',
      name: 'portfolioOverview',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2556:1598': {
      variant: 'spotSquare',
      description: '',
      name: 'addPasswordProtection',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1600': {
      variant: 'spotSquare',
      description: '',
      name: 'addPasswordProtection',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2556:1599': {
      variant: 'spotSquare',
      description: '',
      name: 'givingTogetherSmall',
      spectrum: 'light',
      versionNum: 0,
    },
    '2556:1601': {
      variant: 'spotSquare',
      description: '',
      name: 'givingTogetherSmall',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2677:362': {
      variant: 'spotSquare',
      description: '',
      name: 'announcementAdvancedTrading',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:887': {
      variant: 'spotRectangle',
      description: '',
      name: 'protectedNotes',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:888': {
      variant: 'spotRectangle',
      description: '',
      name: 'protectedNotes',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2196': {
      variant: 'spotSquare',
      description: '',
      name: 'clv',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2197': {
      variant: 'spotSquare',
      description: '',
      name: 'rly',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2198': {
      variant: 'spotSquare',
      description: '',
      name: 'pax',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2199': {
      variant: 'spotSquare',
      description: '',
      name: 'poly',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2200': {
      variant: 'spotSquare',
      description: '',
      name: 'tribe',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2201': {
      variant: 'spotSquare',
      description: '',
      name: 'iotx',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2202': {
      variant: 'spotSquare',
      description: '',
      name: 'orn',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2203': {
      variant: 'spotSquare',
      description: '',
      name: 'ant',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2204': {
      variant: 'spotSquare',
      description: '',
      name: 'fet',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2205': {
      variant: 'spotSquare',
      description: '',
      name: 'asm',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2206': {
      variant: 'spotSquare',
      description: '',
      name: 'rai',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2207': {
      variant: 'spotSquare',
      description: '',
      name: 'quick',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2208': {
      variant: 'spotSquare',
      description: '',
      name: 'pla',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2209': {
      variant: 'spotSquare',
      description: '',
      name: 'ach',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2210': {
      variant: 'spotSquare',
      description: '',
      name: 'ust',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2211': {
      variant: 'spotSquare',
      description: '',
      name: 'mask',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2212': {
      variant: 'spotSquare',
      description: '',
      name: 'farm',
      spectrum: 'light',
      versionNum: 0,
    },
    '2684:2213': {
      variant: 'spotSquare',
      description: '',
      name: 'clv',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2214': {
      variant: 'spotSquare',
      description: '',
      name: 'rly',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2215': {
      variant: 'spotSquare',
      description: '',
      name: 'pax',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2216': {
      variant: 'spotSquare',
      description: '',
      name: 'poly',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2217': {
      variant: 'spotSquare',
      description: '',
      name: 'tribe',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2218': {
      variant: 'spotSquare',
      description: '',
      name: 'iotx',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2219': {
      variant: 'spotSquare',
      description: '',
      name: 'orn',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2220': {
      variant: 'spotSquare',
      description: '',
      name: 'ant',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2221': {
      variant: 'spotSquare',
      description: '',
      name: 'fet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2222': {
      variant: 'spotSquare',
      description: '',
      name: 'asm',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2223': {
      variant: 'spotSquare',
      description: '',
      name: 'rai',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2224': {
      variant: 'spotSquare',
      description: '',
      name: 'quick',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2225': {
      variant: 'spotSquare',
      description: '',
      name: 'pla',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2226': {
      variant: 'spotSquare',
      description: '',
      name: 'ach',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2227': {
      variant: 'spotSquare',
      description: '',
      name: 'ust',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2228': {
      variant: 'spotSquare',
      description: '',
      name: 'mask',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2684:2229': {
      variant: 'spotSquare',
      description: '',
      name: 'farm',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2898:338': {
      variant: 'spotSquare',
      description: '',
      name: 'moneyRewards',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2898:330': {
      variant: 'spotSquare',
      description: '',
      name: 'starToken',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2898:340': {
      variant: 'spotSquare',
      description: '',
      name: 'addMultipleCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2898:339': {
      variant: 'spotSquare',
      description: '',
      name: 'phoneNotifications',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2898:341': {
      variant: 'spotSquare',
      description: '',
      name: 'cardShipped',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2937:417': {
      variant: 'spotSquare',
      description: '',
      name: 'yieldCenterUSDC',
      spectrum: 'light',
      versionNum: 0,
    },
    '2937:416': {
      variant: 'spotSquare',
      description: '',
      name: 'yieldCenterUSDC',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2937:1076': {
      variant: 'heroSquare',
      description: '',
      name: 'currencyPairs',
      spectrum: 'light',
      versionNum: 0,
    },
    '2937:1075': {
      variant: 'heroSquare',
      description: '',
      name: 'orderBooks',
      spectrum: 'light',
      versionNum: 0,
    },
    '2937:1074': {
      variant: 'heroSquare',
      description: '',
      name: 'tradeHistory',
      spectrum: 'light',
      versionNum: 0,
    },
    '2937:1071': {
      variant: 'heroSquare',
      description: '',
      name: 'currencyPairs',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2937:1072': {
      variant: 'heroSquare',
      description: '',
      name: 'orderBooks',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2937:1073': {
      variant: 'heroSquare',
      description: '',
      name: 'tradeHistory',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2937:1077': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCard',
      spectrum: 'light',
      versionNum: 0,
    },
    '2937:1070': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCard',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2960:2368': {
      variant: 'heroSquare',
      description: '',
      name: 'defiEnrollBoost',
      spectrum: 'light',
      versionNum: 0,
    },
    '2960:2365': {
      variant: 'heroSquare',
      description: '',
      name: 'defiEnrollBoost',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2960:2367': {
      variant: 'heroSquare',
      description: '',
      name: 'defiRisk',
      spectrum: 'light',
      versionNum: 0,
    },
    '2960:2363': {
      variant: 'heroSquare',
      description: '',
      name: 'defiRisk',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2960:2366': {
      variant: 'heroSquare',
      description: '',
      name: 'defiEarn',
      spectrum: 'light',
      versionNum: 0,
    },
    '2960:2362': {
      variant: 'heroSquare',
      description: '',
      name: 'defiEarn',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2960:2369': {
      variant: 'heroSquare',
      description: '',
      name: 'defiHow',
      spectrum: 'light',
      versionNum: 0,
    },
    '2960:2364': {
      variant: 'heroSquare',
      description: '',
      name: 'defiHow',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2960:2361': {
      variant: 'spotSquare',
      description: '',
      name: 'defiEarnAnnouncement',
      spectrum: 'light',
      versionNum: 0,
    },
    '2960:2360': {
      variant: 'spotSquare',
      description: '',
      name: 'defiEarnAnnouncement',
      spectrum: 'dark',
      versionNum: 0,
    },
    '2960:2354': {
      variant: 'pictogram',
      description: '',
      name: 'defiEarnMoment',
      spectrum: 'light',
      versionNum: 0,
    },
    '2960:2352': {
      variant: 'pictogram',
      description: '',
      name: 'defiEarnMoment',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:437': {
      variant: 'spotSquare',
      description: '',
      name: 'tru',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:438': {
      variant: 'spotSquare',
      description: '',
      name: 'tru',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:465': {
      variant: 'pictogram',
      description: '',
      name: 'noTransactions',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:492': {
      variant: 'pictogram',
      description: '',
      name: 'noTransactions',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:737': {
      variant: 'heroSquare',
      description: '',
      name: 'directDepositPhone',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:738': {
      variant: 'spotSquare',
      description: '',
      name: 'directDepositExcitement',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:983': {
      variant: 'heroSquare',
      description: '',
      name: 'directDepositPhone',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:1045': {
      variant: 'spotSquare',
      description: '',
      name: 'directDepositExcitement',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:1338': {
      variant: 'heroSquare',
      description: '',
      name: 'cryptoAppsWallet',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:1340': {
      variant: 'heroSquare',
      description: '',
      name: 'cryptoAppsWallet',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:1337': {
      variant: 'heroSquare',
      description: '',
      name: 'cryptoApps',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:1339': {
      variant: 'heroSquare',
      description: '',
      name: 'cryptoApps',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:1445': {
      variant: 'heroSquare',
      description: '',
      name: 'walletLoading',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:1446': {
      variant: 'heroSquare',
      description: '',
      name: 'walletLoading',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:1877': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardSpend',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:1878': {
      variant: 'heroSquare',
      description: '',
      name: 'coinbaseCardSpend',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:2052': {
      variant: 'heroSquare',
      description: '',
      name: 'bitcoinAndOtherCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:2053': {
      variant: 'heroSquare',
      description: '',
      name: 'bitcoinAndOtherCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:2252': {
      variant: 'heroSquare',
      description: '',
      name: 'addMoreCrypto',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:2253': {
      variant: 'heroSquare',
      description: '',
      name: 'addMoreCrypto',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:2647': {
      variant: 'spotRectangle',
      description: '',
      name: 'transferEth',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:2648': {
      variant: 'spotRectangle',
      description: '',
      name: 'transferEth',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:2649': {
      variant: 'spotRectangle',
      description: '',
      name: 'walletReconnect',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:2650': {
      variant: 'spotRectangle',
      description: '',
      name: 'walletReconnect',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:2876': {
      variant: 'spotRectangle',
      description: '',
      name: 'walletReconnectSuccess',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:2878': {
      variant: 'spotRectangle',
      description: '',
      name: 'walletReconnectSuccess',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3193:2877': {
      variant: 'spotRectangle',
      description: '',
      name: 'highFees',
      spectrum: 'light',
      versionNum: 0,
    },
    '3193:2879': {
      variant: 'spotRectangle',
      description: '',
      name: 'highFees',
      spectrum: 'dark',
      versionNum: 0,
    },
    '3235:2932': {
      variant: 'pictogram',
      description: '',
      name: 'noNotificationsGray',
      spectrum: 'dark',
      versionNum: 0,
    },
  },
};
