/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const illustrationMetadata = {
  numIllustrations: 645,
  heroSquareCount: 126,
  pictogramCount: 135,
  spotRectangleCount: 26,
  spotSquareCount: 42,
  newIllustration: [
    'coinbaseOneAuthenticator-dark',
    'coinbaseOneAuthenticator-light',
    'coinbaseOneCardWarning-dark',
    'coinbaseOneCardWarning-light',
    'coinbaseOneChat-dark',
    'coinbaseOneChat-light',
    'coinbaseOneDiscountedAmount-dark',
    'coinbaseOneDiscountedAmount-light',
    'coinbaseOneDocWarning-dark',
    'coinbaseOneDocWarning-light',
    'coinbaseOneEarnCoins-dark',
    'coinbaseOneEarnCoins-light',
    'coinbaseOneFiat-dark',
    'coinbaseOneFiat-light',
    'coinbaseOneInsufficientWallet-dark',
    'coinbaseOneInsufficientWallet-light',
    'coinbaseOnePhoneLightning-dark',
    'coinbaseOnePhoneLightning-light',
    'coinbaseOnePhoneLightningAlt-dark',
    'coinbaseOnePhoneLightningAlt-light',
    'coinbaseOneProtectedCrypto-dark',
    'coinbaseOneProtectedCrypto-light',
    'coinbaseOneRefreshed-dark',
    'coinbaseOneRefreshed-light',
    'coinbaseOneSavingFunds-dark',
    'coinbaseOneSavingFunds-light',
    'coinbaseOneShield-dark',
    'coinbaseOneShield-light',
    'coinbaseOneTrusted-dark',
    'coinbaseOneTrusted-light',
    'fileYourCryptoTaxes-dark',
    'fileYourCryptoTaxes-light',
    'fileYourCryptoTaxesAlt-dark',
    'fileYourCryptoTaxesAlt-light',
    'fileYourCryptoTaxesCheck-dark',
    'fileYourCryptoTaxesCheck-light',
    'fileYourCryptoTaxesCheckAlt-dark',
    'fileYourCryptoTaxesCheckAlt-light',
    'fileYourCryptoTaxesCheckOther-dark',
    'fileYourCryptoTaxesCheckOther-light',
    'fileYourCryptoTaxesOther-dark',
    'fileYourCryptoTaxesOther-light',
    'ordersGray-dark',
    'ordersGray-light',
    'taxBeta-dark',
    'taxBeta-light',
    'taxSeason-dark',
    'taxSeason-light',
    'taxes-dark',
    'taxes-light',
    'yieldHoldingAlt-dark',
    'yieldHoldingAlt-light',
  ],
  modifiedIllustrations: [
    'coinbaseOneAuthenticator-dark',
    'coinbaseOneAuthenticator-light',
    'coinbaseOneChat-dark',
    'coinbaseOneChat-light',
    'coinbaseOneEarnCoins-dark',
    'coinbaseOneEarnCoins-light',
    'coinbaseOneRefreshed-dark',
    'coinbaseOneRefreshed-light',
    'coinbaseOneShield-dark',
    'coinbaseOneShield-light',
    'coinbaseOneTrusted-dark',
    'coinbaseOneTrusted-light',
    'cryptoApps-dark',
    'cryptoApps-light',
    'cryptoAppsWallet-dark',
    'cryptoAppsWallet-light',
    'transferEth-dark',
    'transferEth-light',
    'walletLoading-dark',
    'walletLoading-light',
    'walletReconnect-dark',
    'walletReconnect-light',
    'walletReconnectSuccess-dark',
    'walletReconnectSuccess-light',
  ],
};
