const path = require('path');
const onProcessDoc = require('./utils/onProcessDocgen');

/**
 * Pull in docgen data to any component via `import from ':docgen/{key from sourceFiles}'`;
 * You can inspect available imports in .docusaurus/docusaurus-plugin-docgen/default directory.
 * The alias defined below, i.e. :docgen, will give you access to anything in that directory.
 */
module.exports = {
  docsDir: path.join(__dirname, './docs/components'),
  /**
   * Determines if plugin should run. If plugin is too slow in development,
   * you can either increase watchInterval or set this to false.
   * @default true
   */
  enabled: true,
  // forceDocs: true,
  /**
   * Absolute paths to tsconfig.json's for any projects that sourceFiles belong to.
   * When the plugin is run it will loop through each tsconfig and determine
   * which sourceFiles are present in those packages.
   */
  entryPoints: [
    path.join(__dirname, '../../packages/web/tsconfig.json'),
    path.join(__dirname, '../../packages/web-visualization/tsconfig.json'),
    path.join(__dirname, '../../packages/mobile-visualization/tsconfig.json'),
    path.join(__dirname, '../../packages/mobile/tsconfig.json'),
    path.join(__dirname, '../../packages/common/tsconfig.json'),
    path.join(__dirname, '../../packages/icons/tsconfig.json'),
    path.join(__dirname, '../../packages/illustrations/tsconfig.json'),
  ],
  formatPackageName: (name) => {
    return name.replace('cds-', '');
  },
  onProcessDoc,
  /**
   * How frequently (in minutes) should plugin run after it was last run.
   * This is typically triggered via on save of project file.
   * @default 5
   */
  watchInterval: 20,
  /**
   * Any source files relative to entryPoints above that you want docgen to parse.
   */
  sourceFiles: [
    'accordion/Accordion',
    'accordion/AccordionItem',
    'alpha/AnnouncementCard',
    'alpha/Card',
    'alpha/CardBody',
    'alpha/CardFooter',
    'alpha/CardGroup',
    'alpha/CardHeader',
    'alpha/FeatureEntryCard',
    'alpha/FeedCard',
    'animation/Lottie',
    'animation/LottieStatusAnimation',
    'animation/useLottie',
    'animation/useLottieColorFilters',
    'banner/Banner',
    'buttons/AvatarButton',
    'buttons/Button',
    'buttons/ButtonGroup',
    'buttons/IconButton',
    'buttons/NavigationIconButton',
    'buttons/Tile',
    'buttons/TileButton',
    'cards/AnnouncementCard',
    'cards/Card',
    'cards/CardBody',
    'cards/CardFooter',
    'cards/CardGroup',
    'cards/CardHeader',
    'cards/FeatureEntryCard',
    'cards/FeedCard',
    'cards/NudgeCard',
    'cards/FloatingAssetCard',
    'cards/ContainedAssetCard',
    'cards/UpsellCard',
    'cells/Cell',
    'cells/CellAccessory',
    'cells/CellDetail',
    'cells/CellMedia',
    'cells/ContentCell',
    'cells/ContentCellFallback',
    'cells/ListCell',
    'cells/ListCellFallback',
    'chips/Chip',
    'chips/SelectChip',
    'chips/InputChip',
    'chips/TabbedChips',
    'motion/AnimatedCaret',
    'collapsible/Collapsible',
    'controls/Checkbox',
    'controls/InputIcon',
    'controls/InputIconButton',
    'controls/InputLabel',
    'controls/InputStack',
    'controls/NativeInput',
    'controls/NativeTextArea',
    'controls/RadioGroup',
    'controls/SearchInput',
    'controls/SegmentedControl',
    'controls/Select',
    'select/Select',
    'controls/SelectOption',
    'select/SelectOption',
    'controls/Switch',
    'controls/TextInput',
    'controls/HelperText',
    'dots/DotCount',
    'dots/DotStatusColor',
    'dots/DotSymbol',
    'dropdown/Dropdown',
    'dropdown/MenuItem',
    'hooks/useEventHandler',
    'illustrations/HeroSquare',
    'illustrations/Pictogram',
    'illustrations/SpotSquare',
    'illustrations/SpotIcon',
    'illustrations/SpotRectangle',
    'layout/Box',
    'layout/Divider',
    'layout/Fallback',
    'layout/Grid',
    'layout/GridColumn',
    'layout/Group',
    'layout/HStack',
    'layout/Spacer',
    'layout/VStack',
    'loaders/Spinner',
    'media/Avatar',
    'media/RemoteImage',
    'media/RemoteImageGroup',
    'sticky-footer/StickyFooter',
    'motion/ColorSurge',
    'motion/Shake',
    'motion/Pulse',
    'navigation/NavigationBar',
    'navigation/NavigationTitle',
    'navigation/NavLink',
    'navigation/Sidebar',
    'navigation/SidebarItem',
    'navigation/SidebarMoreMenu',
    'sidebarMoreMenu/SidebarMoreMenu',
    'overlays/Alert',
    'overlays/Drawer/Drawer',
    'overlays/FullscreenAlert',
    'overlays/Modal/FullscreenModal',
    'overlays/Modal/Modal',
    'overlays/Modal/ModalHeader',
    'overlays/Modal/ModalBody',
    'overlays/Modal/ModalFooter',
    'overlays/PortalProvider',
    'overlays/Tooltip/Tooltip',
    'tooltip/Tooltip',
    'overlays/Tray/Tray',
    'tables/Table',
    'tables/TableBody',
    'tables/TableCaption',
    'tables/TableCell',
    'tables/TableCellFallback',
    'tables/TableFooter',
    'tables/TableHeader',
    'tables/TableRow',
    'tables/TableSection',
    'tabs/TabIndicator',
    'tabs/TabLabel',
    'tabs/TabNavigation',
    'tag/Tag',
    'overlays/Toast',
    'overlays/useModal',
    'system/DevicePreferencesProvider',
    'system/EventHandlerProvider',
    'system/FeatureFlagProvider',
    'system/Interactable',
    'system/Pressable',
    'system/PressableOpacity',
    'system/ThemeProvider',
    'typography/Link',
    'typography/TextBody',
    'icons/Icon',
    'icons/LogoMark',
    'icons/LogoWordmark',
    'icons/NavigationIcon',
    'icons/SubBrandLogoMark',
    'icons/SubBrandLogoWordmark',
    'hooks/useSubBrandLogo',
    'hooks/useLogo',
    'visualizations/ProgressBar',
    'visualizations/ProgressBarWithFixedLabels',
    'visualizations/ProgressBarWithFloatLabel',
    'visualizations/ProgressCircle',
    'sparkline/Sparkline',
    'sparkline/SparklineGradient',
    'sparkline/sparkline-interactive/SparklineInteractive',
    'sparkline/sparkline-interactive-header/SparklineInteractiveHeader',
    'visualizations/useSparklinePath',
    'visualizations/useSparklineArea',
    'visualizations/useSparklineCoordinates',
  ],
};
