const { adopters } = require('./data/sidebar/adopters');

const showIndexPageForCategory = {
  type: 'generated-index',
};

module.exports = {
  docs: [
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Debug',
      items: [
        {
          type: 'autogenerated',
          dirName: 'debug',
        },
      ],
    },
    {
      type: 'doc',
      id: 'cds/overview',
      label: `CDS`, // This is hidden, but docusaurus does not allow empty label
      customProps: { hide: true },
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Foundations',
      items: [
        'cds/getting-started',
        'foundation/a11y',
        'foundation/color',
        'foundation/content',
        'foundation/elevation',
        'foundation/layout',
        {
          type: 'category',
          link: showIndexPageForCategory,
          label: 'Motion',
          items: [
            { type: 'doc', id: 'foundation/motion/brand-motion', label: 'Brand' },
            { type: 'doc', id: 'foundation/motion/product-motion-language', label: 'Product' },
            { type: 'doc', id: 'foundation/motion/timing', label: 'Timing' },
            { type: 'doc', id: 'foundation/motion/motion-handoff', label: 'Handoff' },
          ],
        },
        'foundation/scale',
        'foundation/typography',
      ],
    },
    {
      type: 'category',
      label: 'Assets',
      items: [
        {
          type: 'category',
          label: 'Icons',
          items: [
            {
              type: 'doc',
              id: 'foundation/creating-and-maintaining-iconography',
              label: 'Contributing',
            },
            {
              type: 'doc',
              id: 'foundation/iconography',
              label: 'Guidelines',
            },
            'components/icons/Icon/icon',
            {
              type: 'doc',
              id: 'components/icons/NavigationIcon/navigation-icon',
              label: 'Navigation Icon',
            },
          ],
        },
        {
          type: 'category',
          label: 'Illustrations',
          items: [
            {
              type: 'doc',
              id: 'foundation/product-illustration',
              label: 'Guidelines',
            },
            {
              type: 'doc',
              id: 'components/illustrations/HeroSquare/hero-square',
              label: 'Hero Square',
            },
            {
              type: 'doc',
              id: 'components/illustrations/Pictogram/pictogram',
              label: 'Pictogram',
            },
            {
              type: 'doc',
              id: 'components/illustrations/SpotRectangle/spot-rectangle',
              label: 'Spot Rectangle',
            },
            {
              type: 'doc',
              id: 'components/illustrations/SpotSquare/spot-square',
              label: 'Spot Square',
            },
          ],
        },
        {
          type: 'category',
          label: 'Logos',
          items: [
            { type: 'doc', id: 'components/icons/logo', label: 'Logo' },
            {
              type: 'doc',
              id: 'components/icons/SubBrandLogoMark/sub-brand-logo-mark',
              label: 'Sub Brand Mark',
            },
            {
              type: 'doc',
              id: 'components/icons/SubBrandLogoWordmark/sub-brand-logo-wordmark',
              label: 'Sub Brand Wordmark',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Components',
      items: [
        {
          type: 'category',
          label: 'Alert',
          items: ['components/overlays/Alert/alert', 'hooks/useAlert'],
        },
        'components/media/Avatar/avatar',
        {
          type: 'doc',
          id: 'components/buttons/AvatarButton/avatar-button',
          label: 'Avatar Button',
        },
        {
          type: 'category',
          label: 'Accordion',
          items: [
            'components/accordion/Accordion/accordion',
            {
              type: 'doc',
              id: 'components/accordion/AccordionItem/accordion-item',
              label: 'Accordion Item',
            },
          ],
        },
        'components/collapsible/Collapsible/collapsible',
        {
          type: 'category',
          label: 'Button',
          items: [
            'components/buttons/Button/button',
            {
              type: 'doc',
              id: 'components/buttons/ButtonGroup/button-group',
              label: 'Button Group',
            },
            'components/system/Pressable/pressable',
            {
              type: 'doc',
              id: 'components/system/PressableOpacity/pressable-opacity',
              label: 'Pressable Opacity',
            },
            // 'components/buttons/NavigationIconButton/navigation-icon-button',
            // 'components/buttons/TileButton/tile-button',
          ],
        },
        {
          type: 'category',
          label: 'Card',
          items: [
            'components/cards/Card/card',
            { type: 'doc', id: 'components/cards/CardBody/card-body', label: 'Card Body' },
            { type: 'doc', id: 'components/cards/CardFooter/card-footer', label: 'Card Footer' },
            { type: 'doc', id: 'components/cards/CardGroup/card-group', label: 'Card Group' },
            { type: 'doc', id: 'components/cards/CardHeader/card-header', label: 'Card Header' },
            {
              type: 'doc',
              id: 'components/cards/AnnouncementCard/announcement-card',
              label: 'Announcement Card',
            },
            {
              type: 'doc',
              id: 'components/cards/FeatureEntryCard/feature-entry-card',
              label: 'Feature Entry Card',
            },
            { type: 'doc', id: 'components/cards/FeedCard/feed-card', label: 'Feed Card' },
          ],
        },
        {
          type: 'category',
          label: 'Cell',
          items: [
            { type: 'doc', id: 'components/cells/ListCell/list-cell', label: 'List Cell' },
            {
              type: 'doc',
              id: 'components/cells/ListCellFallback/list-cell-fallback',
              label: 'List Cell Fallback',
            },
            { type: 'doc', id: 'components/cells/ContentCell/content-cell', label: 'Content Cell' },
            {
              type: 'doc',
              id: 'components/cells/ContentCellFallback/content-cell-fallback',
              label: 'Content Cell Fallback',
            },
            { type: 'doc', id: 'components/cells/CellMedia/cell-media', label: 'Cell Media' },
          ],
        },
        'components/controls/Checkbox/checkbox',
        'components/layout/Divider/divider',
        {
          type: 'category',
          label: 'Dot',
          items: [
            { type: 'doc', id: 'components/dots/DotCount/dot-count', label: 'Count' },
            {
              type: 'doc',
              id: 'components/dots/DotStatusColor/dot-status-color',
              label: 'Status Color',
            },
            { type: 'doc', id: 'components/dots/DotSymbol/dot-symbol', label: 'Symbol' },
          ],
        },
        'components/overlays/Drawer/drawer',
        {
          type: 'category',
          label: 'Dropdown',
          items: [
            { type: 'doc', id: 'components/overlays/PopoverMenu/popover-menu', label: 'Dropdown' },
            {
              type: 'doc',
              id: 'components/overlays/PopoverTrigger/popover-trigger',
              label: 'Dropdown Trigger',
            },
          ],
        },
        'components/layout/Fallback/fallback',
        'components/layout/Group/group',
        { type: 'doc', id: 'components/buttons/IconButton/icon-button', label: 'Icon Button' },
        { type: 'doc', id: 'components/media/RemoteImage/remote-image', label: 'Image' },
        { type: 'doc', id: 'components/controls/TextInput/text-input', label: 'Input' },
        {
          type: 'category',
          label: 'Navigation',
          items: [
            'components/navigation/NavLink/nav-link',
            'components/navigation/NavigationBar/navigation-bar',
            'components/navigation/NavigationTitle/navigation-title',
            'components/navigation/Sidebar/sidebar',
            'components/navigation/SidebarItem/sidebar-item',
            // 'components/navigation/SidebarMoreMenu/sidebar-more-menu',
          ],
        },
        'components/typography/Link/link',
        {
          type: 'category',
          label: 'Lottie',
          items: [
            'components/animation/Lottie/lottie',
            'components/animation/LottieStatusAnimation/lottie-status-animation',
          ],
        },
        {
          type: 'category',
          label: 'Modal',
          items: [
            'components/overlays/Modal/modal',
            { type: 'doc', id: 'components/overlays/ModalBody/modal-body', label: 'Modal Body' },
            {
              type: 'doc',
              id: 'components/overlays/ModalFooter/modal-footer',
              label: 'Modal Footer',
            },
            {
              type: 'doc',
              id: 'components/overlays/ModalHeader/modal-header',
              label: 'Modal Header',
            },
            'hooks/useModal',
          ],
        },
        'components/controls/RadioGroup/radio-group',
        { type: 'doc', id: 'components/controls/SearchInput/search-input', label: 'Search  Input' },
        {
          type: 'doc',
          id: 'components/overlays/SectionTitle/section-title',
          label: 'Section Title',
        },
        {
          type: 'category',
          label: 'Select',
          items: [
            'components/controls/Select/select',
            {
              type: 'doc',
              id: 'components/controls/SelectOption/select-option',
              label: 'Select Option',
            },
          ],
        },
        {
          type: 'category',
          label: 'Sparkline',
          items: [
            'components/visualizations/Sparkline/sparkline',
            {
              type: 'doc',
              id: 'components/visualizations/SparklineGradient/sparkline-gradient',
              label: 'Sparkline Gradient',
            },
            {
              type: 'doc',
              id: 'components/visualizations/SparklineInteractive/sparkline-interactive',
              label: 'Sparkline Interactive',
            },
            {
              type: 'doc',
              id: 'components/visualizations/SparklineInteractiveHeader/sparkline-interactive-header',
              label: 'Sparkline Interactive Header',
            },
            'hooks/useSparklinePath',
          ],
        },
        'components/loaders/Spinner/spinner',
        {
          type: 'category',
          label: 'Stack',
          items: [
            'components/layout/Box/box',
            'components/layout/HStack/hstack',
            'components/layout/VStack/vstack',
            'components/layout/Spacer/spacer',
          ],
        },
        'components/controls/Switch/switch',
        {
          type: 'category',
          label: 'Table',
          items: [
            'components/tables/Table/table',
            { type: 'doc', id: 'components/tables/TableBody/table-body', label: 'Table Body' },
            { type: 'doc', id: 'components/tables/TableCell/table-cell', label: 'Table Cell' },
            {
              type: 'doc',
              id: 'components/tables/TableCellFallback/table-cell-fallback',
              label: 'Table Cell Fallback',
            },
            {
              type: 'doc',
              id: 'components/tables/TableFooter/table-footer',
              label: 'Table Footer',
            },
            {
              type: 'doc',
              id: 'components/tables/TableHeader/table-header',
              label: 'Table Header',
            },
            { type: 'doc', id: 'components/tables/TableRow/table-row', label: 'Table Row' },
          ],
        },
        {
          type: 'category',
          label: 'Tabs',
          items: [
            { type: 'doc', id: 'components/tabs/TabNavigation/tab-navigation', label: 'Tabs' },
            { type: 'doc', id: 'components/tabs/TabLabel/tab-label', label: 'Tab Label' },
            {
              type: 'doc',
              id: 'components/tabs/TabIndicator/tab-indicator',
              label: 'Tab Indicator',
            },
          ],
        },
        'components/typography/Text/text',
        {
          type: 'doc',
          id: 'components/controls/NativeTextArea/native-text-area',
          label: 'Text Area',
        },
        {
          type: 'category',
          label: 'Toast',
          items: ['components/overlays/Toast/toast', 'hooks/useToast'],
        },
        'components/overlays/Tooltip/tooltip',
        'components/overlays/Tray/tray',
        {
          type: 'category',
          label: 'ProgressBar',
          items: [
            'components/visualizations/ProgressBar/progress-bar',
            {
              type: 'doc',
              id: 'components/visualizations/ProgressBarWithFixedLabels/progress-bar-with-fixed-labels',
              label: 'Progress Bar w/ Fixed Labels',
            },
            {
              type: 'doc',
              id: 'components/visualizations/ProgressBarWithFloatLabel/progress-bar-with-float-label',
              label: 'Progress Bar w/ Float Labels',
            },
          ],
        },
        {
          type: 'doc',
          id: 'components/visualizations/ProgressCircle/progress-circle',
          label: 'Progress Circle',
        },
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      items: ['concepts/messaging/errors'],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [
        { type: 'doc', id: 'recipes/sparkline-interactive', label: 'Asset Chart' },
        { type: 'doc', id: 'partnerships/AppSwitcher/app-switcher', label: 'App Switcher' },
        { type: 'doc', id: 'partnerships/UserSwitcher/user-switcher', label: 'User Switcher' },
        { type: 'doc', id: 'recipes/navigation', label: 'Navigation' },
      ],
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Abstract Components',
      items: [
        {
          type: 'category',
          label: 'DevicePreferencesProvider',
          items: [
            {
              type: 'doc',
              id: 'components/system/DevicePreferencesProvider/device-preferences-provider',
              label: 'Provider',
            },
            'hooks/useDeviceSpectrum',
          ],
        },
        {
          type: 'category',
          label: 'EventHandlerProvider',
          items: [
            {
              type: 'doc',
              id: 'components/system/EventHandlerProvider/event-handler-provider',
              label: 'Provider',
            },
            'hooks/useEventHandler',
          ],
        },
        {
          type: 'doc',
          id: 'components/system/FeatureFlagProvider/feature-flag-provider',
          label: 'FeatureFlagProvider',
        },
        {
          type: 'category',
          label: 'ThemeProvider',
          items: [
            {
              type: 'doc',
              id: 'components/system/ThemeProvider/theme-provider',
              label: 'Provider',
            },
            'hooks/usePalette',
            'hooks/usePaletteConfig',
            'hooks/usePaletteValueToRgbaString',
            'hooks/useSpectrum',
            'hooks/useSpectrumConditional',
            // TODO: 'hooks/useScale',
            'hooks/useScaleConditional',
            'hooks/useAccessibleForeground',
          ],
        },
        {
          type: 'category',
          label: 'PortalProvider',
          items: ['hooks/useOverlay'],
        },
      ],
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Resources',
      items: [
        {
          type: 'category',
          label: 'Adoption',
          items: [{ type: 'doc', id: 'adoption-tracker-overview', label: 'Overview' }, ...adopters],
        },
        { type: 'doc', id: 'a11y-report', label: 'Accessibility Tracker' },
        {
          type: 'category',
          link: showIndexPageForCategory,
          label: 'Changelog',
          items: [
            { type: 'doc', id: 'changelog/common', label: '@cbhq/cds-common' },
            { type: 'doc', id: 'changelog/fonts', label: '@cbhq/cds-fonts' },
            { type: 'doc', id: 'changelog/lottie-files', label: '@cbhq/cds-lottie-files' },
            { type: 'doc', id: 'changelog/mobile', label: '@cbhq/cds-mobile' },
            { type: 'doc', id: 'changelog/utils', label: '@cbhq/cds-utils' },
            { type: 'doc', id: 'changelog/web', label: '@cbhq/cds-web' },
          ],
        },
        {
          type: 'category',
          link: showIndexPageForCategory,
          label: 'Contributing',
          items: [
            { type: 'doc', id: 'contributing/engineering', label: 'Engineering Guide' },
            { type: 'doc', id: 'contributing/design', label: 'Design Guide' },
          ],
        },
        'resources/release',
        'cds/support',
      ],
    },
  ],
};
