const { components } = require('./data/sidebar/components');
const { adopters } = require('./data/sidebar/adopters');

// Removes unfinished categories from side bar
const sectionsToExcludeByLabel = new Set([]);

// Removes unfinished components from section in side bar
// Please alphabetize to avoid merge conflicts
const componentsToExcludeByLabel = new Set([
  'components/buttons/TileButton/tile-button',
  'components/buttons/NavigationIconButton/navigation-icon-button',
]);

// Filter sidebar components
const filteredComponents = components
  .filter((component) => !sectionsToExcludeByLabel.has(component.label))
  .map((componentJSON) => {
    const items = componentJSON.items.filter((path) => !componentsToExcludeByLabel.has(path));

    return {
      ...componentJSON,
      items,
    };
  });

const showIndexPageForCategory = {
  type: 'generated-index',
};

module.exports = {
  docs: [
    {
      type: 'category',
      label: 'CDS',
      link: showIndexPageForCategory,
      items: [
        'cds/overview',
        'cds/whats-happening',
        'cds/getting-started',
        'cds/support',
        {
          type: 'category',
          label: 'Designers guide',
          link: showIndexPageForCategory,
          items: [
            'cds/designers-guide/intro',
            'cds/designers-guide/usage',
            'cds/designers-guide/customization',
            'cds/designers-guide/handoff',
            'cds/designers-guide/going-beyond-cds',
          ],
        },
      ],
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Foundation',
      items: [
        'foundation/overview',
        'foundation/a11y',
        'foundation/color',
        'foundation/content',
        'foundation/elevation',
        'foundation/iconography',
        'foundation/creating-and-maintaining-iconography',
        'foundation/product-illustration',
        'foundation/layout',
        {
          type: 'category',
          link: showIndexPageForCategory,
          label: 'Motion',
          items: [
            'foundation/motion/product-motion-language',
            'foundation/motion/timing',
            'foundation/motion/motion-handoff',
            'foundation/motion/brand-motion',
          ],
        },
        'foundation/scale',
        'foundation/typography',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'category',
          label: 'Messaging',
          items: ['concepts/messaging/errors'],
        },
      ],
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Components',
      items: filteredComponents,
    },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Hooks',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hooks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [
        { type: 'doc', id: 'recipes/navigation', label: 'Navigation' },
        { type: 'doc', id: 'recipes/sparkline-interactive', label: 'Sparkline Interactive' },
      ],
    },
    {
      type: 'category',
      label: 'Partnerships',
      items: ['partnerships/AppSwitcher/app-switcher', 'partnerships/UserSwitcher/user-switcher'],
    },
    {
      type: 'category',
      label: 'Adoption Guides',
      items: [{ type: 'doc', id: 'guides/adoption', label: 'Overview' }],
    },
    {
      type: 'category',
      label: 'Adoption Tracker',
      items: [{ type: 'doc', id: 'adoption-tracker-overview', label: 'Overview' }, ...adopters],
    },
    'a11y-report',
    'analytics',
    { type: 'doc', id: 'guides/migration/overview', label: 'Migration Guides' },
    {
      type: 'category',
      link: showIndexPageForCategory,
      label: 'Resources',
      items: [
        {
          type: 'link',
          label: 'Figma',
          href: 'https://www.figma.com/file/SWoyy3B5IkEpMvk60Lb4V6/CDS-Normal-%F0%9F%8C%9E?node-id=1%3A9',
        },
        {
          type: 'link',
          label: 'Github',
          href: 'https://github.cbhq.net/frontend/cds/tree/master',
        },

        'resources/roadmap',
        {
          type: 'category',
          link: showIndexPageForCategory,
          label: 'Contributing',
          items: [
            { type: 'doc', id: 'contributing/engineering', label: 'Engineering Guide' },
            { type: 'doc', id: 'contributing/design', label: 'Design Guide' },
          ],
        },
        {
          type: 'category',
          link: showIndexPageForCategory,
          label: 'Changelog',
          items: [
            { type: 'doc', id: 'changelog/common', label: '@cbhq/cds-common' },
            { type: 'doc', id: 'changelog/fonts', label: '@cbhq/cds-fonts' },
            { type: 'doc', id: 'changelog/lottie-files', label: '@cbhq/cds-lottie-files' },
            { type: 'doc', id: 'changelog/mobile', label: '@cbhq/cds-mobile' },
            { type: 'doc', id: 'changelog/utils', label: '@cbhq/cds-utils' },
            { type: 'doc', id: 'changelog/web', label: '@cbhq/cds-web' },
          ],
        },
        'resources/release',
        /* Uncomment to enable CDS Code conventions in the side bar
                {
                  type: 'category',
                  label: 'Conventions',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'conventions/overview', label: 'Overview' },
                    { type: 'doc', id: 'conventions/api-design', label: 'API Design' },
                    { type: 'doc', id: 'conventions/composition', label: 'Composition' },
                  ],
                },
                 */
      ],
    },
  ],
};
