/**
 * DO NOT MODIFY
 * Generated from scripts/codegen/main.ts
 */

export const xSmall = {
  name: 'xSmall',
  typography: {
    display1: { fontSize: 61, lineHeight: 68, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 45, lineHeight: 52, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 37, lineHeight: 44, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 25, lineHeight: 32, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 25, lineHeight: 32, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 17, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    title4: { fontSize: 17, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    headline: { fontSize: 14, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 14, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 11, lineHeight: 16, fontFamily: 'CoinbaseText-Medium' },
    label2: { fontSize: 11, lineHeight: 16, fontFamily: 'CoinbaseText-Regular' },
    caption: { fontSize: 10, lineHeight: 12, fontFamily: 'CoinbaseText-Medium' },
    legal: { fontSize: 10, lineHeight: 12, fontFamily: 'CoinbaseText-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 10,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
  },
  control: {
    checkboxSize: 16,
    radioSize: 16,
    switchWidth: 42,
    switchHeight: 24,
    switchThumbSize: 22,
  },
} as const;

export const small = {
  name: 'small',
  typography: {
    display1: { fontSize: 62, lineHeight: 72, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 46, lineHeight: 56, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 38, lineHeight: 48, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 26, lineHeight: 32, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 26, lineHeight: 32, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 18, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    title4: { fontSize: 18, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    headline: { fontSize: 14, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 14, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 12, lineHeight: 16, fontFamily: 'CoinbaseText-Medium' },
    label2: { fontSize: 12, lineHeight: 16, fontFamily: 'CoinbaseText-Regular' },
    caption: { fontSize: 11, lineHeight: 16, fontFamily: 'CoinbaseText-Medium' },
    legal: { fontSize: 11, lineHeight: 16, fontFamily: 'CoinbaseText-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 10,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
  },
  control: {
    checkboxSize: 16,
    radioSize: 16,
    switchWidth: 42,
    switchHeight: 24,
    switchThumbSize: 22,
  },
} as const;

export const medium = {
  name: 'medium',
  typography: {
    display1: { fontSize: 63, lineHeight: 72, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 47, lineHeight: 56, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 39, lineHeight: 48, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 27, lineHeight: 36, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 27, lineHeight: 36, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 19, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    title4: { fontSize: 19, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    headline: { fontSize: 15, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 15, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 13, lineHeight: 16, fontFamily: 'CoinbaseText-Medium' },
    label2: { fontSize: 13, lineHeight: 16, fontFamily: 'CoinbaseText-Regular' },
    caption: { fontSize: 12, lineHeight: 16, fontFamily: 'CoinbaseText-Medium' },
    legal: { fontSize: 12, lineHeight: 16, fontFamily: 'CoinbaseText-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 10,
    '2': 12,
    '3': 16,
    '4': 20,
    '5': 24,
    '6': 28,
    '7': 32,
    '8': 36,
    '9': 40,
    '10': 44,
  },
  control: {
    checkboxSize: 16,
    radioSize: 16,
    switchWidth: 42,
    switchHeight: 24,
    switchThumbSize: 22,
  },
} as const;

export const large = {
  name: 'large',
  typography: {
    display1: { fontSize: 64, lineHeight: 72, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 48, lineHeight: 56, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 40, lineHeight: 48, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 28, lineHeight: 36, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 28, lineHeight: 36, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 20, lineHeight: 28, fontFamily: 'CoinbaseSans-Medium' },
    title4: { fontSize: 20, lineHeight: 28, fontFamily: 'CoinbaseSans-Regular' },
    headline: { fontSize: 16, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 16, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 14, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    label2: { fontSize: 14, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
    caption: { fontSize: 13, lineHeight: 16, fontFamily: 'CoinbaseText-Medium' },
    legal: { fontSize: 13, lineHeight: 16, fontFamily: 'CoinbaseText-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 12,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
  },
  control: {
    checkboxSize: 20,
    radioSize: 20,
    switchWidth: 52,
    switchHeight: 32,
    switchThumbSize: 30,
  },
} as const;

export const xLarge = {
  name: 'xLarge',
  typography: {
    display1: { fontSize: 66, lineHeight: 76, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 50, lineHeight: 60, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 42, lineHeight: 52, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 30, lineHeight: 36, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 30, lineHeight: 36, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 22, lineHeight: 28, fontFamily: 'CoinbaseSans-Medium' },
    title4: { fontSize: 22, lineHeight: 28, fontFamily: 'CoinbaseSans-Regular' },
    headline: { fontSize: 18, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 18, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 16, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    label2: { fontSize: 16, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
    caption: { fontSize: 15, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    legal: { fontSize: 15, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 12,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
  },
  control: {
    checkboxSize: 20,
    radioSize: 20,
    switchWidth: 52,
    switchHeight: 32,
    switchThumbSize: 30,
  },
} as const;

export const xxLarge = {
  name: 'xxLarge',
  typography: {
    display1: { fontSize: 68, lineHeight: 76, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 52, lineHeight: 60, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 44, lineHeight: 52, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 32, lineHeight: 40, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 32, lineHeight: 40, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 24, lineHeight: 32, fontFamily: 'CoinbaseSans-Medium' },
    title4: { fontSize: 24, lineHeight: 32, fontFamily: 'CoinbaseSans-Regular' },
    headline: { fontSize: 20, lineHeight: 28, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 20, lineHeight: 28, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 18, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    label2: { fontSize: 18, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    caption: { fontSize: 17, lineHeight: 20, fontFamily: 'CoinbaseSans-Medium' },
    legal: { fontSize: 17, lineHeight: 20, fontFamily: 'CoinbaseSans-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 12,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
  },
  control: {
    checkboxSize: 20,
    radioSize: 20,
    switchWidth: 52,
    switchHeight: 32,
    switchThumbSize: 30,
  },
} as const;

export const xxxLarge = {
  name: 'xxxLarge',
  typography: {
    display1: { fontSize: 70, lineHeight: 80, fontFamily: 'CoinbaseDisplay-Regular' },
    display2: { fontSize: 54, lineHeight: 64, fontFamily: 'CoinbaseDisplay-Regular' },
    display3: { fontSize: 46, lineHeight: 56, fontFamily: 'CoinbaseDisplay-Regular' },
    title1: { fontSize: 34, lineHeight: 40, fontFamily: 'CoinbaseDisplay-Medium' },
    title2: { fontSize: 34, lineHeight: 40, fontFamily: 'CoinbaseDisplay-Regular' },
    title3: { fontSize: 26, lineHeight: 32, fontFamily: 'CoinbaseDisplay-Medium' },
    title4: { fontSize: 26, lineHeight: 32, fontFamily: 'CoinbaseDisplay-Regular' },
    headline: { fontSize: 22, lineHeight: 28, fontFamily: 'CoinbaseSans-Medium' },
    body: { fontSize: 22, lineHeight: 28, fontFamily: 'CoinbaseSans-Regular' },
    label1: { fontSize: 20, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    label2: { fontSize: 20, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
    caption: { fontSize: 19, lineHeight: 24, fontFamily: 'CoinbaseSans-Medium' },
    legal: { fontSize: 19, lineHeight: 24, fontFamily: 'CoinbaseSans-Regular' },
  },
  spacing: {
    '0': 0,
    '0.25': 2,
    '0.5': 4,
    '0.75': 6,
    '1': 8,
    '1.5': 12,
    '2': 16,
    '3': 24,
    '4': 32,
    '5': 40,
    '6': 48,
    '7': 56,
    '8': 64,
    '9': 72,
    '10': 80,
  },
  control: {
    checkboxSize: 20,
    radioSize: 20,
    switchWidth: 52,
    switchHeight: 32,
    switchThumbSize: 30,
  },
} as const;
