export const mockData = {
  name: 'Button',
  description: '',
  props: [
    {
      name: 'accessibilityLabel',
      required: false,
      description:
        'Full length accessibility label when the child text is not descriptive enough. Accessibility label describing the control. If no accessibilityLabel, it will set it to label Maps to aria-label',
      options: 'string',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'accessibilityHint',
      required: false,
      description:
        'Accessibility hint for assisted devices when focused. Message should indicate the purpose of the control. If not supplied, will default to label',
      options: 'string',
      parent: 'SharedAccessibilityProps',
    },
    {
      name: 'accessibilityLabelledBy',
      required: false,
      description: 'Accessibility prop that describes the component that labels it by its id ',
      options: 'string',
      parent: 'SharedAccessibilityProps',
    },
    {
      name: 'accessibilityLabelId',
      required: false,
      description: 'Used to associate a label with an input for accessibility',
      options: 'string',
      parent: 'SharedAccessibilityProps',
    },
    {
      name: 'accessibilityDescriptionId',
      required: false,
      description: 'Used to associate descriptive text to an input for accessibility',
      options: 'string',
      parent: 'SharedAccessibilityProps',
    },
    {
      name: 'children',
      required: true,
      description: 'Children to render within the button.',
      options: 'boolean | ReactChild | ReactFragment | ReactPortal',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'disabled',
      required: false,
      description: 'Mark the button as disabled. Same as the HTML attribute.',
      options: 'boolean',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'focusable',
      required: false,
      description:
        'When an element is disabled, it may still be focusable. It works similarly to readOnly on form elements. In this case, only aria-disabled will be set.',
      options: 'boolean',
      parent: 'reakit',
    },
    {
      name: 'tabIndex',
      required: false,
      description:
        'Necessary to control roving tabindex for accessibility https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex',
      options: 'number',
      parent: 'Pressable',
    },
    {
      name: 'role',
      required: false,
      description: '',
      options:
        'alert | alertdialog | application | article | banner | button | cell | checkbox | columnheader | combobox | complementary | contentinfo | definition | dialog | directory | document | feed | figure | form | grid | gridcell | group | heading | img | link | list | listbox | listitem | log | main | marquee | math | menu | menubar | menuitem | menuitemcheckbox | menuitemradio | navigation | none | note | option | presentation | progressbar | radio | radiogroup | region | row | rowgroup | rowheader | scrollbar | search | searchbox | separator | slider | spinbutton | status | string & {} | switch | tab | table | tablist | tabpanel | term | textbox | timer | toolbar | tooltip | tree | treegrid | treeitem',
      parent: 'HTMLAttributes',
    },
    {
      name: 'onBlur',
      required: false,
      description: '',
      options: 'FocusEventHandler',
      parent: 'DOMAttributes',
    },
    {
      name: 'onChange',
      required: false,
      description: '',
      options: 'FormEventHandler',
      parent: 'DOMAttributes',
    },
    {
      name: 'onKeyPress',
      required: false,
      description: 'Callback fired when a key is pressed',
      options: '(KeyboardEventHandler<Element> & KeyboardEventHandler)',
      parent: 'Pressable',
    },
    {
      name: 'key',
      required: false,
      description: '',
      options: 'Key | null',
      parent: 'Attributes',
    },
    {
      name: 'autoFocus',
      required: false,
      description: '',
      options: 'boolean',
      parent: 'ButtonHTMLAttributes',
    },
    {
      name: 'name',
      required: false,
      description: 'Uniquely identify the button within a form.',
      options: 'string',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'type',
      required: false,
      defaultValue: 'button',
      description: '',
      options: 'button | submit | reset',
      parent: 'ButtonHTMLAttributes',
    },
    {
      name: 'value',
      required: false,
      description: '',
      options: 'string | number | readonly string[]',
      parent: 'ButtonHTMLAttributes',
    },
    {
      name: 'block',
      required: false,
      description: 'Change to block and expand to 100% of parent width.',
      options: 'boolean',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'compact',
      required: false,
      description: 'Reduce the inner padding within the button itself.',
      options: 'boolean',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'endIcon',
      required: false,
      description: 'Icon to render at the end of the button.',
      options: 'IconName',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'loading',
      required: false,
      description:
        'Mark the button as loading and display a spinner. Is the element currenty loading.',
      options: 'boolean',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'onPress',
      required: false,
      description: 'Callback fired when the element is pressed.',
      options: 'OnPress',
      parent: 'Pressable',
    },
    {
      name: 'startIcon',
      required: false,
      description: 'Icon to render at the start of the button.',
      options: 'IconName',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'to',
      required: false,
      description: 'URL that this links to when pressed.',
      options: 'string',
      parent: 'Pressable',
    },
    {
      name: 'transparent',
      required: false,
      description: 'Mark the background and border as transparent until interacted with.',
      options: 'boolean',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'flush',
      required: false,
      description:
        'Ensure the button aligns flush on the left or right. This prop will translate the entire button left/right, so take care to ensure it is not overflowing awkwardly',
      options: 'start | end',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'variant',
      required: false,
      defaultValue: 'primary',
      description: 'Toggle design and visual variants.',
      options: 'primary | secondary | positive | negative',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'noScaleOnPress',
      required: false,
      description: 'Dont scale element on press.',
      options: 'boolean',
      parent: 'ButtonBaseProps',
    },
    {
      name: 'testID',
      required: false,
      description:
        'Used to locate this element in unit and end-to-end tests. Under the hood, testID translates to data-testid on Web. On Mobile, testID stays the same - testID',
      options: 'string',
      parent: 'SharedProps',
    },
    {
      name: 'ref',
      required: false,
      description: '',
      options: 'Ref<HTMLButtonElement>',
      parent: 'RefAttributes',
    },
  ],
  extends: {
    HTMLAttributes: [
      'id',
      'defaultChecked',
      'defaultValue',
      'suppressContentEditableWarning',
      'suppressHydrationWarning',
      'accessKey',
      'contentEditable',
      'contextMenu',
      'dir',
      'draggable',
      'hidden',
      'lang',
      'placeholder',
      'slot',
      'spellCheck',
      'title',
      'translate',
      'radioGroup',
      'about',
      'datatype',
      'inlist',
      'prefix',
      'property',
      'resource',
      'typeof',
      'vocab',
      'autoCapitalize',
      'autoCorrect',
      'autoSave',
      'color',
      'itemProp',
      'itemScope',
      'itemType',
      'itemID',
      'itemRef',
      'results',
      'security',
      'unselectable',
      'inputMode',
      'is',
    ],
    ButtonHTMLAttributes: [
      'form',
      'formAction',
      'formEncType',
      'formMethod',
      'formNoValidate',
      'formTarget',
    ],
    AriaAttributes: [
      'aria-activedescendant',
      'aria-atomic',
      'aria-autocomplete',
      'aria-busy',
      'aria-checked',
      'aria-colcount',
      'aria-colindex',
      'aria-colspan',
      'aria-controls',
      'aria-current',
      'aria-describedby',
      'aria-details',
      'aria-disabled',
      'aria-dropeffect',
      'aria-errormessage',
      'aria-expanded',
      'aria-flowto',
      'aria-grabbed',
      'aria-haspopup',
      'aria-hidden',
      'aria-invalid',
      'aria-keyshortcuts',
      'aria-label',
      'aria-labelledby',
      'aria-level',
      'aria-live',
      'aria-modal',
      'aria-multiline',
      'aria-multiselectable',
      'aria-orientation',
      'aria-owns',
      'aria-placeholder',
      'aria-posinset',
      'aria-pressed',
      'aria-readonly',
      'aria-relevant',
      'aria-required',
      'aria-roledescription',
      'aria-rowcount',
      'aria-rowindex',
      'aria-rowspan',
      'aria-selected',
      'aria-setsize',
      'aria-sort',
      'aria-valuemax',
      'aria-valuemin',
      'aria-valuenow',
      'aria-valuetext',
    ],
    DOMAttributes: [
      'dangerouslySetInnerHTML',
      'onCopy',
      'onCopyCapture',
      'onCut',
      'onCutCapture',
      'onPaste',
      'onPasteCapture',
      'onCompositionEnd',
      'onCompositionEndCapture',
      'onCompositionStart',
      'onCompositionStartCapture',
      'onCompositionUpdate',
      'onCompositionUpdateCapture',
      'onFocus',
      'onFocusCapture',
      'onBlurCapture',
      'onChangeCapture',
      'onBeforeInput',
      'onBeforeInputCapture',
      'onInput',
      'onInputCapture',
      'onReset',
      'onResetCapture',
      'onSubmit',
      'onSubmitCapture',
      'onInvalid',
      'onInvalidCapture',
      'onLoad',
      'onLoadCapture',
      'onError',
      'onErrorCapture',
      'onKeyDown',
      'onKeyDownCapture',
      'onKeyPressCapture',
      'onKeyUp',
      'onKeyUpCapture',
      'onAbort',
      'onAbortCapture',
      'onCanPlay',
      'onCanPlayCapture',
      'onCanPlayThrough',
      'onCanPlayThroughCapture',
      'onDurationChange',
      'onDurationChangeCapture',
      'onEmptied',
      'onEmptiedCapture',
      'onEncrypted',
      'onEncryptedCapture',
      'onEnded',
      'onEndedCapture',
      'onLoadedData',
      'onLoadedDataCapture',
      'onLoadedMetadata',
      'onLoadedMetadataCapture',
      'onLoadStart',
      'onLoadStartCapture',
      'onPause',
      'onPauseCapture',
      'onPlay',
      'onPlayCapture',
      'onPlaying',
      'onPlayingCapture',
      'onProgress',
      'onProgressCapture',
      'onRateChange',
      'onRateChangeCapture',
      'onSeeked',
      'onSeekedCapture',
      'onSeeking',
      'onSeekingCapture',
      'onStalled',
      'onStalledCapture',
      'onSuspend',
      'onSuspendCapture',
      'onTimeUpdate',
      'onTimeUpdateCapture',
      'onVolumeChange',
      'onVolumeChangeCapture',
      'onWaiting',
      'onWaitingCapture',
      'onAuxClick',
      'onAuxClickCapture',
      'onContextMenu',
      'onContextMenuCapture',
      'onDoubleClick',
      'onDoubleClickCapture',
      'onDrag',
      'onDragCapture',
      'onDragEnd',
      'onDragEndCapture',
      'onDragEnter',
      'onDragEnterCapture',
      'onDragExit',
      'onDragExitCapture',
      'onDragLeave',
      'onDragLeaveCapture',
      'onDragOver',
      'onDragOverCapture',
      'onDragStart',
      'onDragStartCapture',
      'onDrop',
      'onDropCapture',
      'onMouseDown',
      'onMouseDownCapture',
      'onMouseEnter',
      'onMouseLeave',
      'onMouseMove',
      'onMouseMoveCapture',
      'onMouseOut',
      'onMouseOutCapture',
      'onMouseOver',
      'onMouseOverCapture',
      'onMouseUp',
      'onMouseUpCapture',
      'onSelect',
      'onSelectCapture',
      'onTouchCancel',
      'onTouchCancelCapture',
      'onTouchEnd',
      'onTouchEndCapture',
      'onTouchMove',
      'onTouchMoveCapture',
      'onTouchStart',
      'onTouchStartCapture',
      'onPointerDown',
      'onPointerDownCapture',
      'onPointerMove',
      'onPointerMoveCapture',
      'onPointerUp',
      'onPointerUpCapture',
      'onPointerCancel',
      'onPointerCancelCapture',
      'onPointerEnter',
      'onPointerEnterCapture',
      'onPointerLeave',
      'onPointerLeaveCapture',
      'onPointerOver',
      'onPointerOverCapture',
      'onPointerOut',
      'onPointerOutCapture',
      'onGotPointerCapture',
      'onGotPointerCaptureCapture',
      'onLostPointerCapture',
      'onLostPointerCaptureCapture',
      'onScroll',
      'onScrollCapture',
      'onWheel',
      'onWheelCapture',
      'onAnimationStart',
      'onAnimationStartCapture',
      'onAnimationEnd',
      'onAnimationEndCapture',
      'onAnimationIteration',
      'onAnimationIterationCapture',
      'onTransitionEnd',
      'onTransitionEndCapture',
    ],
    ComponentEventDelegationProps: ['eventConfig'],
  },
  packageName: 'web',
  aliasTypes: {},
  parentTypes: {},
};
