platform :ios, '11.0'
inhibit_all_warnings!

node_modules = "../../../node_modules/"
config = JSON.parse(`cd ../../.. && RN_PROJECT=app npx react-native config`)

require_relative "#{node_modules}/react-native/scripts/react_native_pods"
require_relative "#{node_modules}/@react-native-community/cli-platform-ios/native_modules"
# require_relative "#{node_modules}/@nrwl/react-native/nx_post_install"

target 'MobilePlayground' do
  use_react_native!(
    :path => "#{node_modules}/react-native",
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  use_native_modules!(config)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # nx_post_install(installer)
  end
end