$iosVersion = '11.0'
platform :ios, $iosVersion
inhibit_all_warnings!

node_modules = "../../../node_modules"

# `yarn react-native link` only links to the 1st target on xcode project.
# https://github.com/facebook/react-native/issues/22162
# we need to make sure that the `app` target is at the top to link assets like font.
# xcodegen doesn't support target ordering, so using xcodeproj to sort them here.
require 'xcodeproj'
project = Xcodeproj::Project.open('MobilePlayground.xcodeproj')
project.sort
project.save

require_relative "#{node_modules}/react-native/scripts/react_native_pods"
require_relative "#{node_modules}/@react-native-community/cli-platform-ios/native_modules"
# require_relative "#{node_modules}/@nrwl/react-native/nx_post_install"


# config = JSON.parse(`cd .. && npx react-native config`)

target 'MobilePlayground' do
  # use_react_native!(path: "#{node_modules}/react-native")
  use_react_native!(
    :path => "#{node_modules}/react-native",
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  use_native_modules!()
  # use_native_modules!(config)

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    # flipper_post_install(installer)
    react_native_post_install(installer)
    # exclude_arm64_arch(installer)
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)


    #-------------- https://github.com/facebook/flipper/issues/834#issuecomment-905806177 ---------------------------
    # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
    installer.aggregate_targets.each do |aggregate_target| 
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end

     # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
    # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iosVersion
      end
    end

    # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
    `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
  
    #--------------------------------------------------------------------------------------------------------------------------
  end
end