name: MobilePlayground
configs:
  Debug: debug
  Release: release
targets:
  MobilePlayground:
    type: application
    platform: iOS
    deploymentTarget: '11.0'
    sources:
      - path: MobilePlayground
        compilerFlags:
          - '-fstack-protector-all'
    settings:
      base:
        APP_VERSION: '1.0.0'
        BUILD_NUMBER: '001'
        CURRENT_PROJECT_VERSION: '001'
        TARGETED_DEVICE_FAMILY: 1 # support iPhone/iPod touch only
        SWIFT_VERSION: 5.0
        ENABLE_BITCODE: false
        CODE_SIGN_STYLE: Manual
        PRODUCT_NAME: 'MobilePlayground'
        # SWIFT_OBJC_BRIDGING_HEADER: app/Bridging-Header.h
        # RCT_NO_LAUNCH_PACKAGER: true
        'EXCLUDED_ARCHS[sdk=iphonesimulator*]': arm64
        CLANG_ENABLE_OBJC_ARC: true
        APP_DISPLAY_NAME: MobilePlayground
        PRODUCT_BUNDLE_IDENTIFIER: com.coinbase.mobileplayground
      configs:
        Debug:
          DEBUG: true
        Release:
          DEBUG: false
          # RELEASE_STAGE: production
          ENABLE_BITCODE: true
    postBuildScripts:
      - name: Bundle React Native code and images
        script: |
          export NODE_BINARY=node
          export PROJECT_ROOT="$PWD/.."
          ../../../node_modules/react-native/scripts/react-native-xcode.sh $PROJECT_ROOT/src/main.tsx
