export const retailWebYourAssetsMock = [
  {
    id: '667f58cf-0a52-55e4-a47b-357187313e8b',
    name: 'BCH Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'BCH',
      name: 'Bitcoin Cash',
      color: '#8DC351',
      sort_index: 101,
      exponent: 8,
      type: 'crypto',
      address_regex:
        '^([2mn][1-9A-HJ-NP-Za-km-z]{25,34})|^((bchtest:)?(q|p)[a-z0-9]{41})|^((BCHTEST:)?(Q|P)[A-Z0-9]{41})$',
      asset_id: '45f99e13-b522-57d7-8058-c57bf92fe7a3',
      slug: 'bitcoin-cash',
    },
    balance: {
      amount: '1000.00000000',
      currency: 'BCH',
    },
    created_at: '2021-09-02T23:33:48Z',
    updated_at: '2021-09-02T23:33:51Z',
    resource: 'account',
    resource_path: '/v2/accounts/667f58cf-0a52-55e4-a47b-357187313e8b',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: '08ec5cc3-ffe6-536a-a5b3-de10e221a037',
    name: 'Cash (USD)',
    primary: false,
    type: 'fiat',
    currency: {
      code: 'USD',
      name: 'US Dollar',
      color: '#0066cf',
      sort_index: 0,
      exponent: 2,
      type: 'fiat',
    },
    balance: {
      amount: '0.00',
      currency: 'USD',
    },
    created_at: '2021-09-02T23:24:06Z',
    updated_at: '2021-09-02T23:24:06Z',
    resource: 'account',
    resource_path: '/v2/accounts/08ec5cc3-ffe6-536a-a5b3-de10e221a037',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    wire_deposit_information: {
      account_number: null,
      routing_number: '021214891',
      bank_name: 'Cross River Bank',
      bank_address: '885 Teaneck Road, Teaneck, NJ 07666',
      bank_country: {
        code: 'US',
        name: 'United States',
      },
      account_name: 'Coinbase Inc',
      account_address: '100 Pine Street, Suite 1250, San Francisco, CA 94111',
      reference: 'FGNLKXTW',
    },
    swift_deposit_information: null,
  },
  {
    id: 'df4f3062-d44d-526c-91c4-1ae6af0748fd',
    name: 'GBP Wallet',
    primary: false,
    type: 'fiat',
    currency: {
      code: 'GBP',
      name: 'British Pound',
      color: '#0066cf',
      sort_index: 3,
      exponent: 2,
      type: 'fiat',
    },
    balance: {
      amount: '0.00',
      currency: 'GBP',
    },
    created_at: '2021-09-02T23:22:54Z',
    updated_at: '2021-09-02T23:22:54Z',
    resource: 'account',
    resource_path: '/v2/accounts/df4f3062-d44d-526c-91c4-1ae6af0748fd',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    uk_deposit_information: {
      sort_code: '04-06-10',
      account_number: '00013818',
      account_name: 'Jonathan Rossi',
      bank_name: 'Coinbase',
      reference: 'CBAGBPWSZTLUHK',
    },
  },
  {
    id: 'dcb78d77-3803-5b7e-ad91-8bce2ed25e28',
    name: 'EUR Wallet',
    primary: false,
    type: 'fiat',
    currency: {
      code: 'EUR',
      name: 'Euro',
      color: '#0066cf',
      sort_index: 2,
      exponent: 2,
      type: 'fiat',
    },
    balance: {
      amount: '0.00',
      currency: 'EUR',
    },
    created_at: '2021-09-02T23:22:54Z',
    updated_at: '2021-09-02T23:22:54Z',
    resource: 'account',
    resource_path: '/v2/accounts/dcb78d77-3803-5b7e-ad91-8bce2ed25e28',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    sepa_deposit_information: {
      iban: 'TODO-CBINC-ACCOUNT-NUMBER',
      swift: 'LHVBEE22',
      bank_name: 'AS LHV Pank',
      bank_address: 'Tartu mnt 2, 10145 Tallinn, Estonia',
      bank_country: {
        code: 'EE',
        name: 'Estonia',
      },
      account_name: 'Coinbase Inc',
      account_address: '100 Pine Street, Suite 1250, San Francisco, CA 94111',
      reference: 'CBAEURMYVMGSFB',
    },
  },
  {
    id: '2ad2ed31-0336-5cb7-889d-ee833c2c6312',
    name: 'BTC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'BTC',
      name: 'Bitcoin',
      color: '#F7931A',
      sort_index: 100,
      exponent: 8,
      type: 'crypto',
      address_regex:
        '^([2mn][1-9A-HJ-NP-Za-km-z]{25,34})|^(tb1([qpzry9x8gf2tvdw0s3jn54khce6mua7l]{39}|[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{59}))$',
      asset_id: '5b71fc48-3dd3-540c-809b-f8c94d0e68b5',
      slug: 'bitcoin',
    },
    balance: {
      amount: '0.00000000',
      currency: 'BTC',
    },
    created_at: '2021-09-02T23:22:17Z',
    updated_at: '2021-09-02T23:22:17Z',
    resource: 'account',
    resource_path: '/v2/accounts/2ad2ed31-0336-5cb7-889d-ee833c2c6312',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ETH',
    name: 'ETH Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ETH',
      name: 'Ethereum',
      color: '#627EEA',
      sort_index: 102,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'd85dce9b-5b73-5c3c-8978-522ce1d1c1b4',
      slug: 'ethereum',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ETH',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ETH',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ETC',
    name: 'ETC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ETC',
      name: 'Ethereum Classic',
      color: '#59D4AF',
      sort_index: 103,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'c16df856-0345-5358-8a70-2a78c804e61f',
      slug: 'ethereum-classic',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ETC',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ETC',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'LTC',
    name: 'LTC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'LTC',
      name: 'Litecoin',
      color: '#A6A9AA',
      sort_index: 104,
      exponent: 8,
      type: 'crypto',
      address_regex:
        '^((m|n|2|Q)[a-km-zA-HJ-NP-Z1-9]{25,34})|^(tltc1([qpzry9x8gf2tvdw0s3jn54khce6mua7l]{39}|[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{59}))$',
      asset_id: 'c9c24c6e-c045-5fde-98a2-00ea7f520437',
      slug: 'litecoin',
    },
    balance: {
      amount: '0.00000000',
      currency: 'LTC',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/LTC',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ZRX',
    name: 'ZRX Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ZRX',
      name: '0x',
      color: '#302C2C',
      sort_index: 105,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'a2a8f5ae-83a6-542e-9064-7d335ae8a58d',
      slug: '0x',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ZRX',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ZRX',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'BAT',
    name: 'BAT Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'BAT',
      name: 'Basic Attention Token',
      color: '#FF5000',
      sort_index: 106,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'b8950bef-d61b-53cd-bb66-db436f0f81bc',
      slug: 'basic-attention-token',
    },
    balance: {
      amount: '0.00000000',
      currency: 'BAT',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/BAT',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'USDC',
    name: 'USDC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'USDC',
      name: 'USD Coin',
      color: '#2775CA',
      sort_index: 107,
      exponent: 6,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '2b92315d-eab7-5bef-84fa-089a131333f5',
      slug: 'usdc',
    },
    balance: {
      amount: '0.000000',
      currency: 'USDC',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/USDC',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    rewards_apy: '0.0015',
    rewards: {
      apy: '0.0015',
      formatted_apy: '0.15%',
      label: '0.15% APY',
    },
  },
  {
    id: 'ZEC',
    name: 'ZEC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ZEC',
      name: 'Zcash',
      color: '#ECB244',
      sort_index: 108,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(tm|t2)[a-km-zA-HJ-NP-Z1-9]{33}$',
      asset_id: '1d3c2625-a8d9-5458-84d0-437d75540421',
      slug: 'zcash',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ZEC',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ZEC',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'MKR',
    name: 'MKR Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'MKR',
      name: 'Maker',
      color: '#1AAB9B',
      sort_index: 114,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '5553e486-7a85-5433-a5c1-aaeb18a154dd',
      slug: 'maker',
    },
    balance: {
      amount: '0.00000000',
      currency: 'MKR',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/MKR',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'DAI',
    name: 'DAI Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'DAI',
      name: 'Dai',
      color: '#FFB74D',
      sort_index: 115,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '01e9e33b-d099-56fb-aa3b-76c19d0b250e',
      slug: 'dai',
    },
    balance: {
      amount: '0.00000000',
      currency: 'DAI',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/DAI',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    rewards_apy: '0.02',
    rewards: {
      apy: '0.02',
      formatted_apy: '2.00%',
      label: '2.00% APY',
    },
  },
  {
    id: 'OMG',
    name: 'OMG Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'OMG',
      name: 'OMG Network',
      color: '#101010',
      sort_index: 118,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '7616bfa5-9874-5680-87ef-6f04dd3a0e75',
      slug: 'omg-network',
    },
    balance: {
      amount: '0.00000000',
      currency: 'OMG',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/OMG',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'KNC',
    name: 'KNC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'KNC',
      name: 'Kyber Network',
      color: '#31CB9E',
      sort_index: 121,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '8c853af0-5071-5dd7-9f70-1a871107f53c',
      slug: 'kyber-network',
    },
    balance: {
      amount: '0.00000000',
      currency: 'KNC',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/KNC',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'XRP',
    name: 'XRP Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'XRP',
      name: 'XRP',
      color: '#222222',
      sort_index: 125,
      exponent: 6,
      type: 'crypto',
      address_regex: '^r[1-9a-km-zA-HJ-NP-Z]{25,35}$',
      asset_id: 'e17a44c8-6ea1-564f-a02c-2a9ca1d8eec4',
      destination_tag_name: 'XRP Tag',
      destination_tag_regex: '^\\d{1,10}$',
      slug: 'xrp',
    },
    balance: {
      amount: '0.000000',
      currency: 'XRP',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/XRP',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'REP',
    name: 'REP Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'REP',
      name: 'Augur',
      color: '#553580',
      sort_index: 126,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'b8b44189-a54b-526f-b68d-1dbb27b462c3',
      slug: 'augur',
    },
    balance: {
      amount: '0.00000000',
      currency: 'REP',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/REP',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'XLM',
    name: 'XLM Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'XLM',
      name: 'Stellar Lumens',
      color: '#000000',
      sort_index: 127,
      exponent: 7,
      type: 'crypto',
      address_regex: '^G[A-Z2-7]{55}$',
      asset_id: '13b83335-5ede-595b-821e-5bcdfa80560f',
      destination_tag_name: 'XLM Memo',
      destination_tag_regex: '^[ -~]{1,28}$',
      slug: 'stellar',
    },
    balance: {
      amount: '0.0000000',
      currency: 'XLM',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/XLM',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'EOS',
    name: 'EOS Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'EOS',
      name: 'EOS',
      color: '#000000',
      sort_index: 128,
      exponent: 4,
      type: 'crypto',
      address_regex: '(^[a-z1-5.]{1,11}[a-z1-5]$)|(^[a-z1-5.]{12}[a-j1-5]$)',
      asset_id: '8d556883-6c26-5a88-9d8f-fa41fe8ed76e',
      destination_tag_name: 'EOS Memo',
      destination_tag_regex: '^.{1,100}$',
      slug: 'eos',
    },
    balance: {
      amount: '0.0000',
      currency: 'EOS',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/EOS',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'DOGE',
    name: 'DOGE Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'DOGE',
      name: 'Dogecoin',
      color: '#BA9F33',
      sort_index: 129,
      exponent: 8,
      type: 'crypto',
      address_regex: '^((2|n)[a-km-zA-HJ-NP-Z1-9]{25,34})$',
      asset_id: 'd9a3edfa-1be7-589c-bd20-c034f3830b60',
      slug: 'dogecoin',
    },
    balance: {
      amount: '0.00000000',
      currency: 'DOGE',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/DOGE',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'XTZ',
    name: 'XTZ Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'XTZ',
      name: 'Tezos',
      color: '#2C7DF7',
      sort_index: 130,
      exponent: 6,
      type: 'crypto',
      address_regex: '(tz[1|2|3]([a-zA-Z0-9]){33})|(^KT1([a-zA-Z0-9]){33}$)',
      asset_id: '69e559ec-547a-520a-aeb3-01cac23f1826',
      slug: 'tezos',
    },
    balance: {
      amount: '0.000000',
      currency: 'XTZ',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/XTZ',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    rewards: {
      apy: '0.0463',
      formatted_apy: '4.63%',
      label: '4.63% APY',
    },
  },
  {
    id: 'ALGO',
    name: 'ALGO Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ALGO',
      name: 'Algorand',
      color: '#000000',
      sort_index: 131,
      exponent: 6,
      type: 'crypto',
      address_regex: '^[A-Z2-7]{58}$',
      asset_id: '9220d47f-bc0a-53ad-9646-ef49918adcf3',
      slug: 'algorand',
    },
    balance: {
      amount: '0.000000',
      currency: 'ALGO',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ALGO',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'DASH',
    name: 'DASH Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'DASH',
      name: 'Dash',
      color: '#008DE4',
      sort_index: 132,
      exponent: 8,
      type: 'crypto',
      address_regex: '^([y7][a-km-zA-HJ-NP-Z1-9]{25,34})$',
      asset_id: 'b9c43d61-e77d-5e02-9a0d-800b50eb9d5f',
      slug: 'dash',
    },
    balance: {
      amount: '0.00000000',
      currency: 'DASH',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/DASH',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ATOM',
    name: 'ATOM Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ATOM',
      name: 'Cosmos',
      color: '#2E3148',
      sort_index: 133,
      exponent: 6,
      type: 'crypto',
      address_regex: '^cosmos1[ac-hj-np-z02-9]{38}$',
      asset_id: '64c607d2-4663-5649-86e0-3ab06bba0202',
      destination_tag_name: 'ATOM Memo',
      destination_tag_regex: '^\\w{1,24}$',
      slug: 'cosmos',
    },
    balance: {
      amount: '0.000000',
      currency: 'ATOM',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ATOM',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
    rewards: {
      apy: '0.05',
      formatted_apy: '5.00%',
      label: '5.00% APY',
    },
  },
  {
    id: 'OXT',
    name: 'OXT Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'OXT',
      name: 'Orchid',
      color: '#5F45BA',
      sort_index: 136,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '07525606-a404-5f15-a71d-ba0e40e74eca',
      slug: 'orchid',
    },
    balance: {
      amount: '0.00000000',
      currency: 'OXT',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/OXT',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'COMP',
    name: 'COMP Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'COMP',
      name: 'Compound',
      color: '#00D395',
      sort_index: 137,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '65557d44-082d-50a1-a68b-bc98d961f794',
      slug: 'compound',
    },
    balance: {
      amount: '0.00000000',
      currency: 'COMP',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/COMP',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'BAL',
    name: 'BAL Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'BAL',
      name: 'Balancer',
      color: '#1D282A',
      sort_index: 149,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'e0409f05-5a95-5abf-8082-c746da699f82',
      slug: 'balancer',
    },
    balance: {
      amount: '0.00000000',
      currency: 'BAL',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/BAL',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'YFII',
    name: 'YFII Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'YFII',
      name: 'DFI.Money',
      color: '#FA2978',
      sort_index: 153,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '9d5c9eca-87ec-5ad0-846c-aeae910d4a30',
      slug: 'yearn-finance-ii',
    },
    balance: {
      amount: '0.00000000',
      currency: 'YFII',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/YFII',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'BNT',
    name: 'BNT Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'BNT',
      name: 'Bancor Network Token',
      color: '#000B20',
      sort_index: 156,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '1b74d2fd-fa35-558d-a010-38d4481398c6',
      slug: 'bancor-network-token',
    },
    balance: {
      amount: '0.00000000',
      currency: 'BNT',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/BNT',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'SNX',
    name: 'SNX Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'SNX',
      name: 'Synthetix Network Token',
      color: '#0A0118',
      sort_index: 158,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '3bd5bbea-a525-520c-9d2a-2d842e543caa',
      slug: 'synthetix-network-token',
    },
    balance: {
      amount: '0.00000000',
      currency: 'SNX',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/SNX',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'MATIC',
    name: 'MATIC Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'MATIC',
      name: 'Polygon',
      color: '#8247E5',
      sort_index: 162,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '026bcc1e-9163-591c-a709-34dd18b2e7a1',
      slug: 'polygon',
    },
    balance: {
      amount: '0.00000000',
      currency: 'MATIC',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/MATIC',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'SKL',
    name: 'SKL Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'SKL',
      name: 'SKALE',
      color: '#000000',
      sort_index: 163,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'af2d755d-6142-57f4-a092-0aa4fe67a9b5',
      slug: 'skale',
    },
    balance: {
      amount: '0.00000000',
      currency: 'SKL',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/SKL',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ADA',
    name: 'ADA Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ADA',
      name: 'Cardano',
      color: '#0033AD',
      sort_index: 164,
      exponent: 6,
      type: 'crypto',
      address_regex: '(^(addr_test)1[ac-hj-np-z02-9]{6,}$)',
      asset_id: '63062039-7afb-56ff-8e19-5e3215dc404a',
      slug: 'cardano',
    },
    balance: {
      amount: '0.000000',
      currency: 'ADA',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ADA',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ICP',
    name: 'ICP Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ICP',
      name: 'Internet Computer',
      color: '#292A2E',
      sort_index: 167,
      exponent: 8,
      type: 'crypto',
      address_regex: '^[0-9a-f]{64}$',
      asset_id: '8f0fb5e8-9924-50bd-b95c-1d4b88fd20cc',
      slug: 'internet-computer',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ICP',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ICP',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: '1INCH',
    name: '1INCH Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: '1INCH',
      name: '1Inch',
      color: '#1B314F',
      sort_index: 170,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '484f30a6-9e06-58df-80b7-e63141e3ca0c',
      slug: '1inch',
    },
    balance: {
      amount: '0.00000000',
      currency: '1INCH',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/1INCH',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'USDT',
    name: 'USDT Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'USDT',
      name: 'Tether',
      color: '#22A079',
      sort_index: 171,
      exponent: 6,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'b26327c1-9a34-51d9-b982-9b29e6012648',
      slug: 'tether',
    },
    balance: {
      amount: '0.000000',
      currency: 'USDT',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/USDT',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'POLY',
    name: 'POLY Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'POLY',
      name: 'Polymath',
      color: '#1348E4',
      sort_index: 176,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '11c99387-6be3-53cf-8896-5ca867d201d3',
      slug: 'polymath-network',
    },
    balance: {
      amount: '0.00000000',
      currency: 'POLY',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/POLY',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'AMP',
    name: 'AMP Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'AMP',
      name: 'Amp',
      color: '#E42E95',
      sort_index: 182,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'f3b62870-ddd0-5dea-9d80-5190d8558461',
      slug: 'amp',
    },
    balance: {
      amount: '0.00000000',
      currency: 'AMP',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/AMP',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'BOND',
    name: 'BOND Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'BOND',
      name: 'BarnBridge',
      color: '#FF4339',
      sort_index: 187,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'b5652bd9-8ea8-5451-b153-96fbcba1ace5',
      slug: 'barnbridge',
    },
    balance: {
      amount: '0.00000000',
      currency: 'BOND',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/BOND',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'RLY',
    name: 'RLY Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'RLY',
      name: 'Rally',
      color: '#FF8A03',
      sort_index: 188,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '39d7d62b-c1fc-5db4-bc0e-a0465473a748',
      slug: 'rally',
    },
    balance: {
      amount: '0.00000000',
      currency: 'RLY',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/RLY',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'CLV',
    name: 'CLV Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'CLV',
      name: 'Clover',
      color: '#42C37B',
      sort_index: 189,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '453639be-192e-5e36-88e3-38496e542524',
      slug: 'clover-finance',
    },
    balance: {
      amount: '0.00000000',
      currency: 'CLV',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/CLV',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'FARM',
    name: 'FARM Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'FARM',
      name: 'Harvest Finance',
      color: '#BDE4E3',
      sort_index: 190,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '7ea0bd74-3cab-5bf8-94e2-f0c0b3896f07',
      slug: 'harvest-finance',
    },
    balance: {
      amount: '0.00000000',
      currency: 'FARM',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/FARM',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'MASK',
    name: 'MASK Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'MASK',
      name: 'Mask Network',
      color: '#1C68F3',
      sort_index: 191,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '45ce7f01-2962-5576-8dfd-449e4a49b75d',
      slug: 'mask-network',
    },
    balance: {
      amount: '0.00000000',
      currency: 'MASK',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/MASK',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'FET',
    name: 'FET Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'FET',
      name: 'Fetch.ai',
      color: '#1D2743',
      sort_index: 194,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '3672ab4a-25e0-57a8-b029-99239c081958',
      slug: 'fetch',
    },
    balance: {
      amount: '0.00000000',
      currency: 'FET',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/FET',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'PAX',
    name: 'PAX Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'PAX',
      name: 'Paxos Standard',
      color: '#2F8260',
      sort_index: 195,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'be4a78af-d300-59b0-9c70-ba42a93caf56',
      slug: 'paxos-standard',
    },
    balance: {
      amount: '0.00000000',
      currency: 'PAX',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/PAX',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ACH',
    name: 'ACH Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ACH',
      name: 'Alchemy Pay',
      color: '#2E3567',
      sort_index: 196,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '045e4fab-f2ca-58a3-ac2b-8c47c5d23968',
      slug: 'alchemy-pay',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ACH',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ACH',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ASM',
    name: 'ASM Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ASM',
      name: 'Assemble Protocol',
      color: '#0667D0',
      sort_index: 197,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '49e1401a-48a0-58ac-881d-03ef6894a038',
      slug: 'assemble-protocol',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ASM',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ASM',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'PLA',
    name: 'PLA Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'PLA',
      name: 'PlayDapp',
      color: '#02D6B4',
      sort_index: 198,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'baeb8efc-a5a6-5d8a-844c-2b95e4d09c99',
      slug: 'playdapp',
    },
    balance: {
      amount: '0.00000000',
      currency: 'PLA',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/PLA',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'RAI',
    name: 'RAI Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'RAI',
      name: 'Rai Reflex Index',
      color: '#1FC8A7',
      sort_index: 199,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '8adc8071-0938-5583-b672-6033f16f2786',
      slug: 'rai',
    },
    balance: {
      amount: '0.00000000',
      currency: 'RAI',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/RAI',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'TRIBE',
    name: 'TRIBE Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'TRIBE',
      name: 'Tribe',
      color: '#178DD0',
      sort_index: 200,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '09fa97ba-0baa-554b-a4a7-bfc4d00f4086',
      slug: 'tribe',
    },
    balance: {
      amount: '0.00000000',
      currency: 'TRIBE',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/TRIBE',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ORN',
    name: 'ORN Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ORN',
      name: 'Orion Protocol',
      color: '#313151',
      sort_index: 201,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '0c275161-fb4b-50c4-926b-d4d7d093b897',
      slug: 'orion-protocol',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ORN',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ORN',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'IOTX',
    name: 'IOTX Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'IOTX',
      name: 'IoTeX',
      color: '#19263B',
      sort_index: 202,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '56f8ea19-7e6a-5e38-ac47-fc9762b955ae',
      slug: 'iotex',
    },
    balance: {
      amount: '0.00000000',
      currency: 'IOTX',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/IOTX',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'UST',
    name: 'UST Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'UST',
      name: 'TerraUSD',
      color: '#5493F7',
      sort_index: 203,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '05120843-11c1-5b66-9df2-395db6d7ed6b',
      slug: 'terrausd',
    },
    balance: {
      amount: '0.00000000',
      currency: 'UST',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/UST',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'QUICK',
    name: 'QUICK Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'QUICK',
      name: 'Quickswap',
      color: '#418AC9',
      sort_index: 204,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'f04b2f59-319f-5fb5-ba88-2c33cca01901',
      slug: 'quickswap',
    },
    balance: {
      amount: '0.00000000',
      currency: 'QUICK',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/QUICK',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'AXS',
    name: 'AXS Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'AXS',
      name: 'Axie Infinity',
      color: '#0055D5',
      sort_index: 205,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'b76225e9-3cff-5c6f-88a2-2490f70cb02e',
      slug: 'axie-infinity',
    },
    balance: {
      amount: '0.00000000',
      currency: 'AXS',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/AXS',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'REQ',
    name: 'REQ Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'REQ',
      name: 'Request',
      color: '#00E6A0',
      sort_index: 206,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '7c6cf248-e06b-5426-a05d-ac2777159a11',
      slug: 'request',
    },
    balance: {
      amount: '0.00000000',
      currency: 'REQ',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/REQ',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'WLUNA',
    name: 'WLUNA Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'WLUNA',
      name: 'Wrapped Luna',
      color: '#28CD88',
      sort_index: 207,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'ecd5367c-801d-5160-8c7a-6bb5f9bb018b',
      slug: 'wrapped-luna-token',
    },
    balance: {
      amount: '0.00000000',
      currency: 'WLUNA',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/WLUNA',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'TRU',
    name: 'TRU Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'TRU',
      name: 'Truefi',
      color: '#1A5AFF',
      sort_index: 208,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '248c3984-79c8-5df2-a35d-bbd3a3e16e70',
      slug: 'truefi-token',
    },
    balance: {
      amount: '0.00000000',
      currency: 'TRU',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/TRU',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'RAD',
    name: 'RAD Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'RAD',
      name: 'Radicle',
      color: '#53D855',
      sort_index: 209,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'aa75e77c-c936-58a2-9d3c-afb7f23886e1',
      slug: 'radicle',
    },
    balance: {
      amount: '0.00000000',
      currency: 'RAD',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/RAD',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'DDX',
    name: 'DDX Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'DDX',
      name: 'DerivaDAO',
      color: '#2D1680',
      sort_index: 210,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '83cb4677-21c9-557f-9baa-969b3fee1a34',
      slug: 'derivadao',
    },
    balance: {
      amount: '0.00000000',
      currency: 'DDX',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/DDX',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'SUKU',
    name: 'SUKU Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'SUKU',
      name: 'SUKU',
      color: '#0667D0',
      sort_index: 211,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'bfb347d2-9510-5a8f-8aed-001fd3e1131d',
      slug: 'suku',
    },
    balance: {
      amount: '0.00000000',
      currency: 'SUKU',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/SUKU',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'RGT',
    name: 'RGT Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'RGT',
      name: 'Rari Governance Token',
      color: '#0667D0',
      sort_index: 212,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: 'a1548f40-bf11-5f95-a1c4-13cf8ecd8f8f',
      slug: 'rari-governance-token',
    },
    balance: {
      amount: '0.00000000',
      currency: 'RGT',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/RGT',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'XYO',
    name: 'XYO Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'XYO',
      name: 'XYO',
      color: '#0667D0',
      sort_index: 213,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '36d68172-0e1b-5a94-845a-a1e4e1022b75',
      slug: 'xyo',
    },
    balance: {
      amount: '0.00000000',
      currency: 'XYO',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/XYO',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'COTI',
    name: 'COTI Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'COTI',
      name: 'COTI',
      color: '#229FD0',
      sort_index: 214,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(?:0x)?[0-9a-fA-F]{40}$',
      asset_id: '95c91657-a486-5b3f-a6e4-d0831331dcd1',
      slug: 'coti',
    },
    balance: {
      amount: '0.00000000',
      currency: 'COTI',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/COTI',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
  {
    id: 'ZEN',
    name: 'ZEN Wallet',
    primary: true,
    type: 'wallet',
    currency: {
      code: 'ZEN',
      name: 'Horizen',
      color: '#234871',
      sort_index: 215,
      exponent: 8,
      type: 'crypto',
      address_regex: '^(zn|zr|zt|zs)[a-km-zA-HJ-NP-Z1-9]{25,34}$',
      asset_id: 'ef343d07-52fe-5fee-88ad-ddf1a9e2d852',
      slug: 'horizen',
    },
    balance: {
      amount: '0.00000000',
      currency: 'ZEN',
    },
    created_at: null,
    updated_at: null,
    resource: 'account',
    resource_path: '/v2/accounts/ZEN',
    allow_deposits: true,
    allow_withdrawals: true,
    active: true,
  },
] as const;
