name: CI
on:
  push:
    branches: master
  pull_request:
    branches: master

concurrency:
  group: CI-${{github.ref_name}}-${{github.event.pull_request.number || github.sha}}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  lint:
    name: Lint
    runs-on: [large, amd64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100 # TODO: This needs to include the merge-base
      - uses: ./.github/actions/setup
      - name: Lint (All)
        if: ${{ github.event_name == 'push' }}
        run: yarn nx run-many --target=lint
      - name: Lint (Affected)
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn nx affected --target=lint

  format:
    name: Format
    runs-on: [medium, amd64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100 # TODO: This needs to include the merge-base
      - uses: ./.github/actions/setup
      - name: Format (All)
        if: ${{ github.event_name == 'push' }}
        run: yarn nx format:check  --verbose --all
      - name: Format (Affected)
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn nx format:check --verbose
